// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Review=require('../web/music-section-review.js'),DOM=require('../web/music-section-review-dom.js'),Cursor=require('../web/issue-cursor.js'),Position=require('../web/editor-field-position.js'),LegacyPosition=require('../web/shot-field-position.js');
function setup(){
 const E=require('../web/editor-state.js'),panel={fields:Object.fromEntries(E.draftFields.music.map(k=>[k,''])),sections:Array.from({length:40},()=>Object.fromEntries(E.draftRows.music.columns.map(k=>[k,'']))),avoid:[],deliverables:[]};
 const element=()=>({children:[],textContent:'',value:'row-40',disabled:false,classList:{toggle(){}},append(...values){this.children.push(...values);},replaceChildren(){this.children=[];}});
 const nodes=new Map(),document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);},createElement:element};
 const s={panel,ids:Array.from({length:40},(_,i)=>'row-'+(i+1)),selectedId:'row-40',busy:false,visible:true,focusResult:true,focusCalls:[],errors:[]};
 s.dom=DOM.bind(document,{labels:require('../web/music-readiness.js').labels,visible:()=>s.visible,busy:()=>s.busy,onCheck:()=>{s.controller.check();return true;},onLocate:(index,revision)=>{const issue=s.controller.locate(index,revision);if(!issue)return false;s.focusCalls.push({index,revision,field:issue.field,row:issue.row});if(s.throwFocus)throw Error('synthetic focus failure');return s.focusResult;},onError:e=>s.errors.push(e.message)});
 s.controller=Review.createController({capture:()=>({panel:s.panel,ids:s.ids,selectedId:s.selectedId}),onState:s.dom.render});
 s.node=id=>document.getElementById(id);s.next=()=>s.node('section-issue-next').onclick();s.previous=()=>s.node('section-issue-previous').onclick();s.check=()=>s.node('section-issue-check').onclick();s.button=i=>s.node('section-review-issues').children[i].children[0];s.controller.check();return s;
}
test('all five original-row issues can be traversed without changing source or advancing outside bounds',()=>{const s=setup(),before=structuredClone(s.panel);assert.equal(s.previous(),false);for(let i=0;i<5;i++)assert.equal(s.next(),true);assert.equal(s.next(),false);assert.equal(s.node('section-issue-next').disabled,true);assert.deepEqual(s.focusCalls.map(v=>v.field),['name','focus','texture','bars','energy']);assert.ok(s.focusCalls.every(v=>v.row===40));for(let i=0;i<4;i++)assert.equal(s.previous(),true);assert.equal(s.previous(),false);assert.match(s.node('section-issue-note').textContent,/1／5/);assert.deepEqual(s.panel,before);});
test('an explicit list click establishes the cursor for both directions',()=>{const s=setup();assert.equal(s.button(3).onclick(),true);assert.equal(s.next(),true);assert.equal(s.previous(),true);assert.deepEqual(s.focusCalls.map(v=>v.index),[3,4,3]);});
test('a failed or throwing focus keeps the last successful cursor and allows retry',()=>{const s=setup();s.focusResult=false;assert.equal(s.next(),false);assert.match(s.node('section-issue-note').textContent,/尚未定位/);s.focusResult=true;s.throwFocus=true;assert.equal(s.next(),false);assert.deepEqual(s.errors,['synthetic focus failure']);s.throwFocus=false;assert.equal(s.next(),true);assert.equal(s.focusCalls.at(-1).index,0);});
test('selected field edits invalidate old locations and exact restoration resumes the current cursor',()=>{const s=setup();s.next();s.panel.sections[39].name='edited';s.controller.refresh();const old=s.button(0);assert.equal(s.next(),false);assert.equal(old.onclick(),false);assert.match(s.node('section-issue-note').textContent,/重查這一段/);s.panel.sections[39].name='';s.controller.refresh();assert.equal(s.next(),true);assert.equal(s.focusCalls.at(-1).index,1);});
test('source checking refuses an old callback even before a DOM refresh',()=>{const s=setup();const old=s.button(0);s.panel.sections[39].focus='new';assert.equal(old.onclick(),false);assert.equal(s.focusCalls.length,0);});
test('a new report revision resets the cursor and refuses previously retained list callbacks',()=>{const s=setup();s.button(3).onclick();const old=s.button(4);assert.equal(s.check(),true);assert.equal(old.onclick(),false);assert.match(s.node('section-issue-note').textContent,/尚未定位/);assert.equal(s.next(),true);assert.equal(s.focusCalls.at(-1).index,0);});
test('selection and same-value ID order changes stop stale navigation',()=>{for(const edit of [s=>s.selectedId='row-1',s=>s.ids.reverse()]){const s=setup();s.next();edit(s);s.controller.refresh();assert.equal(s.next(),false);assert.equal(s.previous(),false);assert.equal(s.focusCalls.length,1);}});
test('unrelated global and other section edits preserve the selected five-field cursor',()=>{const s=setup();s.next();s.panel.fields['music-bpm']='123';s.panel.sections[0].focus='another section';s.controller.refresh();assert.equal(s.next(),true);assert.equal(s.focusCalls.at(-1).index,1);});
test('busy, hidden and missing selection disable both toolbar and retained list callbacks at action time',()=>{for(const edit of [s=>s.busy=true,s=>s.visible=false,s=>s.node('section-order').value='']){const s=setup(),old=s.button(0);edit(s);s.dom.refresh();assert.equal(s.node('section-issue-next').disabled,true);assert.equal(s.node('section-issue-check').disabled,true);assert.equal(s.next(),false);assert.equal(old.onclick(),false);assert.equal(s.check(),false);assert.equal(s.focusCalls.length,0);}});
test('zero issues disables sequential navigation and still requires whole-song validation',()=>{const s=setup();Object.assign(s.panel.sections[39],{name:'section',bars:'8',energy:'3',focus:'action',texture:'sound'});s.check();assert.equal(s.next(),false);assert.equal(s.previous(),false);assert.match(s.node('section-issue-note').textContent,/仍須整首歌曲驗證/);assert.equal(s.focusCalls.length,0);});
const messages={missing:'段落未檢查',stale:'段落改變',empty:'段落零項仍須驗證',progress:'段落待辦'};
test('shared cursor isolates injected literal messages while default shot wording remains unchanged',()=>{const m={...messages},state={busy:false,detailCount:0,hasReport:false,revision:1,stale:false,visible:true},c=Cursor.createController({capture:()=>state,onLocate:()=>true,messages:m});m.missing='changed';assert.equal(c.refresh().message,messages.missing);state.hasReport=true;state.detailCount=1;assert.match(c.refresh().message,/段落待辦 尚未定位/);state.stale=true;assert.equal(c.refresh().message,messages.stale);state.stale=false;state.detailCount=0;assert.equal(c.refresh().message,messages.empty);const old=Cursor.createController({capture:()=>state,onLocate:()=>true});assert.equal(old.refresh().message,'這一鏡沒有欄位待辦；仍須整份分鏡驗證。');});
test('unknown, invalid Unicode and non-JSON message metadata reject without getter reads or callbacks',()=>{for(const edit of [m=>m.extra='x',m=>m.empty='',m=>m.stale='x'.repeat(1025),m=>m.missing='\ud800',m=>m.progress=1,m=>Object.defineProperty(m,'hidden',{value:'x'})]){const m={...messages};edit(m);assert.throws(()=>Cursor.createController({capture:()=>{throw Error('capture must not run');},onLocate:()=>{throw Error('focus must not run');},messages:m}));}let reads=0;const m={...messages};Object.defineProperty(m,'progress',{enumerable:true,get(){reads++;return 'x';}});assert.throws(()=>Cursor.createController({messages:m}));assert.equal(reads,0);});
test('shared field geometry and legacy wrapper keep identical scroll offsets without source mutation',()=>{assert.equal(LegacyPosition.scrollOffset,Position.scrollOffset);for(const value of [{top:35,bottom:77,height:844,coverBottom:110},{top:912,bottom:973,height:500,coverBottom:100},{top:100,bottom:150,height:500,coverBottom:0},{top:900,bottom:1500,height:720,coverBottom:268}]){const before=structuredClone(value);assert.equal(Position.scrollOffset(value),LegacyPosition.scrollOffset(value));assert.deepEqual(value,before);}});
function actual(){const t=fs.readFileSync('web/app.js','utf8'),a=t.indexOf('function focusMusicSectionIssue('),b=t.indexOf('sectionReviewDOM=',a);let rect={top:20,bottom:62};const field={value:'  原文 🎵  ',isConnected:true,disabled:false,focus(){context.document.activeElement=this;},getBoundingClientRect:()=>rect};const toolbar={getBoundingClientRect:()=>({top:8,bottom:110})},calls=[];const context={musicIssueTarget:()=>field,$:id=>{assert.equal(id,'section-issue-toolbar');return toolbar;},document:{activeElement:null},window:{innerHeight:500,scrollBy:v=>{calls.push(v);rect={top:rect.top-v.top,bottom:rect.bottom-v.top};}},MusicEditorFieldPosition:Position};vm.runInNewContext(t.slice(a,b),context);return {context,field,calls,get rect(){return rect;}};}
test('actual song focus helper reveals the native field below the toolbar and preserves its literal value',()=>{const s=actual();assert.equal(s.context.focusMusicSectionIssue({scope:'sections',row:40,field:'focus'}),true);assert.equal(s.field.value,'  原文 🎵  ');assert.equal(s.context.document.activeElement,s.field);assert.ok(s.rect.top>=122&&s.rect.bottom<=488);assert.equal(s.calls.length,1);});
test('actual song focus helper refuses missing, detached and disabled targets before focus or scrolling',()=>{for(const change of [s=>s.context.musicIssueTarget=()=>null,s=>s.field.isConnected=false,s=>s.field.disabled=true]){const s=actual();change(s);assert.equal(s.context.focusMusicSectionIssue({}),false);assert.equal(s.context.document.activeElement,null);assert.equal(s.calls.length,0);}});
test('fixed assets precede both adapters and toolbar uses semantic buttons with a short-height fallback',()=>{const h=fs.readFileSync('web/index.html','utf8'),css=fs.readFileSync('web/style.css','utf8');assert.ok(h.indexOf('/editor-field-position.js')<h.indexOf('/shot-field-position.js'));assert.ok(h.indexOf('/issue-cursor.js')<h.indexOf('/music-section-review-dom.js'));assert.match(h,/id="section-issue-toolbar"[^>]+role="group"[^>]+aria-label="逐項段落待辦"/);for(const id of ['check','previous','next'])assert.match(h,new RegExp('id="section-issue-'+id+'" type="button"'));assert.match(css,/@media\(max-height:400px\)\{\.section-issue-tools\{position:static\}\}/);});
