// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),P=require('../web/issue-page.js'),D=require('../web/issue-page-dom.js');
const source=(detailCount=200,totalCount=240)=>({detailCount,totalCount,revision:1,stale:false,busy:false,visible:true});
test('all retained details appear once across bounded pages with original absolute indices',()=>{const s=source(),before=structuredClone(s),seen=[];for(let page=0;page<10;page++){const v=P.present(s,page);assert.equal(v.pages,10);assert.equal(v.first,page*20+1);assert.equal(v.last,(page+1)*20);seen.push(...v.indices);assert.match(v.message,/全部 240 項/);assert.match(v.message,/前 200 項/);}assert.deepEqual(seen,Array.from({length:200},(_,i)=>i));assert.deepEqual(s,before);});
test('empty single full partial and capped pages never invent details',()=>{for(const count of [0,1,20,21,199,200]){const s=source(count,count),v=P.present(s,99);assert.equal(v.page,Math.max(0,Math.ceil(count/20)-1));assert.equal(v.last,count);assert.equal(v.canNext,false);assert.ok(v.indices.length<=20);}assert.deepEqual(P.present(source(0,0)).indices,[]);assert.equal(P.present(source(21,21),1).first,21);});
test('unknown metadata nonfinite and impossible totals are rejected',()=>{for(const patch of [{extra:1},{detailCount:201},{detailCount:-1},{detailCount:1.5},{totalCount:199},{totalCount:Infinity},{revision:-1},{busy:0},{stale:null},{visible:'true'}])assert.throws(()=>P.present({...source(),...patch}));for(const n of [-1,0.1,Infinity,NaN,'1'])assert.throws(()=>P.present(source(),n));});
test('stale summaries stay readable while all stale and busy hidden locations are blocked',()=>{for(const patch of [{stale:true},{busy:true},{visible:false}]){let s={...source(),...patch};const c=P.createController({capture:()=>s});assert.equal(c.locate(0,1),null);if(patch.stale){assert.equal(c.move(1),true);assert.equal(c.view().first,21);assert.match(c.view().message,/上一份/);}else assert.equal(c.move(1),false);}});
test('controller handles first middle last backward reset and source revision without mutating source',()=>{let s=source(),seen=[];const c=P.createController({capture:()=>s,onState:v=>seen.push(v)});assert.equal(c.move(-1),false);assert.equal(c.move(2),false);assert.equal(c.move(1),true);assert.deepEqual(c.locate(20,1),{index:20,revision:1});assert.equal(c.locate(0,1),null);assert.equal(c.locate(40,1),null);s={...s,revision:2};assert.equal(c.locate(20,1),null);assert.equal(c.locate(20,2).index,20);c.reset();assert.equal(c.view().first,1);assert.equal(c.locate(20,2),null);seen[0].indices[0]=999;assert.equal(c.view().indices[0],0);});
test('capture changes between checks reject page moves and locations',()=>{let calls=0;const c=P.createController({capture:()=>({...source(),revision:++calls})});assert.equal(c.move(1),false);assert.equal(c.locate(0,calls+1),null);assert.equal(c.view().page,0);});
class Element{constructor(){this.children=[];this.disabled=false;this.hidden=false;this.textContent='';}replaceChildren(){this.children=[];}append(v){this.children.push(v);}}
test('DOM pager renders only current indices and old callbacks cannot locate a newer report',()=>{const nodes=Object.fromEntries(['previous','next','page-note','pages','issues'].map(n=>['report-'+n,new Element()])),document={getElementById:id=>nodes[id]},located=[];let s=source();const c=D.bind(document,{prefix:'report',capture:()=>s,renderItem:(index,locate,disabled)=>({index,locate,disabled}),onLocate:index=>{located.push(index);return true;}});const old=nodes['report-issues'].children[0].locate;assert.equal(nodes['report-issues'].children.length,20);nodes['report-next'].onclick();assert.equal(nodes['report-issues'].children[0].index,20);assert.equal(old(),false);assert.equal(nodes['report-issues'].children[0].locate(),true);s={...s,revision:2};assert.equal(nodes['report-issues'].children[0].locate(),false);c.reset();assert.equal(nodes['report-issues'].children[0].locate(),true);assert.deepEqual(located,[20,0]);s={...s,stale:true};c.refresh();assert.equal(nodes['report-issues'].children[0].disabled,true);assert.equal(nodes['report-issues'].children[0].locate(),false);nodes['report-next'].onclick();assert.equal(nodes['report-issues'].children[0].index,20);assert.equal(nodes['report-previous'].disabled,false);});
test('fixed workbench loads pager modules before app and reuses two reports without wire additions',()=>{const fs=require('node:fs'),html=fs.readFileSync('web/index.html','utf8'),app=fs.readFileSync('web/app.js','utf8'),server=fs.readFileSync('music_lab_server.py','utf8');for(const n of ['issue-page.js','issue-page-dom.js']){assert.ok(html.indexOf('/'+n)<html.indexOf('/app.js'));assert.ok(server.includes('"/'+n+'"'));}for(const prefix of ['lyrics-review','lyrics-export']){for(const suffix of ['pages','previous','next','page-note'])assert.ok(html.includes('id="'+prefix+'-'+suffix+'"'));assert.ok(app.includes("prefix:'"+prefix+"'"));}assert.ok(!app.includes('data.issues.slice(0,20)'));});
test('focused boundary navigation stays on an available page control and unrelated focus is preserved',()=>{const nodes=Object.fromEntries(['previous','next','page-note','pages','issues'].map(n=>['report-'+n,new Element()])),document={getElementById:id=>nodes[id],activeElement:null},s=source(21,21);for(const n of ['previous','next']){const e=nodes['report-'+n];e.isConnected=true;e.focus=()=>document.activeElement=e;}D.bind(document,{prefix:'report',capture:()=>s,renderItem:index=>({index}),onLocate:()=>true});document.activeElement=nodes['report-next'];nodes['report-next'].onclick();assert.equal(document.activeElement,nodes['report-previous']);nodes['report-previous'].onclick();assert.equal(document.activeElement,nodes['report-next']);const field={};document.activeElement=field;nodes['report-next'].onclick();assert.equal(document.activeElement,field);});
