// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
const report=require('../web/delivery-report.js'),importer=require('../web/delivery-import.js'),pack=require('../web/delivery-package.js');
const hash=async raw=>crypto.createHash('sha256').update(raw).digest('hex');
const rows=JSON.parse(execFileSync('python',['-X','utf8','-c',`import json,sys
sys.path.insert(0,"tests")
from test_delivery_report import fixture
from musiclab.delivery_report import files
rows=[]
for scope in ['music','storyboard','lyrics','audio']:
 old,new,source,comparison=fixture(scope)
 rows.append({'old':old,'new':new,'source':source,'comparison':comparison,'expected':files(source,comparison)})
print(json.dumps(rows,ensure_ascii=False))`],{encoding:'utf8',timeout:10000}));
test('Python and browser report bytes agree for all four scopes with literal unsafe labels',()=>{for(const row of rows){const saved=structuredClone(row);assert.deepEqual(report.files(row.source,row.comparison),row.expected);assert.deepEqual(row,saved);const md=row.expected['delivery-comparison.md'];assert.ok(!md.includes('<script>'));assert.ok(!md.includes('新合成原文'));assert.match(md,/ZIP SHA-256：[0-9a-f]{64}/);}});
test('metadata corruption and unsupported schemas refuse instead of producing trusted-looking reports',()=>{for(const mutate of [s=>s.path='outside',s=>s.schema_version=true,s=>s.archive_sha256='bad',s=>s.manifest.tool_version='99',s=>s.manifest.file_count=true,s=>s.manifest.source_bytes=0,s=>s.manifest.files[0].bytes=true]){const s=structuredClone(rows[0].source);mutate(s);assert.throws(()=>report.files(s,rows[0].comparison));}for(const mutate of [c=>c.schema_version=true,c=>c.scope='audio',c=>c.counts.added=true,c=>c.files.reverse(),c=>c.files[0].status='unchanged',c=>c.incoming.source_bytes=0,c=>c.files[0].name='../outside.txt',c=>c.files[0].incoming.sha256='0'.repeat(64)]){const c=structuredClone(rows[0].comparison);mutate(c);assert.throws(()=>report.files(rows[0].source,c));}});
test('result clones metadata and handles 128 rows within the report byte budget',()=>{const full=JSON.parse(execFileSync('python',['-X','utf8','-c',`import io,json
from musiclab.delivery_package import prepare
from musiclab.delivery_inspect import read
from musiclab.delivery_review import compare
from musiclab.delivery_report import files
old={'scope':'lyrics','files':{f'old{i:02}-'+('a'*80)+'.txt':'old' for i in range(64)}}
new={'scope':'lyrics','label':'💡'*200,'files':{f'new{i:02}-'+('b'*80)+'.txt':'' for i in range(64)}}
s=read(io.BytesIO(prepare(new).archive)).data;c=compare(old,{'scope':'lyrics','files':new['files']})
print(json.dumps({'source':s,'comparison':c,'expected':files(s,c)},ensure_ascii=False))`],{encoding:'utf8',timeout:10000}));assert.deepEqual(report.files(full.source,full.comparison),full.expected);assert.equal(full.comparison.files.length,128);assert.ok(Object.values(full.expected).reduce((n,t)=>n+Buffer.byteLength(t),0)<=256*1024);const r=report.report(full.source,full.comparison);r.source.manifest.files.length=0;assert.equal(full.source.manifest.files.length,64);});
function setup(row=rows[0],custom={}){const view={scope:row.old.scope,revision:1,resultRevision:1,bundle:{files:structuredClone(row.old.files)},busy:false,media:[{}]},errors=[];let replacements=0;const wire={files:row.new.files,data:row.source,meta:{version:pack.version,protocol_version:1,needs_review:true}},selected={bytes:row.source.archive_bytes,sha256:row.source.archive_sha256,manifest:row.source.manifest};const options={capture:()=>view,read:async()=>({wire,selected}),hash,onError:e=>errors.push(e.message),replace:r=>{replacements++;view.bundle={files:r.files};view.resultRevision++},restore:b=>{view.bundle=b;view.resultRevision++},...custom};return{view,errors,options,replacements:()=>replacements,file:{name:'selected.zip',size:selected.bytes}};}
test('controller report download is read only and later apply and undo remain available',async()=>{for(const row of rows){const s=setup(row),c=importer.createController(s.options);await c.inspect(s.file);const before=structuredClone(s.view.bundle),media=s.view.media[0];assert.deepEqual(c.report(),row.expected);assert.deepEqual(s.view.bundle,before);assert.equal(s.replacements(),0);assert.equal(s.view.media[0],media);assert.equal(c.status().canApply,true);assert.equal(c.apply(),true);assert.equal(c.report(),null);assert.equal(c.undo(),true);assert.deepEqual(s.view.bundle,before);}});
test('editing results, forms, media, switching scope or busy state rejects stale report metadata',async()=>{for(const change of [v=>v.revision++,v=>v.resultRevision++,v=>v.bundle.files['new.txt']='later',v=>v.media=[{}],v=>v.scope='audio',v=>v.busy=true]){const s=setup(),c=importer.createController(s.options);await c.inspect(s.file);change(s.view);const before=structuredClone(s.view.bundle);assert.equal(c.report(),null);assert.deepEqual(s.view.bundle,before);assert.equal(s.replacements(),0);assert.equal(s.errors.length,1);}});
test('pending reads, cancelled selections and applied previews cannot export a report',async()=>{let release;const hold=new Promise(r=>release=r),s=setup();const read=s.options.read;s.options.read=async()=>{await hold;return read()};const c=importer.createController(s.options),work=c.inspect(s.file);assert.equal(c.report(),null);c.cancel();release();assert.equal(await work,false);assert.equal(c.report(),null);assert.equal(s.replacements(),0);});
function dom(s,throwSubmit=false){const ids=['delivery-import-file','delivery-import-preview','delivery-import-apply','delivery-import-undo','delivery-import-note','delivery-import-files','delivery-import-source','delivery-import-cancel','delivery-review-file','delivery-review-summary','delivery-review-before','delivery-review-incoming','delivery-review-before-note','delivery-review-incoming-note','delivery-reader','delivery-reader-side','delivery-reader-content','delivery-reader-note','delivery-reader-first','delivery-reader-previous','delivery-reader-next','delivery-search-query','delivery-search-find','delivery-search-more','delivery-search-previous','delivery-search-match','delivery-search-note','delivery-search-context-box','delivery-search-context','delivery-original-download','delivery-original-note','delivery-report-json','delivery-report-md','delivery-report-form','delivery-report-name','delivery-report-content'],e={},sent=[];for(const id of ids)e[id]={value:'',replaceChildren(){this.children=[];this.value=''},append(item){(this.children||=[]).push(item)}};s.options.downloadText=(name,content)=>{if(throwSubmit)throw Error('synthetic submit refusal');sent.push({name,content});return true;};const context={MusicDeliveryImport:importer};vm.runInNewContext(fs.readFileSync('web/delivery-text-dom.js','utf8'),Object.assign(context,{MusicDeliveryText:require('../web/delivery-text.js')}));context.MusicDeliveryContext=require('../web/delivery-context.js');context.MusicDeliverySearch=require('../web/delivery-search.js');vm.runInNewContext(fs.readFileSync('web/delivery-search-dom.js','utf8'),context);vm.runInNewContext(fs.readFileSync('web/delivery-import-dom.js','utf8'),context);const c=context.MusicDeliveryImportDom.createAdapter({getElementById:id=>e[id],createElement:()=>({})},s.options);return{e,sent,c};}
test('DOM submits the exact selected format without applying and rejects stale selection',async()=>{const s=setup(),{e,sent,c}=dom(s);assert.equal(e['delivery-report-json'].disabled,true);await c.inspect(s.file);for(const [id,name] of [['delivery-report-json','delivery-comparison.json'],['delivery-report-md','delivery-comparison.md']]){assert.equal(e[id].disabled,false);assert.equal(e[id].onclick(),true);assert.deepEqual(sent.at(-1),{name,content:rows[0].expected[name]});}assert.equal(s.replacements(),0);assert.equal(c.status().canApply,true);s.view.revision++;c.refresh();assert.equal(e['delivery-report-json'].disabled,true);assert.equal(e['delivery-report-json'].onclick(),false);assert.equal(sent.length,2);});
test('download submission failure preserves preview and current results for retry',async()=>{const s=setup(),{e,c}=dom(s,true);await c.inspect(s.file);const before=structuredClone(s.view.bundle);assert.equal(e['delivery-report-json'].onclick(),false);assert.deepEqual(s.view.bundle,before);assert.equal(c.status().canApply,true);assert.equal(s.replacements(),0);assert.deepEqual(s.errors,['synthetic submit refusal']);});
