// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const B=require('../web/text-byte-context.js'),P=require('../web/text-verification.js'),C=require('../web/text-verification-controller.js'),D=require('../web/text-verification-dom.js');
const bytes=s=>new TextEncoder().encode(s),flush=()=>new Promise(setImmediate),expected=s=>({name:'original.txt',content:s});
test('old report remains exactly seven fields and opt-in report is byte-for-byte identical',()=>{const a=expected('原文\r\n🎵\n'),b=bytes('原文\r\n🎶\n');const old=P.inspect(a,b),rich=P.inspectWithContext(a,b);assert.equal(JSON.stringify(old),JSON.stringify(rich.report));assert.equal(Object.keys(old).length,7);assert.ok(rich.context);assert.equal(Object.hasOwn(old,'context'),false);});
test('complete match exposes no context including empty and full eight MiB sources',()=>{for(const s of ['', '\ufeff原文\r\n\0🎵','x'.repeat(P.maxBytes)]){const r=P.inspectWithContext(expected(s),bytes(s));assert.equal(r.report.matched,true);assert.equal(r.context,null);}});
test('same-size tail mismatch still scans the full eight MiB and retains only bounded context',()=>{const s='x'.repeat(P.maxBytes),b=bytes(s);b[b.length-1]=121;const r=P.inspectWithContext(expected(s),b);assert.equal(r.report.first_difference_byte,P.maxBytes-1);assert.ok(JSON.stringify(r.context).length<1200);assert.equal(r.context.selected.byte_at_difference,121);});
test('opt-out comparison does not decode invalid UTF8 and rejects nonboolean options',()=>{assert.equal(B.compare(bytes('x'),new Uint8Array([255])).context,null);for(const x of [1,null,'true',{}])assert.throws(()=>B.compare(bytes('x'),bytes('y'),x));});
test('raw array type and capacity limits reject before comparison',()=>{for(const b of [{byteLength:1},new Uint16Array([1]),new Uint8Array(B.maxBytes+1)])assert.throws(()=>B.compare(bytes('x'),b,true));});
test('BOM newline NUL and HTML remain exact in bounded display and raw bytes',()=>{const s='\ufeffA\r\n\0<script>🎵',r=P.inspectWithContext(expected(s),bytes(s.replace('A','B')));assert.match(r.context.expected.display,/\\ufeffA\\r\\n\\u0000<script>/);assert.ok(r.context.expected.hex.startsWith('ef bb bf'));assert.equal(r.context.expected.byte_at_difference,65);});
test('bidi and invisible controls are visible escapes without changing comparison',()=>{const r=P.inspectWithContext(expected('a\u202eb\u200bc\u2066d'),bytes('x\u202eb\u200bc\u2066d'));assert.equal(r.context.expected.display,'"a\\u202eb\\u200bc\\u2066d"');assert.equal(r.report.first_difference_byte,0);});
test('valid multibyte windows expand at most three bytes per edge and preserve complete characters',()=>{for(let n=0;n<32;n++){const s='a'.repeat(n)+'🎵'.repeat(30)+'中文'.repeat(20),b=bytes(s);b[bytes('a'.repeat(n)+'🎵'.repeat(10)).length]=120;const r=P.inspectWithContext(expected(s),b);for(const w of [r.context.expected,r.context.selected])assert.ok(w.end_byte-w.start_byte<=39);assert.equal(r.context.expected.display_status,'utf8');assert.ok(!r.context.expected.display.includes('�'));}});
test('invalid UTF8 is disclosed and raw bytes are never replaced by replacement characters',()=>{const r=P.inspectWithContext(expected('abc'),new Uint8Array([97,255,99]));assert.equal(r.context.selected.display_status,'invalid_utf8');assert.equal(r.context.selected.display,null);assert.equal(r.context.selected.hex,'61 ff 63');});
test('truncated partial Unicode is invalid while source remains a complete character',()=>{const r=P.inspectWithContext(expected('原文🎵'),bytes('原文🎵').slice(0,-1));assert.equal(r.context.selected.byte_at_difference,null);assert.equal(r.context.selected.display_status,'invalid_utf8');assert.equal(r.context.expected.display_status,'utf8');});
test('empty candidate and strict prefix show explicit EOF with exact byte offsets',()=>{for(const s of ['', 'ab']){const r=P.inspectWithContext(expected('abc'),bytes(s));assert.equal(r.report.first_difference_byte,s.length);assert.equal(r.context.selected.byte_at_difference,null);assert.equal(r.context.selected.total_bytes,s.length);assert.equal(r.context.selected.hex,s?'61 62':'');}});
test('extra candidate bytes show EOF on expected side and raw additional data on selected side',()=>{const r=P.inspectWithContext(expected('ab'),bytes('abc'));assert.equal(r.context.expected.byte_at_difference,null);assert.equal(r.context.selected.byte_at_difference,99);assert.equal(r.report.first_difference_byte,2);});
function harness(){const state={scope:'music',revision:1,busy:false,dirty:false,visible:true,source:expected('原文\r\n🎵')},reports=[],errors=[];const c=C.createController({capture:()=>state,describe:f=>({name:'selected.txt',size:f.data.length}),readFile:f=>f.read?f.read():Promise.resolve(f.data),onReport:(r,m)=>reports.push({r,m}),onError:e=>errors.push(e.message)});return {state,c,reports,errors,file:s=>({data:bytes(s)})};}
test('view deeply isolates bounded context and report callbacks retain original proof only',async()=>{const h=harness();await h.c.verify(h.file('原文\r\n🎶'));const v=h.c.view();v.difference.expected.display='wrong';v.difference.selected.hex='wrong';assert.notEqual(h.c.view().difference.expected.display,'wrong');assert.equal(Object.keys(h.reports[0].r).length,7);assert.equal(Object.hasOwn(h.reports[0].r,'context'),false);assert.equal(Object.hasOwn(h.c.view().difference,'bytes'),false);});
test('new read match read failure cancel and dispose clear prior context',async()=>{for(const action of ['match','error','cancel','dispose']){const h=harness();await h.c.verify(h.file('other'));assert.ok(h.c.view().difference);if(action==='match')await h.c.verify(h.file(h.state.source.content));if(action==='error')await h.c.verify({...h.file('x'),read:async()=>{throw Error('read failure');}});if(action==='cancel'||action==='dispose')h.c[action]();assert.equal(h.c.view().difference,null);}});
test('source revision complete text dirty and hidden state invalidate context without altering source',async()=>{for(const mutate of [s=>s.revision++,s=>s.source.content+='後續',s=>s.dirty=true,s=>s.visible=false]){const h=harness();await h.c.verify(h.file('other'));mutate(h.state);const saved=structuredClone(h.state);h.c.refresh();assert.equal(h.c.view().difference,null);assert.deepEqual(h.state,saved);}});
test('late differing result cannot replace newer matching proof or expose stale text',async()=>{const h=harness();let done;const f=h.file('late');f.read=()=>new Promise(r=>done=()=>r(f.data));const pending=h.c.verify(f);await h.c.verify(h.file(h.state.source.content));done();assert.equal(await pending,false);assert.equal(h.c.view().report.matched,true);assert.equal(h.c.view().difference,null);assert.equal(h.reports.length,1);});
test('current source is rechecked after awaiting reader before context is prepared',async()=>{const h=harness();let done;const f=h.file('wrong');f.read=()=>new Promise(r=>done=()=>r(f.data));const pending=h.c.verify(f);h.state.source.content='後續原文';done();assert.equal(await pending,false);assert.equal(h.c.view().difference,null);assert.equal(h.reports.length,0);});
function dom(prefix,{boxes=true}={}){const h=harness();h.state.scope=prefix==='draft'?'draft':prefix==='audio-accept'?'audio':'music';const nodes={},handlers=new Map(),document={getElementById:id=>nodes[id]};for(const suffix of ['file','note','source','cancel',...(boxes?['context','expected-context','selected-context']:[])])nodes[prefix+'-verify-'+suffix]={id:prefix+'-verify-'+suffix,files:[],disabled:false,value:'',textContent:'',dataset:{},hidden:false};class File{constructor(s){this.data=bytes(s);this.name='candidate.txt';this.size=this.data.length;}arrayBuffer(){return Promise.resolve(this.data.buffer);}}const a=D.bind(document,{capture:()=>h.state,FileType:File,ids:{file:prefix+'-verify-file',note:prefix+'-verify-note',source:prefix+'-verify-source',cancel:prefix+'-verify-cancel'},events:{addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:(n,f)=>handlers.delete(n)},onReport:r=>h.reports.push(r)});const choose=async s=>{nodes[prefix+'-verify-file'].files=[new File(s)];nodes[prefix+'-verify-file'].onchange();await flush();};return {...h,nodes,handlers,a,choose};}
for(const prefix of ['text','draft','audio-accept'])test(prefix+' renders literal bounded source and candidate context without changing callback or panel',async()=>{const h=dom(prefix),saved=structuredClone(h.state);await h.choose('<script>\r\n🎶');assert.equal(h.nodes[prefix+'-verify-context'].hidden,false);assert.match(h.nodes[prefix+'-verify-selected-context'].textContent,/<script>/);assert.equal(h.nodes[prefix+'-verify-selected-context'].innerHTML,undefined);assert.equal(Object.keys(h.reports[0]).length,7);assert.deepEqual(h.state,saved);h.a.dispose();});
test('DOM resets all rendered excerpts after match cancel invalidation pagehide and dispose',async()=>{for(const action of ['match','cancel','invalidate','pagehide','dispose']){const h=dom('text');await h.choose('other');if(action==='match')await h.choose(h.state.source.content);if(action==='cancel')h.nodes['text-verify-cancel'].onclick();if(action==='invalidate'){h.state.revision++;h.a.refresh();}if(action==='pagehide')h.handlers.get('pagehide')();if(action==='dispose')h.a.dispose();assert.equal(h.nodes['text-verify-context'].hidden,true);assert.equal(h.nodes['text-verify-expected-context'].textContent,'');assert.equal(h.nodes['text-verify-selected-context'].textContent,'');if(action!=='dispose')h.a.dispose();}});
test('legacy DOM without optional context boxes retains original matching and differing flows',async()=>{const h=dom('text',{boxes:false});await h.choose('other');assert.equal(h.reports[0].matched,false);await h.choose(h.state.source.content);assert.equal(h.reports[1].matched,true);h.a.dispose();});
