// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const V=require('../web/draft-compare-view.js'),Dom=require('../web/draft-compare-dom.js'),Model=require('../web/draft-compare.js'),Select=require('../web/draft-compare-download.js');
const descriptors=values=>values.map(scope=>({scope,status:'changed'}));
test('view keeps only bounded scope metadata and returns isolated page selections',()=>{const v=V.create(),input=descriptors(Array(25).fill('lyrics'));v.reset(input);input.length=0;const out=v.view();out.indices.length=0;out.expandedIndices.push(0);assert.equal(v.view().count,25);assert.equal(v.view().indices.length,10);assert.equal(v.view().totalExpanded,0);});
test('page expansion affects only ten current entries and preserves other pages',()=>{const v=V.create();v.reset(descriptors(Array(25).fill('lyrics')));v.setPageExpanded(true);v.move(1);assert.equal(v.view().pageExpanded,0);v.toggle(12,true);assert.equal(v.view().totalExpanded,11);v.move(-1);assert.equal(v.view().pageExpanded,10);v.setPageExpanded(false);assert.equal(v.view().totalExpanded,1);v.move(1);assert.deepEqual(v.view().expandedIndices,[12]);});
test('scope filters retain original ordinal expansion without confusing duplicate row labels',()=>{const v=V.create();v.reset(descriptors(['music','lyrics','music','metadata']));v.toggle(2,true);v.selectScope('lyrics');v.toggle(1,true);v.selectScope('music');assert.deepEqual(v.view().indices,[0,2]);assert.deepEqual(v.view().expandedIndices,[2]);v.selectScope('all');assert.equal(v.view().totalExpanded,2);});
test('empty and full 200-entry views have bounded navigation and expansion',()=>{const v=V.create();assert.equal(v.view().pages,1);assert.equal(v.view().canExpand,false);v.reset(descriptors(Array(200).fill('audio')));for(let i=0;i<20;i++){v.setPageExpanded(true);v.move(1);}assert.equal(v.view().totalExpanded,200);assert.equal(v.view().page,19);assert.equal(v.view().canNext,false);for(let i=0;i<22;i++)v.move(-1);assert.equal(v.view().page,0);});
test('invalid scope lists reject before replacing an existing view',()=>{const v=V.create();v.reset(descriptors(['lyrics']));v.toggle(0,true);const before=v.view();let calls=0;const accessor=[];Object.defineProperty(accessor,0,{get(){calls++;return 'music';},enumerable:true});for(const bad of [null,{},Array(201).fill('music'),['other'],Array(1),accessor]){assert.throws(()=>v.reset(bad));assert.deepEqual(v.view(),before);}assert.equal(calls,0);});
test('only current-page positions and explicit boolean expansion are accepted',()=>{const v=V.create();v.reset(descriptors(Array(20).fill('music')));const before=v.view();for(const [index,open] of [[10,true],[-1,true],[0,'true'],[.5,true],[NaN,false]]){assert.throws(()=>v.toggle(index,open));assert.deepEqual(v.view(),before);}for(const bad of [0,null,undefined])assert.throws(()=>v.setPageExpanded(bad));assert.throws(()=>v.move(0));assert.throws(()=>v.selectScope('unknown'));assert.deepEqual(v.view(),before);});
test('new reports and explicit clear remove all previous reading progress',()=>{const v=V.create();v.reset(descriptors(Array(20).fill('lyrics')));v.setPageExpanded(true);v.move(1);v.selectScope('lyrics');v.reset(descriptors(['music']));assert.deepEqual(v.view().expandedIndices,[]);assert.equal(v.view().scope,'all');v.toggle(0,true);v.clear();assert.equal(v.view().count,0);assert.equal(v.view().totalExpanded,0);});
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners=new Map();this.hidden=false;this.disabled=false;this.value='';this.open=false;this.textContent='';this.attributes={};const classes=new Set();this.classList={add:v=>classes.add(v),remove:v=>classes.delete(v),contains:v=>classes.has(v)};}
 append(...v){this.children.push(...v);}replaceChildren(...v){this.children=v;}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,f){this.listeners.set(k,f);}removeEventListener(k,f){if(this.listeners.get(k)===f)this.listeners.delete(k);}emit(k){return this.listeners.get(k)?.();}focus(){}
}
function fixture(prefix,count=25){const elements=Object.fromEntries(['start','cancel','status','report','list','scope','previous','next','page','expand','collapse','open-note','kind','kind-note','row-collection','row-number','row-start','row-cancel','row-status','row-result','download-json','download-markdown','download-status'].map(k=>[k,new Element()]));elements.scope.value='all';const source={baseline:JSON.parse(fs.readFileSync(require.resolve('../examples/draft-comparison-baseline.json'),'utf8'))};source.current=structuredClone(source.baseline);source.current.panels.lyrics.cues=Array.from({length:count},(_,i)=>({start:'',end:'',text:`第${i}句🎵`}));const gate={identity:{},revision:[0],media:[{}],tab:'music',allowed:true,visible:true},errors=[],sent=[];let reads=0;const document={getElementById:id=>elements[id.slice((prefix+'-compare-').length)],createElement:t=>new Element(t),querySelector:()=>null};for(const el of Object.values(elements))el.focus=()=>{document.activeElement=el;};const adapter=Dom.bind(document,{prefix,capture:()=>{reads++;return source;},gate:()=>gate,onError:e=>errors.push(e.message),downloads:{createController:o=>({download:()=>sent.push(o.select())})}});return {elements,source,gate,errors,sent,document,adapter,get reads(){return reads;}};}
for(const prefix of ['draft','library']){
 test(`${prefix} manual expansion survives page return and scope filters`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const first=n.list.children[0];first.open=true;await first.emit('toggle');assert.match(n['open-note'].textContent,/本頁已展開 1 \/ 10/);await n.next.emit('click');await n.previous.emit('click');assert.equal(n.list.children[0].open,true);n.scope.value='music';await n.scope.emit('change');assert.match(n['open-note'].textContent,/共展開 1 筆/);n.scope.value='lyrics';await n.scope.emit('change');assert.equal(n.list.children[0].open,true);assert.deepEqual(s.errors,[]);s.adapter.dispose();});
 test(`${prefix} bulk expansion keeps focus usable and checks full source once per click`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const before=structuredClone(s.source),reads=s.reads;n.expand.focus();await n.expand.emit('click');assert.equal(s.reads,reads+1);assert.ok(n.list.children.every(e=>e.open));assert.equal(s.document.activeElement,n.collapse);for(const e of n.list.children)await e.emit('toggle');assert.equal(s.reads,reads+1);await n.next.emit('click');assert.ok(n.list.children.every(e=>!e.open));await n.expand.emit('click');await n.previous.emit('click');n.collapse.focus();await n.collapse.emit('click');assert.equal(s.document.activeElement,n.expand);assert.match(n['open-note'].textContent,/共展開 10 筆/);assert.deepEqual(s.source,before);s.adapter.dispose();});
 test(`${prefix} queued detached callbacks cannot modify a new page or comparison`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const old=n.list.children[0],callback=old.listeners.get('toggle');await n.next.emit('click');assert.equal(old.listeners.size,0);old.open=true;const reads=s.reads;callback();assert.equal(s.reads,reads);assert.match(n['open-note'].textContent,/共展開 0 筆/);const second=n.list.children[0],late=second.listeners.get('toggle');await n.start.emit('click');second.open=true;late();assert.match(n['open-note'].textContent,/共展開 0 筆/);assert.ok(n.list.children.every(e=>!e.open));s.adapter.dispose();});
 test(`${prefix} hidden source edits reject expansion before updating reading progress`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const old=n.list.children[0];s.source.current.panels.lyrics.cues[0].text='後續編修';await n.expand.emit('click');assert.equal(n.report.hidden,true);assert.equal(old.listeners.size,0);assert.equal(n['open-note'].textContent,'');assert.equal(s.source.current.panels.lyrics.cues[0].text,'後續編修');assert.equal(n.expand.disabled,true);assert.match(s.errors.at(-1),/來源已有變更/);s.adapter.dispose();});
 test(`${prefix} stale refresh and explicit clear discard progress without complete source reads`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');await n.expand.emit('click');const reads=s.reads,rows=[...n.list.children];s.gate.revision[0]++;s.adapter.refresh();assert.equal(s.reads,reads);assert.equal(n.report.hidden,true);assert.ok(rows.every(e=>e.listeners.size===0));await n.start.emit('click');assert.ok(n.list.children.every(e=>!e.open));await n.expand.emit('click');s.adapter.clear();assert.equal(n.list.children.length,0);assert.equal(n['open-note'].textContent,'');s.adapter.dispose();});
 test(`${prefix} current report downloads are byte-identical after expand filter and pagination`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const report=await Model.compare(s.source);await n['download-json'].emit('click');await n['download-markdown'].emit('click');await n.expand.emit('click');await n.next.emit('click');n.scope.value='lyrics';await n.scope.emit('change');await n.collapse.emit('click');await n['download-json'].emit('click');await n['download-markdown'].emit('click');assert.deepEqual(s.sent,[Select.select(report,'json'),Select.select(report,'markdown'),Select.select(report,'json'),Select.select(report,'markdown')]);s.adapter.dispose();});
 test(`${prefix} truncated reports expand only retained entries and keep complete count hints`,async()=>{const s=fixture(prefix,1000),n=s.elements;await n.start.emit('click');const expected=await Model.compare(s.source);assert.ok(expected.details.length>10&&expected.details.length<=200);assert.match(n.page.textContent,new RegExp(expected.details.length+' 筆保留明細；完整計數'));await n.expand.emit('click');assert.equal(n.list.children.length,10);assert.match(n['open-note'].textContent,/共展開 10 筆/);assert.match(n.status.textContent,/作品差異 1000/);s.adapter.dispose();});
 test(`${prefix} dispose removes owned static and dynamic listeners and rejects saved callbacks`,async()=>{const s=fixture(prefix),n=s.elements;await n.start.emit('click');const rows=[...n.list.children],callback=rows[0].listeners.get('toggle');s.adapter.dispose();assert.ok(rows.every(e=>e.listeners.size===0));assert.ok(Object.values(n).every(e=>e.listeners.size===0));rows[0].open=true;const reads=s.reads;callback();assert.equal(s.reads,reads);assert.equal(n['open-note'].textContent,'');});
 test(`${prefix} empty comparison leaves bulk and page controls disabled`,async()=>{const s=fixture(prefix,0),n=s.elements;await n.start.emit('click');assert.equal(n.expand.disabled,true);assert.equal(n.collapse.disabled,true);assert.equal(n.previous.disabled,true);assert.equal(n.next.disabled,true);assert.match(n['open-note'].textContent,/本頁已展開 0 \/ 0/);s.adapter.dispose();});
}
test('both native sections load the pure view first and expose named current-page controls',()=>{const html=fs.readFileSync(require.resolve('../web/index.html'),'utf8');assert.ok(html.indexOf('/draft-compare-view.js')<html.indexOf('/draft-compare-dom.js'));for(const p of ['draft','library'])for(const suffix of ['expand','collapse','open-note','kind','kind-note'])assert.match(html,new RegExp(`id="${p}-compare-${suffix}"`));assert.match(html,/展開本頁差異/);assert.match(html,/收合本頁差異/);});
test('kind selection intersects scope while counts describe all retained kinds in that scope',()=>{const v=V.create();v.reset([{scope:'lyrics',status:'added'},{scope:'music',status:'changed'},{scope:'lyrics',status:'removed'},{scope:'metadata',status:'changed'},{scope:'lyrics',status:'changed'}]);v.selectKind('changed');assert.deepEqual(v.view().indices,[1,3,4]);v.selectScope('lyrics');assert.deepEqual(v.view().indices,[4]);assert.deepEqual(v.view().kindCounts,{all:3,changed:1,added:1,removed:1});v.selectKind('added');assert.deepEqual(v.view().indices,[0]);v.selectScope('audio');assert.equal(v.view().count,0);assert.deepEqual(v.view().kindCounts,{all:0,changed:0,added:0,removed:0});});
test('descriptor and returned kind counts are isolated without retaining report text',()=>{const source=[{scope:'lyrics',status:'added'}],v=V.create();v.reset(source);source[0].status='removed';source[0].scope='music';const out=v.view();out.kindCounts.added=0;out.indices.push(99);assert.deepEqual(v.view().kindCounts,{all:1,changed:0,added:1,removed:0});assert.deepEqual(v.selectKind('added').indices,[0]);assert.equal(v.selectScope('music').count,0);});
test('unknown incomplete or accessor descriptors reject atomically without invoking getters',()=>{const v=V.create();v.reset([{scope:'lyrics',status:'added'}]);v.toggle(0,true);v.selectKind('added');const before=v.view();let calls=0;const accessor={scope:'lyrics'};Object.defineProperty(accessor,'status',{get(){calls++;return 'added';}});for(const row of ['lyrics',null,{scope:'lyrics'},{scope:'lyrics',status:'other'},{scope:'other',status:'added'},{scope:'lyrics',status:'added',text:'forbidden'},accessor]){assert.throws(()=>v.reset([{scope:'music',status:'changed'},row]));assert.deepEqual(v.view(),before);}for(const bad of [null,'unknown',true,{},'Changed']){assert.throws(()=>v.selectKind(bad));assert.deepEqual(v.view(),before);}assert.equal(calls,0);});
test('filtered page expansion uses original ordinals across duplicate labels and kind changes',()=>{const v=V.create();v.reset(Array.from({length:200},(_,i)=>({scope:i%2?'lyrics':'music',status:i%3===0?'added':i%3===1?'changed':'removed'})));v.selectKind('added');v.setPageExpanded(true);const first=[...v.view().indices];v.move(1);v.toggle(v.view().indices[0],true);const last=v.view().expandedIndices[0];v.selectScope('lyrics');v.selectKind('removed');v.setPageExpanded(true);v.selectScope('all');v.selectKind('added');assert.deepEqual(v.view().expandedIndices,first);v.move(1);assert.deepEqual(v.view().expandedIndices,[last]);v.setPageExpanded(false);assert.equal(v.view().totalExpanded,20);});
test('changing either filter resets only its page and new reports clear both filters and expansion',()=>{const v=V.create();v.reset(Array.from({length:25},()=>({scope:'lyrics',status:'added'})));v.move(1);v.selectKind('added');assert.equal(v.view().page,0);v.setPageExpanded(true);v.move(1);v.selectScope('lyrics');assert.equal(v.view().page,0);assert.equal(v.view().kind,'added');v.reset([{scope:'metadata',status:'changed'}]);assert.equal(v.view().kind,'all');assert.equal(v.view().scope,'all');assert.equal(v.view().totalExpanded,0);v.clear();assert.deepEqual(v.view().kindCounts,{all:0,changed:0,added:0,removed:0});});
function mixedFixture(prefix){const s=fixture(prefix);s.source.baseline.panels.lyrics.cues=Array.from({length:27},(_,i)=>({start:'',end:'',text:`原第${i}句`}));s.source.current.panels.music.fields['music-bpm']='96.5';s.source.current.panels.music.deliverables.push('新增合成交付');return s;}
for(const prefix of ['draft','library']){
 test(`${prefix} change kinds combine with scope and show retained counts including empty intersections`,async()=>{const s=mixedFixture(prefix),n=s.elements;await n.start.emit('click');const r=await Model.compare(s.source);for(const kind of ['all','changed','added','removed']){n.kind.value=kind;await n.kind.emit('change');const count=r.details.filter(d=>kind==='all'||d.status===kind).length;assert.match(n.page.textContent,new RegExp(`此篩選 ${count} 筆保留明細`));}n.scope.value='lyrics';await n.scope.emit('change');assert.match(n['kind-note'].textContent,/全部 27 筆、變更 25 筆、新增 0 筆、移除 2 筆/);n.kind.value='added';await n.kind.emit('change');assert.match(n.list.children[0].textContent,/沒有保留/);assert.equal(n.expand.disabled,true);assert.equal(n.kind.disabled,false);assert.equal(n.next.disabled,true);assert.deepEqual(s.errors,[]);s.adapter.dispose();});
 test(`${prefix} kind switches retain manual expansion and ignore detached toggle callbacks`,async()=>{const s=mixedFixture(prefix),n=s.elements;await n.start.emit('click');n.kind.value='removed';await n.kind.emit('change');const row=n.list.children[0];row.open=true;await row.emit('toggle');const late=row.listeners.get('toggle');n.kind.value='added';await n.kind.emit('change');const reads=s.reads;late();assert.equal(s.reads,reads);n.kind.value='removed';await n.kind.emit('change');assert.equal(n.list.children[0].open,true);assert.match(n['open-note'].textContent,/共展開 1 筆/);assert.deepEqual(s.errors,[]);s.adapter.dispose();});
 test(`${prefix} filtered bulk expansion changes only its current ten retained ordinals`,async()=>{const s=mixedFixture(prefix),n=s.elements;await n.start.emit('click');n.kind.value='removed';await n.kind.emit('change');await n.expand.emit('click');assert.match(n['open-note'].textContent,/共展開 2 筆/);n.kind.value='changed';await n.kind.emit('change');const reads=s.reads;n.expand.focus();await n.expand.emit('click');assert.equal(s.reads,reads+1);assert.equal(s.document.activeElement,n.collapse);assert.match(n['open-note'].textContent,/共展開 12 筆/);await n.next.emit('click');assert.ok(n.list.children.every(e=>!e.open));n.kind.value='removed';await n.kind.emit('change');assert.ok(n.list.children.every(e=>e.open));await n.collapse.emit('click');assert.match(n['open-note'].textContent,/共展開 10 筆/);s.adapter.dispose();});
 test(`${prefix} source changes are checked before changing kind and preserve subsequent edits`,async()=>{const s=mixedFixture(prefix),n=s.elements;await n.start.emit('click');s.source.current.panels.lyrics.cues[0].text='後來的原文';n.kind.value='removed';await n.kind.emit('change');assert.equal(n.report.hidden,true);assert.equal(n.kind.disabled,true);assert.equal(n.kind.value,'all');assert.equal(n['kind-note'].textContent,'');assert.equal(s.source.current.panels.lyrics.cues[0].text,'後來的原文');assert.match(s.errors.at(-1),/來源已有變更/);s.adapter.dispose();});
 test(`${prefix} all type filters keep full JSON and Markdown bytes and new reports reset reading state`,async()=>{const s=mixedFixture(prefix),n=s.elements;await n.start.emit('click');const report=await Model.compare(s.source),expected=[Select.select(report,'json'),Select.select(report,'markdown')];for(const kind of ['changed','added','removed','all']){n.kind.value=kind;await n.kind.emit('change');await n['download-json'].emit('click');await n['download-markdown'].emit('click');assert.deepEqual(s.sent.slice(-2),expected);}await n.expand.emit('click');n.kind.value='removed';await n.kind.emit('change');await n.start.emit('click');assert.equal(n.kind.value,'all');assert.match(n['open-note'].textContent,/共展開 0 筆/);s.adapter.clear();assert.equal(n['kind-note'].textContent,'');assert.equal(n.kind.disabled,true);s.adapter.dispose();assert.equal(n.kind.listeners.size,0);});
}
