// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../web/draft-compare.js'),C=require('../web/draft-compare-controller.js'),D=require('../web/draft-compare-dom.js');
const root=path.resolve(__dirname,'..');
const draft=()=>JSON.parse(fs.readFileSync(path.join(root,'examples/draft-comparison-baseline.json'),'utf8'));
const request=()=>{const baseline=draft(),current=structuredClone(baseline);current.panels.music.fields['music-title']=' 原文\r\n🎵 ';return {baseline,current};};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function setup(generate=P.compare){let payload=request(),g={identity:{},revision:[0,0,0,0],media:[{},null],tab:'music',allowed:true,visible:true},reads=0;const states=[],ready=[],errors=[];
 const c=C.create({capture:()=>{reads++;return payload;},gate:()=>g,generate,onState:v=>states.push(v),onReady:v=>ready.push(v),onError:e=>errors.push(e.message)});
 return {c,g,payload,states,ready,errors,get reads(){return reads;}};
}
test('complete local comparison preserves raw inputs and separates metadata from four-panel changes',async()=>{
 const p=request(),before=structuredClone(p);p.current.saved_at='new';p.current.panels.lyrics.cues=[{start:'00.0',end:'1',text:''}];const expected=structuredClone(p),r=await P.compare(p);
 assert.equal(r.change_count,3);assert.equal(r.panels.music.change_count,1);assert.equal(r.panels.lyrics.change_count,1);assert.equal(r.metadata_changed,true);assert.deepEqual(p,expected);assert.equal(r.details[1].fields[0].after.excerpt,' 原文\r\n🎵 ');assert.equal(r.details[2].fields[0].before,null);assert.deepEqual(before.baseline,p.baseline);
});
test('metadata-only and fully identical reports do not claim creative differences',async()=>{const a=draft(),b=structuredClone(a);b.tab='lyrics';b.saved_at='later';const r=await P.compare({baseline:a,current:b});assert.equal(r.creative_changed,false);assert.equal(r.metadata.changed_fields.length,2);const same=await P.compare({baseline:a,current:a});assert.equal(same.status,'identical');assert.equal(same.change_count,0);assert.equal(same.source.baseline_sha256,same.source.current_sha256);assert.ok(same.source.baseline_bytes>500);});
test('UTF8 prefix never splits emoji and empty strings remain distinct from missing values',async()=>{const p=request();p.current.panels.music.fields['music-title']='a'.repeat(127)+'🎵尾';p.current.panels.lyrics.cues=[{start:'',end:'',text:''}];const r=await P.compare(p),v=r.details[0].fields[0].after;assert.equal(v.excerpt,'a'.repeat(127));assert.equal(v.excerpt_truncated,true);assert.equal(v.bytes,134);const empty=r.details[1].fields[2];assert.equal(empty.before,null);assert.equal(empty.after.bytes,0);assert.equal(empty.after.excerpt,'');assert.match(empty.after.sha256,/^e3b0c442/);});
test('10000 raw cues are completely counted after the 200-detail limit',async()=>{const a=draft(),b=structuredClone(a);a.panels.lyrics.cues=Array.from({length:10000},()=>({start:'',end:'',text:'a'}));b.panels.lyrics.cues=a.panels.lyrics.cues.map(v=>({...v,text:'b'}));const r=await P.compare({baseline:a,current:b});assert.equal(r.change_count,10000);assert.equal(r.details.length,200);assert.equal(r.details_truncated,true);assert.equal(r.panels.lyrics.collections.cues.changed_rows,10000);});
test('detail byte budget keeps whole rows and full counts for control-heavy storyboard text',async()=>{const a=draft(),b=structuredClone(a),columns=require('../contracts/draft-v3.json').rows.storyboard.columns;a.panels.storyboard.shots=Array.from({length:80},()=>Object.fromEntries(columns.map(k=>[k,k==='screen_direction'?'neutral':k==='motif_id'?'':'x'])));b.panels.storyboard.shots=a.panels.storyboard.shots.map(v=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k,['screen_direction','motif_id'].includes(k)?x:'\0'.repeat(100)])));const r=await P.compare({baseline:a,current:b});assert.equal(r.change_count,80);assert.ok(r.details.length<80&&r.details.length>0);assert.equal(r.details_truncated,true);assert.ok(Buffer.byteLength(JSON.stringify(r,null,2)+'\n')+Buffer.byteLength(P.markdown(r))<=P.maxReportBytes);assert.ok(r.details.every(d=>d.fields.length===10));});
test('positional insertion reports subsequent changed rows and never guesses stable IDs or moves',async()=>{const a=draft(),b=structuredClone(a);a.panels.lyrics.cues=[{start:'1',end:'2',text:'重複'},{start:'2',end:'3',text:'重複'}];b.panels.lyrics.cues=[{start:'',end:'',text:'新句'},...structuredClone(a.panels.lyrics.cues)];const r=await P.compare({baseline:a,current:b});assert.deepEqual(r.details.map(d=>[d.row,d.status]),[[1,'changed'],[2,'changed'],[3,'added']]);});
test('source rejects unknown shape, legacy, sparse arrays, getters, invalid Unicode and oversized canonical documents',()=>{
 const a=draft();for(const mutate of [v=>v.extra=true,v=>v.schema_version=2,v=>v.panels.lyrics.cues=Array(1),v=>v.panels.music.fields['music-title']='\ud800',v=>v.panels.music.fields['music-title']='x'.repeat(P.maxDraft)]){const b=structuredClone(a);mutate(b);assert.throws(()=>P.prepare({baseline:a,current:b}));}
 let calls=0;const b=structuredClone(a);Object.defineProperty(b,'saved_at',{get(){calls++;return 'bad';},enumerable:true});assert.throws(()=>P.prepare({baseline:a,current:b}));assert.equal(calls,0);
});
test('hash failure yields no completed report and source objects stay unchanged',async()=>{const p=request(),before=structuredClone(p);await assert.rejects(P.compare(p,{sha256:async()=>{throw Error('failed');}}),/failed/);await assert.rejects(P.compare(p,{sha256:async()=> 'wrong'}),/雜湊/);assert.deepEqual(p,before);});
test('controller produces a current report, isolates callbacks and ignores generated capture clock changes',async()=>{const s=setup();assert.equal(await s.c.run(),true);const report=s.c.read();s.payload.baseline.saved_at='next clock';assert.deepEqual(s.c.read(),report);s.ready[0].details.length=0;assert.ok(s.c.read().details.length>0);assert.equal(s.states.at(-1).ready,true);});
test('refresh and invalidation only read lightweight gate and stale reports cannot be read',async()=>{const s=setup();await s.c.run();const reads=s.reads;s.g.revision[0]++;s.c.refresh();assert.equal(s.reads,reads);assert.equal(s.states.at(-1).stale,true);assert.throws(()=>s.c.read(),/已有變更/);s.c.clear();assert.equal(s.states.at(-1).ready,false);});
test('late success after each gate identity, media, revision or tab change is ignored',async()=>{for(const mutate of [g=>g.identity={},g=>g.media[0]={},g=>g.revision[1]++,g=>g.tab='lyrics',g=>g.allowed=false,g=>g.visible=false]){const d=deferred(),s=setup(()=>d.promise),pending=s.c.run();mutate(s.g);d.resolve(await P.compare(s.payload));assert.equal(await pending,false);assert.equal(s.ready.length,0);assert.equal(s.errors.length,0);}});
test('unannounced source mutation is rejected before committing a late success',async()=>{const d=deferred(),s=setup(()=>d.promise),pending=s.c.run(),old=await P.compare(s.payload);s.payload.current.panels.music.fields['music-title']='changed';d.resolve(old);assert.equal(await pending,false);assert.equal(s.ready.length,0);assert.match(s.errors[0],/來源已有編修/);});
test('late errors after cancel clear or dispose never replace a later valid report',async()=>{for(const method of ['cancel','clear','dispose']){const d=deferred(),s=setup(()=>d.promise),pending=s.c.run();s.c[method]();d.reject(Error('late'));assert.equal(await pending,false);assert.equal(s.errors.length,0);assert.equal(s.ready.length,0);}});
test('busy hidden and disposed controllers do not capture complete drafts',async()=>{for(const flag of ['allowed','visible']){const s=setup();s.g[flag]=false;assert.equal(await s.c.run(),false);assert.equal(s.reads,0);}const s=setup();s.c.dispose();assert.equal(await s.c.run(),false);assert.equal(s.reads,0);});
test('failed comparison is retryable and concurrent starts never duplicate generation',async()=>{let calls=0;const d=deferred(),s=setup(async p=>{calls++;if(calls===1)return d.promise;return P.compare(p);}),first=s.c.run();assert.equal(await s.c.run(),false);assert.equal(calls,1);d.reject(Error('temporary'));assert.equal(await first,false);assert.equal(await s.c.run(),true);assert.equal(s.ready.length,1);});
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners=new Map();this.hidden=false;this.disabled=false;this.value='';this.textContent='';this.classList={add(){},remove(){}};this.attributes={};}
 append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,f){this.listeners.set(k,f);}removeEventListener(k,f){if(this.listeners.get(k)===f)this.listeners.delete(k);}async emit(k){return this.listeners.get(k)?.();}
}
function domSetup(){const elements={};for(const s of ['start','cancel','status','report','list','scope','previous','next','page','expand','collapse','open-note','download-json','download-markdown','download-status'])elements[s]=new Element();elements.scope.value='all';const document={getElementById:id=>elements[id.replace('draft-compare-','')],createElement:tag=>new Element(tag),querySelector:()=>null};const p=request(),g={identity:{},revision:[0],media:[],tab:'music',allowed:true,visible:true};const errors=[];const downloads={createController:options=>require('../web/text-download.js').createController({...options,send:()=>true})};const adapter=D.bind(document,{prefix:'draft',downloads,capture:()=>p,gate:()=>g,onError:e=>errors.push(e.message)});return {elements,document,p,g,adapter,errors};}
test('literal DOM presentation keeps injected markup inert, shows both sides, filters and never applies drafts',async()=>{const s=domSetup();s.p.current.panels.music.fields['music-title']='<img src=x onerror=alert(1)>\r\n🎵';const before=structuredClone(s.p);await s.elements.start.emit('click');assert.match(s.elements.status.textContent,/作品差異 1/);assert.equal(s.elements.report.hidden,false);const row=s.elements.list.children[0];assert.equal(row.tagName,'details');const pre=row.children[1].children[1].children[1].children[1];assert.equal(pre.tagName,'pre');assert.equal(pre.textContent,'<img src=x onerror=alert(1)>\r\n🎵');assert.equal(pre.children.length,0);assert.deepEqual(s.p,before);s.elements.scope.value='lyrics';await s.elements.scope.emit('change');assert.match(s.elements.list.children[0].textContent,/沒有保留/);assert.equal(s.errors.length,0);});
test('DOM pagination shows at most ten full entries and stale refresh hides reports without source reads',async()=>{const s=domSetup();s.p.current.panels.lyrics.cues=Array.from({length:25},(_,i)=>({start:'',end:'',text:String(i)}));await s.elements.start.emit('click');assert.equal(s.elements.list.children.length,10);assert.match(s.elements.page.textContent,/1 \/ 3/);await s.elements.next.emit('click');assert.match(s.elements.page.textContent,/2 \/ 3/);await s.elements.next.emit('click');assert.equal(s.elements.list.children.length,6);assert.equal(s.elements.next.disabled,true);s.g.revision[0]++;s.adapter.refresh();assert.equal(s.elements.report.hidden,true);assert.equal(s.elements.scope.disabled,true);s.adapter.clear();assert.equal(s.elements.list.children.length,0);s.adapter.dispose();assert.equal(s.elements.start.listeners.size,0);});
test('workbench loads shared comparison assets before app and keeps explicit Apply controls separate',()=>{const html=fs.readFileSync(path.join(root,'web/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'web/app.js'),'utf8');for(const name of ['draft-compare.js','draft-compare-controller.js','draft-compare-dom.js'])assert.ok(html.indexOf('/'+name)<html.indexOf('/app.js'));for(const prefix of ['draft','library'])assert.match(html,new RegExp('id="'+prefix+'-compare-status"[^>]*role="status"'));assert.match(app,/draftPreview\.proposal\(\)/);assert.match(app,/checkedLibraryReview\(\)/);assert.match(app,/draftComparison\?\.invalidate/);assert.match(html,/id="draft-convert"/);assert.match(html,/id="library-apply"/);});
test('pagination transfers keyboard focus to an enabled control at both ends',async()=>{const s=domSetup();for(const el of Object.values(s.elements))el.focus=()=>{s.document.activeElement=el;};s.p.current.panels.lyrics.cues=Array.from({length:20},()=>({start:'',end:'',text:'literal'}));await s.elements.start.emit('click');s.document.activeElement=s.elements.next;await s.elements.next.emit('click');await s.elements.next.emit('click');assert.equal(s.document.activeElement,s.elements.previous);s.document.activeElement=s.elements.previous;await s.elements.previous.emit('click');await s.elements.previous.emit('click');assert.equal(s.document.activeElement,s.elements.next);});
test('unobserved gate changes settle late success and error as stale rather than leaving a busy message',async()=>{for(const fail of [false,true]){const d=deferred(),s=setup(()=>d.promise),pending=s.c.run();s.g.tab='lyrics';if(fail)d.reject(Error('late'));else d.resolve(await P.compare(s.payload));assert.equal(await pending,false);assert.equal(s.states.at(-1).busy,false);assert.equal(s.states.at(-1).stale,true);assert.equal(s.errors.length,0);}});
test('reading a completed report after a gate change publishes stale state before refusal',async()=>{const s=setup();await s.c.run();s.g.tab='lyrics';assert.throws(()=>s.c.read(),/已有變更/);assert.equal(s.states.at(-1).stale,true);assert.equal(s.states.at(-1).ready,false);});
