// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),S=require('../web/studio-timeline.js');
function setup(overrides={}){
 const e={id:'c1',value:{start:' 0.5 ',end:'1.5',text:' 原文 🎵  '}},s={entries:[e],row:{id:e.id,...e.value},duration:'004.000',media:{source:'blob:a',current_source:'blob:a',duration:4,position:0,ready:true,error:false},busy:false,visible:true,playing:false,start:'0.5',end:'1.5'},errors=[],writes=[];
 const capture=()=>structuredClone(s),options={capture,seek:v=>{s.media.position=v;writes.push(['seek',v]);},play:()=>{s.playing=true;writes.push(['play']);},pause:()=>{s.playing=false;writes.push(['pause']);},onError:e=>errors.push(e.message),...overrides};
 return {s,errors,writes,options,p:S.createPlayback(options),edit:()=>S.createCueEdit({capture,write:(id,a,b)=>{s.row.start=a;s.row.end=b;Object.assign(s.entries[0].value,{start:a,end:b});},onError:options.onError})};
}
test('timeline uses half-open boundaries, distinguishes gaps overlaps and invalid rows without changing inputs',()=>{
 const entries=[{id:'a',value:{start:'0',end:'1'}},{id:'b',value:{start:'1',end:'2'}},{id:'bad',value:{start:'\ufeff1',end:'2'}}],before=structuredClone(entries);
 assert.equal(S.active(entries,1,4).matches[0].id,'b');assert.equal(S.active(entries,2,4).status,'gap');assert.deepEqual(S.active(entries,1,4).invalid,[3]);assert.equal(S.active([...entries,{id:'c',value:{start:'.5',end:'1.5'}}],1,4).status,'overlap');assert.deepEqual(entries,before);assert.equal(S.active(entries,1,NaN).matches.length,0);
});
test('manual beat grid has bounded count and invalid or missing BPM never guesses a tempo',()=>{assert.deepEqual(S.beats('120','.25',2),[.25,.75,1.25,1.75]);for(const [b,o,d] of [['','0',4],['120','',4],['NaN','0',4],['401','0',4],['120','-1',4],['120','5',4],['120','0',1000]])assert.deepEqual(S.beats(b,o,d),[]);});
test('span rejects empty BOM negative-underflow reversed and media-outside ranges',()=>{for(const a of ['', '\ufeff0', '-1e-999', 'NaN'])assert.throws(()=>S.span(a,'1',4));for(const b of ['0','.5','4.001'])assert.throws(()=>S.span('.5',b,4));assert.deepEqual(S.span('.5','4',4),{start:.5,end:4});});
test('loop starts explicitly and seeks on end while preserving lyric source and native playback speed',async()=>{const a=setup(),row=structuredClone(a.s.row);assert.equal(await a.p.begin(true),true);assert.deepEqual(a.writes,[['seek',.5],['play']]);a.s.media.position=1.75;a.p.refresh();assert.equal(a.s.media.position,.5);assert.equal(a.s.playing,true);assert.deepEqual(a.s.row,row);assert.equal(a.p.stop(),true);assert.equal(a.s.media.position,.5);assert.equal(a.s.playing,false);});
test('no-op false wrong seek or thrown seek never starts loop',async()=>{for(const kind of ['noop','false','wrong','throw']){const a=setup(),p=S.createPlayback({...a.options,seek:v=>{if(kind==='false')return false;if(kind==='wrong')a.s.media.position=v+.01;if(kind==='throw')throw Error('denied');}});assert.equal(await p.begin(true),false);assert.ok(a.writes.every(w=>w[0]!=='play'));assert.equal(a.errors.length,1);}});
test('hidden busy error unready source mismatch and invalid loop ranges cannot start',async()=>{for(const mutate of [s=>s.visible=false,s=>s.busy=true,s=>s.media.error=true,s=>s.media.ready=false,s=>s.media.current_source='blob:b',s=>s.end='']){const a=setup();mutate(a.s);assert.equal(await a.p.begin(true),false);assert.deepEqual(a.writes,[]);}});
test('gate or loop-range change stops owned playback once and keeps native position',async()=>{for(const mutate of [s=>s.visible=false,s=>s.busy=true,s=>s.end='2']){const a=setup();await a.p.begin(true);a.s.media.position=.8;mutate(a.s);a.p.refresh();a.p.refresh();assert.equal(a.s.playing,false);assert.equal(a.s.media.position,.8);assert.equal(a.writes.filter(w=>w[0]==='pause').length,1);}});
test('replacement source releases ownership without pausing replacement playback',async()=>{const a=setup();await a.p.begin(true);Object.assign(a.s.media,{source:'blob:b',current_source:'blob:b',position:2});a.p.refresh();assert.equal(a.s.playing,true);assert.equal(a.s.media.position,2);assert.equal(a.writes.filter(w=>w[0]==='pause').length,0);assert.equal(a.p.stop(),false);});
test('pending start refuses duplicate and late completion after explicit stop pauses same source',async()=>{const a=setup();let resolve;const p=S.createPlayback({...a.options,play:()=>new Promise(r=>resolve=()=>{a.s.playing=true;r();})});const result=p.begin(true);assert.equal(await p.begin(true),false);p.stop();resolve();assert.equal(await result,false);assert.equal(a.s.playing,false);assert.equal(a.writes.filter(w=>w[0]==='seek').length,1);});
test('late completion after replacing source does not pause replacement',async()=>{const a=setup();let resolve;const p=S.createPlayback({...a.options,play:()=>new Promise(r=>resolve=r)});const result=p.begin(true);Object.assign(a.s.media,{source:'blob:b',current_source:'blob:b'});a.s.playing=true;p.refresh();resolve();assert.equal(await result,false);assert.equal(a.s.playing,true);});
test('native ended at duration can restart loop but manual pause cannot',async()=>{const a=setup();a.s.end='4';await a.p.begin(true);a.s.media.position=4;a.s.playing=false;a.p.refresh(true);await Promise.resolve();assert.equal(a.s.media.position,.5);assert.equal(a.s.playing,true);a.s.playing=false;a.p.refresh();assert.equal(a.s.playing,false);});
test('play refusal and pause no-op report failure and never announce confirmed playback',async()=>{const a=setup(),p=S.createPlayback({...a.options,play:()=>false});assert.equal(await p.begin(),false);assert.equal(p.refresh().canStop,false);assert.equal(a.errors.length,1);const b=setup(),q=S.createPlayback({...b.options,pause:()=>{}});await q.begin();assert.equal(q.dispose(),false);assert.equal(b.s.playing,true);assert.equal(b.errors.length,1);});
test('cue proposal only previews, cancellation preserves all raw values and application has exact undo',()=>{const a=setup(),c=a.edit(),before=structuredClone(a.s);assert.equal(c.propose(.6,1.6),true);assert.deepEqual(a.s,before);c.cancel();assert.deepEqual(a.s,before);c.propose(.6,1.6);assert.equal(c.apply(),true);assert.equal(a.s.row.text,before.row.text);assert.equal(a.s.duration,before.duration);assert.equal(a.s.row.start,'0.6');assert.equal(c.undo(),true);assert.deepEqual(a.s,before);});
test('cue source, selection, other rows, duration and media changes invalidate stale proposal',()=>{for(const mutate of [s=>s.row.text+='x',s=>s.row.id='other',s=>s.entries.push({id:'c2',value:{start:'2',end:'3',text:'x'}}),s=>s.duration='5',s=>s.media.source='b',s=>s.visible=false,s=>s.busy=true]){const a=setup(),c=a.edit();c.propose(.6,1.6);mutate(a.s);c.refresh();const before=structuredClone(a.s);assert.equal(c.apply(),false);assert.deepEqual(a.s,before);}});
test('cue false no-op partial write throws or wrong raw readback cannot establish undo',()=>{for(const kind of ['false','noop','partial','throw','wrong']){const a=setup(),c=S.createCueEdit({capture:a.options.capture,write:(id,x,y)=>{if(kind==='false')return false;if(kind==='throw')throw Error('no');if(kind==='partial')a.s.row.start=x;if(kind==='wrong'){a.s.row.start='00.6';a.s.row.end=y;Object.assign(a.s.entries[0].value,{start:'00.6',end:y});}},onError:a.options.onError});c.propose(.6,1.6);assert.equal(c.apply(),false);assert.equal(c.refresh().canUndo,false);assert.equal(a.errors.length,1);}});
test('cue failed undo retains record for retry and never replaces newer edits',()=>{const a=setup();let refuse=false;const c=S.createCueEdit({capture:a.options.capture,write:(id,x,y)=>{if(refuse)return false;a.s.row.start=x;a.s.row.end=y;Object.assign(a.s.entries[0].value,{start:x,end:y});},onError:a.options.onError});c.propose(.6,1.6);c.apply();refuse=true;assert.equal(c.undo(),false);assert.equal(c.refresh().canUndo,true);refuse=false;assert.equal(c.undo(),true);c.propose(.6,1.6);c.apply();a.s.row.text='new';const before=structuredClone(a.s);assert.equal(c.undo(),false);assert.deepEqual(a.s,before);});
test('cue reentrant apply is refused during native write',()=>{const a=setup();let c,inner;c=S.createCueEdit({capture:a.options.capture,write:(id,x,y)=>{inner=c.apply();a.s.row.start=x;a.s.row.end=y;Object.assign(a.s.entries[0].value,{start:x,end:y});},onError:a.options.onError});c.propose(.6,1.6);assert.equal(c.apply(),true);assert.equal(inner,false);});
function imageSetup(){let count=0;const revoked=[],pending=new Map(),c=S.createImages({createURL:()=>`blob:${++count}`,revokeURL:u=>revoked.push(u),load:u=>new Promise((resolve,reject)=>pending.set(u,{resolve,reject}))});return {c,revoked,pending,file:{type:'image/png',name:'test.png',size:12}};}
test('images accept decoded bounded local files and replace only after success',async()=>{const a=imageSetup(),p=a.c.select('s1',a.file);a.pending.get('blob:1').resolve({width:10,height:10});assert.equal(await p,true);const q=a.c.select('s1',a.file);a.pending.get('blob:2').reject(Error('decode'));await assert.rejects(q);assert.equal(a.c.get('s1').url,'blob:1');assert.deepEqual(a.revoked,['blob:2']);a.c.remove('s1');assert.deepEqual(a.revoked,['blob:2','blob:1']);});
test('image validation rejects SVG oversized file and excessive pixels without replacing art',async()=>{const a=imageSetup();for(const file of [{...a.file,type:'image/svg+xml'},{...a.file,size:12*1024*1024+1}])await assert.rejects(a.c.select('s1',file));const p=a.c.select('s1',a.file);a.pending.get('blob:1').resolve({width:10000,height:10000});await assert.rejects(p);assert.equal(a.c.get('s1'),null);assert.deepEqual(a.revoked,['blob:1']);});
test('late image load cannot resurrect removed replaced or disposed shots and each URL revoked once',async()=>{for(const action of ['remove','retain','dispose','replace']){const a=imageSetup(),p=a.c.select('s1',a.file);let newer;if(action==='remove')a.c.remove('s1');if(action==='retain')a.c.retain([]);if(action==='dispose')a.c.dispose();if(action==='replace'){newer=a.c.select('s1',{...a.file,name:'new.png'});a.pending.get('blob:2').resolve({width:10,height:10});await newer;}a.pending.get('blob:1').resolve({width:10,height:10});assert.equal(await p,false);assert.equal(a.c.get('s1')?.name||null,action==='replace'?'new.png':null);assert.equal(a.revoked.filter(u=>u==='blob:1').length,1);}});

test('image decode cannot commit after its gate changes',async()=>{const a=imageSetup();let allowed=true;const p=a.c.select('s1',a.file,()=>allowed);allowed=false;a.pending.get('blob:1').resolve({width:10,height:10});assert.equal(await p,false);assert.equal(a.c.get('s1'),null);assert.deepEqual(a.revoked,['blob:1']);});
test('cue identity requires unique ids and the same original row values',()=>{for(const mutate of [s=>s.entries.push(structuredClone(s.entries[0])),s=>s.row.text='wrong',s=>s.entries[0].id='']){const a=setup();mutate(a.s);const c=a.edit(),before=structuredClone(a.s);assert.equal(c.propose(.6,1.6),false);assert.deepEqual(a.s,before);}});
