// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),P=require('../web/editor-copy.js'),DOM=require('../web/editor-order-dom.js');
function element(){return {isConnected:true,hidden:false,disabled:false,value:'',children:[],listeners:new Map(),addEventListener(t,f){this.listeners.set(t,f);},removeEventListener(t,f){assert.equal(this.listeners.get(t),f);this.listeners.delete(t);},replaceChildren(){this.children=[];this.value='';this.rebuilds=(this.rebuilds||0)+1;},append(o){this.children.push(o);if(this.children.length===1)this.value=o.value;},focus(){this.focused=true;},emit(t,target=this){this.listeners.get(t)?.({target});}};}
function setup(){
 const nodes={},events=[];let busy=false,reads=0,writes=0;
 for(const [list,scope] of [['shots','storyboard'],['cues','lyrics']]){nodes[scope]=element();nodes[list]=element();for(const suffix of ['order','earlier','later','order-undo','order-show','order-note'])nodes[list+'-'+suffix]=element();}
 function render(list,entries){nodes[list].children=entries.map(e=>{const row={dataset:{historyId:e.id},parentElement:nodes[list],value:e.value,selected:false,querySelector:()=>({textContent:e.value.purpose||'',value:e.value.text||''}),toggleAttribute:(_n,v)=>row.selected=v,closest:()=>row};return row;});}
 for(const list of ['shots','cues'])render(list,Array.from({length:3},(_,i)=>({id:list+'-'+i,value:Object.fromEntries(P.specs[list].fields.map(k=>[k,k==='open'?false:k==='text'||k==='purpose'?'<script> 原文\r\n🎵 '+i:String(i)]))})));
 const document={getElementById:id=>nodes[id],createElement:tag=>{assert.equal(tag,'option');return {};}};
 const adapter=DOM.bind(document,{busy:()=>busy,capture:list=>{reads++;return nodes[list].children.map(r=>({id:r.dataset.historyId,value:r.value}));},apply:(list,e)=>{writes++;render(list,e);},focusRow:(...a)=>events.push(['focus',...a]),onChanged:(...a)=>events.push(['changed',...a]),onError:e=>events.push(['error',e.message])});adapter.refresh();
 return {nodes,adapter,events,render,set busy(v){busy=v;},get reads(){return reads;},get writes(){return writes;}};
}
test('native select moves stable identity and boundary action returns focus to the selector',()=>{const s=setup(),select=s.nodes['shots-order'];select.value='shots-1';select.emit('change');s.nodes['shots-earlier'].emit('click');assert.deepEqual(s.nodes.shots.children.map(r=>r.dataset.historyId),['shots-1','shots-0','shots-2']);assert.equal(select.value,'shots-1');assert.equal(select.focused,true);assert.equal(s.nodes['shots-earlier'].disabled,true);assert.equal(s.nodes['shots-order-undo'].disabled,false);assert.equal(s.nodes.shots.children[0].selected,true);s.nodes['shots-order-show'].emit('click');assert.deepEqual(s.events.at(-1),['focus','shots',0]);s.nodes['shots-order-undo'].emit('click');assert.deepEqual(s.nodes.shots.children.map(r=>r.dataset.historyId),['shots-0','shots-1','shots-2']);assert.equal(s.nodes['shots-order-undo'].disabled,true);});
test('busy hidden and disabled controls gate actions before capturing raw sources',()=>{for(const kind of ['busy','hidden','disabled']){const s=setup();if(kind==='busy')s.busy=true;if(kind==='hidden')s.nodes.lyrics.hidden=true;if(kind==='disabled')s.nodes['cues-later'].disabled=true;if(kind!=='disabled')s.adapter.refresh();s.nodes['cues-later'].emit('click');s.nodes['cues-order-show'].emit('click');assert.equal(s.reads,0);assert.equal(s.writes,0);if(kind!=='disabled')assert.deepEqual(s.events,[]);}});
test('labels are literal abbreviated display and typing updates one option without rebuilding choices or reading full sources',()=>{const s=setup(),select=s.nodes['cues-order'],options=[...select.children],count=select.rebuilds;assert.match(options[0].textContent,/<script>/);const row=s.nodes.cues.children[1];row.value.text='新句\r\n🎵';s.nodes.cues.emit('input',row);assert.equal(select.rebuilds,count);assert.deepEqual(select.children,options);assert.equal(options[1].textContent,'2 · 新句 🎵');assert.equal(s.reads,0);s.adapter.refresh();assert.equal(select.rebuilds,count);});
test('later edits survive undo and structural changes invalidate it without altering current rows',()=>{const s=setup();s.nodes['cues-later'].emit('click');const row=s.nodes.cues.children[1];row.value.text='後續編修\r\n';row.value.start='4.250';s.nodes.cues.emit('input',row);s.nodes['cues-order-undo'].emit('click');assert.equal(s.nodes.cues.children[0].value.text,'後續編修\r\n');assert.equal(s.nodes.cues.children[0].value.start,'4.250');s.nodes['cues-later'].emit('click');s.nodes.cues.children.pop();s.adapter.refresh();assert.equal(s.nodes['cues-order-undo'].disabled,true);assert.match(s.nodes['cues-order-note'].textContent,/不可撤回/);const writes=s.writes;s.nodes['cues-order-undo'].emit('click');assert.equal(s.writes,writes);});
test('empty state keeps all actions disabled and dispose removes fourteen owned listeners',()=>{const s=setup();s.nodes.cues.children=[];s.adapter.refresh();assert.equal(s.nodes['cues-order'].children[0].textContent,'尚無歌詞');for(const suffix of ['order','earlier','later','order-undo','order-show'])assert.equal(s.nodes['cues-'+suffix].disabled,true);s.adapter.dispose();for(const n of Object.values(s.nodes))assert.equal(n.listeners.size,0);});
test('actual app adapter writes only named scope, marks dirty and uses existing focus helper',()=>{const source=fs.readFileSync('web/app.js','utf8'),start=source.indexOf('editorOrder=MusicEditorOrderDOM.bind('),end=source.indexOf('function refreshDeletionHistory(',start),events=[];let options;const context={editorOrder:null,MusicEditorOrderDOM:{bind:(_d,o)=>{options=o;return {}; }},document:{},state:{busy:false},entriesFor:()=>[],collections:{shots:{scope:'storyboard',label:'鏡頭'},cues:{scope:'lyrics',label:'歌詞句'}},writeEntries:(...a)=>events.push(['write',...a]),markDirty:(...a)=>events.push(['dirty',...a]),focusEntry:(...a)=>events.push(['focus',...a]),say:(...a)=>events.push(['say',...a])};vm.runInNewContext(source.slice(start,end),context);for(const [list,scope] of [['shots','storyboard'],['cues','lyrics']]){events.length=0;options.apply(list,[]);options.focusRow(list,1);options.onChanged(list,{from:0,to:1},false);assert.deepEqual(events[1],['dirty',scope]);assert.deepEqual(events[2],['focus',list,1,list==='cues'?'new':'entry']);assert.match(events[3][1],/原時間與創作保留/);}options.onError(Error('保留'));assert.deepEqual(events.at(-1),['say','保留',true]);});
