// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Review=require('../web/lyrics-cue-review.js'),DOM=require('../web/lyrics-cue-review-dom.js'),Cursor=require('../web/issue-cursor.js'),Position=require('../web/editor-field-position.js');
function setup(){
 const nodes={};function element(){return {children:[],textContent:'',value:'row-221',disabled:false,hidden:false,isConnected:true,classList:{toggle(){}},append(...items){this.children.push(...items);},replaceChildren(){this.children=[];},focus(){document.activeElement=this;}};}
 const document={activeElement:null,getElementById:id=>nodes[id]||(nodes[id]=element()),createElement:element};
 const s={value:{lyrics:{title:' 合成🎵 ',duration:'8',cues:Array.from({length:220},()=>({start:'1',end:'2',text:' 原句🎵  '})).concat({start:'0',end:'8',text:' 長句 <literal> '})},ids:Array.from({length:221},(_,i)=>'row-'+(i+1)),selectedId:'row-221'},visible:true,busy:false,focusResult:true,calls:[],errors:[]};
 s.dom=DOM.bind(document,{visible:()=>s.visible,busy:()=>s.busy,onCheck:()=>{s.controller.check();return true;},onLocate:(index,revision)=>{const issue=s.controller.locate(index,revision);if(!issue)return false;if(s.throwFocus)throw Error('synthetic focus failure');s.calls.push({index,revision,...issue});return s.focusResult;},onError:e=>s.errors.push(e.message)});
 s.controller=Review.createController({capture:()=>s.value,onState:s.dom.render});s.node=id=>document.getElementById(id);s.next=()=>s.node('cue-issue-next').onclick();s.previous=()=>s.node('cue-issue-previous').onclick();s.check=()=>s.node('cue-issue-check').onclick();s.button=i=>s.node('cue-review-issues').children[i].children[0];s.controller.check();return s;
}
test('all 200 retained details traverse ten pages while all 220 relationships remain explicit',()=>{const s=setup(),before=structuredClone(s.value);assert.equal(s.previous(),false);for(let i=0;i<200;i++){assert.equal(s.next(),true);assert.equal(s.dom.page().page,Math.floor(i/20));}assert.equal(s.next(),false);assert.ok(s.node('cue-issue-next').disabled);assert.deepEqual(s.calls.map(v=>v.related_row),Array.from({length:200},(_,i)=>i+1));assert.ok(s.calls.every(v=>v.row===221&&v.field==='end'));assert.match(s.node('cue-issue-note').textContent,/200／200/);assert.match(s.node('cue-issue-note').textContent,/全部 220 項/);assert.match(s.node('cue-issue-note').textContent,/只走保留的前 200 項/);for(let i=0;i<199;i++)assert.equal(s.previous(),true);assert.equal(s.previous(),false);assert.equal(s.dom.page().page,0);assert.deepEqual(s.value,before);});
test('last first-page list click sets cursor and next previous synchronize page boundaries',()=>{const s=setup();assert.equal(s.button(19).onclick(),true);assert.equal(s.next(),true);assert.equal(s.dom.page().page,1);assert.equal(s.previous(),true);assert.equal(s.dom.page().page,0);assert.deepEqual(s.calls.map(v=>v.index),[19,20,19]);});
test('manual page change does not move cursor until an explicit list location succeeds',()=>{const s=setup();s.next();s.node('cue-review-next').onclick();assert.equal(s.calls.length,1);assert.equal(s.button(12).onclick(),true);assert.equal(s.next(),true);assert.equal(s.calls.at(-1).index,33);assert.equal(s.dom.page().page,1);});
test('failed and throwing focus retain successful cursor and current page for retry',()=>{const s=setup();s.button(19).onclick();s.focusResult=false;assert.equal(s.next(),false);assert.equal(s.dom.page().page,0);assert.match(s.node('cue-issue-note').textContent,/20／200/);s.focusResult=true;s.throwFocus=true;assert.equal(s.next(),false);assert.equal(s.dom.page().page,0);assert.deepEqual(s.errors,['synthetic focus failure']);s.throwFocus=false;assert.equal(s.next(),true);assert.equal(s.calls.at(-1).index,20);assert.equal(s.dom.page().page,1);});
test('other-row changes invalidate the full relationship source and exact restoration resumes cursor',()=>{const s=setup();s.next();s.value.lyrics.cues[0].start='3';s.controller.refresh();const old=s.button(1);assert.equal(s.next(),false);assert.equal(old.onclick(),false);assert.match(s.node('cue-issue-note').textContent,/重查這一句/);s.value.lyrics.cues[0].start='1';s.controller.refresh();assert.equal(s.next(),true);assert.equal(s.calls.at(-1).index,1);});
test('source checking refuses callbacks before a DOM refresh and preserves later edits',()=>{const s=setup(),old=s.button(0);s.value.lyrics.cues[0].text='new';const after=structuredClone(s.value);assert.equal(old.onclick(),false);assert.equal(s.calls.length,0);assert.deepEqual(s.value,after);});
test('selection and same-value stable-ID changes stop sequential locations',()=>{for(const edit of [s=>s.value.selectedId='row-1',s=>s.value.ids.reverse()]){const s=setup();s.next();edit(s);s.controller.refresh();assert.equal(s.next(),false);assert.equal(s.previous(),false);assert.equal(s.calls.length,1);}});
test('rechecking resets cursor and page and refuses old revision list callbacks',()=>{const s=setup();s.node('cue-review-next').onclick();const old=s.button(3);old.onclick();assert.equal(s.check(),true);assert.equal(s.dom.page().page,0);assert.equal(old.onclick(),false);assert.match(s.node('cue-issue-note').textContent,/尚未定位/);assert.equal(s.next(),true);assert.equal(s.calls.at(-1).index,0);});
test('busy hidden and missing selection guard both toolbar and retained callbacks at action time',()=>{for(const edit of [s=>s.busy=true,s=>s.visible=false,s=>s.node('cues-order').value='']){const s=setup(),old=s.button(0);edit(s);s.dom.refresh();assert.ok(s.node('cue-issue-next').disabled&&s.node('cue-issue-check').disabled);assert.equal(s.next(),false);assert.equal(old.onclick(),false);assert.equal(s.check(),false);assert.equal(s.calls.length,0);}});
test('selected zero disables navigation and retains whole lyrics and listening requirements',()=>{const s=setup();s.value.lyrics.cues[220].end='0.5';s.check();assert.equal(s.next(),false);assert.equal(s.previous(),false);assert.match(s.node('cue-issue-note').textContent,/仍須完整歌詞包與實聽/);assert.ok(s.node('cue-review-pages').hidden);});
test('global duration issue remains original row zero and can be the first sequential location',()=>{const s=setup();s.value.lyrics.duration='bad';s.check();assert.equal(s.next(),true);assert.equal(s.calls[0].row,0);assert.equal(s.calls[0].field,'duration');assert.match(s.node('cue-issue-note').textContent,/全部 221 項/);});
test('legacy cursor default still refuses 33 details and explicit limits reject before capture',()=>{let reads=0;for(const maxDetails of [0,201,1.5,true,'200',NaN,Infinity])assert.throws(()=>Cursor.createController({maxDetails,capture:()=>{reads++;},onLocate:()=>true}));assert.equal(reads,0);const source={busy:false,detailCount:33,hasReport:true,revision:1,stale:false,visible:true};assert.throws(()=>Cursor.createController({capture:()=>source,onLocate:()=>true}).refresh());source.detailCount=32;assert.equal(Cursor.createController({capture:()=>source,onLocate:()=>true}).refresh().detailCount,32);source.detailCount=200;assert.equal(Cursor.createController({maxDetails:200,capture:()=>source,onLocate:()=>true}).refresh().detailCount,200);source.detailCount=201;assert.throws(()=>Cursor.createController({maxDetails:200,capture:()=>source,onLocate:()=>true}).refresh());});
function actual(){const app=fs.readFileSync('web/app.js','utf8'),a=app.indexOf('function focusCueReviewIssue('),b=app.indexOf('cueReviewDOM=',a);let rect={top:20,bottom:62},toolbar={top:8,bottom:110};const calls=[],field={value:' 原句 🎵  ',isConnected:true,disabled:false,focus(){context.document.activeElement=this;},getBoundingClientRect:()=>rect},context={cueIssueTarget:()=>field,$:id=>{assert.equal(id,'cue-issue-toolbar');return {getBoundingClientRect:()=>toolbar};},document:{activeElement:null},window:{innerHeight:500,scrollBy:value=>{calls.push(value);rect={top:rect.top-value.top,bottom:rect.bottom-value.top};}},MusicEditorFieldPosition:Position};vm.runInNewContext(app.slice(a,b),context);return {context,field,calls,setToolbar:value=>{toolbar=value;},get rect(){return rect;}};}
test('actual cue focus exposes the native field below sticky toolbar and preserves raw value',()=>{const s=actual();assert.equal(s.context.focusCueReviewIssue({row:221,field:'end'}),true);assert.ok(s.rect.top>=122&&s.rect.bottom<=488);assert.equal(s.field.value,' 原句 🎵  ');assert.equal(s.calls.length,1);assert.equal(s.context.document.activeElement,s.field);});
test('actual focus refuses missing detached disabled or unsuccessfully focused targets',()=>{for(const edit of [s=>s.context.cueIssueTarget=()=>null,s=>s.field.isConnected=false,s=>s.field.disabled=true,s=>s.field.focus=()=>{}]){const s=actual();edit(s);assert.equal(s.context.focusCueReviewIssue({row:1,field:'start'}),false);assert.equal(s.calls.length,0);assert.equal(s.context.document.activeElement,null);}});
test('offscreen toolbar does not cover global duration fields above the cue table',()=>{for(const toolbar of [{top:1000,bottom:1100},{top:-100,bottom:-10}]){const s=actual();s.setToolbar(toolbar);assert.equal(s.context.focusCueReviewIssue({row:0,field:'duration'}),true);assert.equal(s.calls.length,0);}});
test('toolbar and fixed dependencies use native buttons wrapping and short-height fallback',()=>{const html=fs.readFileSync('web/index.html','utf8'),css=fs.readFileSync('web/style.css','utf8');assert.ok(html.indexOf('/issue-cursor.js')<html.indexOf('/lyrics-cue-review-dom.js'));assert.ok(html.indexOf('/editor-field-position.js')<html.indexOf('/app.js'));assert.match(html,/id="cue-issue-toolbar"[^>]+role="group"[^>]+aria-label="逐項單句待辦"/);for(const id of ['check','previous','next'])assert.match(html,new RegExp('id="cue-issue-'+id+'" type="button"'));assert.match(css,/@media\(max-height:400px\)\{\.cue-issue-tools\{position:static\}\}/);});
