// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Review=require('../web/music-section-review.js'),Request=require('../web/readiness-request.js'),V=require('../musiclab/assets/delivery-versions.js');
const payload=()=>({...JSON.parse(fs.readFileSync('examples/unfinished-song-review.json','utf8')),row:2});
const wire=p=>{const data=Review.report(p);return {data,files:{'music-section-review.json':JSON.stringify(data,null,2)+'\n','music-section-review.md':Review.markdown(data)},meta:{version:V.current,protocol_version:1,needs_review:true}};};
function setup(){const p=payload(),s={panel:p.panel,ids:p.panel.sections.map((_,i)=>'id-'+i),selectedId:'id-1'},reports=[],errors=[],states=[],waiting=[],stale=[];const source=Review.createController({capture:()=>s});const c=Request.createController({source,checkedResult:Review.checkedResult,request:(p,current)=>new Promise((resolve,reject)=>waiting.push({p,current,resolve,reject})),onReport:v=>reports.push(v),onError:e=>errors.push(e.message),onState:v=>states.push(v),onStale:()=>stale.push(true)});return {s,source,c,reports,errors,states,waiting,stale};}
test('complete report envelope, metadata, raw source, JSON and Markdown must all match',()=>{const p=payload(),good=wire(p),before=structuredClone(good);assert.deepEqual(Review.checkedResult(p,good).data,good.data);assert.deepEqual(good,before);for(const edit of [r=>r.meta.version='0.150.0',r=>r.meta.needs_review=false,r=>r.meta.protocol_version=2,r=>r.extra=true,r=>r.data.row=1,r=>r.data.source.section.texture+='other',r=>r.files['music-section-review.json']='{}',r=>r.files['music-section-review.md']+='x',r=>r.files.extra='x']){const bad=wire(p);edit(bad);assert.throws(()=>Review.checkedResult(p,bad));}});
test('runtime hidden properties, getters, undefined and invalid Unicode are refused before file inspection',()=>{for(const edit of [r=>Object.defineProperty(r,'hidden',{value:1}),r=>Object.defineProperty(r.files,'hidden',{value:1}),r=>r.extra=undefined,r=>r.files['music-section-review.md']='\ud800']){const bad=wire(payload());edit(bad);assert.throws(()=>Review.checkedResult(payload(),bad));}let reads=0;const bad=wire(payload());Object.defineProperty(bad,'data',{get(){reads++;return {};},enumerable:true});assert.throws(()=>Review.checkedResult(payload(),bad));assert.equal(reads,0);});
test('selected report cap refuses oversized selected text and keeps unrelated source text',()=>{const p=payload();p.panel.sections[1].texture='a'.repeat(256*1024);assert.throws(()=>Review.report(p));p.panel.sections[1].texture='';p.panel.sections[0].texture='a'.repeat(256*1024);assert.equal(Review.report(p).row,2);});
test('payload proof binds original row and count even if selected and other rows contain identical values',()=>{const s=setup();s.s.panel.sections=s.s.panel.sections.map(()=>structuredClone(s.s.panel.sections[1]));const p=s.source.payload();assert.equal(s.source.isCurrent(p),true);assert.equal(s.source.isCurrent(structuredClone(p)),false);p.row=1;assert.equal(s.source.isCurrent(p),false);const count=s.source.payload();count.panel.sections.pop();assert.equal(s.source.isCurrent(count),false);});
test('request success returns checked files and only metadata pending state with copied transport payload',async()=>{const s=setup(),work=s.c.check();const original=structuredClone(s.s);assert.deepEqual(s.states,[{pending:true}]);s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await work,true);assert.equal(s.reports.length,1);assert.deepEqual(s.s,original);assert.deepEqual(s.states.at(-1),{pending:false});});
test('selected text, selection and same-text row order changes suppress late success and error',async()=>{for(const edit of [s=>s.s.panel.sections[1].texture='later',s=>s.s.selectedId='id-0',s=>s.s.ids.reverse()])for(const failure of [false,true]){const s=setup(),work=s.c.check();edit(s);const after=structuredClone(s.s);if(failure)s.waiting[0].reject(Error('old'));else s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await work,false);assert.equal(s.reports.length,0);assert.equal(s.errors.length,0);assert.equal(s.stale.length,1);assert.deepEqual(s.s,after);}});
test('a malformed reply keeps prior results and a valid retry succeeds',async()=>{const s=setup(),first=s.c.check(),bad=wire(s.waiting[0].p);bad.meta.needs_review=false;s.waiting[0].resolve(bad);assert.equal(await first,false);assert.equal(s.errors.length,1);assert.equal(s.reports.length,0);const retry=s.c.check();s.waiting[1].resolve(wire(s.waiting[1].p));assert.equal(await retry,true);assert.equal(s.reports.length,1);});
test('cancellation and late predecessor replies cannot finish a newer pending request',async()=>{const s=setup(),old=s.c.check();s.c.invalidate();const next=s.c.check();s.waiting[0].reject(Error('late'));assert.equal(await old,false);assert.deepEqual(s.states.at(-1),{pending:true});s.waiting[1].resolve(wire(s.waiting[1].p));assert.equal(await next,true);assert.equal(s.errors.length,0);});
test('outer cancellation quietly preserves prior files for either eventual success or error',async()=>{for(const failure of [false,true]){const s=setup();let active=true;const work=s.c.check(()=>active);active=false;if(failure)s.waiting[0].reject(Error('abort'));else s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await work,false);assert.deepEqual(s.reports,[]);assert.deepEqual(s.errors,[]);assert.deepEqual(s.stale,[]);}});
function app(){const t=fs.readFileSync('web/app.js','utf8'),a=t.indexOf('const sectionReviewRequest='),b=t.indexOf('function checkMusicReady()',a),s=setup(),nodes={'section-review-report':{},'music-visual':{hidden:false}},files=[],messages=[];let active=true,resolve,reject;const current=()=>active;current.signal={synthetic:true};const ctx={$:id=>nodes[id],sectionReviewController:s.source,sectionReviewDOM:{refresh(){}},MusicReadinessRequest:Request,MusicSectionReview:Review,run:(_b,task)=>task(current),api:(route,p,binary,signal)=>{assert.equal(route,'/api/music-section-review');assert.equal(binary,false);assert.equal(signal,current.signal);return new Promise((r,j)=>{resolve=r;reject=j;});},setFiles:(f,note)=>files.push({f,note}),say:(message,error)=>messages.push({message,error})};vm.runInNewContext(t.slice(a,b),ctx);return {...s,nodes,files,messages,start:()=>nodes['section-review-report'].onclick(),resolve:r=>resolve(r),reject:e=>reject(e),set active(v){active=v;}};}
test('actual app binding commits complete checked files and preserves output on late or malformed reply',async()=>{const s=app(),work=s.start();s.resolve(wire(s.waiting[0]?.p??{panel:s.s.panel,row:2}));assert.equal(await work,true);assert.equal(s.files.length,1);assert.equal(s.nodes['music-visual'].hidden,true);const late=app(),pending=late.start();late.s.panel.sections[1].texture='later';late.reject(Error('old'));assert.equal(await pending,false);assert.equal(late.files.length,0);assert.ok(late.messages.every(v=>!v.message.includes('old')));});
test('shared request asset loads before both adapters without adding source or DOM responsibilities',()=>{const html=fs.readFileSync('web/index.html','utf8');assert.ok(html.indexOf('/readiness-request.js')<html.indexOf('/storyboard-shot-request.js'));assert.ok(html.indexOf('/readiness-request.js')<html.indexOf('/app.js'));assert.ok(html.includes('section-review-report'));});
