// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../web/editor-copy.js'),DOM=require('../web/editor-copy-dom.js');
const value=list=>Object.fromEntries(P.specs[list].fields.map(k=>[k,k==='open'?false:k==='screen_direction'?'neutral':k+'\r\n🎵\t ']));
function setup(){let live=Object.fromEntries(Object.keys(P.specs).map(l=>[l,{entries:[{id:'source-'+l,value:value(l)},{id:'tail-'+l,value:value(l)}],visible:true,busy:false}])),writes=0,reads=0,ids=0;const events=[];
 const options={allowed:l=>live[l].visible&&!live[l].busy&&live[l].entries.length<P.specs[l].limit,allowedUndo:l=>live[l].visible&&!live[l].busy,capture:l=>{reads++;return live[l];},newId:()=> 'new-'+ ++ids,apply:(l,entries)=>{writes++;live[l].entries=entries;},onCopied:(...a)=>events.push(['copy',...a]),onUndone:(...a)=>events.push(['undo',...a]),onError:e=>events.push(['error',e.message])};
 const c=P.createController(options);return {c,live,options,events,get writes(){return writes;},get reads(){return reads;}};
}
test('each list undoes only its copied row and preserves later original fields and exact stable IDs',()=>{for(const l of Object.keys(P.specs)){const s=setup(),before=structuredClone(s.live[l]);assert.equal(s.c.copy(l,'source-'+l),true);const field=P.specs[l].fields.find(k=>k!=='open');s.live[l].entries[0].value[field]='original edited\r\n🎵';const expected=structuredClone(before);expected.entries[0].value[field]='original edited\r\n🎵';assert.equal(s.c.undo(l),true);assert.deepEqual(s.live[l],expected);assert.equal(s.c.view(l).canUndo,false);assert.equal(s.c.undo(l),false);assert.deepEqual(s.events.at(-1),['undo',l,{index:0,id:'source-'+l}]);}});
test('three independent checkpoints survive other-panel operations and clear only the requested list',()=>{const s=setup();for(const l of Object.keys(P.specs))assert.equal(s.c.copy(l,'source-'+l),true);s.c.clear('shots');assert.equal(s.c.view('shots').canUndo,false);assert.equal(s.c.undo('cues'),true);assert.equal(s.c.view('arrangement').canUndo,true);assert.equal(s.live.shots.entries.length,3);assert.equal(s.c.undo('arrangement'),true);});
test('only the latest successful copy is removed; earlier copies remain unchanged',()=>{const s=setup();assert.equal(s.c.copy('cues','source-cues'),true);assert.equal(s.c.copy('cues','new-1'),true);assert.equal(s.c.undo('cues'),true);assert.deepEqual(s.live.cues.entries.map(e=>e.id),['source-cues','new-1','tail-cues']);assert.equal(s.c.undo('cues'),false);});
test('editing any copied content field refuses removal and retains the checkpoint for exact retry',()=>{for(const l of Object.keys(P.specs))for(const key of P.specs[l].fields.filter(k=>k!=='open')){const s=setup();s.c.copy(l,'source-'+l);const row=s.live[l].entries[1],original=row.value[key];row.value[key]+='edited';const before=structuredClone(s.live[l]);assert.equal(s.c.undo(l),false);assert.deepEqual(s.live[l],before);assert.match(s.events.at(-1)[1],/已有修改/);row.value[key]=original;assert.equal(s.c.undo(l),true);}});
test('shot details expansion is transient and undo preserves other current open states',()=>{const s=setup();s.c.copy('shots','source-shots');s.live.shots.entries[1].value.open=false;s.live.shots.entries[2].value.open=true;assert.equal(s.c.undo('shots'),true);assert.equal(s.live.shots.entries[1].value.open,true);});
test('added deleted reordered and replaced stable IDs reject the whole undo without mutation',()=>{for(const change of ['add','delete','reorder','replace']){const s=setup();s.c.copy('arrangement','source-arrangement');const rows=s.live.arrangement.entries;if(change==='add')rows.push({id:'another',value:value('arrangement')});if(change==='delete')rows.pop();if(change==='reorder')rows.reverse();if(change==='replace')rows[2].id='replaced';const before=structuredClone(s.live.arrangement);assert.equal(s.c.undo('arrangement'),false);assert.deepEqual(s.live.arrangement,before);assert.match(s.events.at(-1)[1],/列數或順序/);}});
test('full capacity disables copying while undo remains available and restores one free slot',()=>{for(const l of Object.keys(P.specs)){const s=setup();s.live[l].entries=Array.from({length:P.specs[l].limit-1},(_,i)=>({id:'r'+i,value:value(l)}));assert.equal(s.c.copy(l,'r0'),true);assert.equal(s.live[l].entries.length,P.specs[l].limit);assert.equal(s.c.copy(l,'r0'),false);assert.equal(s.c.view(l).canUndo,true);assert.equal(s.c.undo(l),true);assert.equal(s.live[l].entries.length,P.specs[l].limit-1);}});
test('busy hidden missing checkpoint and disposed undo do not read or write sources',()=>{for(const flag of ['busy','visible']){const s=setup();assert.equal(s.c.undo('cues'),false);assert.equal(s.reads,0);s.c.copy('cues','source-cues');const reads=s.reads,writes=s.writes;s.live.cues[flag]=flag==='busy';assert.equal(s.c.view('cues').canUndo,false);assert.equal(s.c.undo('cues'),false);assert.equal(s.reads,reads);assert.equal(s.writes,writes);}const s=setup();s.c.copy('cues','source-cues');const reads=s.reads;s.c.dispose();assert.equal(s.c.undo('cues'),false);assert.equal(s.c.view('cues').canUndo,false);assert.equal(s.reads,reads);});
test('failure and missing-source copy preserve the previous successful checkpoint',()=>{const s=setup();s.c.copy('cues','source-cues');assert.equal(s.c.copy('cues','missing'),false);assert.equal(s.c.view('cues').canUndo,true);assert.equal(s.c.undo('cues'),true);});
test('full current capture is rechecked before undo apply and intervening edits are preserved',()=>{const t=setup();let count=0;const orig=t.options.capture;t.options.capture=l=>{if(++count===6)t.live[l].entries[0].value.text='intervening';return orig(l);};const c=P.createController(t.options);assert.equal(c.copy('cues','source-cues'),true);const writes=t.writes;assert.equal(c.undo('cues'),false);assert.equal(t.writes,writes);assert.equal(t.live.cues.entries[0].value.text,'intervening');});
test('undo writer failure retains current data and checkpoint and does not announce success',()=>{const t=setup();let fail=false;const options={...t.options,apply:(...a)=>{if(fail)throw Error('writer failed');t.options.apply(...a);}};const c=P.createController(options);c.copy('cues','source-cues');const before=structuredClone(t.live.cues);fail=true;assert.equal(c.undo('cues'),false);assert.deepEqual(t.live.cues,before);assert.equal(c.view('cues').canUndo,true);assert.equal(t.events.some(e=>e[0]==='undo'),false);fail=false;assert.equal(c.undo('cues'),true);});
test('mismatched actual undo outcome never consumes the checkpoint or rolls back later edits',()=>{const s=setup();let undo=false;const options={...s.options,apply:(l,entries)=>{s.options.apply(l,entries);if(undo)s.live[l].entries[0].value.text='later';}};const c=P.createController(options);c.copy('cues','source-cues');undo=true;assert.equal(c.undo('cues'),false);assert.equal(s.live.cues.entries[0].value.text,'later');assert.equal(c.view('cues').canUndo,true);assert.match(s.events.at(-1)[1],/撤回後內容/);});
test('checkpoint copies only IDs and copied fields and cannot expose retained original source values',()=>{const s=setup();s.c.copy('shots','source-shots');const cp=P.checkpoint('shots',s.live.shots,'source-shots','new-1');assert.deepEqual(Object.keys(cp).sort(),['copiedId','ids','list','sourceId','value']);cp.value.purpose='changed';cp.ids[0]='changed';assert.equal(s.c.undo('shots'),true);assert.deepEqual(Object.keys(s.c.view('shots')),['canUndo']);});
test('clear all releases all three independent records without source reads or writes',()=>{const s=setup();for(const l of Object.keys(P.specs))s.c.copy(l,'source-'+l);const reads=s.reads,writes=s.writes;s.c.clear();for(const l of Object.keys(P.specs))assert.equal(s.c.view(l).canUndo,false);assert.equal(s.reads,reads);assert.equal(s.writes,writes);});
test('actual app routes successful copy undo to its scope and clears checkpoints on new content',()=>{const app=fs.readFileSync('web/app.js','utf8'),start=app.indexOf('editorCopy=MusicEditorCopyDOM.bind('),end=app.indexOf('editorOrder=MusicEditorOrderDOM.bind(',start),events=[];let options;vm.runInNewContext(app.slice(start,end),{editorCopy:null,MusicEditorCopyDOM:{bind:(_d,o)=>{options=o;return {}; }},document:{},state:{busy:false},entriesFor:()=>[],rowSequence:0,collections:{cues:{scope:'lyrics',label:'歌詞句'}},writeEntries:(...a)=>events.push(['write',...a]),markDirty:(...a)=>events.push(['dirty',...a]),refreshCollectionControls:()=>events.push(['refresh']),focusEntry:(...a)=>events.push(['focus',...a]),say:(...a)=>events.push(['say',...a])});options.onUndone('cues',{index:0,id:'original'});assert.deepEqual(events[1],['focus','cues',0,'new']);assert.match(events[2][1],/其他原列編修/);assert.match(app,/function clearDeletionHistory\(scope\).*editorCopy\?\.clear\(scope\)/);});
function domSetup(){const nodes={},prefixes={arrangement:'section',shots:'shot',cues:'cue'},events=[];let busy=false,reads=0,ids=0;
 const listen=node=>Object.assign(node,{listeners:new Map(),addEventListener:(type,fn)=>node.listeners.set(type,fn),removeEventListener:(type,fn)=>{assert.equal(node.listeners.get(type),fn);node.listeners.delete(type);}});
 const rows=(list,entries)=>entries.map(e=>{const row={dataset:{historyId:e.id},parentElement:nodes[list],value:e.value,contains:b=>b===row.button};row.button={disabled:false,isConnected:true,closest:()=>row};return row;});
 for(const [l,spec] of Object.entries(P.specs)){nodes[spec.scope]={hidden:false,isConnected:true};const node=nodes[l]=listen({isConnected:true,children:[],querySelectorAll:()=>node.children.map(r=>r.button)});node.children=rows(l,[{id:'source-'+l,value:value(l)}]);nodes[prefixes[l]+'-copy-undo']=listen({disabled:true,isConnected:true});nodes[prefixes[l]+'-copy-undo-note']={textContent:''};}
 const adapter=DOM.bind({getElementById:id=>nodes[id]},{busy:()=>busy,capture:l=>{reads++;return nodes[l].children.map(r=>({id:r.dataset.historyId,value:r.value}));},newId:()=> 'new-'+ ++ids,apply:(l,entries)=>{nodes[l].children=rows(l,entries);events.push(['apply',l]);},onCopied:(...a)=>events.push(['copied',...a]),onUndone:(...a)=>events.push(['undone',...a]),onError:e=>events.push(['error',e.message])});
 return {nodes,events,adapter,copy(l){const row=nodes[l].children[0];nodes[l].listeners.get('click')({target:{closest:()=>row.button}});},undo(l){nodes[prefixes[l]+'-copy-undo'].listeners.get('click')();},get reads(){return reads;},set busy(v){busy=v;}};
}
test('DOM undo controls are independent and refresh does not read full field data',()=>{const s=domSetup();s.adapter.refresh();assert.equal(s.reads,0);s.copy('cues');const reads=s.reads;s.adapter.refresh();assert.equal(s.reads,reads);assert.equal(s.nodes['cue-copy-undo'].disabled,false);assert.equal(s.nodes['shot-copy-undo'].disabled,true);s.undo('cues');assert.equal(s.nodes.cues.children.length,1);assert.equal(s.nodes['cue-copy-undo'].disabled,true);assert.deepEqual(s.events.at(-1),['undone','cues',{index:0,id:'source-cues'}]);});
test('DOM undo works at full capacity while copy buttons are disabled',()=>{const s=domSetup();s.nodes.arrangement.children=Array.from({length:39},(_,i)=>{const row={...s.nodes.arrangement.children[0],dataset:{historyId:'r'+i},value:value('arrangement')};row.button={disabled:false,isConnected:true,closest:()=>row};row.contains=b=>b===row.button;return row;});s.copy('arrangement');assert.equal(s.nodes.arrangement.children.length,40);assert.equal(s.nodes.arrangement.children[0].button.disabled,true);assert.equal(s.nodes['section-copy-undo'].disabled,false);s.undo('arrangement');assert.equal(s.nodes.arrangement.children.length,39);});
test('DOM busy hidden and detached undo cannot capture or write and refresh resumes the checkpoint',()=>{for(const flag of ['busy','hidden','detached']){const s=domSetup();s.copy('shots');const reads=s.reads;if(flag==='busy')s.busy=true;if(flag==='hidden')s.nodes.storyboard.hidden=true;if(flag==='detached')s.nodes['shot-copy-undo'].isConnected=false;s.adapter.refresh();s.undo('shots');assert.equal(s.reads,reads);assert.equal(s.nodes.shots.children.length,2);s.busy=false;s.nodes.storyboard.hidden=false;s.nodes['shot-copy-undo'].isConnected=true;s.adapter.refresh();s.undo('shots');assert.equal(s.nodes.shots.children.length,1);}});
test('DOM edited copy displays literal failure without losing source data and supports retry',()=>{const s=domSetup();s.copy('cues');s.nodes.cues.children[1].value.text+='later';s.undo('cues');assert.equal(s.nodes.cues.children.length,2);assert.match(s.events.at(-1)[1],/已有修改/);s.nodes.cues.children[1].value.text=value('cues').text;s.undo('cues');assert.equal(s.nodes.cues.children.length,1);});
test('DOM scope clear and disposal release only owned records and listeners',()=>{const s=domSetup();s.copy('arrangement');s.copy('shots');s.adapter.clear('music');assert.equal(s.nodes['section-copy-undo'].disabled,true);assert.equal(s.nodes['shot-copy-undo'].disabled,false);s.adapter.dispose();for(const l of Object.keys(P.specs))assert.equal(s.nodes[l].listeners.size,0);for(const prefix of ['section','shot','cue'])assert.equal(s.nodes[prefix+'-copy-undo'].listeners.size,0);});
test('actual three undo controls use literal labels with list and live-note ARIA associations',()=>{const html=fs.readFileSync('web/index.html','utf8');for(const [prefix,l,label] of [['section','arrangement','段落'],['shot','shots','鏡頭'],['cue','cues','歌詞']]){assert.match(html,new RegExp('id="'+prefix+'-copy-undo"[^>]*aria-controls="'+l+'"[^>]*aria-describedby="'+prefix+'-copy-undo-note"[^>]*>撤回最近複製'+label));assert.match(html,new RegExp('id="'+prefix+'-copy-undo-note"[^>]*role="status"[^>]*aria-live="polite"'));}});
