// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm');
const model=require('../web/delivery-import.js'),pack=require('../web/delivery-package.js');
const hash=async raw=>crypto.createHash('sha256').update(raw).digest('hex'),sha='a'.repeat(64);
const file=name=>({name,size:2000});
const later=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
async function result(scope='music',version='0.39.0'){
 const source={scope,label:'來源<script>literal</script>\n原文',files:{'empty.txt':'','plan.md':'原文\n','view.html':'<script>neverExecute()</script>'}};
 return {selected:{bytes:2000,sha256:sha,manifest:await pack.manifest(source,hash,version)},wire:{files:source.files,data:{format:'zoe-delivery-inspection',schema_version:1,archive_bytes:2000,archive_sha256:sha,manifest:await pack.manifest(source,hash,version)},meta:{version:pack.version,protocol_version:1,needs_review:true}}};
}
function setup(read,changes={}){
 const view={scope:'music',revision:1,resultRevision:1,bundle:{files:{'old.md':'old'},note:'original',dirty:false,inputIndependent:false},busy:false,media:[{}]},seen={errors:[],states:[],replaced:[],restored:[]};
 const controller=model.createController({capture:()=>view,read,hash,onState:s=>seen.states.push(s),onError:e=>seen.errors.push(e.message),replace:w=>{seen.replaced.push(w);view.resultRevision++;view.bundle={files:w.files,note:'imported',dirty:false,inputIndependent:true}},restore:(bundle,revision)=>{seen.restored.push([bundle,revision]);view.resultRevision++;view.bundle=bundle;if(bundle&&!bundle.inputIndependent&&view.revision!==revision)view.bundle.dirty=true},...changes});return{view,seen,controller};
}
test('old/current source version and every scope verifies all text without execution',async()=>{for(const scope of ['music','storyboard','lyrics','audio'])for(const version of ['0.38.0','0.39.0','0.40.0','0.41.0','0.42.0','0.43.0','0.44.0','0.45.0','0.46.0','0.47.0','0.48.0','0.49.0','0.50.0','0.51.0','0.52.0','0.53.0','0.54.0','0.55.0','0.56.0','0.57.0','0.58.0','0.59.0','0.60.0','0.61.0','0.62.0','0.63.0','0.64.0','0.65.0','0.66.0','0.67.0','0.68.0','0.69.0','0.73.0']){const r=await result(scope,version),before=structuredClone(r);assert.deepEqual(await model.checked(r.wire,r.selected,hash),r.wire);assert.deepEqual(r,before);}});
for(const [name,edit] of Object.entries({version:r=>r.wire.meta.version='unknown',protocol:r=>r.wire.meta.protocol_version=2,review:r=>r.wire.meta.needs_review=false,metaExtra:r=>r.wire.meta.path='private',dataExtra:r=>r.wire.data.path='private',schema:r=>r.wire.data.schema_version=2,archiveHash:r=>r.wire.data.archive_sha256='b'.repeat(64),archiveSize:r=>r.wire.data.archive_bytes=2001,selectedExtra:r=>r.selected.path='private',tool:r=>r.wire.data.manifest.tool_version='99.0.0',label:r=>r.wire.data.manifest.label='wrong',order:r=>r.wire.data.manifest.files.reverse(),entryHash:r=>r.wire.data.manifest.files[0].sha256='0'.repeat(64),text:r=>r.wire.files['plan.md']='wrong text',fileExtra:r=>r.wire.files['extra.md']='extra'}))test('rejects '+name+' without replacing original results',async()=>{const r=await result();edit(r);const {view,seen,controller}=setup(async()=>r),old=structuredClone(view.bundle);assert.equal(await controller.inspect(file('result.zip')),false);assert.equal(controller.apply(),false);assert.deepEqual(view.bundle,old);assert.equal(seen.replaced.length,0);assert.equal(seen.errors.length,1);});
test('preview is explicit, cloned and cancel preserves original bundle',async()=>{const r=await result(),{view,seen,controller}=setup(async()=>r),before=structuredClone(view.bundle);assert.equal(await controller.inspect(file('result.zip')),true);assert.equal(controller.status().canApply,true);const preview=controller.status().proposal;preview.files['plan.md']='mutated';controller.cancel();assert.equal(controller.apply(),false);assert.deepEqual(view.bundle,before);assert.equal(seen.replaced.length,0);});
test('apply and scoped undo preserve later input and media, restored old dependent output becomes dirty',async()=>{const r=await result(),{view,seen,controller}=setup(async()=>r),old=structuredClone(view.bundle);await controller.inspect(file('result.zip'));assert.equal(controller.apply(),true);assert.deepEqual(view.bundle.files,r.wire.files);view.revision++;const media={newNativeFile:true};view.media=[media];view.input='later raw edit';assert.equal(controller.undo(),true);assert.equal(view.input,'later raw edit');assert.equal(view.media[0],media);assert.deepEqual(view.bundle,{...old,dirty:true});assert.equal(controller.undo(),false);assert.equal(seen.restored.length,1);});
test('empty prior bundle undo returns to empty without losing input',async()=>{const r=await result(),{view,controller}=setup(async()=>r);view.bundle=null;await controller.inspect(file('result.zip'));controller.apply();assert.equal(controller.undo(),true);assert.equal(view.bundle,null);});
test('new generated results or changed scope invalidates undo even if text is identical',async()=>{const r=await result(),{view,controller}=setup(async()=>r);await controller.inspect(file('result.zip'));controller.apply();view.resultRevision++;assert.equal(controller.undo(),false);assert.equal(controller.status().canUndo,false);});
for(const change of ['revision','resultRevision','scope','media','busy','bundle'])test('target '+change+' change while read preserves newer state',async()=>{const pending=later(),{view,seen,controller}=setup(()=>pending.promise),work=controller.inspect(file('result.zip'));if(change==='media')view.media=[{}];else if(change==='bundle')view.bundle.files['later.md']='new';else view[change]=({revision:2,resultRevision:2,scope:'lyrics',busy:true})[change];const old=structuredClone(view.bundle);pending.resolve(await result());assert.equal(await work,false);assert.equal(controller.apply(),false);assert.deepEqual(view.bundle,old);assert.equal(seen.replaced.length,0);});
test('target edit after preview disables apply and preserves literal original input',async()=>{const {view,controller,seen}=setup(()=>result());await controller.inspect(file('result.zip'));view.revision++;view.input='0.000 unfinished';assert.equal(controller.status().canApply,false);assert.equal(controller.apply(),false);assert.equal(view.input,'0.000 unfinished');assert.equal(seen.replaced.length,0);});
test('cross-scope ZIP requires manual switch and never changes target',async()=>{const {view,seen,controller}=setup(()=>result('lyrics'));assert.equal(await controller.inspect(file('lyrics.zip')),false);assert.equal(view.scope,'music');assert.equal(seen.replaced.length,0);assert.match(seen.errors[0],/其他工作台/);});
test('latest file wins and old success/failure is ignored',async()=>{const a=later(),b=later(),{controller,seen}=setup(f=>f.name==='old.zip'?a.promise:b.promise);const old=controller.inspect(file('old.zip')),fresh=controller.inspect(file('fresh.zip'));b.resolve(await result());assert.equal(await fresh,true);a.reject(Error('late error'));assert.equal(await old,false);assert.equal(seen.errors.length,0);assert.equal(controller.status().canApply,true);});
test('cancel and invalid latest selection clear pending or outstanding read',async()=>{const pending=later(),{controller}=setup(()=>pending.promise),work=controller.inspect(file('old.zip'));assert.equal(await controller.inspect(file('bad.txt')),false);pending.resolve(await result());assert.equal(await work,false);assert.equal(controller.status().pending,false);const next=setup(()=>result());await next.controller.inspect(file('good.zip'));await next.controller.inspect({name:'large.zip',size:pack.maxArchive+1});assert.equal(next.controller.status().pending,false);});
test('busy selection and current transport failure do not replace any result',async()=>{const {view,seen,controller}=setup(async()=>{throw Error('controlled transport')});view.busy=true;assert.equal(await controller.inspect(file('selected.zip')),false);view.busy=false;assert.equal(await controller.inspect(file('selected.zip')),false);assert.equal(seen.replaced.length,0);assert.equal(seen.errors.length,2);});
test('hashing reply is asynchronous and rechecks target before showing preview',async()=>{const hold=later(),entered=later(),r=await result(),{view,seen,controller}=setup(async()=>r,{hash:async raw=>{entered.resolve();await hold.promise;return hash(raw)}});const work=controller.inspect(file('selected.zip'));await entered.promise;view.resultRevision++;hold.resolve('a'.repeat(64));assert.equal(await work,false);assert.equal(seen.replaced.length,0);});
test('DOM adapter renders source literally and uses real selected File; no HTML injection',async()=>{const ids=['delivery-import-file','delivery-import-preview','delivery-import-apply','delivery-import-undo','delivery-import-note','delivery-import-files','delivery-import-source','delivery-import-cancel','delivery-review-file','delivery-review-summary','delivery-review-before','delivery-review-incoming','delivery-review-before-note','delivery-review-incoming-note','delivery-reader','delivery-reader-side','delivery-reader-content','delivery-reader-note','delivery-reader-first','delivery-reader-previous','delivery-reader-next','delivery-search-query','delivery-search-find','delivery-search-more','delivery-search-previous','delivery-search-match','delivery-search-note','delivery-search-context-box','delivery-search-context','delivery-original-download','delivery-original-note','delivery-report-json','delivery-report-md','delivery-report-form','delivery-report-name','delivery-report-content'],elements={};for(const id of ids)elements[id]={replaceChildren(){this.children=[]},append(item){(this.children||=[]).push(item)}};let state={scope:'music',revision:1,resultRevision:1,bundle:null,busy:false,media:[]};const r=await result(),context={MusicDeliveryImport:model};vm.runInNewContext(fs.readFileSync('web/delivery-text-dom.js','utf8'),Object.assign(context,{MusicDeliveryText:require('../web/delivery-text.js')}));context.MusicDeliveryContext=require('../web/delivery-context.js');context.MusicDeliverySearch=require('../web/delivery-search.js');vm.runInNewContext(fs.readFileSync('web/delivery-search-dom.js','utf8'),context);vm.runInNewContext(fs.readFileSync('web/delivery-import-dom.js','utf8'),context);const controller=context.MusicDeliveryImportDom.createAdapter({getElementById:id=>elements[id],createElement:()=>({textContent:''})},{capture:()=>state,read:async f=>{assert.equal(f.name,'original.zip');return r},hash,replace:()=>state.resultRevision++,restore:()=>state.resultRevision++,onError:()=>assert.fail()});await controller.inspect(file('original.zip'));assert.equal(elements['delivery-import-preview'].hidden,false);assert.match(elements['delivery-import-source'].textContent,/<script>literal<\/script>/);assert.equal(elements['delivery-import-files'].children.length,3);assert.equal(elements['delivery-import-apply'].disabled,false);elements['delivery-import-apply'].onclick();assert.equal(elements['delivery-import-undo'].disabled,false);elements['delivery-import-undo'].onclick();assert.equal(elements['delivery-import-undo'].disabled,true);});

test('ready event only follows a current verified preview, allowing a prior error to clear',async()=>{let n=0,ready=0;const {controller,seen}=setup(async()=>{if(n++===0)throw Error('first failure');return result()},{onReady:()=>ready++});assert.equal(await controller.inspect(file('first.zip')),false);assert.equal(ready,0);assert.equal(await controller.inspect(file('valid.zip')),true);assert.equal(ready,1);assert.equal(controller.status().canApply,true);assert.equal(seen.errors.length,1);});
