// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const S=require('../web/issue-summary.js');
const detail=()=>({location:'第221句',field:'結束',message:'時間與另一句重疊',relation:'第33句'});
test('literal original location field reason and relationship retain exact Unicode and spaces',()=>{const d=detail();d.message=' <b> 原文🎵  </b> ';const before=structuredClone(d);assert.equal(S.format(d),'第221句 · 結束： <b> 原文🎵  </b> （第33句）');assert.deepEqual(d,before);});
test('relation null remains distinct from an empty or missing relation',()=>{const d=detail();d.relation=null;assert.equal(S.format(d),'第221句 · 結束：時間與另一句重疊');delete d.relation;assert.throws(()=>S.format(d));d.relation='';assert.throws(()=>S.format(d));});
test('a current located item presents exactly one caption without holding a source or report',()=>{const d=detail(),before=structuredClone(d);assert.equal(S.present({current:true,index:199,detail:d}),' 目前定位：'+S.format(d));assert.deepEqual(d,before);assert.deepEqual(Object.keys(S).sort(),['format','present']);});
test('unlocated or unavailable states explicitly clear captions and refuse stale detail injection',()=>{for(const v of [{current:true,index:null,detail:null},{current:false,index:null,detail:null},{current:false,index:33,detail:null}]){assert.equal(S.present(v),'');assert.throws(()=>S.present({...v,detail:detail()}));}});
test('index metadata accepts retained endpoints and rejects boolean fractional negative and unretained values',()=>{for(const i of [0,199])assert.match(S.present({current:true,index:i,detail:detail()}),/目前定位/);for(const i of [-1,200,1.1,true,'0',NaN,Infinity])assert.throws(()=>S.present({current:true,index:i,detail:detail()}));});
test('caption fields are bounded and malformed Unicode is never normalized',()=>{for(const k of ['location','field','message','relation']){const d=detail();d[k]='x'.repeat(k==='message'?1024:64);assert.doesNotThrow(()=>S.format(d));d[k]+='x';assert.throws(()=>S.format(d));d[k]='\ud800';assert.throws(()=>S.format(d));}});
test('unknown hidden symbol sparse and non-JSON metadata reject before presentation',()=>{for(const edit of [d=>d.extra='x',d=>Object.defineProperty(d,'hidden',{value:'x'}),d=>d[Symbol('x')]='x',d=>d.message=undefined,d=>d.message=Array(1),d=>d.message=Infinity]){const d=detail();edit(d);assert.throws(()=>S.format(d));}});
test('getters on caption or current metadata are rejected without reading them',()=>{let reads=0;const d=detail();Object.defineProperty(d,'message',{enumerable:true,get(){reads++;return 'bad';}});assert.throws(()=>S.format(d));const v={index:0,detail:detail()};Object.defineProperty(v,'current',{enumerable:true,get(){reads++;return true;}});assert.throws(()=>S.present(v));assert.equal(reads,0);});
test('null caption and unknown current flags cannot present a fake successful location',()=>{for(const v of [{current:true,index:0,detail:null},{current:1,index:0,detail:detail()},{current:'true',index:0,detail:detail()},{current:true,index:0,detail:detail(),report:{}}])assert.throws(()=>S.present(v));});
test('fixed module precedes all adapters and adds only an allowlisted static asset',()=>{const h=fs.readFileSync('web/index.html','utf8'),server=fs.readFileSync('music_lab_server.py','utf8');for(const n of ['storyboard-shot-review-dom','music-section-review-dom','lyrics-cue-review-dom'])assert.ok(h.indexOf('/issue-summary.js')<h.indexOf('/'+n+'.js'));assert.match(server,/"\/issue-summary\.js": \("web\/issue-summary\.js", "text\/javascript"\)/);assert.ok(!server.includes('/api/issue-summary'));});
function actual(){const t=fs.readFileSync('web/app.js','utf8'),a=t.indexOf('function revealActiveIssue('),b=t.indexOf('function focusMusicSectionIssue(',a);let rect={top:110,bottom:150},cover={top:8,bottom:230};const calls=[],target={isConnected:true,disabled:false,value:' 原文🎵  ',focus(){throw Error('reveal must not focus');},getBoundingClientRect:()=>rect},toolbar={getBoundingClientRect:()=>cover},context={document:{activeElement:target},window:{innerHeight:500,scrollBy:v=>{calls.push(v);rect={top:rect.top-v.top,bottom:rect.bottom-v.top};}},MusicEditorFieldPosition:require('../web/editor-field-position.js')};vm.runInNewContext(t.slice(a,b),context);return {context,target,toolbar,calls,set cover(v){cover=v;},get rect(){return rect;}};}
test('post-caption geometry reveals an already active field after toolbar growth without re-focusing or editing',()=>{const s=actual();assert.equal(s.context.revealActiveIssue(s.target,s.toolbar),true);assert.ok(s.rect.top>=242&&s.rect.bottom<=488);assert.equal(s.target.value,' 原文🎵  ');assert.equal(s.calls.length,1);assert.equal(s.calls[0].behavior,'instant');});
test('post-caption reveal ignores another active control detached disabled and missing targets',()=>{for(const change of [s=>s.context.document.activeElement={},s=>s.target.isConnected=false,s=>s.target.disabled=true,s=>s.target=null]){const s=actual();change(s);assert.equal(s.context.revealActiveIssue(s.target,s.toolbar),false);assert.equal(s.calls.length,0);}});
test('offscreen or static toolbars do not move already visible original fields',()=>{for(const c of [{top:700,bottom:850},{top:-240,bottom:-20}]){const s=actual();s.cover=c;assert.equal(s.context.revealActiveIssue(s.target,s.toolbar),true);assert.equal(s.calls.length,0);}});
