// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../web/editor-position-dom.js'),O=require('../web/entry-order.js');
test('actual panel navigation refreshes position availability after visibility changes without modifying creative values',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('web/app.js','utf8').split('\n').find(line=>line.startsWith("document.querySelectorAll('[data-tab]').forEach")),panels=['music','storyboard','lyrics','audio'].map(id=>({id,hidden:id!=='music'})),buttons=panels.map(p=>({dataset:{tab:p.id},classList:{toggle(){}},setAttribute(){},removeAttribute(){}})),events=[];
 const state={busy:false,tab:'music',bundles:{},revisions:{music:3,storyboard:4,lyrics:5},currentCue:null,cuePosition:null};const original=structuredClone(state.revisions);
 const context={state,document:{querySelectorAll:q=>q==='.panel'?panels:buttons},clearOutput:()=>{},setFiles:()=>{},say:()=>{},lyricsSearchController:null,storyboardSearchController:null,musicSearchController:null,lyricsReviewPager:null,lyricsExportPager:null,musicReadyPager:null,storyboardReadyPager:null,storyboardTimingPager:null,editorCopy:null,editorOrder:null,editorPosition:{refresh:()=>events.push({tab:state.tab,visible:panels.find(p=>p.id===state.tab).hidden===false})}};
 vm.runInNewContext(source,context);for(const b of buttons)b.onclick();assert.deepEqual(events,panels.map(p=>({tab:p.id,visible:true})));assert.deepEqual(state.revisions,original);state.busy=true;buttons[0].onclick();assert.equal(events.length,4);
});
function setup(){
 const nodes={},document={body:{},activeElement:null,getElementById:id=>nodes[id]};let busy=false,writes=0,mode='normal';
 function element(){return {isConnected:true,hidden:false,disabled:false,value:'',attributes:{},listeners:new Map(),setAttribute(k,v){this.attributes[k]=v;},addEventListener(t,f){this.listeners.set(t,f);},removeEventListener(t,f){assert.equal(this.listeners.get(t),f);this.listeners.delete(t);},focus(){document.activeElement=this;},emit(t,event={}){document.activeElement=this;this.listeners.get(t)?.({target:this,...event});}};}
 for(const [list,scope,prefix] of [['arrangement','music','section'],['shots','storyboard','shots'],['cues','lyrics','cues']]){nodes[scope]=element();nodes[list]={isConnected:true,children:['a','b','c','d'].map(id=>({dataset:{historyId:id}}))};for(const suffix of ['order','position','position-move','position-note'])nodes[prefix+'-'+suffix]=element();nodes[prefix+'-order'].value='b';}
 const adapter=D.bind(document,{busy:()=>busy,onMove:(list,id,index)=>{writes++;if(mode==='false')return false;const order=O.moveTo(nodes[list].children.map(r=>r.dataset.historyId),id,index);nodes[list].children=(mode==='wrong'?order.ids.toReversed():order.ids).map(id=>({dataset:{historyId:id}}));if(mode==='foreign')document.activeElement={foreign:true};adapter.refresh();return true;}});adapter.refresh();return {nodes,document,adapter,get writes(){return writes;},set busy(v){busy=v;},set mode(v){mode=v;}};
}
test('native position controls move once to destination and return focus to the selected stable row selector',()=>{for(const prefix of ['section','shots','cues']){const s=setup(),input=s.nodes[prefix+'-position'],button=s.nodes[prefix+'-position-move'];input.value='0004';input.emit('input');assert.equal(button.disabled,false);button.emit('click');const list=prefix==='section'?'arrangement':prefix;assert.deepEqual(s.nodes[list].children.map(r=>r.dataset.historyId),['a','c','d','b']);assert.equal(s.nodes[prefix+'-order'].value,'b');assert.equal(input.value,'0004');assert.equal(button.disabled,true);assert.equal(s.document.activeElement,s.nodes[prefix+'-order']);assert.equal(s.writes,1);}});
test('blank current invalid and out of range values remain literal with accessible notes and no movement',()=>{const s=setup(),input=s.nodes['shots-position'],button=s.nodes['shots-position-move'];for(const value of ['','2','0','1.5','1e0','5']){input.value=value;input.emit('input');assert.equal(button.disabled,true);button.emit('click');assert.equal(s.writes,0);assert.equal(input.value,value);}assert.equal(input.attributes['aria-invalid'],'true');assert.match(s.nodes['shots-position-note'].textContent,/1–4/);});
test('busy hidden disconnected and disabled native controls gate writes while view controls stay out of persistent data',()=>{for(const kind of ['busy','hidden','disconnected','disabled']){const s=setup(),input=s.nodes['shots-position'],button=s.nodes['shots-position-move'];input.value='4';input.emit('input');if(kind==='busy')s.busy=true;if(kind==='hidden')s.nodes.storyboard.hidden=true;if(kind==='disconnected')s.nodes.shots.isConnected=false;if(kind==='disabled')button.disabled=true;if(kind!=='disabled')s.adapter.refresh();button.emit('click');assert.equal(s.writes,0);if(kind!=='disabled')assert.equal(input.disabled,true);}});
test('selection changes update source and current destination hints without reordering or writing input values',()=>{const s=setup(),input=s.nodes['cues-position'];input.value='4';input.emit('input');s.nodes['cues-order'].value='d';s.nodes['cues-order'].emit('change');assert.equal(s.nodes['cues-position-move'].disabled,true);assert.equal(input.value,'4');assert.match(s.nodes['cues-position-note'].textContent,/已在第 4/);assert.equal(s.writes,0);});
test('failed writers wrong actual permutations and intervening external focus never steal native focus',()=>{for(const mode of ['false','wrong','foreign']){const s=setup();s.mode=mode;s.nodes['shots-position'].value='4';s.nodes['shots-position'].emit('input');s.nodes['shots-position-move'].emit('click');if(mode==='foreign')assert.deepEqual(s.document.activeElement,{foreign:true});else assert.equal(s.document.activeElement,s.nodes['shots-position-move']);}});
test('position adapter disposes its twelve owned listeners and stops reading or refreshing',()=>{const s=setup();assert.equal(Object.values(s.nodes).reduce((n,e)=>n+(e.listeners?.size||0),0),12);s.adapter.dispose();for(const e of Object.values(s.nodes))if(e.listeners)assert.equal(e.listeners.size,0);s.nodes['shots-position'].value='4';s.nodes['shots-position'].emit('input');s.nodes['shots-position-move'].emit('click');assert.equal(s.writes,0);s.adapter.refresh();});

test('actual order completion refreshes position view for movement and undo after final selected ID',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('web/app.js','utf8'),start=source.indexOf('editorOrder=MusicEditorOrderDOM.bind('),end=source.indexOf('function refreshDeletionHistory(',start);let options;const events=[];
 const context={editorOrder:null,editorPosition:{refresh:()=>events.push('position')},MusicEditorOrderDOM:{bind:(_d,o)=>{options=o;return {}; }},document:{},state:{busy:false},entriesFor:()=>[],collections:{shots:{scope:'storyboard',label:'鏡頭'},cues:{scope:'lyrics',label:'歌詞句'}},writeEntries:()=>{},markDirty:()=>{},focusEntry:()=>{},say:()=>events.push('message')};
 vm.runInNewContext(source.slice(start,end),context);for(const list of ['shots','cues'])for(const undo of [false,true]){events.length=0;options.onChanged(list,{from:2,to:0},undo);assert.deepEqual(events,['position','message']);}
});

const keyEvent=(extra={})=>({key:'Enter',altKey:false,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:13,defaultPrevented:false,prevents:0,preventDefault(){this.defaultPrevented=true;this.prevents++;},...extra});
function key(s,prefix,extra={}){const input=s.nodes[prefix+'-position'],event=keyEvent(extra);s.document.activeElement=input;event.target=input;input.listeners.get('keydown')?.(event);return event;}
test('plain Enter in all three owned position inputs consumes implicit form submission and moves once',()=>{
 for(const prefix of ['section','shots','cues']){const s=setup(),input=s.nodes[prefix+'-position'];input.value='0004';input.emit('input');const e=key(s,prefix);assert.equal(e.defaultPrevented,true);assert.equal(e.prevents,1);assert.equal(s.writes,1);assert.equal(input.value,'0004');assert.equal(s.document.activeElement,s.nodes[prefix+'-order']);assert.equal(s.nodes[prefix+'-order'].value,'b');const list=prefix==='section'?'arrangement':prefix;assert.deepEqual(s.nodes[list].children.map(r=>r.dataset.historyId),['a','c','d','b']);}
});
test('blank invalid no-op and repeated Enter keep literal input and native input focus while preventing submission',()=>{
 for(const [value,extra] of [['',{}],['0',{}],['1e0',{}],['5',{}],['2',{}],['4',{repeat:true}]]){const s=setup(),input=s.nodes['section-position'];input.value=value;input.emit('input');const e=key(s,'section',extra);assert.equal(e.prevents,1);assert.equal(s.writes,0);assert.equal(input.value,value);assert.equal(s.document.activeElement,input);}
});
test('composition 229 modifiers other keys and pre-consumed events retain native behavior',()=>{
 for(const extra of [{isComposing:true},{keyCode:229},{altKey:true},{ctrlKey:true},{metaKey:true},{shiftKey:true},{key:'Escape'},{defaultPrevented:true}]){const s=setup();s.nodes['shots-position'].value='4';s.nodes['shots-position'].emit('input');const e=key(s,'shots',extra);assert.equal(e.prevents,0);assert.equal(s.writes,0);assert.equal(s.document.activeElement,s.nodes['shots-position']);}
});
test('foreign inactive readonly hidden disconnected busy disabled and disposed position input never consumes Enter',()=>{
 for(const mode of ['foreign','inactive','readonly','hidden','disconnected','busy','disabled','disposed']){const s=setup(),input=s.nodes['cues-position'];input.value='4';input.emit('input');s.document.activeElement=input;const e=keyEvent({target:input});if(mode==='foreign')e.target={};if(mode==='inactive')s.document.activeElement={};if(mode==='readonly')input.readOnly=true;if(mode==='hidden')input.hidden=true;if(mode==='disconnected')input.isConnected=false;if(mode==='busy')s.busy=true;if(mode==='disabled')input.disabled=true;if(mode==='disposed')s.adapter.dispose();input.listeners.get('keydown')?.(e);assert.equal(e.prevents,0,mode);assert.equal(s.writes,0,mode);}
});
test('consumed position Enter does not steal focus or report movement for failed and mismatched writers',()=>{
 for(const mode of ['false','wrong','foreign']){const s=setup();s.mode=mode;s.nodes['shots-position'].value='4';s.nodes['shots-position'].emit('input');const e=key(s,'shots');assert.equal(e.prevents,1);if(mode==='foreign')assert.deepEqual(s.document.activeElement,{foreign:true});else assert.equal(s.document.activeElement,s.nodes['shots-position']);}
});
