// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Cursor=require('../web/issue-cursor.js');
function pure(count=3){
 const s={source:{detailCount:count,hasReport:true,revision:4,stale:false,busy:false,visible:true},calls:[],views:[],result:true,hook:()=>{}};
 s.c=Cursor.createController({maxDetails:200,capture:()=>s.source,onLocate:(index,revision)=>{s.calls.push({index,revision});s.hook();return s.result;},onState:v=>s.views.push(v)});return s;
}
test('return never guesses a first issue before a successful location',()=>{const s=pure();assert.equal(s.c.refresh().canReturn,false);assert.equal(s.c.returnCurrent(),false);assert.deepEqual(s.calls,[]);assert.equal(s.views.at(-1).index,null);});
test('one retained issue remains directly returnable with both adjacent moves disabled',()=>{const s=pure(1),before=structuredClone(s.source);assert.equal(s.c.move(1),true);assert.equal(s.views.at(-1).canPrevious,false);assert.equal(s.views.at(-1).canNext,false);assert.equal(s.views.at(-1).canReturn,true);const message=s.views.at(-1).message;assert.equal(s.c.returnCurrent(),true);assert.deepEqual(s.calls,[{index:0,revision:4},{index:0,revision:4}]);assert.equal(s.views.at(-1).index,0);assert.equal(s.views.at(-1).message,message);assert.deepEqual(s.source,before);});
test('return retains arbitrary original indices including 199 and does not advance pagination metadata',()=>{for(const index of [0,20,33,199]){const s=pure(200);s.c.locate(index,4);assert.equal(s.c.returnCurrent(),true);assert.deepEqual(s.calls.at(-1),{index,revision:4});assert.equal(s.views.at(-1).index,index);}});
test('stale busy and hidden sources disable return while exact availability restoration preserves its location',()=>{for(const key of ['stale','busy','visible']){const s=pure();s.c.locate(1);s.source[key]=key!=='visible';assert.equal(s.c.refresh().canReturn,false);assert.equal(s.c.returnCurrent(),false);assert.equal(s.calls.length,1);s.source[key]=key==='visible';assert.equal(s.c.refresh().canReturn,true);assert.equal(s.c.returnCurrent(),true);assert.deepEqual(s.calls.at(-1),{index:1,revision:4});}});
test('new report revisions and changed counts clear return rather than importing an old position',()=>{for(const change of [s=>s.source.revision++,s=>s.source.detailCount=2,s=>{s.source.hasReport=false;s.source.detailCount=0;}]){const s=pure();s.c.locate(1);change(s);assert.equal(s.c.returnCurrent(),false);assert.equal(s.views.at(-1).index,null);assert.equal(s.views.at(-1).canReturn,false);assert.equal(s.calls.length,1);}});
test('failed and throwing return callbacks preserve the last successful cursor and allow retry',()=>{const s=pure();s.c.locate(1);s.result=false;assert.equal(s.c.returnCurrent(),false);assert.equal(s.views.at(-1).index,1);s.hook=()=>{throw Error('focus failed');};assert.throws(()=>s.c.returnCurrent(),/focus failed/);assert.equal(s.c.refresh().index,1);s.hook=()=>{};s.result=true;assert.equal(s.c.returnCurrent(),true);assert.equal(s.views.at(-1).index,1);});
test('replacement or loss of availability during return cannot claim a successful old focus',()=>{for(const change of [s=>s.source.revision++,s=>s.source.busy=true,s=>s.source.stale=true]){const s=pure();s.c.locate(1);s.hook=()=>change(s);assert.equal(s.c.returnCurrent(),false);assert.equal(s.views.at(-1).canReturn,false);}});
test('edited published DTO cannot forge a different return index',()=>{const s=pure();s.c.locate(1);const v=s.c.refresh();v.index=2;v.canReturn=false;v.revision=100;assert.equal(s.c.returnCurrent(),true);assert.deepEqual(s.calls.at(-1),{index:1,revision:4});});
const adapters=[['shot',require('../web/storyboard-shot-review-dom.js')],['section',require('../web/music-section-review-dom.js')],['cue',require('../web/lyrics-cue-review-dom.js')]];
function dom(prefix,Adapter){
 const nodes=new Map(),element=()=>({children:[],textContent:'',value:'row-1',disabled:false,isConnected:true,hidden:false,classList:{toggle(){}},append(...v){this.children.push(...v);},replaceChildren(){this.children=[];},focus(){doc.activeElement=this;}}),doc={activeElement:null,getElementById:id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);},createElement:element};
 const s={nodes,doc,visible:true,busy:false,result:true,calls:[],reveals:[],errors:[]};
 s.d=Adapter.bind(doc,{labels:{focus:'任務',start:'開始'},visible:()=>s.visible,busy:()=>s.busy,onCheck:()=>true,onLocate:(index,revision)=>{s.calls.push({index,revision});return s.result;},onReveal:issue=>s.reveals.push(issue),onError:e=>s.errors.push(e)});
 s.render=(count=1,revision=4,stale=false)=>s.d.render({revision,stale,report:{row:40,totalSections:40,total_shots:40,total_rows:40,issueCount:count,issue_count:count,issues:Array.from({length:count},(_,i)=>({row:40,field:prefix==='section'?'focus':'start',message:' 原文 <b>🎵 '+i+' </b> ',related_row:null}))}});
 s.return=()=>nodes.get(prefix+'-issue-return');s.next=()=>nodes.get(prefix+'-issue-next');s.select=()=>nodes.get(prefix==='shot'?'shots-order':prefix==='section'?'section-order':'cues-order');return s;
}
for(const [prefix,Adapter] of adapters){
 test(prefix+' DOM enables return only after actual successful location and uses the same literal caption',()=>{const s=dom(prefix,Adapter);s.render();assert.equal(s.return().disabled,true);s.next().onclick();assert.equal(s.return().disabled,false);const caption=s.nodes.get(prefix+'-issue-note').textContent;assert.equal(s.return().onclick(),true);assert.deepEqual(s.calls,[{index:0,revision:4},{index:0,revision:4}]);assert.equal(s.nodes.get(prefix+'-issue-note').textContent,caption);assert.match(caption,/原文 <b>🎵 0 <\/b>/);assert.equal(s.next().disabled,true);});
 test(prefix+' DOM held return handlers recheck stale hidden busy and missing selection',()=>{for(const block of [s=>s.visible=false,s=>s.busy=true,s=>s.select().value='',s=>s.render(1,4,true)]){const s=dom(prefix,Adapter);s.render();s.next().onclick();const held=s.return().onclick;block(s);assert.equal(held(),false);assert.equal(s.calls.length,1);assert.equal(s.return().disabled,true);}});
 test(prefix+' DOM new revision and zero issues cannot inherit a return and failed focus can retry',()=>{const s=dom(prefix,Adapter);s.render();s.next().onclick();s.result=false;assert.equal(s.return().onclick(),false);assert.equal(s.return().disabled,false);s.result=true;assert.equal(s.return().onclick(),true);s.render(1,5);assert.equal(s.return().disabled,true);assert.equal(s.return().onclick(),false);s.next().onclick();s.render(0,6);assert.equal(s.return().disabled,true);});
}
test('cue return reveals the retained original item after manual paging without moving its cursor',()=>{const s=dom('cue',adapters[2][1]);s.render(200);for(let i=0;i<=33;i++)assert.equal(s.next().onclick(),true);assert.equal(s.d.page().page,1);s.nodes.get('cue-review-previous').onclick();assert.equal(s.d.page().page,0);assert.equal(s.return().onclick(),true);assert.equal(s.d.page().page,1);assert.deepEqual(s.calls.at(-1),{index:33,revision:4});assert.match(s.nodes.get('cue-issue-note').textContent,/34／200/);});
