// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('../web/editor-state.js'),R=require('../web/music-readiness.js'),S=require('../web/music-section-review.js');
const section=(value={})=>({name:'段落原文 🎵',bars:'8',energy:'3',focus:'敘事原文',texture:'聲音原文',...value});
const panel=(count=40)=>({fields:Object.fromEntries(E.draftFields.music.map(k=>[k,''])),sections:Array.from({length:count},()=>section()),avoid:[],deliverables:[]});
function setup(){const p=panel(),ids=p.sections.map((_,i)=>'section-'+i),s={panel:p,ids,selectedId:ids[39]},states=[];return {s,states,c:S.createController({capture:()=>s,onState:v=>states.push(v)})};}
test('all five original row 40 issues remain available beyond the whole-song 200-detail limit',()=>{const p=panel();p.sections=p.sections.map(()=>section(Object.fromEntries(E.draftRows.music.columns.map(k=>[k,'']))));const before=structuredClone(p),whole=R.inspect(p),single=R.inspectRow(p,40);assert.equal(whole.issues.length,200);assert.ok(whole.issueCount>200);assert.ok(!whole.issues.some(i=>i.scope==='sections'&&i.row===40));assert.equal(single.row,40);assert.equal(single.totalSections,40);assert.equal(single.issueCount,5);assert.deepEqual(new Set(single.issues.map(i=>i.field)),new Set(E.draftRows.music.columns));assert.ok(single.issues.every(i=>i.scope==='sections'&&i.row===40));assert.deepEqual(p,before);});
test('selected and whole-song rules give the same original row issues for valid and invalid numbers',()=>{for(const v of [{bars:'0'},{bars:'1.5'},{bars:'129'},{bars:'bad'},{energy:'0'},{energy:'5.1'},{energy:'NaN'},{name:'\u0085 '},{focus:' '},{texture:''},{bars:'128',energy:'5'}]){const p=panel(3);p.sections[1]=section(v);assert.deepEqual(R.inspectRow(p,2).issues,R.inspect(p).issues.filter(i=>i.scope==='sections'&&i.row===2));}});
test('row indexes must exist and retain raw Unicode and whitespace without numeric rewriting',()=>{const p=panel(1);p.sections[0]=section({bars:' 8.00 ',name:' 原文\r\n🎵 ',texture:'\t音色 '});const d=R.inspectRow(p,1);assert.equal(d.issueCount,0);assert.deepEqual(d.section,p.sections[0]);for(const row of [0,2,-1,1.1,'1',true,NaN])assert.throws(()=>R.inspectRow(p,row));});
test('full source shape, capacity, dense rows and Unicode are checked before a selected-row report',()=>{for(const change of [p=>p.extra=true,p=>p.sections.push(...Array.from({length:41},()=>section())),p=>delete p.sections[0],p=>p.sections[1].extra=true,p=>p.sections[1].name='\ud800',p=>p.fields['music-theme']='x'.repeat(8*1024*1024)]){const p=panel(2);change(p);assert.throws(()=>R.inspectRow(p,1));}});
test('a current original row can be located without changing input, IDs or selection',()=>{const {s,c}=setup();s.panel.sections[39].focus='';const before=structuredClone(s),v=c.check();assert.equal(v.report.row,40);assert.equal(c.locate(0,v.revision).field,'focus');assert.deepEqual(s,before);v.report.section.name='external';assert.equal(c.refresh().report.section.name,s.panel.sections[39].name);});
test('selection, same-text ID order and selected source changes stop old locations, with exact recovery',()=>{for(const change of [s=>s.selectedId=s.ids[38],s=>s.ids.reverse(),s=>s.panel.sections[39].focus='later',s=>s.panel.sections.pop()]){const {s,c}=setup();s.panel.sections[39].focus='';const v=c.check(),original=structuredClone(s);change(s);const before=structuredClone(s);assert.equal(c.locate(0,v.revision),null);assert.equal(c.refresh().stale,true);assert.deepEqual(s,before);Object.assign(s,original);assert.equal(c.refresh().stale,false);assert.equal(c.locate(0,v.revision).row,40);}});
test('unrelated sections and global song fields do not invalidate the selected five-field checklist',()=>{const {s,c}=setup();s.panel.sections[39].focus='';const v=c.check();s.panel.sections[0].texture='後續編修';s.panel.fields['music-bpm']='90';s.panel.avoid.push('後續');assert.equal(c.refresh().stale,false);assert.equal(c.locate(0,v.revision).row,40);});
test('recheck advances report revision and clear rejects older callbacks without changing the song',()=>{const {s,c}=setup();s.panel.sections[39].focus='';const old=c.check(),before=structuredClone(s),current=c.check();assert.ok(current.revision>old.revision);assert.equal(c.locate(0,old.revision),null);assert.equal(c.locate(0,current.revision).row,40);c.clear();assert.equal(c.locate(0,current.revision),null);assert.deepEqual(s,before);});
test('bad IDs, count mismatch and empty selection preserve previous report and revision',()=>{for(const change of [s=>delete s.ids[0],s=>s.ids[0]=s.ids[1],s=>s.ids[0]='x'.repeat(65),s=>s.ids.pop(),s=>s.selectedId='']){const {s,c}=setup();s.panel.sections[39].focus='';const v=c.check();change(s);assert.throws(()=>c.check());const after=c.refresh();assert.deepEqual(after.report,v.report);assert.equal(after.revision,v.revision);assert.equal(after.stale,true);}});
test('empty music is not reported as a selected section, and zero issues still remain local diagnostics',()=>{const p=panel(0);assert.throws(()=>R.inspectRow(p,1));const {s,c}=setup(),v=c.check();assert.equal(v.report.issueCount,0);assert.equal(c.locate(0),null);assert.ok(!Object.hasOwn(v.report,'files')&&!Object.hasOwn(v.report,'format'));});
test('fixed assets precede app and do not introduce an HTTP operation',()=>{const html=fs.readFileSync('web/index.html','utf8'),server=fs.readFileSync('music_lab_server.py','utf8');for(const name of ['music-section-review.js','music-section-review-dom.js']){assert.ok(html.indexOf('/'+name)<html.indexOf('/app.js'));assert.ok(server.includes('"/'+name+'"'));}assert.ok(!server.includes('/api/music-section-review'));});
