// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../web/music-section-review-dom.js');
function setup(){const nodes=new Map();const element=()=>({children:[],textContent:'',value:'id',disabled:false,classList:{toggle(){}},append(...v){this.children.push(...v);},replaceChildren(){this.children=[];}});const doc={getElementById:id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);},createElement:element};const s={nodes,visible:true,busy:false,calls:[],checked:0,errors:[]};s.d=D.bind(doc,{labels:{focus:'敘事任務'},visible:()=>s.visible,busy:()=>s.busy,onCheck:()=>{s.checked++;return true;},onLocate:(index,revision)=>{s.calls.push({index,revision});return true;},onError:e=>s.errors.push(e)});return s;}
const view=(extra={})=>({stale:false,revision:2,report:{row:40,totalSections:40,issueCount:1,issues:[{row:40,field:'focus',message:'<script>原文</script>'}]},...extra});
const button=s=>s.nodes.get('section-review-issues').children[0].children[0];
test('literal selected-row issues preserve original row and pass the report revision to focus',()=>{const s=setup();s.d.render(view());assert.equal(button(s).textContent,'段落 40 · 敘事任務：<script>原文</script>');assert.equal(button(s).onclick(),true);assert.deepEqual(s.calls,[{index:0,revision:2}]);});
test('old buttons are refused after new reports even if their handlers remain referenced',()=>{const s=setup();s.d.render(view());const old=button(s);s.d.render(view({revision:3}));assert.equal(old.onclick(),false);assert.deepEqual(s.calls,[]);button(s).onclick();assert.deepEqual(s.calls,[{index:0,revision:3}]);});
test('busy, hidden, stale and empty selection are checked when a previously enabled handler runs',()=>{for(const block of [s=>s.busy=true,s=>s.visible=false,s=>s.nodes.get('section-order').value='',s=>s.d.render(view({stale:true}))]){const s=setup();s.d.render(view());const old=button(s);block(s);assert.equal(old.onclick(),false);assert.deepEqual(s.calls,[]);}});
test('explicit check respects source availability, delegates once and reports zero as still needing whole-song validation',()=>{const s=setup();s.d.render(view());s.nodes.get('section-review-check').onclick();assert.equal(s.checked,1);s.busy=true;s.d.refresh();assert.equal(s.nodes.get('section-review-check').disabled,true);s.nodes.get('section-review-check').onclick();assert.equal(s.checked,1);s.busy=false;const zero=view();zero.report.issues=[];zero.report.issueCount=0;s.d.render(zero);assert.equal(s.nodes.get('section-review-issues').children.length,0);assert.match(s.nodes.get('section-review-status').textContent,/仍須整首歌曲驗證/);});
