// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const C=require('../web/backup-verification-controller.js'),D=require('../web/backup-verification-dom.js');
const raw=new TextEncoder().encode('合成備份🎵\r\n').buffer,sha=crypto.createHash('sha256').update(new Uint8Array(raw)).digest('hex'),flush=()=>new Promise(setImmediate);
function gate(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function harness(){const state={revision:1,busy:false,proof:{bytes:raw.byteLength,sha256:sha,entry_count:1}},reports=[],errors=[];let reads=0,hashes=0,activeReads=0,activeHashes=0,peak=0;const hashGates=[];
 const c=C.createController({capture:()=>state,describe:f=>({name:f.name,size:f.size}),readFile:async f=>{reads++;activeReads++;peak=Math.max(peak,activeReads+activeHashes);try{return f.read?await f.read.promise:raw;}finally{activeReads--;}}
 ,hash:async()=>{hashes++;activeHashes++;peak=Math.max(peak,activeReads+activeHashes);try{return hashGates.length?await hashGates.shift().promise:sha;}finally{activeHashes--;}}
 ,onReport:r=>reports.push(r),onError:e=>errors.push(e.message)});
 return {c,state,reports,errors,hashGates,file:()=>({name:'synthetic.zip',size:raw.byteLength,read:null}),get reads(){return reads;},get hashes(){return hashes;},get peak(){return peak;},get unfinished(){return activeReads+activeHashes;}};}
test('cancelled reads remain counted until settling and a third attempt never reads or replaces source',async()=>{const h=harness(),before=structuredClone(h.state),a=h.file(),b=h.file();a.read=gate();b.read=gate();const first=h.c.verify(a);h.c.cancel();const second=h.c.verify(b);h.c.cancel();assert.equal(h.c.view().waitingForWork,true);assert.equal(await h.c.verify(h.file()),false);assert.equal(h.reads,2);assert.equal(h.peak,2);a.read.resolve(raw);await first;assert.equal(h.c.view().available,true);b.read.reject(Error('old'));await second;assert.deepEqual(h.state,before);assert.equal(h.reports.length,0);assert.equal(h.errors.length,0);assert.equal(h.unfinished,0);});
test('cancelled hashes occupy both slots after reads finish until the actual hashes settle',async()=>{const h=harness(),a=gate(),b=gate();h.hashGates.push(a,b);const first=h.c.verify(h.file());await flush();h.c.cancel();const second=h.c.verify(h.file());await flush();h.c.cancel();assert.equal(h.hashes,2);assert.equal(h.unfinished,2);assert.equal(await h.c.verify(h.file()),false);assert.equal(h.reads,2);a.resolve(sha);await first;assert.equal(h.c.view().available,true);b.reject(Error('late hash'));await second;assert.equal(h.errors.length,0);assert.equal(h.reports.length,0);assert.equal(h.unfinished,0);});
test('one read and one hash share the same capacity and repeated cancellation cannot accumulate extra work',async()=>{const h=harness(),hash=gate(),a=h.file();a.read=gate();const first=h.c.verify(a);h.c.cancel();h.hashGates.push(hash);const second=h.c.verify(h.file());await flush();h.c.cancel();for(let i=0;i<30;i++){assert.equal(await h.c.verify(h.file()),false);h.c.cancel();}assert.equal(h.reads,2);assert.equal(h.hashes,1);assert.equal(h.peak,2);a.read.resolve(raw);hash.resolve(sha);await Promise.all([first,second]);assert.equal(h.unfinished,0);assert.equal(h.reports.length,0);});
test('capacity refusal does not supersede the newest pending proof and an old completion cannot replace its result',async()=>{const h=harness(),a=h.file(),b=h.file();a.read=gate();b.read=gate();const first=h.c.verify(a);h.c.cancel();const second=h.c.verify(b);assert.equal(await h.c.verify(h.file()),false);assert.equal(h.c.view().pending,true);b.read.resolve(raw);assert.equal(await second,true);const current=h.c.view().report;a.read.resolve(raw);await first;assert.deepEqual(h.c.view().report,current);assert.equal(h.reports.length,1);});
test('metadata rejection uses no slot while read shortfall or hash rejection releases the owned slot for retry',async()=>{const h=harness(),oversized=h.file();oversized.size=32*1024*1024+1;assert.equal(await h.c.verify(oversized),false);assert.equal(h.reads,0);const short=h.file();short.read=gate();const shortWork=h.c.verify(short);short.read.resolve(new ArrayBuffer(1));assert.equal(await shortWork,false);const bad=gate();h.hashGates.push(bad);const hashWork=h.c.verify(h.file());await flush();bad.reject(Error('hash failure'));assert.equal(await hashWork,false);assert.equal(h.unfinished,0);assert.equal(await h.c.verify(h.file()),true);assert.equal(h.reports.length,1);assert.equal(h.errors.length,3);});
test('source invalidation busy refresh and cancellation retain unfinished work until completion',async()=>{const h=harness(),a=h.file(),b=h.file();a.read=gate();b.read=gate();const first=h.c.verify(a);h.state.revision++;h.c.refresh();const second=h.c.verify(b);h.c.cancel();h.state.busy=true;h.c.refresh();assert.equal(h.c.view().available,false);h.state.busy=false;h.c.refresh();assert.equal(h.c.view().available,false);a.read.resolve(raw);await first;assert.equal(h.c.view().available,true);b.read.resolve(raw);await second;assert.equal(h.reports.length,0);assert.equal(h.unfinished,0);});
test('disposing during a hash leaves the real operation owned until its terminal outcome without late callbacks',async()=>{const h=harness(),a=gate();h.hashGates.push(a);const first=h.c.verify(h.file());await flush();h.c.dispose();assert.equal(h.unfinished,1);assert.equal(await h.c.verify(h.file()),false);a.resolve(sha);await first;assert.equal(h.unfinished,0);assert.equal(h.reports.length,0);assert.equal(h.errors.length,0);});
test('full metadata source epoch changes for revision bytes hash and entry count and is isolated from returned DTOs',()=>{for(const change of [s=>s.revision++,s=>s.proof.bytes++,s=>s.proof.sha256='f'.repeat(64),s=>s.proof.entry_count++]){const h=harness(),v=h.c.view();assert.equal(h.c.view().contextRevision,v.contextRevision);h.state.busy=true;assert.equal(h.c.view().contextRevision,v.contextRevision);h.state.busy=false;change(h.state);assert.equal(h.c.view().contextRevision,v.contextRevision+1);v.contextRevision=999;v.source.sha256='a'.repeat(64);assert.notEqual(h.c.view().contextRevision,999);assert.notEqual(h.state.proof.sha256,'a'.repeat(64));}});
function domHarness(){const state={revision:1,busy:false,proof:{bytes:raw.byteLength,sha256:sha,entry_count:1}},events=new Map(),errors=[],hashGates=[];const document={activeElement:null,getElementById:id=>nodes[id]};
 const make=()=>{const handlers=new Map(),attrs=new Map();return {files:[],value:'',textContent:'',disabled:false,dataset:{},handlers,attrs,focus(){if(this.disabled)return;const old=document.activeElement;document.activeElement=this;if(old!==this)old?.handlers.get('blur')?.();},hasAttribute:k=>attrs.has(k),setAttribute:(k,v)=>attrs.set(k,v),addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:(n,f)=>{assert.equal(handlers.get(n),f);handlers.delete(n);}};};
 const nodes=Object.fromEntries(['backup-verify-file','backup-verify-source','backup-verify-note','backup-verify-cancel','other'].map(id=>[id,make()]));document.activeElement=nodes.other;
 class File{constructor(){this.name='synthetic.zip';this.size=raw.byteLength;}arrayBuffer(){return Promise.resolve(raw);}}
 const adapter=D.bind(document,{capture:()=>state,FileType:File,hash:()=>hashGates.shift().promise,events:{addEventListener:(n,f)=>events.set(n,f),removeEventListener:(n,f)=>{assert.equal(events.get(n),f);events.delete(n);}},onError:e=>errors.push(e.message)});
 const choose=async()=>{const g=gate();hashGates.push(g);nodes['backup-verify-file'].files=[new File()];nodes['backup-verify-file'].onchange();await flush();return g;};const cancel=()=>{nodes['backup-verify-cancel'].focus();nodes['backup-verify-cancel'].onclick();};
 return {state,nodes,document,events,errors,adapter,choose,cancel};}
test('backup DOM cancellation focuses picker or capped note and settling a current hash restores picker',async()=>{const h=domHarness(),a=await h.choose();h.cancel();assert.equal(h.document.activeElement,h.nodes['backup-verify-file']);const b=await h.choose();h.cancel();assert.equal(h.document.activeElement,h.nodes['backup-verify-note']);assert.equal(h.nodes['backup-verify-file'].disabled,true);assert.match(h.nodes['backup-verify-note'].textContent,/雜湊/);a.resolve(sha);await flush();assert.equal(h.document.activeElement,h.nodes['backup-verify-file']);b.resolve(sha);await flush();assert.equal(h.nodes['backup-verify-note'].dataset.match,'unknown');h.adapter.dispose();assert.equal(h.events.size,0);assert.equal(h.nodes['backup-verify-note'].handlers.size,0);});
test('backup DOM loses a capped invitation on later edits and source changes while preserving current proof',async()=>{for(const changed of ['focus','source','pagehide']){const h=domHarness(),a=await h.choose();h.cancel();const b=await h.choose();h.cancel();if(changed==='focus'){h.nodes.other.focus();h.nodes.other.value='後續原文';}else if(changed==='source'){h.state.proof.entry_count++;h.adapter.refresh();}else h.events.get('pagehide')();a.resolve(sha);b.reject(Error('late'));await flush();assert.equal(h.document.activeElement,changed==='focus'?h.nodes.other:h.nodes['backup-verify-note']);assert.equal(h.errors.length,0);assert.equal(h.nodes['backup-verify-note'].dataset.match,'unknown');h.adapter.dispose();}});
test('backup DOM disposal removes its owned focus listener and ignores delayed hash completion',async()=>{const h=domHarness(),a=await h.choose();h.cancel();const b=await h.choose();h.cancel();h.adapter.dispose();a.resolve(sha);b.resolve(sha);await flush();assert.equal(h.document.activeElement,h.nodes['backup-verify-note']);assert.equal(h.nodes['backup-verify-cancel'].disabled,true);assert.equal(h.nodes['backup-verify-cancel'].onclick,null);assert.equal(h.nodes['backup-verify-note'].handlers.size,0);assert.equal(h.errors.length,0);});
test('four controls use the shared bounded focus metadata and fixed local asset without new backend operations',()=>{const html=fs.readFileSync('web/index.html','utf8'),server=fs.readFileSync('music_lab_server.py','utf8'),css=fs.readFileSync('web/style.css','utf8');assert.ok(html.indexOf('/verification-focus.js')<html.indexOf('/backup-verification-dom.js'));assert.ok(html.indexOf('/verification-focus.js')<html.indexOf('/text-verification-dom.js'));assert.ok(server.includes('"/verification-focus.js": ("web/verification-focus.js", "text/javascript")'));const note=html.match(/<p id="backup-verify-note"[^>]*>/)[0],cancel=html.match(/<button id="backup-verify-cancel"[^>]*>/)[0];assert.match(note,/tabindex="-1"/);assert.match(cancel,/aria-controls="backup-verify-note"/);assert.match(cancel,/aria-describedby="backup-verify-note"/);for(const prefix of ['text','draft','audio-accept','backup'])assert.ok(css.includes('#'+prefix+'-verify-note:focus'));});
