// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../web/text-verification-page.js'),W=require('../web/delivery-text.js'),C=require('../web/text-verification-controller.js');
const bytes=s=>new TextEncoder().encode(s),source=content=>({name:'original.txt',content});
test('owned byte slice matches the existing complete-text range and rejects wrong type capacity or character boundaries',()=>{const s='\ufeffA\r\n🎵',b=bytes(s);assert.deepEqual(W.sliceBytes(b),W.window(s));for(const v of [new Uint16Array([1]),{},new Uint8Array(8*1024*1024+1)])assert.throws(()=>W.sliceBytes(v));assert.throws(()=>W.sliceBytes(b,1));});
test('a difference beyond the old 32768-unit preview is centered in a bounded current-source page',()=>{const s='x'.repeat(5*1024*1024)+'🎵\r\n'+'tail'.repeat(3000),p=P.prepare(source(s)),position=5*1024*1024+3,start=p.differenceStart(position),page=p.window(start),v=P.presentation(page,position);assert.equal(page.max_bytes,16384);assert.ok(page.end_byte-page.start_byte<=16384);assert.equal(v.marked,'🎵');assert.equal(v.hasPosition,true);assert.ok(start>32768);});
test('every byte of a Unicode character locates the complete character including surrogate pairs',()=>{for(const char of ['🎵','中','é'])for(let i=0;i<bytes(char).length;i++){const p=P.prepare(source('a'+char+'b')),page=p.window(0),v=P.presentation(page,1+i);assert.equal(v.before,'a');assert.equal(v.marked,char);assert.equal(v.after,'b');}});
test('raw source CRLF BOM NUL bidi and tab are preserved while presentation explicitly escapes them',()=>{const s='\ufeffA\r\n\0\t\u202eB',p=P.prepare(source(s)),page=p.window(0),v=P.presentation(page,bytes('\ufeffA\r\n').length);assert.equal(page.text,s);assert.equal(v.marked,'\\u0000');assert.equal(v.before,'\\ufeffA\\r\n');assert.equal(v.after,'\\t\\u202eB');});
test('EOF empty source and a page without the difference are explicit rather than guessed',()=>{const p=P.prepare(source('abc')),v=P.presentation(p.window(0),3);assert.equal(v.atEOF,true);assert.equal(v.marked,'');assert.equal(P.presentation(P.prepare(source('')).window(0),0).atEOF,true);const long=P.prepare(source('x'.repeat(20000)));assert.equal(P.presentation(long.window(0),19999).hasPosition,false);});
test('unknown page fields positions invalid Unicode and oversized complete sources reject',()=>{const p=P.prepare(source('abc')),page=p.window(0);for(const index of [-1,4,NaN,0.5])assert.throws(()=>P.presentation(page,index));assert.throws(()=>P.presentation({...page,extra:true},0));assert.throws(()=>P.prepare(source('\ud800')));assert.throws(()=>P.prepare(source('x'.repeat(8*1024*1024+1))));});
function harness(content='x'.repeat(40000)+'🎵'+'tail'.repeat(10000)){const state={scope:'music',revision:1,busy:false,dirty:false,visible:true,source:source(content)},reports=[],errors=[];let reads=0;const c=C.createController({capture:()=>state,describe:f=>({name:'candidate.txt',size:f.data.length}),readFile:async f=>{reads++;return f.data;},onReport:r=>reports.push(r),onError:e=>errors.push(e.message)});return {state,c,reports,errors,get reads(){return reads;},file:s=>({data:bytes(s)})};}
test('original reading is opt-in after mismatch and navigation never rereads the selected File or expands report',async()=>{const h=harness(),bad=h.state.source.content.replace('🎵','🎶');await h.c.verify(h.file(bad));assert.equal(h.c.view().original.page,null);assert.equal(h.c.openOriginal(),true);const page=h.c.view().original.page;assert.ok(page.start_byte<=40003&&page.end_byte>40003);assert.equal(P.presentation(page,40003).marked,'🎵');assert.equal(h.c.nextOriginal(),true);assert.equal(h.c.previousOriginal(),true);assert.equal(h.c.firstOriginal(),true);assert.equal(h.c.view().original.page.start_byte,0);assert.equal(h.reads,1);assert.equal(Object.keys(h.reports[0]).length,7);});
test('page view is isolated and closing or exact source invalidation erases page and navigation history',async()=>{for(const change of ['close','revision','text','busy','dirty','hidden','cancel','dispose']){const h=harness();await h.c.verify(h.file('other'));h.c.openOriginal();h.c.nextOriginal();const v=h.c.view();v.original.page.text='wrong';assert.notEqual(h.c.view().original.page.text,'wrong');if(change==='close')h.c.closeOriginal();if(change==='revision')h.state.revision++;if(change==='text')h.state.source.content+='later';if(change==='busy')h.state.busy=true;if(change==='dirty')h.state.dirty=true;if(change==='hidden')h.state.visible=false;if(change==='cancel'||change==='dispose')h.c[change]();if(!['close','cancel','dispose'].includes(change))h.c.refresh();assert.equal(h.c.view().original.page,null);assert.equal(h.c.view().original.canPrevious,false);}});
test('matching proof and new pending verification cannot open old original pages',async()=>{const h=harness();assert.equal(h.c.openOriginal(),false);await h.c.verify(h.file(h.state.source.content));assert.equal(h.c.openOriginal(),false);await h.c.verify(h.file('other'));h.c.openOriginal();const pending=h.c.verify(h.file('next'));assert.equal(h.c.view().original.page,null);assert.equal(h.c.openOriginal(),false);await pending;h.c.dispose();assert.equal(h.c.openOriginal(),false);});
test('failed current confirmation callback preserves original report but cannot expose an original page',async()=>{const state={scope:'draft',revision:1,busy:false,dirty:false,visible:true,source:source('original')},c=C.createController({capture:()=>state,describe:()=>({name:'bad.txt',size:5}),readFile:async()=>bytes('other'),onReport:()=>{throw Error('callback failure');}});assert.equal(await c.verify({}),false);assert.equal(c.view().report.matched,false);assert.equal(c.openOriginal(),false);assert.equal(c.view().original.page,null);});
test('closed navigation does not open or prepare a source and boundary actions preserve the displayed page',async()=>{const h=harness();await h.c.verify(h.file('other'));assert.equal(h.c.nextOriginal(),false);assert.equal(h.c.previousOriginal(),false);assert.equal(h.c.view().original.canRead,false);h.c.openOriginal();const page=h.c.view().original.page;assert.equal(h.c.previousOriginal(),false);assert.deepEqual(h.c.view().original.page,page);h.c.closeOriginal();assert.equal(h.c.nextOriginal(),false);assert.equal(h.c.view().original.canRead,false);});
test('escaped control presentation remains bounded by six times the page bytes without changing raw content',()=>{const s='\0'.repeat(16384),page=P.prepare(source(s)).window(0),v=P.presentation(page,8000);assert.equal(v.before.length+v.marked.length+v.after.length,98304);assert.equal(page.text,s);});
const D=require('../web/text-verification-dom.js'),flush=()=>new Promise(setImmediate);
function pageDOM(prefix,{partial=false}={}){
 const h=harness(),nodes={},handlers=new Map();h.state.scope=prefix==='draft'?'draft':prefix==='audio-accept'?'audio':'music';
 const doc={activeElement:null,getElementById:id=>nodes[id]||null,createTextNode:text=>({textContent:text}),createElement:tag=>node(tag)};
 function node(id){return {id,files:[],value:'',disabled:false,hidden:false,dataset:{},children:[],_text:'',attrs:{},get textContent(){return this.children.length?this.children.map(n=>n.textContent).join(''):this._text;},set textContent(s){this._text=s;this.children=[];},setAttribute(k,v){this.attrs[k]=v;},hasAttribute(k){return Object.hasOwn(this.attrs,k);},replaceChildren(...v){this.children=v;this._text='';},focus(){doc.activeElement=this;},addEventListener(){},removeEventListener(){}};}
 for(const suffix of ['file','note','source','cancel','context','expected-context','selected-context'])nodes[prefix+'-verify-'+suffix]=node(prefix+'-verify-'+suffix);
 for(const suffix of ['open','region','first','previous','next','close','note',...(partial?[]:['content'])])nodes[prefix+'-verify-original-'+suffix]=node(prefix+'-verify-original-'+suffix);
 let fileReads=0,release;class File{constructor(s,pending=false){this.data=bytes(s);this.name='candidate.txt';this.size=this.data.length;this.pending=pending;}arrayBuffer(){fileReads++;return this.pending?new Promise(r=>release=()=>r(this.data.buffer)):Promise.resolve(this.data.buffer);}}
 const a=D.bind(doc,{capture:()=>h.state,FileType:File,ids:{file:prefix+'-verify-file',note:prefix+'-verify-note',source:prefix+'-verify-source',cancel:prefix+'-verify-cancel'},events:{addEventListener:(k,v)=>handlers.set(k,v),removeEventListener:k=>handlers.delete(k)},onReport:r=>h.reports.push(r)});
 const choose=async(s,pending=false)=>{const f=nodes[prefix+'-verify-file'];f.files=[new File(s,pending)];f.onchange();await flush();};
 return {...h,doc,nodes,handlers,a,choose,get fileReads(){return fileReads;},release:()=>release(),n:key=>nodes[prefix+'-verify-original-'+key]};
}
for(const prefix of ['text','draft','audio-accept'])test(prefix+' explicitly locates the full original character and keeps focus on manual page actions only',async()=>{const h=pageDOM(prefix),original=h.state.source.content;await h.choose(original.replace('🎵','🎶'));assert.equal(h.n('open').disabled,false);assert.equal(h.n('region').hidden,true);h.n('open').onclick();assert.equal(h.n('region').hidden,false);const mark=h.n('content').children.find(n=>n.id==='mark');assert.equal(mark.textContent,'🎵');assert.equal(h.doc.activeElement,mark);h.a.refresh();assert.equal(h.n('content').children.find(n=>n.id==='mark'),mark);h.n('next').onclick();assert.equal(h.doc.activeElement,h.n('content'));h.n('previous').onclick();assert.equal(h.n('content').children.find(n=>n.id==='mark').textContent,'🎵');h.n('first').onclick();assert.match(h.n('note').textContent,/差異不在本段/);h.n('open').onclick();h.n('close').onclick();assert.equal(h.doc.activeElement,h.n('open'));assert.equal(h.n('content').textContent,'');assert.equal(h.fileReads,1);assert.equal(h.state.source.content,original);assert.equal(Object.keys(h.reports[0]).length,7);h.a.dispose();});
test('literal DOM reading does not execute source HTML and control escaping is explicit',async()=>{const h=pageDOM('text');h.state.source.content='<script>\0\ufeff\u202e';await h.choose('other');h.n('open').onclick();assert.equal(h.n('content').textContent,'<script>\\u0000\\ufeff\\u202e');assert.equal(h.n('content').innerHTML,undefined);assert.match(h.n('note').textContent,/控制字元以跳脫符號/);h.a.dispose();});
test('match revision pagehide cancel and disposal erase original DOM without replacing later edits',async()=>{for(const action of ['match','revision','pagehide','cancel','dispose']){const h=pageDOM('text');await h.choose('other');h.n('open').onclick();if(action==='match')await h.choose(h.state.source.content);if(action==='revision'){h.state.revision++;h.state.source.content+='later';h.a.refresh();}if(action==='pagehide')h.handlers.get('pagehide')();if(action==='cancel')h.nodes['text-verify-cancel'].onclick();if(action==='dispose')h.a.dispose();assert.equal(h.n('region').hidden,true);assert.equal(h.n('content').textContent,'');assert.equal(h.n('open').disabled,true);if(action==='revision')assert.ok(h.state.source.content.endsWith('later'));if(action==='dispose')assert.equal(h.n('open').onclick,null);else h.a.dispose();}});
test('pending read clears previous original and late completion after source revision cannot reopen it',async()=>{const h=pageDOM('text');await h.choose('other');h.n('open').onclick();await h.choose('late',true);assert.equal(h.n('region').hidden,true);assert.equal(h.n('open').disabled,true);h.state.revision++;h.state.source.content+='later';h.a.refresh();h.release();await flush();assert.equal(h.n('open').disabled,true);assert.equal(h.n('content').textContent,'');assert.equal(h.reports.length,1);h.a.dispose();});
test('partial optional reader DOM keeps the existing verification flow available',async()=>{const h=pageDOM('text',{partial:true});await h.choose('other');assert.equal(h.reports[0].matched,false);assert.equal(h.n('open').onclick,undefined);await h.choose(h.state.source.content);assert.equal(h.reports[1].matched,true);h.a.dispose();});
