// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../web/storyboard-shot-review-dom.js');
function setup(){const nodes=new Map();function element(){return {children:[],textContent:'',value:'id',disabled:false,classList:{toggle(){}},append(...v){this.children.push(...v);},replaceChildren(){this.children=[];}};}
 const doc={getElementById(id){if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);},createElement:element};let busy=false,visible=true,calls=[];
 const d=D.bind(doc,{labels:{visual:'畫面動作'},visible:()=>visible,busy:()=>busy,onLocate:(index,revision)=>calls.push({index,revision})});
 return {d,nodes,calls,set busy(v){busy=v;},set visible(v){visible=v;}};
}
const view=()=>({report:{row:100,total_shots:120,issue_count:1,issues:[{row:100,field:'visual',message:'<原文>',related_row:null}]},stale:false,revision:4});
test('DOM preserves literal issue text and rejects a callback from an old report revision',()=>{const s=setup();s.d.render(view());const button=s.nodes.get('shot-review-issues').children[0].children[0];assert.equal(button.textContent,'鏡頭 100 · 畫面動作：<原文>');button.onclick();assert.deepEqual(s.calls,[{index:0,revision:4}]);s.d.render({...view(),revision:5});button.onclick();assert.equal(s.calls.length,1);});
test('DOM busy, hidden, stale and empty selection gates keep source buttons unavailable',()=>{const s=setup();s.d.render(view());assert.equal(s.nodes.get('shot-review-check').disabled,false);s.busy=true;s.d.refresh();assert.equal(s.nodes.get('shot-review-check').disabled,true);s.busy=false;s.visible=false;s.d.refresh();assert.equal(s.nodes.get('shot-review-report').disabled,true);s.visible=true;s.d.render({...view(),stale:true});assert.equal(s.nodes.get('shot-review-issues').children[0].children[0].disabled,true);s.nodes.get('shots-order').value='';s.d.refresh();assert.equal(s.nodes.get('shot-review-check').disabled,true);});

test('toolbar advances after actual focus and keeps the same position across cloned refresh',()=>{const s=setup();s.calls.length=0;const d=D.bind({getElementById:id=>s.nodes.get(id)||(()=>{const e={value:'id',disabled:false,textContent:'',classList:{toggle(){}},replaceChildren(){},append(){}};s.nodes.set(id,e);return e;})(),createElement:()=>({append(){}})},{labels:{visual:'畫面動作'},visible:()=>true,busy:()=>false,onLocate:(index,revision)=>{s.calls.push({index,revision});return true;}});const v=view();v.report.issues.push({...v.report.issues[0],field:'visual'});v.report.issue_count=2;d.render(v);s.nodes.get('shot-issue-next').onclick();assert.match(s.nodes.get('shot-issue-note').textContent,/1／2/);d.render(structuredClone(v));s.nodes.get('shot-issue-next').onclick();assert.match(s.nodes.get('shot-issue-note').textContent,/2／2/);assert.equal(s.nodes.get('shot-issue-next').disabled,true);s.nodes.get('shot-issue-previous').onclick();assert.deepEqual(s.calls,[{index:0,revision:4},{index:1,revision:4},{index:0,revision:4}]);});
test('toolbar callback gates are rechecked even if a disabled button handler is invoked',()=>{const s=setup();s.d.render(view());for(const key of ['busy','visible']){s[key]=key==='busy';s.nodes.get('shot-issue-next').onclick();assert.deepEqual(s.calls,[]);s[key]=key==='visible';}s.d.render({...view(),stale:true});s.nodes.get('shot-issue-next').onclick();assert.deepEqual(s.calls,[]);});
test('toolbar check delegates without focus or writes and respects busy and selection',()=>{const s=setup();let checked=0;const doc={getElementById:id=>s.nodes.get(id),createElement:()=>({append(){}})};s.d.render(view());const d=D.bind(doc,{labels:{visual:'畫面動作'},visible:()=>true,busy:()=>s.nodes.get('shot-review-check').disabled,onLocate:()=>true,onCheck:()=>checked++});s.nodes.get('shot-issue-check').onclick();assert.equal(checked,1);s.nodes.get('shot-review-check').disabled=true;s.nodes.get('shot-issue-check').onclick();assert.equal(checked,1);s.nodes.get('shot-review-check').disabled=false;s.nodes.get('shots-order').value='';s.nodes.get('shot-issue-check').onclick();assert.equal(checked,1);});
