// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {execFileSync}=require('node:child_process');
const R=require('../web/music-readiness.js');
const partial=()=>JSON.parse(fs.readFileSync('examples/unfinished-song-review.json','utf8')).panel;
const wire=p=>{const data=R.report(p);return {data,files:{'music-review.json':JSON.stringify(data),'music-review.md':R.markdown(data)},meta:{version:'0.31.0',protocol_version:1,needs_review:true}};};
test('versioned song report preserves raw fields and original positions without inventing content',()=>{const p=partial(),before=structuredClone(p),d=R.report(p);assert.equal(d.schema_version,1);assert.equal(d.status,'needs_correction');assert.equal(d.issue_count,3);assert.deepEqual(d.issues.map(i=>[i.scope,i.row,i.field]),[['sections',3,'focus'],['sections',4,'bars'],['deliverables',2,'text']]);assert.deepEqual(d.source,p);d.source.sections[0].focus='changed';assert.deepEqual(p,before);assert.match(R.markdown(d),/實唱／實聽/);});
test('zero report remains field-only and full count is distinguished from detail truncation',()=>{const p=partial();p.sections=Array.from({length:40},()=>Object.fromEntries(['name','bars','energy','focus','texture'].map(k=>[k,''])));p.avoid=Array(100).fill('');p.deliverables=Array(100).fill('');const d=R.report(p);assert.equal(d.issue_count,400);assert.equal(d.issues.length,200);assert.equal(d.details_truncated,true);assert.match(R.markdown(d),/全部欄位已檢查/);p.sections=[{name:'段',bars:'1',energy:'1',focus:'事',texture:'聲'}];p.avoid=[];p.deliverables=['成果'];assert.equal(R.report(p).status,'fields_checked');assert.match(R.markdown(R.report(p)),/仍須完整建立/);});
test('actual Python report is accepted with complete source JSON and Markdown matching',()=>{const p=partial();const reply=JSON.parse(execFileSync(process.platform==='win32'?'python':'python3',['-X','utf8','-c',"import json;from musiclab.application import build;print(json.dumps(build('music_review',{'panel':json.loads(input())}).wire(),ensure_ascii=False))"],{input:JSON.stringify(p),encoding:'utf8',timeout:10000}));assert.deepEqual(R.checkedResult(p,reply),reply);});
test('unknown versions source changes hidden edits and false success cannot replace previous files',()=>{const mutations=[v=>v.data.schema_version=999,v=>v.data.status='fields_checked',v=>v.data.issue_count=0,v=>v.data.source.fields['music-lyrics']='hidden edit',v=>v.data.source.sections.reverse(),v=>v.data.issues.pop(),v=>v.data.extra=true,v=>v.meta.protocol_version=2,v=>v.meta.needs_review=false,v=>v.files['music-review.json']='{}',v=>v.files['music-review.md']='fake',v=>v.files['extra']='bad'];for(const edit of mutations){const p=partial(),w=wire(p);edit(w);assert.throws(()=>R.checkedResult(p,w));}});
test('strict report JSON rejects duplicate keys Unicode corruption and mismatching same-title report',()=>{const p=partial();for(const content of ['{"schema_version":1,"schema_version":999}','{"x":"\\ud800"}']){const w=wire(p);w.files['music-review.json']=content;assert.throws(()=>R.checkedResult(p,w));}const other=partial();other.sections[2].focus='other';assert.throws(()=>R.checkedResult(p,wire(other)));});
test('accepted wire and caller source remain isolated while object key order is canonical',()=>{const p=partial(),w=wire(p);w.data.source.fields=Object.fromEntries(Object.entries(w.data.source.fields).reverse());w.files['music-review.json']=JSON.stringify(w.data);const accepted=R.checkedResult(p,w);accepted.data.source.sections[0].focus='changed';assert.notEqual(w.data.source.sections[0].focus,'changed');assert.notEqual(p.sections[0].focus,'changed');});
function handler(){const source=fs.readFileSync('web/app.js','utf8'),start=source.indexOf("$('music-ready-report').onclick="),end=source.indexOf("$('music-form').onsubmit",start),elements={'music-ready-report':{},'music-visual':{hidden:false}},events=[];let resolve;const p=partial();const ctx={$:id=>elements[id],capturePanel:()=>p,musicReadyController:{check:()=>events.push('local-check')},MusicReadiness:R,api:(_route,payload)=>{events.push({route:_route,payload:structuredClone(payload)});return new Promise(r=>resolve=r);},setFiles:(files,note)=>events.push({files,note}),say:text=>events.push(text),run:(_b,fn)=>fn(()=>ctx.current),current:true};vm.createContext(ctx);vm.runInContext(source.slice(start,end),ctx);return {p,ctx,elements,events,start:()=>elements['music-ready-report'].onclick(),respond:r=>resolve(r)};}
test('actual report handler sends unchanged incomplete source and only replaces files after verified reply',async()=>{const s=handler(),before=structuredClone(s.p),pending=s.start();assert.deepEqual(s.events.slice(0,2),['local-check',{route:'/api/music-review',payload:{panel:before}}]);assert.equal(s.elements['music-visual'].hidden,false);s.respond(wire(s.p));await pending;assert.equal(s.elements['music-visual'].hidden,true);assert.deepEqual(Object.keys(s.events[2].files),['music-review.json','music-review.md']);assert.deepEqual(s.p,before);});
test('actual handler leaves prior visual files and later edits when request is stale',async()=>{const s=handler(),pending=s.start();s.p.sections[2].focus='later edit';s.ctx.current=false;s.respond(wire(partial()));await pending;assert.equal(s.elements['music-visual'].hidden,false);assert.equal(s.events.length,2);assert.equal(s.p.sections[2].focus,'later edit');});
test('actual handler rejects foreign reply before visual or file mutation',async()=>{const s=handler(),pending=s.start();const bad=wire(s.p);bad.data.issue_count=0;s.respond(bad);await assert.rejects(pending,/不一致/);assert.equal(s.elements['music-visual'].hidden,false);assert.equal(s.events.length,2);});
