// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),D=require('../web/editor-selection-dom.js');
function setup(){
 const nodes={},events=[];let busy=false;
 const document={activeElement:null,getElementById:id=>nodes[id]};
 for(const [list,panel,select] of [['arrangement','music','section-order'],['shots','storyboard','shots-order'],['cues','lyrics','cues-order']]){
  nodes[panel]={hidden:false,isConnected:true};nodes[select]={value:list+'-0'};const container=nodes[list]={id:list,isConnected:true,children:[],listeners:new Map(),addEventListener:(t,f)=>container.listeners.set(t,f),removeEventListener:(t,f)=>{assert.equal(container.listeners.get(t),f);container.listeners.delete(t);}};
  for(let i=0;i<2;i++){const row={dataset:{historyId:list+'-'+i},parentElement:container,isConnected:true};const input={isConnected:true,disabled:false,hidden:false,closest:()=>row};row.input=input;row.contains=t=>t===input;container.children.push(row);}
 }
 const adapter=D.bind(document,{busy:()=>busy,onSelection:(list,id,index)=>{events.push({list,id,index});nodes[{arrangement:'section-order',shots:'shots-order',cues:'cues-order'}[list]].value=id;return true;},onError:e=>events.push({error:e.message})});
 return {nodes,document,adapter,events,set busy(v){busy=v;},focus(list,index){const input=nodes[list].children[index].input;document.activeElement=input;nodes[list].listeners.get('focusin')({target:input});}};
}
test('one owned focus listener per list follows native field focus and stable row IDs',()=>{const s=setup();for(const list of ['arrangement','shots','cues']){s.focus(list,1);assert.deepEqual(s.events.at(-1),{list,id:list+'-1',index:1});assert.equal(s.nodes[list].listeners.size,1);}});
test('focus from a new or restored row chooses that current identity after structure replacement',()=>{const s=setup(),row=s.nodes.cues.children[1];row.dataset.historyId='new-or-restored';s.nodes.cues.children.reverse();s.focus('cues',0);assert.deepEqual(s.events.at(-1),{list:'cues',id:'new-or-restored',index:0});assert.equal(s.nodes['cues-order'].value,'new-or-restored');});
test('busy hidden detached disabled foreign or no-longer-active focus cannot change selection',()=>{for(const kind of ['busy','hidden','detached-row','detached-field','disabled','field-hidden','foreign','inactive']){const s=setup(),row=s.nodes.shots.children[1],input=row.input;s.document.activeElement=input;if(kind==='busy')s.busy=true;if(kind==='hidden')s.nodes.storyboard.hidden=true;if(kind==='detached-row')row.isConnected=false;if(kind==='detached-field')input.isConnected=false;if(kind==='disabled')input.disabled=true;if(kind==='field-hidden')input.hidden=true;if(kind==='foreign')row.parentElement=s.nodes.cues;if(kind==='inactive')s.document.activeElement=s.nodes.shots.children[0].input;s.nodes.shots.listeners.get('focusin')({target:input});assert.deepEqual(s.events,[],kind);assert.equal(s.nodes['shots-order'].value,'shots-0',kind);}});
test('dispose removes all three owned listeners without changing selected rows',()=>{const s=setup();s.adapter.dispose();for(const list of ['arrangement','shots','cues'])assert.equal(s.nodes[list].listeners.size,0);assert.deepEqual(s.events,[]);});
test('busy completion refresh follows a diagnostic field already focused without moving it or reviving disposed work',()=>{const s=setup();s.busy=true;s.focus('shots',1);assert.equal(s.adapter.refresh(),false);assert.deepEqual(s.events,[]);s.busy=false;assert.equal(s.adapter.refresh(),true);assert.equal(s.nodes['shots-order'].value,'shots-1');assert.equal(s.document.activeElement,s.nodes.shots.children[1].input);s.nodes.storyboard.hidden=true;assert.equal(s.adapter.refresh(),false);s.nodes.storyboard.hidden=false;s.adapter.dispose();assert.equal(s.adapter.refresh(),false);});
test('actual app selection callback updates view state only and preserves dirty and movement histories',()=>{const app=fs.readFileSync('web/app.js','utf8'),a=app.indexOf('const editorSelection=MusicEditorSelectionDOM.bind('),b=app.indexOf('function refreshCollectionControls(',a),events=[],select={value:''};let options;const context={MusicEditorSelectionDOM:{bind:(_d,o)=>{options=o;return {}; }},document:{},state:{busy:false},$:()=>select,refreshMusicSelection:()=>events.push('music-view'),editorOrder:{select:(...args)=>{events.push(args);return true;}},say:()=>{}};vm.runInNewContext(app.slice(a,b),context);assert.equal(options.onSelection('arrangement','music-new',2),true);assert.equal(select.value,'music-new');assert.deepEqual(events,['music-view']);assert.equal(options.onSelection('shots','shot-new',2),true);assert.deepEqual(events.at(-1),['shots','shot-new']);assert.equal(options.onSelection('cues','cue-new',2),true);assert.deepEqual(events.at(-1),['cues','cue-new']);});
test('music selection refresh reads IDs only and updates boundary buttons without rebuilding options or focus',()=>{const app=fs.readFileSync('web/app.js','utf8'),a=app.indexOf('function refreshMusicSelection('),b=app.indexOf('function renderMusicOrder(',a),rows=['a','b'].map(id=>({dataset:{historyId:id},toggleAttribute:(_n,v)=>{selected[id]=v;}})),selected={},nodes={arrangement:{children:rows},'section-order':{value:'b'},'section-earlier':{},'section-later':{}};const ctx={$:id=>nodes[id],state:{busy:false}};vm.runInNewContext(app.slice(a,b),ctx);ctx.refreshMusicSelection();assert.deepEqual(selected,{a:false,b:true});assert.equal(nodes['section-earlier'].disabled,false);assert.equal(nodes['section-later'].disabled,true);ctx.state.busy=true;ctx.refreshMusicSelection();assert.equal(nodes['section-earlier'].disabled,true);});
