// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const M=require('../web/backup-selection.js'),D=require('../web/backup-selection-dom.js'),Download=require('../web/backup-download-dom.js');
const id=n=>'draft-'+n.toString(16).padStart(32,'0');
const record=(n,label='版本 '+n+' 🎵')=>({library_schema_version:1,id:id(n),label,stored_at:'2026-10-06T10:00:00+00:00',sha256:'a'.repeat(64),bytes:200,draft_schema_version:3,created_with:'0.130.0',titles:{music:'合成歌曲',storyboard:'',lyrics:''}});
function harness(displayed=[record(1),record(2)]){let s={enabled:true,busy:false,selected:displayed[0]||null,displayed};const errors=[];const c=M.createController({capture:()=>s,onError:e=>errors.push(e.message)});return {c,errors,get s(){return s;},set s(v){s=v;}};}
test('legacy and empty display never remove retained choices or infer the whole library',()=>{const h=harness();h.c.addDisplayed();delete h.s.displayed;assert.equal(h.c.removeDisplayed(),false);assert.equal(h.c.refresh().canRemoveDisplayed,false);h.s.displayed=[];assert.equal(h.c.removeDisplayed(),false);assert.deepEqual(h.c.request(),{ids:[id(1),id(2)]});});
test('bulk removal changes only the displayed intersection and leaves captured metadata untouched',()=>{const h=harness([record(1),record(2),record(3)]);h.c.addDisplayed();h.s.displayed=[record(2),record(4)];const source=structuredClone(h.s);assert.equal(h.c.refresh().removableDisplayedCount,1);assert.equal(h.c.removeDisplayed(),true);assert.deepEqual(h.c.request(),{ids:[id(1),id(3)]});assert.deepEqual(h.s,source);assert.equal(h.c.removeDisplayed(),false);});
test('partial search page removal leaves unloaded matches until the user appends another page',()=>{const h=harness(Array.from({length:41},(_,i)=>record(i+1)));h.c.addDisplayed();h.s.displayed=Array.from({length:20},(_,i)=>record(i+12));h.c.removeDisplayed();assert.deepEqual(h.c.request().ids,[...Array.from({length:11},(_,i)=>id(i+1)),...Array.from({length:10},(_,i)=>id(i+32))]);h.s.displayed=Array.from({length:31},(_,i)=>record(i+1));assert.equal(h.c.refresh().removableDisplayedCount,11);h.c.removeDisplayed();assert.deepEqual(h.c.request().ids,Array.from({length:10},(_,i)=>id(i+32)));});
test('identical repeated IDs remove one retained entry and do not multiply removal counts',()=>{const h=harness();h.c.addDisplayed();h.s.displayed=[record(1),record(1)];assert.equal(h.c.refresh().removableDisplayedCount,1);assert.equal(h.c.removeDisplayed(),true);assert.deepEqual(h.c.request(),{ids:[id(2)]});});
test('a late conflicting selected version prevents every earlier removal',()=>{const h=harness([record(1),record(2),record(3)]);h.c.addDisplayed();h.s.displayed=[record(1),record(2,'矛盾')];assert.equal(h.c.refresh().canRemoveDisplayed,false);assert.match(h.c.refresh().displayedRemoveProblem,/整批未移出/);assert.equal(h.c.removeDisplayed(),false);assert.deepEqual(h.c.request(),{ids:[id(1),id(2),id(3)]});});
test('conflicting repeated unselected IDs also invalidate the whole page before removal',()=>{const h=harness([record(1)]);h.c.addDisplayed();h.s.displayed=[record(1),record(2),record(2,'矛盾')];assert.equal(h.c.removeDisplayed(),false);assert.deepEqual(h.c.request(),{ids:[id(1)]});});
test('invalid displayed getters and sparse metadata refuse removal without executing caller code',()=>{let touched=0;for(const kind of ['getter','sparse','extra']){const h=harness();h.c.addDisplayed();if(kind==='getter')Object.defineProperty(h.s.displayed,'1',{enumerable:true,get(){touched++;return record(2);}});if(kind==='sparse')delete h.s.displayed[1];if(kind==='extra')h.s.displayed.path='forbidden';assert.equal(h.c.removeDisplayed(),false);assert.equal(h.c.refresh().count,2);}assert.equal(touched,0);});
test('removal is still available at capacity when adding displayed new IDs would overflow',()=>{const h=harness(Array.from({length:1000},(_,i)=>record(i+1)));h.c.addDisplayed();h.s.displayed=[record(1),record(1001)];const v=h.c.refresh();assert.equal(v.canAddDisplayed,false);assert.equal(v.canRemoveDisplayed,true);assert.equal(v.removableDisplayedCount,1);assert.equal(v.displayedRemoveProblem,null);assert.equal(h.c.removeDisplayed(),true);assert.equal(h.c.request().ids.length,999);assert.equal(h.c.request().ids.includes(id(1)),false);});
test('all 1000 selected displayed IDs can be removed without a whole-library request fallback',()=>{const h=harness(Array.from({length:1000},(_,i)=>record(i+1)));h.c.addDisplayed();assert.equal(h.c.removeDisplayed(),true);assert.equal(h.c.request(),null);assert.equal(h.c.refresh().canDownload,false);assert.equal(h.c.refresh().canRemoveDisplayed,false);});
test('busy disabled and disposed removal actions preserve choices and refuse late callbacks',()=>{const h=harness();h.c.addDisplayed();for(const flags of [{busy:true},{enabled:false}]){const before=h.s;h.s={...before,...flags};assert.equal(h.c.removeDisplayed(),false);assert.equal(h.c.refresh().count,2);assert.equal(h.c.refresh().canRemoveDisplayed,false);h.s=before;}h.c.dispose();h.s=null;assert.equal(h.c.removeDisplayed(),false);});
test('previously captured download IDs remain unchanged after later bulk removal',()=>{const h=harness();h.c.addDisplayed();const request=h.c.request();h.s.displayed=[record(1)];h.c.removeDisplayed();assert.deepEqual(request,{ids:[id(1),id(2)]});assert.deepEqual(h.c.request(),{ids:[id(2)]});});
function dom(){const document={activeElement:null,body:{append(){}},getElementById:k=>nodes[k],createElement:()=>element()};function element(){return {textContent:'',disabled:false,children:[],files:[],dataset:{},attrs:{},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},setAttribute(k,v){this.attrs[k]=v;},focus(){document.activeElement=this;},click(){},remove(){}};}const nodes=Object.fromEntries(['backup-selection-add','backup-selection-add-displayed','backup-selection-remove-displayed','backup-selection-remove-note','backup-selection-displayed-note','backup-selection-clear','backup-selection-list','backup-selection-note','backup-download','backup-download-cancel','backup-save-selected','backup-save-batch','backup-verify-file','backup-verify-source','backup-verify-note','backup-verify-cancel'].map(k=>[k,element()]));let s={enabled:true,busy:false,selected:record(1),displayed:[record(1),record(2)]},notify=()=>{};const handlers=new Map(),events={addEventListener:(n,f)=>{if(!handlers.has(n))handlers.set(n,new Set());handlers.get(n).add(f);},removeEventListener:(n,f)=>handlers.get(n)?.delete(f)};const adapter=D.bind(document,{capture:()=>s,events,onChange:()=>notify()});return {document,nodes,adapter,events,handlers,get s(){return s;},set s(v){s=v;},set notify(f){notify=f;}};}
test('DOM shows removable intersection separately from all displayed records and uses literal scope',()=>{const h=dom();h.nodes['backup-selection-add'].onclick();assert.match(h.nodes['backup-selection-remove-displayed'].textContent,/1 版/);assert.match(h.nodes['backup-selection-remove-note'].textContent,/已載入的 2 版中，1 版/);assert.match(h.nodes['backup-selection-remove-note'].textContent,/保存原檔保留/);h.adapter.dispose();});
test('keyboard removal sends focus to a usable re-add control and updates download availability immediately',()=>{const h=dom();let changes=0;h.notify=()=>{changes++;h.nodes['backup-save-batch'].disabled=h.adapter.request()===null;};h.nodes['backup-selection-add-displayed'].onclick();const remove=h.nodes['backup-selection-remove-displayed'];remove.focus();assert.equal(remove.onclick(),true);assert.equal(remove.disabled,true);assert.equal(h.nodes['backup-save-batch'].disabled,true);assert.equal(h.document.activeElement,h.nodes['backup-selection-add-displayed']);assert.equal(h.nodes['backup-selection-add-displayed'].disabled,false);assert.equal(changes,2);h.adapter.dispose();});
test('search with no removals keeps original DOM nodes and focused controls without reporting a change',()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();const item=h.nodes['backup-selection-list'].children[0];item.children[1].focus();h.s.displayed=[record(3)];h.adapter.refresh();assert.equal(h.nodes['backup-selection-remove-displayed'].disabled,true);assert.equal(h.nodes['backup-selection-remove-displayed'].onclick(),false);assert.equal(h.nodes['backup-selection-list'].children[0],item);assert.equal(h.document.activeElement,item.children[1]);h.adapter.dispose();});
test('pagehide removes the new handler and metadata without editing caller source',()=>{const h=dom(),before=structuredClone(h.s);h.nodes['backup-selection-add-displayed'].onclick();for(const f of [...h.handlers.get('pagehide')])f();assert.equal(h.nodes['backup-selection-remove-displayed'].onclick,null);assert.equal(h.nodes['backup-selection-remove-displayed'].disabled,true);assert.deepEqual(h.s,before);assert.equal(h.adapter.request(),null);});
const later=()=>{let resolve;const promise=new Promise(r=>{resolve=r;});return {promise,resolve};};
test('the existing downloader freezes residual IDs and rejects bulk removal while sending',async()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();h.s.displayed=[record(1)];h.nodes['backup-selection-remove-displayed'].onclick();const pending=later(),requests=[],timers=[],raw=new TextEncoder().encode('synthetic zip').buffer,hash=async b=>crypto.createHash('sha256').update(new Uint8Array(b)).digest('hex');const download=Download.createAdapter(h.document,{events:h.events,allowed:()=>h.s.enabled,verificationAllowed:()=>h.s.enabled&&!h.s.busy,maximum:()=>32*1024*1024,captureBatch:h.adapter.request,prepare:async(signal,p)=>{requests.push(p);await pending.promise;return {backup_schema_version:1,backup_sha256:await hash(raw),bytes:raw.byteLength,entry_count:p.ids.length,selection:'selected',download_url:'/api/drafts/backup/download/'+'1'.repeat(32)};},fetch:async()=>new Response(raw,{headers:{'Content-Length':String(raw.byteLength),'Content-Type':'application/octet-stream'}}),hash,onState:({busy})=>{h.s.busy=busy;h.adapter.refresh();},say(){},byteOptions:{url:{createObjectURL:()=>String(timers.length),revokeObjectURL(){}},BlobType:Blob,schedule:f=>{timers.push(f);return timers.length;},cancel(){}}});h.notify=()=>download.refresh();const work=h.nodes['backup-save-batch'].onclick();await Promise.resolve();assert.equal(h.nodes['backup-selection-remove-displayed'].onclick(),false);h.s.displayed=[record(2)];pending.resolve();assert.equal(await work,true);assert.deepEqual(requests,[{ids:[id(2)]}]);for(const f of timers)f();download.dispose();h.adapter.dispose();});
