// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const Focus=require('../web/verification-focus.js'),Text=require('../web/text-verification-dom.js'),Backup=require('../web/backup-verification-dom.js');
const bytes=s=>new TextEncoder().encode(s),original='合成原文\r\n🎵\n',flush=()=>new Promise(setImmediate);
function pure(options={}){const view={available:true,pending:false,waiting:false,contextRevision:1},calls=[];let active='picker';const c=Focus.createController({capture:()=>view,noteFocused:()=>active==='note',focusPicker:()=>{calls.push('picker');active='picker';return true;},focusNote:()=>{calls.push('note');active='note';return options.focusSucceeds!==false;}});return {view,c,calls,get active(){return active;},set active(v){active=v;}};}
function dom({prefix='text',backup=false,legacy=false,onReport=()=>{}}={}){
 const raw=bytes(original),sha=crypto.createHash('sha256').update(raw).digest('hex');
 const state=backup?{revision:1,busy:false,proof:{bytes:raw.length,sha256:sha,entry_count:1}}:{scope:prefix==='draft'?'draft':prefix==='audio-accept'?'audio':'music',revision:1,busy:false,dirty:false,visible:true,source:{name:prefix+'-original.txt',content:original}};
 const handlers=new Map(),reports=[],errors=[],focuses=[],document={activeElement:null,getElementById:id=>nodes[id]},nodes={};
 function make(id){const events=new Map(),attrs=new Map();return {id,files:[],value:'',disabled:false,textContent:'',dataset:{},events,attrs,focus(){if(this.disabled)return;const old=document.activeElement;document.activeElement=this;focuses.push(id);if(old!==this)old?.events.get('blur')?.();},hasAttribute:k=>attrs.has(k),setAttribute:(k,v)=>attrs.set(k,v),addEventListener:(n,f)=>events.set(n,f),removeEventListener:(n,f)=>{assert.equal(events.get(n),f);events.delete(n);}};}
 for(const suffix of ['file','note','source','cancel'])nodes[prefix+'-verify-'+suffix]=make(prefix+'-verify-'+suffix);nodes.other=make('other');document.activeElement=nodes.other;
 const file=nodes[prefix+'-verify-file'],note=nodes[prefix+'-verify-note'],cancel=nodes[prefix+'-verify-cancel'];
 class File{constructor(text=original){this.name=backup?'synthetic.zip':'synthetic.txt';this.data=bytes(text);this.size=this.data.length;this.started=0;this.resolve=null;this.reject=null;}arrayBuffer(){this.started++;return new Promise((resolve,reject)=>{this.resolve=()=>resolve(this.data.buffer);this.reject=()=>reject(Error('injected read failure'));});}}
 const events={addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:(n,f)=>{assert.equal(handlers.get(n),f);handlers.delete(n);}};
 let failHash=false;
 const adapter=backup?Backup.bind(document,{capture:()=>state,FileType:File,events,hash:async b=>{if(failHash)throw Error('injected hash failure');return crypto.createHash('sha256').update(new Uint8Array(b)).digest('hex');},onError:e=>errors.push(e.message)}):Text.bind(document,{capture:()=>state,FileType:File,events,ids:{file:file.id,note:note.id,source:nodes[prefix+'-verify-source'].id,...(!legacy?{cancel:cancel.id}:{})},onReport:(r,m)=>{reports.push({r,m});onReport({nodes,state,r,m});},onError:e=>errors.push(e.message)});
 const choose=(text=original)=>{const f=new File(text);file.files=[f];file.focus();file.onchange();return f;};
 const cancelWork=()=>{cancel.focus();cancel.onclick();};
 return {adapter,state,document,nodes,file,note,cancel,events:handlers,reports,errors,focuses,choose,cancelWork,get failHash(){return failHash;},set failHash(v){failHash=v;}};
}
test('selection focuses the status before disabling its picker and later refresh adds no focus invitation',()=>{const h=pure(),before={...h.view};h.c.selected();assert.equal(h.active,'note');assert.deepEqual(h.view,before);h.view.pending=true;h.c.refresh(h.view);h.view.pending=false;h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);});
test('selection refuses pending unavailable unknown or invalid source metadata and capture failures',()=>{for(const patch of [{pending:true},{available:false},{available:1},{pending:null},{waiting:'true'},{contextRevision:0},{contextRevision:1.5},{contextRevision:NaN}]){const h=pure();Object.assign(h.view,patch);h.c.selected();assert.deepEqual(h.calls,[]);}const c=Focus.createController({capture:()=>{throw Error('source');},noteFocused:()=>true,focusPicker:()=>assert.fail(),focusNote:()=>assert.fail()});c.selected();});
test('selection clears an older capped cancellation invitation even if a new file cannot start',()=>{const h=pure();h.view.available=false;h.view.waiting=true;h.c.cancelled();assert.deepEqual(h.calls,['note']);h.c.selected();h.view.available=true;h.view.waiting=false;h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);});
test('failed selected note focus never falls back to picker or promises a later focus',()=>{const h=pure({focusSucceeds:false});h.c.selected();h.active='other';h.c.refresh({...h.view,pending:true});h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);assert.equal(h.active,'other');});
test('disposed focus policy rejects selection and future completion without injected side effects',()=>{const h=pure();h.c.dispose();h.c.selected();h.c.refresh(h.view);assert.deepEqual(h.calls,[]);});
for(const prefix of ['text','draft','audio-accept'])test(prefix+' selection retains note focus through a matching result and leaves original source and callback metadata unchanged',async()=>{const h=dom({prefix}),before=structuredClone(h.state),f=h.choose();assert.equal(h.document.activeElement,h.note);assert.equal(h.file.disabled,true);assert.equal(f.started,1);f.resolve();await flush();assert.equal(h.note.dataset.match,'true');assert.equal(h.document.activeElement,h.note);assert.deepEqual(h.state,before);assert.equal(h.reports.length,1);assert.equal(h.reports[0].m.name,'synthetic.txt');assert.equal(h.reports[0].r.expected_name,prefix+'-original.txt');h.adapter.dispose();});
test('same-sized text difference remains readable at the note without accepting a matching proof',async()=>{const h=dom(),before=structuredClone(h.state),f=h.choose('合成原文\r\n🎶\n');f.resolve();await flush();assert.equal(h.note.dataset.match,'false');assert.match(h.note.textContent,/第一個差異/);assert.equal(h.document.activeElement,h.note);assert.equal(h.reports[0].r.matched,false);assert.deepEqual(h.state,before);h.adapter.dispose();});
test('read errors stay at the selected note and an explicit matching retry works without lost source',async()=>{const h=dom(),before=structuredClone(h.state),f=h.choose();f.reject();await flush();assert.match(h.note.textContent,/injected read failure/);assert.equal(h.document.activeElement,h.note);assert.equal(h.note.dataset.match,'unknown');const retry=h.choose();retry.resolve();await flush();assert.equal(h.note.dataset.match,'true');assert.equal(h.errors.length,1);assert.equal(h.reports.length,1);assert.deepEqual(h.state,before);h.adapter.dispose();});
test('empty chooser changes leave focus and source alone and do not start verification',()=>{const h=dom(),before=structuredClone(h.state);h.file.files=[];h.file.onchange();assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.focuses.length,0);assert.deepEqual(h.state,before);assert.equal(h.reports.length,0);h.adapter.dispose();});
test('a later edit and return to the note survive matching mismatch and error completion without any late focus call',async()=>{for(const outcome of ['match','mismatch','error']){const h=dom(),f=h.choose(outcome==='mismatch'?'合成原文\r\n🎶\n':original);h.nodes.other.focus();h.nodes.other.value='後續編修';const count=h.focuses.length;if(outcome==='error')f.reject();else f.resolve();await flush();assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.nodes.other.value,'後續編修');assert.equal(h.focuses.length,count);h.note.focus();h.adapter.refresh();assert.equal(h.document.activeElement,h.note);h.adapter.dispose();}});
test('source identity changes suppress late reports and never create focus resumption',async()=>{for(const change of [s=>s.revision++,s=>s.scope='lyrics',s=>s.source.content+='新來源']){const h=dom(),f=h.choose();change(h.state);h.adapter.refresh();h.nodes.other.focus();const count=h.focuses.length;f.resolve();await flush();assert.equal(h.reports.length,0);assert.equal(h.note.dataset.match,'unknown');assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.focuses.length,count);h.adapter.dispose();}});
test('a report callback may focus a subsequent workflow without finally stealing that focus back',async()=>{const h=dom({prefix:'draft',onReport:({nodes})=>{nodes.other.value='callback後續';nodes.other.focus();}}),f=h.choose();f.resolve();await flush();assert.equal(h.reports.length,1);assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.nodes.other.value,'callback後續');h.adapter.dispose();});
test('legacy optional cancel adapters preserve existing ordinary completion and do not add note focus handlers',async()=>{const h=dom({legacy:true}),f=h.choose();assert.equal(h.document.activeElement,h.file);f.resolve();await flush();assert.equal(h.reports.length,1);assert.equal(h.document.activeElement,h.file);assert.equal(h.note.events.size,0);h.adapter.dispose();});
test('pagehide disposal and cancelled earlier reads retain only the latest explicit selection without late focus or report replacement',async()=>{for(const leave of ['pagehide','dispose','cancel']){const h=dom(),first=h.choose();if(leave==='pagehide')h.events.get('pagehide')();else if(leave==='dispose')h.adapter.dispose();else h.cancelWork();h.nodes.other.focus();const count=h.focuses.length;first.resolve();await flush();assert.equal(h.reports.length,0);assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.focuses.length,count);if(leave!=='dispose')h.adapter.dispose();}});
test('backup matching and same-sized SHA difference retain readable note focus and original proof',async()=>{for(const text of [original,'合成原文\r\n🎶\n']){const h=dom({prefix:'backup',backup:true}),before=structuredClone(h.state),f=h.choose(text);assert.equal(h.document.activeElement,h.note);f.resolve();await flush();assert.equal(h.note.dataset.match,String(text===original));assert.equal(h.document.activeElement,h.note);assert.deepEqual(h.state,before);assert.equal(h.errors.length,0);h.adapter.dispose();}});
test('backup read and hash errors permit retry while preserving later edit focus and original source',async()=>{for(const failure of ['read','hash']){const h=dom({prefix:'backup',backup:true}),before=structuredClone(h.state),f=h.choose();h.nodes.other.focus();h.nodes.other.value='後續備份編修';h.failHash=failure==='hash';if(failure==='read')f.reject();else f.resolve();await flush();assert.equal(h.errors.length,1);assert.equal(h.note.dataset.match,'unknown');assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.nodes.other.value,'後續備份編修');h.failHash=false;const retry=h.choose();retry.resolve();await flush();assert.equal(h.note.dataset.match,'true');assert.equal(h.document.activeElement,h.note);assert.deepEqual(h.state,before);h.adapter.dispose();}});
test('cancel from the selected note still returns to the picker or capped note and old work cannot steal a newer edit',async()=>{const h=dom(),first=h.choose();h.cancelWork();assert.equal(h.document.activeElement,h.file);const second=h.choose();h.cancelWork();assert.equal(h.document.activeElement,h.note);h.nodes.other.focus();h.nodes.other.value='繼續編修';const count=h.focuses.length;first.resolve();second.resolve();await flush();assert.equal(h.reports.length,0);assert.equal(h.document.activeElement,h.nodes.other);assert.equal(h.nodes.other.value,'繼續編修');assert.equal(h.focuses.length,count);h.adapter.dispose();});
