// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const adapters={shot:require('../web/storyboard-shot-review-dom.js'),section:require('../web/music-section-review-dom.js'),cue:require('../web/lyrics-cue-review-dom.js')};
function setup(kind){
 const nodes={};const element=()=>({children:[],value:'original',disabled:false,hidden:false,textContent:'',classList:{toggle(){}},append(...v){this.children.push(...v);},replaceChildren(){this.children=[];}});const document={getElementById:id=>nodes[id]||(nodes[id]=element()),createElement:element};
 const issues=[{row:40,field:kind==='cue'?'start':'visual',message:' <literal> 原文🎵 ',related_row:2},{row:40,field:'end',message:'第二項',related_row:null}];
 const report=kind==='section'?{row:40,totalSections:40,issueCount:2,issues:issues.map(({related_row,...i})=>i)}:{row:40,[kind==='shot'?'total_shots':'total_rows']:40,issue_count:2,issues};
 const state={view:{report,stale:false,revision:4},busy:false,visible:true,focus:true,calls:[],reveals:[],errors:[]};
 const get=id=>document.getElementById(id),selection={shot:'shots-order',section:'section-order',cue:'cues-order'}[kind];
 state.dom=adapters[kind].bind(document,{labels:{visual:'畫面',end:'結束'},busy:()=>state.busy,visible:()=>state.visible,onCheck:()=>{state.view={...state.view,revision:state.view.revision+1};state.dom.render(state.view);return true;},onLocate:(index,revision)=>{state.calls.push({index,revision});if(state.throwFocus)throw Error('focus failure');return state.focus;},onReveal:issue=>{state.reveals.push({issue:structuredClone(issue),note:get(kind+'-issue-note').textContent});if(state.throwReveal)throw Error('reveal failure');return true;},onError:e=>state.errors.push(e.message)});
 state.get=get;state.selection=selection;state.render=()=>state.dom.render(state.view);state.next=()=>get(kind+'-issue-next').onclick();state.previous=()=>get(kind+'-issue-previous').onclick();state.note=()=>get(kind+'-issue-note').textContent;state.button=i=>get(kind==='cue'?'cue-review-issues':kind+'-review-issues').children[i].children[0];state.render();return state;
}
for(const kind of Object.keys(adapters)){
 test(kind+' summary matches the same literal list item only after successful original-field location',()=>{const s=setup(kind),before=structuredClone(s.view);assert.ok(!s.note().includes('目前定位'));const first=s.button(0).textContent;assert.equal(s.next(),true);assert.ok(s.note().endsWith('目前定位：'+first));assert.equal(s.reveals.at(-1).note,s.note());assert.deepEqual(s.view,before);});
 test(kind+' failed and throwing focus keep the previous successful caption without publishing attempted detail',()=>{const s=setup(kind);s.next();const before=s.note();s.focus=false;assert.equal(s.next(),false);assert.equal(s.note(),before);s.focus=true;s.throwFocus=true;assert.equal(s.next(),false);assert.equal(s.note(),before);assert.deepEqual(s.errors,['focus failure']);s.throwFocus=false;assert.equal(s.next(),true);assert.match(s.note(),/第二項/);});
 test(kind+' stale busy hidden and missing selection remove current explanation while preserving the report',()=>{for(const edit of [s=>s.view.stale=true,s=>s.busy=true,s=>s.visible=false,s=>s.get(s.selection).value='']){const s=setup(kind);s.next();const before=structuredClone(s.view.report);edit(s);s.render();assert.ok(!s.note().includes('目前定位'));assert.equal(s.next(),false);assert.deepEqual(s.view.report,before);}});
 test(kind+' cloned refresh retains caption and exact availability restoration can resume without moving cursor',()=>{const s=setup(kind);s.next();const before=s.note();s.view=structuredClone(s.view);s.render();assert.equal(s.note(),before);s.view.stale=true;s.render();assert.ok(!s.note().includes('目前定位'));s.view.stale=false;s.render();assert.equal(s.note(),before);assert.equal(s.previous(),false);});
 test(kind+' new revision and zero report clear caption and reject an old list callback',()=>{const s=setup(kind);s.next();const old=s.button(1),calls=s.calls.length;s.get(kind+'-issue-check').onclick();assert.ok(!s.note().includes('目前定位'));assert.equal(old.onclick(),false);assert.equal(s.calls.length,calls);s.view={...s.view,revision:6,report:{...s.view.report,issues:[],issueCount:0,issue_count:0}};s.render();assert.ok(!s.note().includes('目前定位'));assert.equal(s.next(),false);});
 test(kind+' post-caption layout error is reported without changing text report or successful focus index',()=>{const s=setup(kind);s.throwReveal=true;assert.equal(s.next(),true);assert.match(s.note(),/1／2/);assert.ok(s.note().includes('目前定位'));assert.deepEqual(s.errors,['reveal failure']);s.throwReveal=false;assert.equal(s.next(),true);assert.match(s.note(),/2／2/);});
}
