// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const R=require('../web/music-readiness.js'),V=require('../web/planning-values.js'),C=require('../web/readiness-state.js'),Editor=require('../web/editor-state.js'),P=require('../web/planning-import.js');
function draft(){const panels={};for(const [name,fields] of Object.entries(Editor.draftFields)){panels[name]={fields:Object.fromEntries(fields.map(k=>[k,'']))};if(Editor.draftRows[name])panels[name][Editor.draftRows[name].key]=[];}
  panels.music.avoid=[];panels.music.deliverables=[];panels.storyboard.motifs=[];panels.lyrics.fields['lyrics-format']='.lrc';panels.audio.fields['audio-profile']='video';
  return P.planningDraft({format:'zoe-music-lab-draft',schema_version:3,tool_version:'test',saved_at:'',tab:'music',panels},'music',JSON.parse(fs.readFileSync('examples/first-light-music.json','utf8')));
}
function setup(){const d=draft(),ids=d.panels.music.sections.map((s,i)=>'row-'+i),states=[];const c=R.createController({capture:()=>d.panels.music,captureIds:()=>ids,onState:s=>states.push(s)});return {d,ids,states,c};}
test('song fields inspect without changing original raw text or optional lyrics',()=>{const p=draft().panels.music;p.fields['music-lyrics']='';const before=structuredClone(p),r=R.inspect(p);assert.equal(r.issueCount,0);assert.equal(r.filledSections,6);assert.deepEqual(p,before);r.issues.push({bad:true});assert.equal(R.inspect(p).issueCount,0);});
test('all required globals and every section column locate the original position',()=>{
  for(const field of Editor.draftFields.music.filter(k=>k!=='music-lyrics')){const p=draft().panels.music;p.fields[field]='\u0085 ';assert.ok(R.inspect(p).issues.some(i=>i.scope==='fields'&&i.row===0&&i.field===field));}
  for(let row=0;row<6;row++)for(const field of Editor.draftRows.music.columns){const p=draft().panels.music;p.sections[row][field]='';const r=R.inspect(p);assert.equal(r.filledSections,5);assert.ok(r.issues.some(i=>i.row===row+1&&i.field===field));}
});
test('field ranges reject original bad integer and decimal values while fractional BPM and energy stay valid',()=>{
  for(const [scope,field,value] of [['fields','music-bpm','19'],['fields','music-bpm','301'],['fields','music-beats','0'],['fields','music-beats','13'],['fields','music-beats','2.5'],['sections','bars','0'],['sections','bars','129'],['sections','bars','1.5'],['sections','energy','0.9'],['sections','energy','5.1']]){const p=draft().panels.music;(scope==='fields'?p.fields:p.sections[2])[field]=value;const before=structuredClone(p);assert.ok(R.inspect(p).issues.some(i=>i.field===field&&i.code==='invalid_range'));assert.deepEqual(p,before);}
  const p=draft().panels.music;p.fields['music-bpm']='120.0004';p.sections[1].energy='3.0004';assert.equal(R.inspect(p).issueCount,0);assert.equal(p.fields['music-bpm'],'120.0004');
});
test('nonfinite and nondecimal forms are diagnosed without interpreting them as zero',()=>{for(const value of ['NaN','Infinity','0x78','0b1111000','_120','120_','1__20','\u001c120','\ufeff120']){const p=draft().panels.music;p.fields['music-bpm']=value;assert.ok(R.inspect(p).issues.some(i=>i.field==='music-bpm'&&i.code==='invalid_number'));}});
test('Python text whitespace and number whitespace differ, and Unicode decimals and underscores remain compatible',()=>{
  assert.equal(V.trim('\u001c\u0085 x \u0085\u001f'),'x');assert.equal(V.trim('\ufeff'),'\ufeff');assert.equal(V.number('\u0085 １２０.０００４ \u0085'),120.0004);assert.equal(V.number('1_2_0'),120);assert.throws(()=>V.number('\u001c120'));
  const p=draft().panels.music;p.avoid=['\ufeff'];p.deliverables=['\ufeff'];assert.equal(R.inspect(p).issueCount,0);assert.equal(P.requirementIssue(p),null);p.avoid=['\u0085'];assert.equal(R.inspect(p).issues[0].scope,'avoid');assert.equal(P.requirementIssue(p).key,'avoid');
});
test('empty avoid is optional while deliverable and section collections have actionable locations',()=>{const p=draft().panels.music;p.avoid=[];p.deliverables=[];p.sections=[];assert.deepEqual(R.inspect(p).issues.map(i=>[i.field,i.code]),[['sections','no_sections'],['deliverables','no_deliverables']]);});
test('all forty rows and both hundred-item lists count even when detail cap is reached',()=>{const p=draft().panels.music;p.sections=Array.from({length:40},()=>Object.fromEntries(Editor.draftRows.music.columns.map(k=>[k,''])));p.avoid=Array(100).fill('');p.deliverables=Array(100).fill('');const r=R.inspect(p);assert.equal(r.issueCount,400);assert.equal(r.issues.length,200);assert.equal(r.filledSections,0);assert.equal(r.truncated,true);});
test('strict shapes Unicode and eight MiB caps reject misleading source',()=>{for(const edit of [p=>p.extra=true,p=>p.sections[0].extra='',p=>p.fields['music-bpm']=120,p=>p.sections=Array(41).fill(p.sections[0]),p=>p.avoid=Array(101).fill('x'),p=>p.deliverables=[null],p=>p.fields['music-title']='\ud800',p=>p.fields['music-title']='漢'.repeat(3*1024*1024)]){const p=draft().panels.music;edit(p);assert.throws(()=>R.inspect(p));}});
test('same-text rows changing stable order make old original-position locations stale',()=>{const {d,ids,c}=setup();d.panels.music.sections[1]=structuredClone(d.panels.music.sections[0]);d.panels.music.sections[0].focus='';d.panels.music.sections[1].focus='';c.check();[ids[0],ids[1]]=[ids[1],ids[0]];assert.equal(c.locate(0),null);assert.equal(c.refresh().stale,true);});
test('silent edits deletion ordering and optional lyrics are rechecked before locating; unrelated panels and media stay independent',()=>{
  for(const edit of [s=>s.d.panels.music.fields['music-bpm']='99',s=>s.d.panels.music.sections.reverse(),s=>s.d.panels.music.sections.pop(),s=>s.ids.reverse(),s=>s.d.panels.music.fields['music-lyrics']='later']){const s=setup();s.d.panels.music.sections[2].focus='';s.c.check();edit(s);const before=structuredClone(s.d);assert.equal(s.c.locate(0),null);assert.deepEqual(s.d,before);}
  const s=setup();s.d.panels.music.sections[2].focus='';s.c.check();s.d.panels.storyboard.fields['mv-title']='later board';const media={native:true};assert.equal(s.c.refresh().stale,false);assert.equal(s.c.locate(0).row,3);assert.equal(media.native,true);
});
test('canonical object order source recovery and clear keep reports isolated',()=>{const s=setup();s.d.panels.music.sections[2].focus='';const v=s.c.check(),p=structuredClone(s.d.panels.music);v.report.issues[0].row=99;s.d.panels.music.fields=Object.fromEntries(Object.entries(p.fields).reverse());assert.equal(s.c.locate(0).row,3);s.d.panels.music.sections[2].focus='later';assert.equal(s.c.refresh().stale,true);s.d.panels.music=p;assert.equal(s.c.refresh().stale,false);s.c.clear();assert.equal(s.c.locate(0),null);});
test('shared checkpoint captures once and isolates even an inspector that changes its working copy',()=>{const value={x:'original'},states=[];let reads=0;const c=C.createController({capture:()=>{reads++;return value;},source:v=>({x:v.x}),inspect:v=>{v.x='changed';return {issues:[{field:'x'}]};},onState:v=>states.push(v)});c.check();assert.equal(reads,1);assert.equal(value.x,'original');assert.equal(c.refresh().stale,false);states[0].report.issues[0].field='bad';assert.equal(c.locate(0).field,'x');});
test('actual music submit refuses missing fields before conversion or HTTP and still enters the complete service when ready',()=>{const source=fs.readFileSync('web/app.js','utf8'),a=source.indexOf("$('music-form').onsubmit="),b=source.indexOf('function stalePlanningReview',a),form={},calls=[];let ready=false;const ctx={$:()=>form,state:{busy:false},clearRequirementError:()=>{},checkMusicReady:()=>ready,say:()=>{},run:(_button,fn)=>calls.push(fn),MusicPlanReview:{inspect:o=>o.request(o.operation,o.brief)},MusicPlanning:P,captureDraft:draft,api:(route,brief)=>{calls.push(route);return brief;},applyPlanningResult:()=>{}};vm.createContext(ctx);vm.runInContext(source.slice(a,b),ctx);const event={preventDefault:()=>{},submitter:{}};form.onsubmit(event);assert.equal(calls.length,0);ready=true;form.onsubmit(event);const result=calls[0](()=>true);assert.equal(calls[1],'/api/music');assert.equal(result.arrangement.length,6);});
test('actual local song seed preview uses readiness before the existing seed service',async()=>{const source=fs.readFileSync('web/app.js','utf8'),a=source.indexOf("$('seed-preview').onclick="),b=source.indexOf("$('seed-file').onchange",a),button={};let ready=false,called=0;const ctx={$:()=>button,run:(_b,fn)=>fn(()=>true),checkMusicReady:()=>ready,seedController:{inspect:()=>{called++;return true;}},say:()=>{}};vm.createContext(ctx);vm.runInContext(source.slice(a,b),ctx);await button.onclick();assert.equal(called,0);ready=true;await button.onclick();assert.equal(called,1);});
test('field-zero does not mean the complete derived total-duration domain accepts a song',()=>{const p=draft().panels.music;p.fields['music-bpm']='20';p.fields['music-beats']='12';p.sections=Array.from({length:40},()=>({...p.sections[0],bars:'128'}));assert.equal(R.inspect(p).issueCount,0);});
