// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const fs=require('node:fs'),vm=require('node:vm');
const M=require('../web/backup-selection.js'),D=require('../web/backup-selection-dom.js'),Download=require('../web/backup-download-dom.js');
const id=n=>'draft-'+n.toString(16).padStart(32,'0');
const record=(n,label='版本 '+n+' 🎵')=>({library_schema_version:1,id:id(n),label,stored_at:'2026-10-06T10:00:00+00:00',sha256:'a'.repeat(64),bytes:200,draft_schema_version:3,created_with:'0.127.0',titles:{music:'合成歌曲',storyboard:'',lyrics:''}});
function harness(){let s={enabled:true,busy:false,selected:record(1)},last;const errors=[];const c=M.createController({capture:()=>s,onState:v=>{last=v;},onError:e=>errors.push(e.message)});return {c,errors,get s(){return s;},set s(v){s=v;},get view(){return last;}};}
test('batch metadata source requires exact data flags and checked saved metadata without field getters',()=>{assert.deepEqual(M.checked({enabled:true,busy:false,selected:null}),{enabled:true,busy:false,selected:null});let touched=0;for(const s of [null,[],{}, {enabled:1,busy:false,selected:null},{enabled:true,busy:false,selected:null,path:'x'},Object.defineProperty({enabled:true,busy:false},'selected',{enumerable:true,get(){touched++;return record(1);}}),{enabled:true,busy:false,selected:{id:id(1)}}])assert.throws(()=>M.checked(s));assert.equal(touched,0);});
test('batch selection accumulates across searching and empty displayed lists without loading drafts',()=>{const h=harness();assert.equal(h.c.add(),true);h.s.selected=record(2);assert.equal(h.c.add(),true);h.s.selected=null;const view=h.c.refresh();assert.equal(view.canAdd,false);assert.equal(view.canDownload,true);assert.deepEqual(h.c.request(),{ids:[id(1),id(2)]});assert.equal(view.count,2);assert.deepEqual(Object.keys(view.entries[0]),['id','label','stored_at']);});
test('duplicates never multiply and conflicting immutable metadata does not replace the retained name',()=>{const h=harness();h.c.add();assert.equal(h.c.add(),false);h.s.selected=record(1,'改名');assert.equal(h.c.add(),false);assert.equal(h.errors.length,1);assert.equal(h.c.refresh().entries[0].label,'版本 1 🎵');});
test('added metadata view and click-time requests are isolated from caller mutation',()=>{const h=harness();h.c.add();const p=h.c.request(),v=h.c.refresh();p.ids.push(id(2));v.entries[0].label='caller';h.s.selected.label='later';assert.equal(h.c.refresh().entries[0].label,'版本 1 🎵');assert.deepEqual(h.c.request(),{ids:[id(1)]});});
test('busy disabled and invalid source preserve prior selection and refuse actions or downloads',()=>{const h=harness();h.c.add();for(const change of [{busy:true},{enabled:false}]){const original=h.s;h.s={...original,...change};assert.equal(h.c.add(),false);assert.equal(h.c.remove(id(1)),false);assert.equal(h.c.clear(),false);assert.equal(h.c.request(),null);assert.equal(h.c.refresh().count,1);h.s=original;}h.s.extra=true;assert.equal(h.c.add(),false);assert.throws(()=>h.c.request());assert.equal(h.c.refresh().canDownload,false);});
test('removal and clearing change only the temporary selection, including a missing displayed choice',()=>{const h=harness(),original=structuredClone(h.s);h.c.add();assert.equal(h.c.remove('../x'),false);assert.equal(h.c.remove(id(2)),false);h.s.selected=null;assert.equal(h.c.remove(id(1)),true);assert.equal(h.c.request(),null);h.s=original;h.c.add();assert.equal(h.c.clear(),true);assert.equal(h.c.clear(),false);assert.deepEqual(h.s,original);});
test('batch allows exactly 1000 unique saved IDs and requests sorted complete copies',()=>{const h=harness();for(let n=1000;n>=1;n--){h.s.selected=record(n);assert.equal(h.c.add(),true);}h.s.selected=record(1001);assert.equal(h.c.add(),false);assert.equal(h.c.refresh().canAdd,false);const p=h.c.request();assert.equal(p.ids.length,1000);assert.deepEqual(p.ids,Array.from({length:1000},(_,n)=>id(n+1)));assert.equal(h.c.remove(id(500)),true);assert.equal(h.c.add(),true);});
test('disposal clears metadata and prevents later callbacks from capturing or exporting',()=>{const h=harness();h.c.add();h.c.dispose();assert.equal(h.view.count,0);h.s=null;assert.equal(h.c.add(),false);assert.equal(h.c.remove(id(1)),false);assert.equal(h.c.clear(),false);assert.equal(h.c.request(),null);});
function fakeDocument(){const document={activeElement:null,body:{append(){}},getElementById:k=>nodes[k],createElement:()=>element()};function element(){return {textContent:'',disabled:false,children:[],files:[],dataset:{},attrs:{},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},setAttribute(k,v){this.attrs[k]=v;},focus(){document.activeElement=this;},click(){},remove(){}};}const nodes=Object.fromEntries(['backup-selection-add','backup-selection-clear','backup-selection-list','backup-selection-note','backup-download','backup-download-cancel','backup-save-selected','backup-save-batch','backup-verify-file','backup-verify-source','backup-verify-note','backup-verify-cancel'].map(k=>[k,element()]));return {document,nodes};}
function dom(){const f=fakeDocument();let s={enabled:true,busy:false,selected:record(1,'<img onerror=bad> 同名 🎵')},notify=()=>{};const handlers=new Map(),events={addEventListener:(n,fn)=>{if(!handlers.has(n))handlers.set(n,new Set());handlers.get(n).add(fn);},removeEventListener:(n,fn)=>handlers.get(n)?.delete(fn)};const errors=[];const adapter=D.bind(f.document,{capture:()=>s,events,onChange:()=>notify(),onError:e=>errors.push(e.message)});return {...f,adapter,events,handlers,errors,get s(){return s;},set s(v){s=v;},set notify(f){notify=f;}};}
test('DOM lists literal names dates and IDs, keeps nodes and keyboard focus on unchanged refresh',()=>{const h=dom();h.nodes['backup-selection-add'].onclick();const item=h.nodes['backup-selection-list'].children[0],remove=item.children[1];assert.match(item.children[0].textContent,/<img onerror=bad>/);assert.match(remove.attrs['aria-label'],new RegExp(id(1)));remove.focus();h.adapter.refresh();assert.equal(h.nodes['backup-selection-list'].children[0],item);assert.equal(h.document.activeElement,remove);h.adapter.dispose();});
test('DOM removal preserves next usable focus and falls back to the list when search has no choice',()=>{const h=dom();h.nodes['backup-selection-add'].onclick();h.s.selected=record(2);h.nodes['backup-selection-add'].onclick();let first=h.nodes['backup-selection-list'].children[0].children[1];first.focus();first.onclick();assert.equal(h.document.activeElement,h.nodes['backup-selection-list'].children[0].children[1]);h.s.selected=null;h.adapter.refresh();const last=h.nodes['backup-selection-list'].children[0].children[1];last.focus();last.onclick();assert.equal(h.document.activeElement,h.nodes['backup-selection-list']);assert.equal(h.adapter.request(),null);h.adapter.dispose();});
test('DOM busy prevents edits and pagehide disposes only owned controls and metadata',()=>{const h=dom();h.nodes['backup-selection-add'].onclick();h.s.busy=true;h.adapter.refresh();assert.equal(h.nodes['backup-selection-clear'].disabled,true);assert.equal(h.nodes['backup-selection-list'].children[0].children[1].disabled,true);assert.equal(h.nodes['backup-selection-clear'].onclick(),undefined);assert.equal(h.adapter.request(),null);for(const f of [...h.handlers.get('pagehide')])f();assert.equal(h.adapter.request(),null);assert.equal(h.nodes['backup-selection-add'].onclick,null);assert.equal(h.handlers.get('pagehide').size,0);});
const later=()=>{let resolve;const promise=new Promise(r=>{resolve=r;});return {resolve,promise};};
function transfer(h){const raw=new TextEncoder().encode('synthetic zip').buffer,hash=async b=>crypto.createHash('sha256').update(new Uint8Array(b)).digest('hex'),pending=later(),requests=[],notes=[],timers=[];let delay=false;const adapter=Download.createAdapter(h.document,{events:h.events,allowed:()=>h.s.enabled,verificationAllowed:()=>h.s.enabled&&!h.s.busy,maximum:()=>32*1024*1024,captureSelected:()=>h.s.selected?.id||null,captureBatch:h.adapter.request,prepare:async(signal,p)=>{requests.push({signal,p});if(delay)await pending.promise;return {backup_schema_version:1,backup_sha256:await hash(raw),bytes:raw.byteLength,entry_count:p.ids?p.ids.length:3,selection:p.ids?'selected':'all',download_url:'/api/drafts/backup/download/'+'1'.repeat(32)};},fetch:async()=>new Response(raw,{headers:{'Content-Length':String(raw.byteLength),'Content-Type':'application/octet-stream'}}),hash,say:t=>notes.push(t),byteOptions:{url:{createObjectURL:()=>String(timers.length),revokeObjectURL(){}},BlobType:Blob,schedule:f=>{timers.push(f);return timers.length;},cancel(){}}});h.notify=()=>adapter.refresh();return {adapter,requests,notes,pending,set delay(v){delay=v;},flush(){for(const f of timers.splice(0))f();}};}
test('batch button freezes all selected IDs and summary count even if caller selection changes mid-transfer',async()=>{const h=dom();h.s.selected=record(2);h.nodes['backup-selection-add'].onclick();h.s.selected=record(1);h.nodes['backup-selection-add'].onclick();const t=transfer(h);t.delay=true;const work=h.nodes['backup-save-batch'].onclick();await Promise.resolve();assert.equal(h.nodes['backup-save-batch'].disabled,true);h.nodes['backup-selection-clear'].onclick();h.s.selected=record(3);t.pending.resolve();assert.equal(await work,true);assert.deepEqual(t.requests[0].p,{ids:[id(1),id(2)]});assert.match(t.notes.at(-1),/選取清單 2 版/);assert.match(h.nodes['backup-verify-source'].textContent,/2 版/);t.flush();t.adapter.dispose();h.adapter.dispose();});
test('cancelled batch preserves prior whole proof and never submits its late bytes',async()=>{const h=dom(),t=transfer(h);assert.equal(await h.nodes['backup-download'].onsubmit({preventDefault(){}}),true);t.flush();const proof=h.nodes['backup-verify-source'].textContent;h.nodes['backup-selection-add'].onclick();t.delay=true;const work=h.nodes['backup-save-batch'].onclick();await Promise.resolve();h.nodes['backup-download-cancel'].onclick();assert.equal(t.requests[1].signal.aborted,true);t.pending.resolve();assert.equal(await work,false);assert.equal(h.nodes['backup-verify-source'].textContent,proof);t.adapter.dispose();h.adapter.dispose();});
test('empty batch does not fall back to whole library and disposal disables its download handler',async()=>{const h=dom(),t=transfer(h);assert.equal(h.nodes['backup-save-batch'].disabled,true);assert.equal(h.nodes['backup-save-batch'].onclick(),false);assert.equal(t.requests.length,0);t.adapter.dispose();assert.equal(h.nodes['backup-save-batch'].disabled,true);assert.equal(h.nodes['backup-save-batch'].onclick,null);h.adapter.dispose();});
test('selection changes immediately refresh the existing download availability without editing saved data',()=>{const h=dom(),t=transfer(h);h.nodes['backup-selection-add'].onclick();assert.equal(h.nodes['backup-save-batch'].disabled,false);h.nodes['backup-selection-list'].children[0].children[1].onclick();assert.equal(h.nodes['backup-save-batch'].disabled,true);h.nodes['backup-selection-add'].onclick();assert.equal(h.nodes['backup-save-batch'].disabled,false);h.nodes['backup-selection-clear'].onclick();assert.equal(h.nodes['backup-save-batch'].disabled,true);assert.equal(t.requests.length,0);t.adapter.dispose();h.adapter.dispose();});
test('actual application run refreshes native batch controls at start and after failure without changing selection',async()=>{const h=dom();h.nodes['backup-selection-add'].onclick();const t=transfer(h);const state={busy:false,tab:'music',revisions:{music:0},backupSelection:{refresh:()=>{h.s.busy=state.busy;return h.adapter.refresh();}}};const c=vm.createContext({state,say(){},markDirty(){},timingControls(){},cueStampEdit:null,operationGate:{begin:()=>({}),current:()=>true,cancelled:()=>false,finish(){}},console});const source=fs.readFileSync('web/app.js','utf8');vm.runInContext(source.slice(source.indexOf('async function run('),source.indexOf('function cancelRun(')),c);const observed=[];await c.run({textContent:'build',disabled:false},async()=>{observed.push({clearDisabled:h.nodes['backup-selection-clear'].disabled,downloadDisabled:h.nodes['backup-save-batch'].disabled,request:h.adapter.request()});throw Error('controlled failure');});assert.deepEqual(observed,[{clearDisabled:true,downloadDisabled:true,request:null}]);assert.equal(h.nodes['backup-selection-clear'].disabled,false);assert.equal(h.nodes['backup-save-batch'].disabled,false);assert.deepEqual(h.adapter.request(),{ids:[id(1)]});t.adapter.dispose();h.adapter.dispose();});
