// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Review=require('../web/storyboard-shot-review.js'),Request=require('../web/storyboard-shot-request.js'),V=require('../musiclab/assets/delivery-versions.js');
const payload=()=>({...JSON.parse(fs.readFileSync('examples/unfinished-storyboard-review.json','utf8')),row:3});
const wire=p=>{const data=Review.report(p);return {data,files:{'storyboard-shot-review.json':JSON.stringify(data,null,2)+'\n','storyboard-shot-review.md':Review.markdown(data)},meta:{version:V.current,protocol_version:1,needs_review:true}};};
function setup(){let value={panel:payload().panel,ids:['a','b','c','d'],selectedId:'c'},local=null;const reports=[],errors=[],states=[],stale=[],waiting=[];
 const source=Review.createController({capture:()=>value,onState:v=>local=v});
 const controller=Request.createController({source,request:(p,current)=>new Promise((resolve,reject)=>waiting.push({payload:p,current,resolve,reject})),onReport:v=>reports.push(v),onError:e=>errors.push(e.message),onState:v=>states.push(v),onStale:()=>stale.push(true)});
 return {source,controller,reports,errors,states,stale,waiting,get value(){return value;},get local(){return local;}};
}
test('full runtime envelope refuses root and file hidden or symbol fields before inspection',()=>{const p=payload(),good=wire(p);for(const [target,key] of [['root','hidden'],['files','hidden'],['root',Symbol('hidden')],['files',Symbol('hidden')]]){const bad=wire(p);Object.defineProperty(target==='root'?bad:bad.files,key,{value:'unexpected'});assert.throws(()=>Review.checkedResult(p,bad));assert.deepEqual(Review.checkedResult(p,good).data,good.data);}});
test('full runtime envelope refuses own root and file getters without invoking them',()=>{const p=payload();for(const where of ['data','files','meta','json']){const bad=wire(p);let reads=0;const object=where==='json'?bad.files:bad,key=where==='json'?'storyboard-shot-review.json':where,value=object[key];Object.defineProperty(object,key,{enumerable:true,get(){reads++;return value;}});assert.throws(()=>Review.checkedResult(p,bad));assert.equal(reads,0);}});
test('full runtime envelope refuses nonfinite values and invalid Unicode in every returned text entry',()=>{const p=payload();for(const edit of [w=>w.meta.protocol_version=Infinity,w=>w.files['storyboard-shot-review.md']='\ud800',w=>w.files['storyboard-shot-review.json']='\ud800',w=>w.data.issues[0].message='\ud800']){const bad=wire(p);edit(bad);assert.throws(()=>Review.checkedResult(p,bad));}});
test('current request returns checked files with metadata-only pending state and copied transport payload',async()=>{const s=setup(),current=()=>true;current.signal={synthetic:true};const work=s.controller.check(current);assert.deepEqual(s.states,[{pending:true}]);assert.equal(s.waiting[0].current,current);s.waiting[0].resolve(wire(s.waiting[0].payload));assert.equal(await work,true);assert.equal(s.reports.length,1);assert.equal(s.errors.length,0);assert.deepEqual(s.states,[{pending:true},{pending:false}]);assert.deepEqual(Object.keys(s.waiting[0].payload),['panel','row']);});
test('source change suppresses late successful report and retains newer local values',async()=>{const s=setup(),work=s.controller.check();s.value.panel.shots[2].visual='later value';s.waiting[0].resolve(wire(s.waiting[0].payload));assert.equal(await work,false);assert.equal(s.reports.length,0);assert.deepEqual(s.errors,[]);assert.equal(s.stale.length,1);assert.equal(s.value.panel.shots[2].visual,'later value');});
test('source change suppresses the old error and publishes only current stale status',async()=>{const s=setup(),work=s.controller.check();s.value.selectedId='d';s.waiting[0].reject(Error('old selected shot failure'));assert.equal(await work,false);assert.deepEqual(s.errors,[]);assert.equal(s.stale.length,1);assert.equal(s.reports.length,0);});
test('identity order changes reject late errors even when original row text is identical',async()=>{const s=setup(),work=s.controller.check();[s.value.ids[0],s.value.ids[1]]=[s.value.ids[1],s.value.ids[0]];s.waiting[0].reject(Error('late error'));assert.equal(await work,false);assert.equal(s.errors.length,0);assert.equal(s.stale.length,1);});
test('a current malformed reply preserves the previous report and permits good retry',async()=>{const s=setup(),first=s.controller.check(),bad=wire(s.waiting[0].payload);bad.meta.needs_review=false;s.waiting[0].resolve(bad);assert.equal(await first,false);assert.equal(s.reports.length,0);assert.equal(s.errors.length,1);const retry=s.controller.check();s.waiting[1].resolve(wire(s.waiting[1].payload));assert.equal(await retry,true);assert.equal(s.reports.length,1);});
test('latest request owns pending state and an older success cannot finish it',async()=>{const s=setup(),first=s.controller.check(),second=s.controller.check();s.waiting[0].resolve(wire(s.waiting[0].payload));assert.equal(await first,false);assert.deepEqual(s.states,[{pending:true},{pending:true}]);assert.equal(s.reports.length,0);s.waiting[1].resolve(wire(s.waiting[1].payload));assert.equal(await second,true);assert.deepEqual(s.states.at(-1),{pending:false});assert.equal(s.reports.length,1);});
test('an older failure cannot replace a newer successful report or status',async()=>{const s=setup(),first=s.controller.check(),second=s.controller.check();s.waiting[1].resolve(wire(s.waiting[1].payload));assert.equal(await second,true);const before=structuredClone(s.reports);s.waiting[0].reject(Error('late predecessor'));assert.equal(await first,false);assert.deepEqual(s.reports,before);assert.deepEqual(s.errors,[]);assert.equal(s.stale.length,0);});
test('outer cancellation suppresses both successful and failed callbacks and releases pending state',async()=>{for(const failure of [false,true]){const s=setup();let active=true;const work=s.controller.check(()=>active);active=false;if(failure)s.waiting[0].reject(Error('aborted'));else s.waiting[0].resolve(wire(s.waiting[0].payload));assert.equal(await work,false);assert.deepEqual(s.reports,[]);assert.deepEqual(s.errors,[]);assert.deepEqual(s.stale,[]);assert.deepEqual(s.states.at(-1),{pending:false});}});
test('explicit invalidation releases only its request and a new request remains pending',async()=>{const s=setup(),old=s.controller.check();s.controller.invalidate();const current=s.controller.check();s.waiting[0].reject(Error('old'));assert.equal(await old,false);assert.deepEqual(s.states.at(-1),{pending:true});s.waiting[1].resolve(wire(s.waiting[1].payload));assert.equal(await current,true);assert.equal(s.errors.length,0);});
test('bad selection preserves the last local report and makes no HTTP request',async()=>{const s=setup();s.source.check();const before=structuredClone(s.local);s.value.selectedId='missing';assert.equal(await s.controller.check(),false);assert.deepEqual(s.local,before);assert.equal(s.waiting.length,0);assert.equal(s.errors.length,1);assert.deepEqual(s.states,[{pending:true},{pending:false}]);});
function app(){const text=fs.readFileSync('web/app.js','utf8'),a=text.indexOf('const shotReviewRequest='),b=text.indexOf("$('mv-ready-report').onclick=",a),nodes={'shot-review-report':{},'mv-visual':{hidden:false}},messages=[],files=[];let selected=true,active=true,resolve,reject;const p=payload();const current=()=>active;current.signal={synthetic:true};
 const context={$:id=>nodes[id],shotReviewController:{payload:()=>p,check(){},isCurrent:()=>selected},MusicStoryboardShotRequest:Request,shotReviewDOM:{refresh(){}},api:(route,body,binary,signal)=>{assert.equal(route,'/api/storyboard-shot-review');assert.equal(binary,false);assert.equal(signal,current.signal);return new Promise((r,j)=>{resolve=r;reject=j;});},setFiles:(f,note)=>files.push({f,note}),say:(m,error)=>messages.push({m,error}),run:(_b,task)=>task(current)};
 vm.runInNewContext(text.slice(a,b),context);return {nodes,messages,files,p,start:()=>nodes['shot-review-report'].onclick(),resolve:r=>resolve(r),reject:e=>reject(e),set selected(v){selected=v;},set active(v){active=v;}};
}
test('actual app adapter commits checked report and rejects late selected errors through the request layer',async()=>{const s=app(),work=s.start();s.resolve(wire(s.p));assert.equal(await work,true);assert.equal(s.nodes['mv-visual'].hidden,true);assert.equal(s.files.length,1);const late=app(),pending=late.start();late.selected=false;late.reject(Error('old selected shot failure'));assert.equal(await pending,false);assert.equal(late.files.length,0);assert.equal(late.nodes['mv-visual'].hidden,false);assert.ok(late.messages.every(v=>!v.m.includes('old selected')));});
test('actual app adapter keeps prior output on malformed response and outer cancellation',async()=>{for(const cancelled of [false,true]){const s=app(),work=s.start();if(cancelled){s.active=false;s.reject(Error('abort'));}else{const bad=wire(s.p);bad.data.row=1;s.resolve(bad);}assert.equal(await work,false);assert.equal(s.files.length,0);assert.equal(s.nodes['mv-visual'].hidden,false);assert.equal(s.messages.length,cancelled?0:1);}});
