// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../web/issue-page.js'),Cursor=require('../web/issue-cursor.js');
function setup(){const s={source:{detailCount:200,totalCount:9999,revision:3,stale:false,busy:false,visible:true},views:[]};s.c=P.createController({capture:()=>s.source,onState:v=>s.views.push(v)});return s;}
test('reveal selects only the page containing a valid retained index without rewriting count or source',()=>{const s=setup(),before=structuredClone(s.source);for(let i=0;i<200;i++){assert.equal(s.c.reveal(i,3),true);assert.equal(s.c.view().page,Math.floor(i/20));}assert.equal(s.views.length,9);assert.equal(s.c.view().totalCount,9999);assert.deepEqual(s.source,before);});
test('reveal invalid index and old revision refuse without publishing or moving',()=>{const s=setup();for(const index of [-1,200,1.5,NaN,true,'20',undefined])assert.equal(s.c.reveal(index,3),false);assert.equal(s.c.reveal(40,2),false);assert.equal(s.c.reveal(40,undefined),false);assert.equal(s.c.view().page,0);assert.equal(s.views.length,0);});
test('reveal refuses busy hidden stale and empty sources while manual stale reading remains available',()=>{for(const change of [s=>s.source.busy=true,s=>s.source.visible=false,s=>s.source.stale=true,s=>s.source.detailCount=0]){const s=setup();change(s);assert.equal(s.c.reveal(40,3),false);assert.equal(s.views.length,0);assert.equal(s.c.view().page,0);}const s=setup();s.source.stale=true;assert.equal(s.c.move(1),true);assert.equal(s.c.view().page,1);assert.equal(s.c.reveal(0,3),false);});
test('reveal rechecks full metadata and refuses a source changed between captures',()=>{const original=setup().source;let captures=0,states=0;const c=P.createController({capture:()=>({...original,revision:++captures===1?3:4}),onState:()=>states++});assert.equal(c.reveal(40,3),false);assert.equal(states,0);});
test('retained list callbacks still require their current page and exact revision after reveal',()=>{const s=setup();assert.ok(s.c.locate(0,3));assert.ok(s.c.reveal(40,3));assert.equal(s.c.locate(0,3),null);assert.equal(s.c.locate(40,2),null);assert.deepEqual(s.c.locate(40,3),{index:40,revision:3});assert.ok(s.c.reveal(0,3));assert.equal(s.c.locate(40,3),null);});
test('cursor refuses non-own JSON metadata getters without reads under explicit 200 capacity',()=>{let reads=0;const source={busy:false,detailCount:200,hasReport:true,revision:1,stale:false,visible:true};Object.defineProperty(source,'detailCount',{enumerable:true,get(){reads++;return 200;}});const c=Cursor.createController({maxDetails:200,capture:()=>source,onLocate:()=>{throw Error('focus must not run');}});assert.throws(()=>c.refresh());assert.equal(reads,0);});
test('cursor successful focus followed by stale or revised state does not advance position',()=>{for(const field of ['stale','revision','detailCount']){const source={busy:false,detailCount:200,hasReport:true,revision:1,stale:false,visible:true},views=[],c=Cursor.createController({maxDetails:200,capture:()=>source,onLocate:()=>{source[field]=field==='stale'?true:field==='revision'?2:199;return true;},onState:v=>views.push(v)});assert.equal(c.move(1),false);assert.equal(views.at(-1).index,null);}});
test('legacy shot messages and 32 detail default remain unchanged with a separate explicit cursor',()=>{const source={busy:false,detailCount:0,hasReport:false,revision:0,stale:false,visible:true},old=Cursor.createController({capture:()=>source,onLocate:()=>true}),modern=Cursor.createController({maxDetails:200,capture:()=>source,onLocate:()=>true,messages:{missing:'歌詞未查',stale:'歌詞改變',empty:'歌詞零項',progress:'歌詞待辦'}});assert.equal(old.refresh().message,'先檢查選定鏡頭待辦，再逐項定位。');assert.equal(modern.refresh().message,'歌詞未查');source.hasReport=true;assert.equal(old.refresh().message,'這一鏡沒有欄位待辦；仍須整份分鏡驗證。');});
