// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../web/editor-keys-dom.js');
function setup(open=[false,true,false]){
 const nodes={},events=[],document={body:{},activeElement:null,getElementById:id=>nodes[id]};let busy=false,mode='normal';
 for(const [list,panel] of [['arrangement','music'],['shots','storyboard'],['cues','lyrics']]){nodes[panel]={isConnected:true,hidden:false};nodes[list]={id:list,isConnected:true,children:[],listeners:new Map(),addEventListener(t,f){this.listeners.set(t,f);},removeEventListener(t,f){assert.equal(this.listeners.get(t),f);this.listeners.delete(t);}};}
 function render(items){for(const row of nodes.shots.children){row.isConnected=false;row.summary.isConnected=false;}nodes.shots.children=items.map(item=>{
  const row={dataset:{historyId:item.id},isConnected:true,parentElement:nodes.shots,creative:structuredClone(item.creative),querySelectorAll:()=>[],contains:t=>t===row.summary,querySelector:q=>q==='details'?row.details:null};
  row.details={parentElement:row,open:item.open,querySelector:q=>q==='summary'?row.summary:null};row.summary={tagName:'SUMMARY',isConnected:true,disabled:false,hidden:false,parentElement:row.details,closest:()=>row,focus(){document.activeElement=this;events.push(['focus',item.id]);}};
  for(const name of ['value','selectionStart','selectionEnd','selectionDirection','setSelectionRange'])Object.defineProperty(row.summary,name,{get:()=>assert.fail('summary read input property '+name)});
  return row;
 });}
 render(['a','b','c'].map((id,i)=>({id,open:open[i],creative:{start:' 00'+i+'.000 ',end:'',visual:' 原文\r\n<script>🎵\t'+id,camera:'原運鏡'}})));
 const values=()=>nodes.shots.children.map(r=>({id:r.dataset.historyId,open:r.details.open,creative:structuredClone(r.creative)}));
 const adapter=D.bind(document,{busy:()=>busy,onMove:(list,id,delta)=>{events.push(['move',list,id,delta]);if(mode==='false')return false;const items=values(),index=items.findIndex(r=>r.id===id);[items[index],items[index+delta]]=[items[index+delta],items[index]];if(mode==='wrong')items.reverse();render(items);if(mode==='changed-open')nodes.shots.children[index+delta].details.open=!nodes.shots.children[index+delta].details.open;if(mode==='missing-summary')nodes.shots.children[index+delta].details.querySelector=()=>null;document.activeElement=mode==='foreign-focus'?{foreign:true}:document.body;return true;},onError:e=>events.push(['error',e.message])});
 function key(index=1,extra={},transform=()=>{}){const target=nodes.shots.children[index].summary;document.activeElement=target;transform(target,nodes.shots.children[index]);const e={key:'ArrowUp',altKey:true,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:38,target,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...extra};nodes.shots.listeners.get('keydown')?.(e);return e;}
 return {nodes,document,events,adapter,values,key,set busy(v){busy=v;},set mode(v){mode=v;}};
}
test('collapsed and expanded summaries move both ways preserving stable focus and every raw field and per-ID open state',()=>{
 for(const open of [[false,false,false],[true,true,false],[false,true,false]])for(const direction of [-1,1]){const s=setup(open),before=s.values(),e=s.key(1,direction===1?{key:'ArrowDown',keyCode:40}:{}),expected=structuredClone(before);[expected[1],expected[1+direction]]=[expected[1+direction],expected[1]];assert.equal(e.defaultPrevented,true);assert.deepEqual(s.values(),expected);assert.equal(s.document.activeElement,s.nodes.shots.children[1+direction].summary);assert.deepEqual(s.events,[['move','shots','b',direction],['focus','b']]);}
});
test('summary first and last boundaries retain current native control and do not consume',()=>{for(const [index,extra] of [[0,{}],[2,{key:'ArrowDown',keyCode:40}]]){const s=setup(),before=s.values(),e=s.key(index,extra);assert.equal(e.defaultPrevented,false);assert.deepEqual(s.values(),before);assert.equal(s.document.activeElement,s.nodes.shots.children[index].summary);assert.deepEqual(s.events,[]);}});
test('Enter space arrows composition repeat and combined keys retain native summary behavior without input properties',()=>{for(const extra of [{key:'Enter'},{key:' '},{altKey:false},{ctrlKey:true},{metaKey:true},{shiftKey:true},{repeat:true},{isComposing:true},{keyCode:229},{defaultPrevented:true}]){const s=setup(),before=s.values(),e=s.key(1,extra);assert.equal(e.defaultPrevented,extra.defaultPrevented===true);assert.deepEqual(s.values(),before);assert.deepEqual(s.events,[]);}});
test('busy hidden detached disabled nested nonprimary foreign and inactive summary controls are ignored',()=>{
 for(const kind of ['busy','hidden','detached','disabled','target-hidden','nested','nonprimary','foreign','inactive']){const s=setup(),before=s.values();if(kind==='busy')s.busy=true;if(kind==='hidden')s.nodes.storyboard.hidden=true;const e=s.key(1,{},(target,row)=>{if(kind==='detached')row.isConnected=false;if(kind==='disabled')target.disabled=true;if(kind==='target-hidden')target.hidden=true;if(kind==='nested')row.details.parentElement={};if(kind==='nonprimary')row.details.querySelector=()=>({tagName:'SUMMARY'});if(kind==='foreign')row.parentElement=s.nodes.cues;if(kind==='inactive')s.document.activeElement=s.document.body;});assert.equal(e.defaultPrevented,false,kind);assert.deepEqual(s.values(),before);assert.deepEqual(s.events,[],kind);}
});
test('summaries in other editor lists do not become row shortcuts',()=>{for(const list of ['arrangement','cues']){const s=setup(),row=s.nodes.shots.children[1];s.nodes[list].children=[row];row.parentElement=s.nodes[list];s.document.activeElement=row.summary;const e={key:'ArrowUp',altKey:true,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:38,target:row.summary,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};s.nodes[list].listeners.get('keydown')(e);assert.equal(e.defaultPrevented,false);assert.deepEqual(s.events,[]);}});
test('failed mismatched writes and intervening external focus do not refocus summaries or roll back external state',()=>{for(const mode of ['false','wrong','foreign-focus']){const s=setup();s.mode=mode;s.key();assert.equal(s.events.filter(e=>e[0]==='focus').length,0);if(mode==='foreign-focus')assert.deepEqual(s.document.activeElement,{foreign:true});}});
test('changed disclosure state or missing native summary after a successful writer preserves intervening state without focus',()=>{for(const mode of ['changed-open','missing-summary']){const s=setup();s.mode=mode;s.key();assert.equal(s.events.filter(e=>e[0]==='focus').length,0);assert.equal(s.nodes.shots.children[0].dataset.historyId,'b');}});
test('summary support owns only the same three listeners and disposed adapters cannot consume events',()=>{const s=setup();s.adapter.dispose();const e=s.key();assert.equal(e.defaultPrevented,false);assert.deepEqual(s.events,[]);for(const list of ['arrangement','shots','cues'])assert.equal(s.nodes[list].listeners.size,0);});
