// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../web/backup-selection.js'),D=require('../web/backup-selection-dom.js');
const id=n=>'draft-'+n.toString(16).padStart(32,'0');
const record=(n,label='版本 '+n+' 🎵')=>({library_schema_version:1,id:id(n),label,stored_at:'2026-10-06T10:00:00+00:00',sha256:'a'.repeat(64),bytes:200,draft_schema_version:3,created_with:'0.129.0',titles:{music:'合成歌曲',storyboard:'',lyrics:''}});
function harness(displayed=[record(1),record(2)]){let s={enabled:true,busy:false,selected:displayed[0]||null,displayed},last;const errors=[];const c=M.createController({capture:()=>s,onState:v=>{last=v;},onError:e=>errors.push(e.message)});return {c,errors,get s(){return s;},set s(v){s=v;},get view(){return last;}};}
test('legacy three-field captures remain valid and cannot imply a whole-library selection',()=>{const h=harness();delete h.s.displayed;assert.equal(h.c.refresh().canAddDisplayed,false);assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.request(),null);assert.equal(h.c.add(),true);assert.deepEqual(h.c.request(),{ids:[id(1)]});});
test('bulk adds only the captured displayed page and then follows manually appended pages',()=>{const h=harness([record(3),record(2)]);assert.equal(h.c.addDisplayed(),true);assert.deepEqual(h.c.request(),{ids:[id(2),id(3)]});h.s.displayed.push(record(1));assert.equal(h.c.refresh().newDisplayedCount,1);assert.equal(h.c.addDisplayed(),true);assert.deepEqual(h.c.request(),{ids:[id(1),id(2),id(3)]});});
test('search replacement keeps earlier choices and an empty result cannot clear or download the whole library',()=>{const h=harness();h.c.addDisplayed();h.s={...h.s,selected:record(4),displayed:[record(4)]};h.c.addDisplayed();h.s={...h.s,selected:null,displayed:[]};assert.equal(h.c.addDisplayed(),false);assert.deepEqual(h.c.request(),{ids:[id(1),id(2),id(4)]});assert.equal(h.c.refresh().canAddDisplayed,false);});
test('identical repeats are counted once including duplicates within a captured page',()=>{const h=harness([record(2),record(2),record(1)]);assert.equal(h.c.refresh().newDisplayedCount,2);assert.equal(h.c.addDisplayed(),true);assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.refresh().count,2);assert.equal(h.c.refresh().canAddDisplayed,false);});
test('a conflicting retained version refuses every new ID regardless of its position',()=>{const h=harness([record(1)]);h.c.addDisplayed();h.s.displayed=[record(2),record(1,'矛盾'),record(3)];assert.equal(h.c.refresh().canAddDisplayed,false);assert.match(h.c.refresh().displayedProblem,/整批未加入/);assert.equal(h.c.addDisplayed(),false);assert.deepEqual(h.c.request(),{ids:[id(1)]});assert.equal(h.c.refresh().entries[0].label,'版本 1 🎵');assert.equal(h.errors.length,1);});
test('conflicting duplicate metadata within a new page never leaves an earlier partial addition',()=>{const h=harness([record(2),record(3),record(2,'矛盾')]);assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.request(),null);assert.equal(h.c.refresh().count,0);});
test('1000 unique displayed versions are accepted and later mixed overflow is atomic',()=>{const h=harness(Array.from({length:1000},(_,i)=>record(1000-i)));assert.equal(h.c.addDisplayed(),true);const before=h.c.request();assert.equal(before.ids.length,1000);assert.equal(before.ids[0],id(1));h.s.displayed=[record(1),record(1001)];assert.equal(h.c.addDisplayed(),false);assert.deepEqual(h.c.request(),before);assert.equal(h.c.remove(id(500)),true);assert.equal(h.c.addDisplayed(),true);assert.equal(h.c.request().ids.length,1000);});
test('invalid and oversized displayed metadata rejects the complete source before any selection mutation',()=>{for(const displayed of [null,{},Array(1),Array.from({length:1001},(_,i)=>record(i)),[record(2),{...record(3),bytes:0}],[record(1),{...record(2),titles:{music:'\ud800',storyboard:'',lyrics:''}}]]){const h=harness([record(1)]);h.c.add();h.s.displayed=displayed;assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.refresh().count,1);assert.equal(h.c.refresh().canDownload,false);}});
test('all nested metadata getters including ID and title are refused without execution',()=>{let touched=0;for(const where of ['root','id','titles','music','index']){const h=harness();const getter={enumerable:true,get(){touched++;return where==='music'?'x':record(2);}};if(where==='root')Object.defineProperty(h.s,'displayed',getter);if(where==='id'||where==='titles')Object.defineProperty(h.s.displayed[1],where,getter);if(where==='music')Object.defineProperty(h.s.displayed[1].titles,'music',getter);if(where==='index')Object.defineProperty(h.s.displayed,'1',getter);assert.equal(h.c.addDisplayed(),false);}assert.equal(touched,0);});
test('single selection ID getter is also refused before existing revision validation',()=>{let touched=0;const selected=Object.defineProperty(record(1),'id',{enumerable:true,get(){touched++;return id(1);}});assert.throws(()=>M.checked({enabled:true,busy:false,selected}));assert.equal(touched,0);});
test('array hooks symbols and extra data fields are rejected without executing caller hooks',()=>{let touched=0;for(const key of ['toJSON',Symbol.iterator,'path']){const h=harness();h.s.displayed[key]=()=>{touched++;return [];};assert.equal(h.c.addDisplayed(),false);}assert.equal(touched,0);});
test('checked displayed metadata, views and fixed ID requests do not retain caller references',()=>{const h=harness();const copy=M.checked(h.s);copy.displayed[0].titles.music='changed';assert.equal(h.s.displayed[0].titles.music,'合成歌曲');h.c.addDisplayed();const request=h.c.request(),view=h.c.refresh();h.s.displayed[0].label='later';view.entries[0].label='caller';request.ids.length=0;assert.equal(h.c.refresh().entries[0].label,'版本 1 🎵');assert.deepEqual(h.c.request(),{ids:[id(1),id(2)]});});
test('busy disabled and disposed bulk actions preserve prior IDs and never call capture after disposal',()=>{const h=harness();h.c.addDisplayed();for(const flags of [{busy:true},{enabled:false}]){const old=h.s;h.s={...old,...flags};assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.refresh().canAddDisplayed,false);assert.equal(h.c.request(),null);assert.equal(h.c.refresh().count,2);h.s=old;}h.c.dispose();h.s=null;assert.equal(h.c.addDisplayed(),false);assert.equal(h.c.request(),null);});
function dom(){const document={activeElement:null,getElementById:k=>nodes[k],createElement:()=>element()};function element(){return {textContent:'',disabled:false,children:[],attrs:{},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},setAttribute(k,v){this.attrs[k]=v;},focus(){document.activeElement=this;}};}const nodes=Object.fromEntries(['backup-selection-add','backup-selection-add-displayed','backup-selection-displayed-note','backup-selection-clear','backup-selection-list','backup-selection-note','backup-save-batch','library-select'].map(k=>[k,element()]));nodes['backup-save-batch'].disabled=true;let s={enabled:true,busy:false,selected:record(1),displayed:[record(1),record(2)]},changes=0;const handlers=new Map(),events={addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:n=>handlers.delete(n)};const errors=[];const bind={capture:()=>s,events,onChange:()=>{changes++;nodes['backup-save-batch'].disabled=!adapter?.request();},onError:e=>errors.push(e.message)};let adapter;adapter=D.bind(document,bind);return {document,nodes,bind,adapter,handlers,errors,get s(){return s;},set s(v){s=v;},get changes(){return changes;}};}
test('rendered bulk scope describes displayed and not-yet-loaded versions with literal metadata',()=>{const h=dom();h.s.displayed[0].label='<img onerror=bad> 🎵';h.s.selected=h.s.displayed[0];h.adapter.refresh();assert.match(h.nodes['backup-selection-add-displayed'].textContent,/2 版/);assert.match(h.nodes['backup-selection-displayed-note'].textContent,/不包含尚未讀取/);assert.equal(h.nodes['backup-selection-add-displayed'].onclick(),true);assert.match(h.nodes['backup-selection-list'].children[0].children[0].textContent,/<img onerror=bad>/);assert.equal(h.nodes['backup-save-batch'].disabled,false);h.adapter.dispose();});
test('keyboard bulk action moves focus from the newly disabled control to enabled batch download',()=>{const h=dom(),button=h.nodes['backup-selection-add-displayed'];button.focus();button.onclick();assert.equal(button.disabled,true);assert.equal(h.document.activeElement,h.nodes['backup-save-batch']);assert.equal(h.nodes['backup-save-batch'].disabled,false);h.adapter.dispose();});
test('a focused single add moves to bulk while other displayed versions remain',()=>{const h=dom();h.nodes['backup-selection-add'].focus();h.nodes['backup-selection-add'].onclick();assert.equal(h.document.activeElement,h.nodes['backup-selection-add-displayed']);assert.equal(h.nodes['backup-selection-add-displayed'].disabled,false);h.adapter.dispose();});
test('failed bulk action keeps focus and original list; manual refresh does not steal focus',()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();const item=h.nodes['backup-selection-list'].children[0];item.children[1].focus();h.adapter.refresh();assert.equal(h.document.activeElement,item.children[1]);h.s.displayed=[record(3),record(1,'矛盾')];h.adapter.refresh();h.nodes['backup-selection-add-displayed'].focus();assert.equal(h.nodes['backup-selection-add-displayed'].onclick(),false);assert.equal(h.document.activeElement,h.nodes['backup-selection-add-displayed']);assert.equal(h.nodes['backup-selection-list'].children[0],item);assert.match(h.nodes['backup-selection-displayed-note'].textContent,/整批未加入/);h.adapter.dispose();});
test('pagehide clears the new owned handler and disables bulk without changing source metadata',()=>{const h=dom(),before=structuredClone(h.s);h.nodes['backup-selection-add-displayed'].onclick();h.handlers.get('pagehide')();assert.equal(h.nodes['backup-selection-add-displayed'].onclick,null);assert.equal(h.nodes['backup-selection-add-displayed'].disabled,true);assert.deepEqual(h.s,before);assert.equal(h.adapter.request(),null);});
test('actual app capture uses currently published metadata and never fetches additional pages during bulk add',()=>{const h=dom();h.adapter.dispose();const state={busy:false},c=vm.createContext({state,document:h.document,libraryEnabled:true,libraryRecords:[record(8),record(7)],backupRestoring:false,backupDownloading:false,MusicBackupSelectionDom:{bind:(document,options)=>D.bind(document,{...options,events:h.bind.events})},$:id=>h.nodes[id],backupSay(){}});h.nodes['library-select'].value=id(8);const source=fs.readFileSync('web/app.js','utf8'),start=source.indexOf('state.backupSelection=MusicBackupSelectionDom.bind('),end=source.indexOf('state.backupDownload=',start);vm.runInContext(source.slice(start,end),c);h.nodes['backup-selection-add-displayed'].onclick();assert.deepEqual(Array.from(c.state.backupSelection.request().ids),[id(7),id(8)]);c.libraryRecords=[record(9)];h.nodes['library-select'].value=id(9);c.state.backupSelection.refresh();h.nodes['backup-selection-add-displayed'].onclick();assert.deepEqual(Array.from(c.state.backupSelection.request().ids),[id(7),id(8),id(9)]);c.state.backupSelection.dispose();});
