// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../web/issue-cursor.js');
function setup(){let source={detailCount:3,hasReport:true,revision:4,stale:false,busy:false,visible:true};const calls=[],views=[];let result=true,hook=()=>{};
 const c=C.createController({capture:()=>source,onLocate:(index,revision)=>{calls.push({index,revision});hook();return result;},onState:v=>views.push(v)});
 return {c,calls,views,get source(){return source;},set source(v){source=v;},set result(v){result=v;},set hook(v){hook=v;}};
}
test('next starts at the first issue and stops at the last, previous never wraps',()=>{const s=setup();let v=s.c.refresh();assert.equal(v.canPrevious,false);assert.equal(v.canNext,true);assert.equal(s.c.move(-1),false);for(let i=0;i<3;i++){assert.equal(s.c.move(1),true);assert.equal(s.views.at(-1).index,i);}assert.equal(s.c.move(1),false);assert.equal(s.c.move(-1),true);assert.deepEqual(s.calls,[{index:0,revision:4},{index:1,revision:4},{index:2,revision:4},{index:1,revision:4}]);});
test('clicking an arbitrary original issue establishes the next and previous cursor',()=>{const s=setup();assert.equal(s.c.locate(1,4),true);assert.equal(s.views.at(-1).canPrevious,true);assert.equal(s.c.move(1),true);assert.equal(s.views.at(-1).index,2);});
test('failed focus does not advance the cursor and permits retry',()=>{const s=setup();s.result=false;assert.equal(s.c.move(1),false);assert.equal(s.views.at(-1).index,null);s.result=true;assert.equal(s.c.move(1),true);assert.equal(s.views.at(-1).index,0);});
test('stale, hidden, busy and missing reports block callbacks while preserving cursor',()=>{for(const key of ['stale','busy','visible']){const s=setup();s.c.locate(1);s.source[key]=key!=='visible';assert.equal(s.c.move(1),false);assert.equal(s.calls.length,1);assert.equal(s.views.at(-1).index,1);s.source[key]=key==='visible';assert.equal(s.c.move(1),true);}const s=setup();s.source={...s.source,hasReport:false,detailCount:0};assert.equal(s.c.move(1),false);assert.equal(s.calls.length,0);});
test('new report revision resets navigation without focusing a field',()=>{const s=setup();s.c.locate(2,4);s.source.revision=5;const v=s.c.refresh();assert.equal(v.index,null);assert.equal(s.calls.length,1);assert.equal(s.c.locate(2,4),false);assert.equal(s.calls.length,1);assert.equal(s.c.move(1),true);assert.deepEqual(s.calls.at(-1),{index:0,revision:5});});
test('count changes reset the index and old out-of-range targets are refused',()=>{const s=setup();s.c.locate(2);s.source.detailCount=1;assert.equal(s.c.locate(2),false);assert.equal(s.views.at(-1).index,null);assert.equal(s.c.move(1),true);assert.equal(s.c.move(1),false);});
test('a replacement report during a focus callback cannot inherit the old location',()=>{const s=setup();s.hook=()=>s.source.revision++;assert.equal(s.c.move(1),false);assert.equal(s.views.at(-1).index,null);assert.equal(s.views.at(-1).revision,5);});
test('a source becoming stale or busy during focus cannot mark successful location',()=>{for(const key of ['stale','busy']){const s=setup();s.hook=()=>s.source[key]=true;assert.equal(s.c.move(1),false);assert.equal(s.views.at(-1).index,null);}});
test('refresh and output metadata cannot modify caller input or internal location',()=>{const s=setup(),before=structuredClone(s.source);const v=s.c.refresh();v.index=2;v.revision=100;assert.deepEqual(s.source,before);assert.equal(s.c.move(1),true);assert.equal(s.views.at(-1).index,0);assert.deepEqual(Object.keys(s.views.at(-1)).sort(),['canNext','canPrevious','canReturn','detailCount','index','message','revision']);});
test('empty report explains incomplete acceptance and never locates',()=>{const s=setup();s.source.detailCount=0;const v=s.c.refresh();assert.equal(v.canNext,false);assert.match(v.message,/仍須整份分鏡驗證/);assert.equal(s.c.move(1),false);assert.deepEqual(s.calls,[]);});
test('invalid metadata, accessors, symbols and hidden fields are rejected without getter reads',()=>{for(const change of [v=>v.detailCount=33,v=>v.detailCount=1.5,v=>v.revision=-1,v=>v.busy='true',v=>v.hasReport=false,v=>v.extra=0,v=>Object.defineProperty(v,'hidden',{value:1}),v=>v[Symbol('x')]=1]){const s=setup();change(s.source);assert.throws(()=>s.c.refresh());assert.deepEqual(s.calls,[]);}const s=setup();let reads=0;Object.defineProperty(s.source,'revision',{enumerable:true,get(){reads++;return 4;}});assert.throws(()=>s.c.move(1));assert.equal(reads,0);});
test('unknown directions and targets never invoke focus',()=>{const s=setup();for(const d of [0,2,'1',true,NaN])assert.equal(s.c.move(d),false);for(const i of [-1,3,1.5,'1',true,NaN])assert.equal(s.c.locate(i),false);assert.deepEqual(s.calls,[]);});
