// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Editor=require('../web/editor-state.js'),Retention=require('../web/draft-retention.js'),D=require('../web/text-verification-dom.js'),C=require('../web/text-verification-controller.js'),Download=require('../web/text-download.js');
const bytes=s=>new TextEncoder().encode(s);
function draft(title='initial'){
 const panels=Object.fromEntries(Object.entries(Editor.draftFields).map(([name,fields])=>[name,{fields:Object.fromEntries(fields.map(id=>[id,'']))}]));
 Object.entries(Editor.draftRows).forEach(([name,rule])=>panels[name][rule.key]=[]);
 panels.music.avoid=[' 原文\r\n🎵  '];panels.music.deliverables=[];panels.storyboard.motifs=[];
 panels.music.fields['music-title']=title;panels.lyrics.fields['lyrics-format']='.lrc';panels.audio.fields['audio-profile']='distribution';
 return Editor.validateDraft({format:'zoe-music-lab-draft',schema_version:3,tool_version:'0.123.0',saved_at:'synthetic',tab:'music',panels});
}
function harness(){
 let current=draft();const nodes={},notes=[],sent=[],listeners=new Set();
 for(const id of ['draft-export','draft-confirm-download','draft-verify-file','draft-verify-note','draft-verify-source','draft-download-stamp'])nodes[id]={files:[],value:'',disabled:true,dataset:{},textContent:''};
 class File{constructor(name,content){this.name=name;this.content=content;this.size=bytes(content).length;this.reads=0;}async arrayBuffer(){this.reads++;return bytes(this.content).buffer;}}
 const retention=Retention.createGuard({capture:()=>current,capturePanel:n=>current.panels[n],events:{addEventListener(){},removeEventListener(){}},onState(){}});retention.initialize(current);
 const state={busy:false,files:{'original.txt':'完整成果'},tab:'music'};
 const scope={state,draftRetention:retention,MusicEditor:Editor,MusicTextVerificationDOM:{bind:(doc,o)=>D.bind(doc,{...o,FileType:File,events:{addEventListener:(n,f)=>listeners.add(f),removeEventListener:(n,f)=>listeners.delete(f)}})},document:{getElementById:id=>nodes[id]},TextEncoder,JSON,$:id=>nodes[id],captureDraft:()=>structuredClone(current),say:(m,e)=>notes.push({m,e})};
 scope.textDownloader={bind:(form,o)=>{const c=Download.createController({...o,send:v=>{sent.push({...v,content:Buffer.from(v.bytes).toString('utf8')});return true;}});form.send=()=>c.download();}};
 const app=fs.readFileSync('web/app.js','utf8'),start=app.indexOf('let draftDownloadSource='),end=app.indexOf("$('draft-open').onchange",start);assert.ok(start>0&&end>start);vm.runInNewContext(app.slice(start,end),scope);
 function change(title){current=draft(title);retention.refresh();}
 function file(content=sent.at(-1)?.content,name='saved (1).json'){return new File(name,content);}
 async function verify(f){const picker=nodes['draft-verify-file'];picker.files=[f];picker.value='selected';picker.onchange();await new Promise(setImmediate);}
 return {nodes,notes,sent,retention,state,File,change,file,verify,download:()=>nodes['draft-export'].send(),current:()=>structuredClone(current),dispose:()=>state.draftVerification.dispose()};
}
test('draft picker is unavailable before an actual successful download send',()=>{const h=harness();assert.equal(h.nodes['draft-verify-file'].disabled,true);assert.match(h.nodes['draft-verify-source'].textContent,/先下載/);assert.equal(h.nodes['draft-download-stamp'].textContent,'');assert.equal(h.sent.length,0);h.dispose();});
test('exact full sent bytes including Unicode original whitespace and newline confirm the pending snapshot',async()=>{const h=harness();h.change(' 原作🎵  ');const before=h.current();assert.equal(h.download(),true);assert.equal(h.retention.status().dirty,true);assert.equal(h.nodes['draft-verify-file'].disabled,false);const f=h.file();await h.verify(f);assert.equal(f.reads,1);assert.equal(h.retention.status().dirty,false);assert.equal(h.retention.status().mode,'download');assert.equal(h.retention.status().pendingDownload,false);assert.equal(h.nodes['draft-verify-note'].dataset.match,'true');assert.deepEqual(h.current(),before);assert.equal(h.nodes['draft-verify-file'].value,'');h.dispose();});
test('checking the older download after later edits retains only its snapshot and keeps the current form dirty',async()=>{const h=harness();h.change('送出時');h.download();const original=h.file();h.change('之後的編修');const before=h.current();await h.verify(original);assert.equal(h.retention.status().dirty,true);assert.equal(h.retention.status().pendingDownload,false);assert.match(h.notes.at(-1).m,/新編修仍需另存/);assert.deepEqual(h.current(),before);h.change('送出時');assert.equal(h.retention.status().dirty,false);h.dispose();});
test('a same-sized different byte cannot confirm a pending draft or change inputs',async()=>{const h=harness();h.change('送出時');h.download();const before=h.current(),f=h.file(h.sent.at(-1).content.replace('送出時','錯誤稿'));assert.equal(f.size,h.sent.at(-1).bytes.length);await h.verify(f);assert.equal(h.retention.status().pendingDownload,true);assert.equal(h.retention.status().dirty,true);assert.equal(h.nodes['draft-verify-note'].dataset.match,'false');assert.deepEqual(h.current(),before);h.dispose();});
test('BOM changed JSON formatting omitted tail and unknown version refuse exact source confirmation',async()=>{for(const mutate of [s=>'\ufeff'+s,s=>JSON.stringify(JSON.parse(s)),s=>s.slice(0,-1),s=>s.replace('0.123.0','99.0.0')]){const h=harness();h.change('編修');h.download();await h.verify(h.file(mutate(h.sent.at(-1).content)));assert.equal(h.retention.status().pendingDownload,true);assert.equal(h.nodes['draft-verify-note'].dataset.match,'false');h.dispose();}});
test('the selected file may be renamed and literal hostile-looking basename is displayed as text',async()=>{const h=harness();h.change('x');h.download();await h.verify(h.file(undefined,'<literal>🎵.json'));assert.equal(h.retention.status().dirty,false);assert.match(h.nodes['draft-verify-note'].textContent,/<literal>🎵\.json/);h.dispose();});
test('busy states refuse file reads and a busy refresh cancels an already pending proof',async()=>{const h=harness();h.change('x');h.download();h.state.busy=true;h.state.draftVerification.refresh();const f=h.file();await h.verify(f);assert.equal(f.reads,0);h.state.busy=false;h.state.draftVerification.refresh();let resolve;const delayed=h.file();delayed.arrayBuffer=()=>new Promise(r=>resolve=r);void h.verify(delayed);h.state.busy=true;h.state.draftVerification.refresh();h.state.busy=false;h.state.draftVerification.refresh();resolve(bytes(delayed.content).buffer);await new Promise(setImmediate);assert.equal(h.retention.status().pendingDownload,true);assert.equal(h.nodes['draft-verify-note'].dataset.match,'unknown');h.dispose();});
test('an old read success or error cannot confirm the next sent snapshot',async()=>{for(const error of [false,true]){const h=harness();h.change('old');h.download();let resolve,reject;const delayed=h.file();delayed.arrayBuffer=()=>new Promise((r,j)=>{resolve=r;reject=j;});void h.verify(delayed);h.change('new');h.download();if(error)reject(Error('old failed'));else resolve(bytes(delayed.content).buffer);await new Promise(setImmediate);assert.equal(h.retention.status().pendingDownload,true);assert.equal(h.retention.status().dirty,true);assert.equal(h.nodes['draft-verify-note'].dataset.match,'unknown');await h.verify(h.file());assert.equal(h.retention.status().dirty,false);h.dispose();}});
test('an exact new file beats an old pending result and replacing a download clears prior proof',async()=>{const h=harness();h.change('old');h.download();let resolve;const old=h.file();old.arrayBuffer=()=>new Promise(r=>resolve=r);void h.verify(old);h.change('new');h.download();await h.verify(h.file());assert.equal(h.retention.status().dirty,false);resolve(bytes(old.content).buffer);await new Promise(setImmediate);assert.equal(h.nodes['draft-verify-note'].dataset.match,'true');h.change('third');h.download();assert.equal(h.nodes['draft-verify-note'].dataset.match,'unknown');assert.equal(h.retention.status().pendingDownload,true);h.dispose();});
test('1 MiB draft limit rejects oversize metadata before arrayBuffer while standard verifier retains 8 MiB default',async()=>{const h=harness();h.change('x');h.download();const f=h.file();f.size=1024*1024+1;await h.verify(f);assert.equal(f.reads,0);assert.equal(h.retention.status().pendingDownload,true);assert.match(h.nodes['draft-verify-note'].textContent,/1048576/);for(const limit of [0,-1,1.5,8*1024*1024+1])assert.throws(()=>C.createController({maxBytes:limit}));h.dispose();});
test('incomplete reads native-file impersonation and size drift cannot mark a draft retained',async()=>{for(const kind of ['short','drift','io','fake']){const h=harness();h.change('x');h.download();let f=h.file();if(kind==='fake')f={name:'x',size:1,arrayBuffer:()=>assert.fail('fake native file')};else f.arrayBuffer=async()=>{if(kind==='short')return bytes('x').buffer;if(kind==='drift'){f.size++;return bytes(f.content).buffer;}throw Error('read failed');};await h.verify(f);assert.equal(h.retention.status().pendingDownload,true);assert.equal(h.retention.status().dirty,true);await h.verify(h.file());assert.equal(h.retention.status().dirty,false);h.dispose();}});
test('manual confirmation remains explicit and repeated file checks cannot confirm nonexistent pending saves',async()=>{const h=harness();h.change('x');h.download();h.nodes['draft-confirm-download'].onclick();assert.equal(h.retention.status().pendingDownload,false);h.change('new');const before=h.current();await h.verify(h.file());assert.equal(h.retention.status().dirty,true);assert.deepEqual(h.current(),before);h.dispose();});
test('dispose refuses late proof and no chosen content is loaded into project panels',async()=>{const h=harness();h.change('x');h.download();let resolve;const f=h.file();f.arrayBuffer=()=>new Promise(r=>resolve=r);void h.verify(f);const before=h.current();h.dispose();resolve(bytes(f.content).buffer);await new Promise(setImmediate);assert.equal(h.retention.status().pendingDownload,true);assert.deepEqual(h.current(),before);assert.equal(h.state.files['original.txt'],'完整成果');});
test('draft DOM integration uses canonical sent text and has no media write transport or preview read',()=>{const app=fs.readFileSync('web/app.js','utf8'),start=app.indexOf('let draftDownloadSource='),end=app.indexOf("$('draft-open').onchange",start),s=app.slice(start,end);assert.match(s,/content:selected\.content/);assert.match(s,/scope:'draft'/);assert.match(s,/maxBytes:1024\*1024/);assert.doesNotMatch(s,/output-content|arrayBuffer\(|\/api\/|applyDraft\(|markDirty\(|player\.|files\[/);});
