// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const context=require('../web/delivery-context.js'),search=require('../web/delivery-search.js'),text=require('../web/delivery-text.js'),importer=require('../web/delivery-import.js');
const original='\ufeff甲🎵\r\n'+('🎵'.repeat(25)+'記憶點'+'乙'.repeat(30)+'\x00<script>literal</script>\r\n').repeat(45),hash=async raw=>crypto.createHash('sha256').update(raw).digest('hex');
test('bounded original contexts match real Python byte slices across BOM emoji controls and CRLF',()=>{
 const queries=['記憶點','🎵','\ufeff','\r\n','\x00','<script>literal</script>'];
 const python=JSON.parse(execFileSync('python',['-X','utf8','-c','import json,sys\nfrom musiclab.delivery_search import search\ns,q=json.loads(sys.argv[1]);print(json.dumps([search(s,k,include_context=True) for k in q]))',JSON.stringify([original,queries])],{encoding:'utf8',timeout:10000}));
 assert.deepEqual(queries.map(query=>search.search(original,{query,include_context:true})),python);
 for(const [i,v] of python.entries()){assert.deepEqual(search.checked(v,{query:queries[i],include_context:true}),v);for(const item of v.context.items){const bytes=new TextEncoder().encode(original);assert.equal(item.text,new TextDecoder('utf8',{fatal:true,ignoreBOM:true}).decode(bytes.subarray(item.start_byte,item.end_byte)));assert.ok(item.match_start_byte-item.start_byte<=64);assert.ok(item.end_byte-item.match_end_byte<=64);}}
});
test('optional context leaves the seven-key default reply unchanged and strict boolean rejects',()=>{
 const normal=search.search(original,{query:'記憶點'}),enabled=search.search(original,{query:'記憶點',include_context:true});assert.deepEqual(normal,search.search(original,{query:'記憶點',include_context:false}));delete enabled.context;assert.deepEqual(enabled,normal);
 for(const include_context of [null,0,1,'true',{},[]])assert.throws(()=>search.search(original,{query:'記憶點',include_context}));assert.throws(()=>search.checked(normal,{query:'記憶點',include_context:true}));
});
test('edge contexts do not silently drop BOM or split Unicode and max source remains bounded',()=>{
 const q='\x00'.repeat(1024),all=search.search(('a'.repeat(70)+q+'b'.repeat(70)).repeat(50),{query:q,max_matches:50,include_context:true});assert.equal(all.context.items.length,50);assert.ok(all.context.items.every(i=>new TextEncoder().encode(i.text).length===1152));assert.ok(JSON.stringify(all).length<400000);
 const prepared=text.prepare('a'.repeat(8388608-10)+'尾端🎵'),tail=prepared.search({query:'尾端🎵',include_context:true});assert.equal(tail.context.items[0].end_byte,8388608);assert.equal(prepared.window(tail.matches[0].start_byte).text,'尾端🎵');assert.equal(tail.context.items[0].text,'a'.repeat(64)+'尾端🎵');
 assert.deepEqual(search.search('',{query:'x',include_context:true}).context.items,[]);assert.equal(search.search('hit',{query:'hit',include_context:true}).context.items[0].text,'hit');
});
test('context reply checks reject unknown schema bounds size wrong query or reordered positions',()=>{
 const req={query:'記憶點',include_context:true},good=search.search(original,req),i=good.context.items[0];
 for(const change of [v=>v.context.schema_version=2,v=>v.context.flank_bytes=65,v=>v.context.extra=0,v=>v.context.items.pop(),v=>v.context.items[0]={...i,start_byte:i.start_byte-1},v=>v.context.items[0]={...i,end_byte:i.end_byte+1},v=>v.context.items[0]={...i,match_start_byte:i.match_start_byte+1},v=>v.context.items[0]={...i,text:i.text.replace('記憶點','另一點')},v=>v.context.items[0]={...i,text:'\ud800'},v=>v.context.items[0]={...i,extra:0}]){const value=structuredClone(good);change(value);assert.throws(()=>search.checked(value,req));}
 for(const [raw,matches] of [['x',[]],[new Uint8Array(1),[{start_byte:false,end_byte:1}]],[new TextEncoder().encode('a🎵z'),[{start_byte:2,end_byte:5}]],[new Uint8Array(1025),[{start_byte:0,end_byte:1025}]],[new Uint8Array(1),Array(51).fill({start_byte:0,end_byte:1})]])assert.throws(()=>context.contexts(raw,matches));
});
test('presentation labels contain distinguishable original neighbours and mark controls without changing DTO',()=>{
 const source='\ufeff主歌\r\n回答\t甲\x00'+' '.repeat(160)+'副歌\n回答\t乙<script>',r=search.search(source,{query:'回答',include_context:true}),copy=structuredClone(r),labels=r.context.items.map((v,i)=>context.label(v,r.query,i+1,r.source_bytes));assert.match(labels[0],/主歌↵【回答】⇥甲\\u0000/);assert.match(labels[1],/副歌↵【回答】⇥乙<script>/);assert.ok(labels[1].startsWith('第2筆 · …'));assert.equal(context.label(search.search('回答',{query:'回答',include_context:true}).context.items[0],'回答',1,6),'第1筆 · 【回答】');assert.deepEqual(r,copy);
 const long=search.search('a'.repeat(1024),{query:'a'.repeat(1024),include_context:true});assert.ok(context.label(long.context.items[0],long.query,1,1024).endsWith('…'));assert.equal(long.context.items[0].text.length,1024);
 const spaces=search.search(' '.repeat(80)+'   '+' '.repeat(80),{query:'   ',start_byte:80,max_matches:1,include_context:true});assert.equal(spaces.context.items[0].text.length,131);assert.match(context.label(spaces.context.items[0],spaces.query,1,163),/ · … 【   】 …$/);assert.equal(spaces.context.items[0].text,' '.repeat(131));
});
const wires=JSON.parse(execFileSync('python',['-X','utf8','-c',`import json,io,sys
from musiclab.delivery_package import prepare
from musiclab.application import inspect_delivery
t=json.loads(sys.argv[1]);print(json.dumps([inspect_delivery(io.BytesIO(prepare({'scope':s,'files':{'full.txt':t,'empty.txt':''}}).archive),True).wire() for s in ['music','storyboard','lyrics','audio']]))`,JSON.stringify(original)],{encoding:'utf8',timeout:10000}));
function setup(scope='music'){
 const wire=structuredClone(wires.find(w=>w.data.manifest.scope===scope)),d=wire.data,view={scope,revision:1,resultRevision:1,bundle:{files:{'full.txt':'原成果\r\n記憶點\x00'},dirty:false},media:[{}],busy:false},errors=[];
 const options={capture:()=>view,read:async()=>({wire,selected:{bytes:d.archive_bytes,sha256:d.archive_sha256,manifest:d.manifest}}),hash,onError:e=>errors.push(e.message),replace:r=>{view.bundle={files:r.files};view.resultRevision++;},restore:b=>{view.bundle=b;view.resultRevision++;}};
 return {wire,view,errors,options,file:{name:'original.zip',size:d.archive_bytes}};
}
test('four scopes share encoded original for contexts windows and both retained and incoming sources',async()=>{
 const saved=text.prepare;let calls=0;text.prepare=s=>{calls++;return saved(s)};
 try{for(const scope of ['music','storyboard','lyrics','audio']){const s=setup(scope),c=importer.createController(s.options),old=structuredClone(s.view.bundle),media=s.view.media[0];await c.inspect(s.file);const n=calls,a=c.textSearch('full.txt','incoming',{query:'記憶點',include_context:true});assert.equal(calls,n+1);assert.equal(c.textWindow('full.txt','incoming',a.matches[0].start_byte).text.startsWith('記憶點'),true);c.textSearch('full.txt','incoming',{query:'🎵',include_context:true});assert.equal(calls,n+1);assert.equal(c.textSearch('full.txt','before',{query:'記憶點',include_context:true}).context.items[0].text,old.files['full.txt']);assert.deepEqual(s.view.bundle,old);assert.equal(s.view.media[0],media);c.cancel();}}
 finally{text.prepare=saved;}
});
function dom(s){const ids=[...fs.readFileSync('web/index.html','utf8').matchAll(/id="(delivery-[^"]+)"/g)].map(v=>v[1]),nodes={};for(const id of ids)nodes[id]={value:'',open:false,replaceChildren(){this.children=[];this.value=''},append(v){(this.children||=[]).push(v)}};nodes['delivery-reader-side'].value='incoming';const ctx={MusicDeliveryContext:context,MusicDeliveryText:text,MusicDeliverySearch:search,MusicDeliveryImport:importer};for(const file of ['delivery-text-dom.js','delivery-search-dom.js','delivery-import-dom.js'])vm.runInNewContext(fs.readFileSync('web/'+file,'utf8'),ctx);const c=ctx.MusicDeliveryImportDom.createAdapter({getElementById:id=>nodes[id],createElement:()=>({})},s.options);return {c,nodes};}
test('DOM result labels show original context and selecting preserves both context and reader then clears on edits',async()=>{
 const s=setup(),{c,nodes:n}=dom(s);await c.inspect(s.file);n['delivery-reader'].open=true;n['delivery-review-file'].value='full.txt';n['delivery-review-file'].onchange();n['delivery-search-query'].value='記憶點';n['delivery-search-find'].onclick();assert.equal(n['delivery-search-context-box'].hidden,true);assert.match(n['delivery-search-match'].children[1].textContent,/【記憶點】/);assert.equal(n['delivery-search-match'].onchange({target:{value:'0'}}),true);assert.equal(n['delivery-search-context-box'].hidden,false);assert.ok(n['delivery-search-context'].value.includes('🎵記憶點乙'));assert.ok(n['delivery-reader-content'].value.startsWith('記憶點'));const original=n['delivery-search-context'].value;n['delivery-search-query'].value='🎵';n['delivery-search-query'].oninput({target:n['delivery-search-query']});assert.equal(n['delivery-search-context-box'].hidden,true);assert.equal(n['delivery-search-context'].value,'');assert.ok(original.length>0);n['delivery-search-find'].onclick();n['delivery-search-match'].onchange({target:{value:'0'}});s.view.revision++;c.refresh();assert.equal(n['delivery-search-context'].value,'');assert.equal(n['delivery-search-context-box'].hidden,true);c.cancel();
});
test('DOM selected literal context clears on next batch source empty apply and undo with original preserved',async()=>{
 const s=setup(),{c,nodes:n}=dom(s),old=structuredClone(s.view.bundle);await c.inspect(s.file);n['delivery-reader'].open=true;n['delivery-review-file'].value='full.txt';n['delivery-review-file'].onchange();n['delivery-search-query'].value='<script>literal</script>';n['delivery-search-find'].onclick();n['delivery-search-match'].onchange({target:{value:'0'}});assert.ok(n['delivery-search-context'].value.includes('<script>literal</script>'));n['delivery-search-more'].onclick();assert.equal(n['delivery-search-context'].value,'');assert.match(n['delivery-search-match'].children[1].textContent,/第21筆/);n['delivery-reader-side'].value='before';n['delivery-reader-side'].onchange();assert.equal(n['delivery-search-context-box'].hidden,true);n['delivery-reader-side'].value='incoming';n['delivery-reader-side'].onchange();n['delivery-review-file'].value='empty.txt';n['delivery-review-file'].onchange();n['delivery-search-find'].onclick();assert.equal(n['delivery-search-match'].disabled,true);assert.equal(n['delivery-search-context'].value,'');assert.equal(c.apply(),true);assert.equal(c.undo(),true);assert.deepEqual(s.view.bundle,old);assert.equal(n['delivery-search-context-box'].hidden,true);
});
