// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('../web/storyboard-shot-review.js'),W=require('../web/storyboard-readiness.js'),V=require('../musiclab/assets/delivery-versions.js');
const panel=()=>{const p=JSON.parse(fs.readFileSync('examples/unfinished-storyboard-review.json','utf8')).panel;p.shots=Array.from({length:120},()=>Object.fromEntries(Object.keys(p.shots[0]).map(k=>[k,''])));return p;};
const payload=()=>({panel:panel(),row:100});
const wire=p=>{const data=S.report(p);return {data,files:{'storyboard-shot-review.json':JSON.stringify(data,null,2)+'\n','storyboard-shot-review.md':S.markdown(data)},meta:{version:V.current,protocol_version:1,needs_review:true}};};
test('later selected row has all original issues beyond retained whole details',()=>{const p=payload(),before=structuredClone(p),d=S.report(p);assert.equal(d.issue_count,11);assert.equal(d.row,100);assert.equal(d.total_shots,120);assert.ok(d.issues.every(i=>i.row===100));assert.ok(!W.report(p.panel).issues.some(i=>i.row===100));assert.deepEqual(p,before);});
test('invalid rows and extra payload values are rejected without correction',()=>{for(const row of [true,0,-1,1.5,121,null,'100',NaN,Infinity])assert.throws(()=>S.report({...payload(),row}));assert.throws(()=>S.report({...payload(),extra:1}));});
test('input JSON value boundaries do not trust sparse or overridden collections',()=>{for(const decorate of [p=>delete p.shots[0],p=>p.shots.map=()=>[],p=>p.shots[Symbol.iterator]=function*(){},p=>p.shots[0].visual='\ud800']){const p=payload();decorate(p.panel);assert.throws(()=>S.report(p));}});
test('complete response matches source, full JSON, markdown and current metadata',()=>{const p=payload(),w=wire(p);assert.deepEqual(S.checkedResult(p,w).data,w.data);for(const mutate of [v=>v.data.row=1,v=>v.data.source.shot.visual='other',v=>v.meta.needs_review=false,v=>v.meta.version='unknown',v=>v.files['extra.txt']='',v=>v.files['storyboard-shot-review.md']+='changed',v=>v.files['storyboard-shot-review.json']='{"duplicate":1,"duplicate":2}',v=>v.data.issues[0].extra=1]){const bad=structuredClone(w);mutate(bad);assert.throws(()=>S.checkedResult(p,bad));assert.deepEqual(S.checkedResult(p,w).data,w.data);}});
function setup(){let value={panel:panel(),ids:Array.from({length:120},(_,i)=>`row-${i+1}`),selectedId:'row-100'},view;const c=S.createController({capture:()=>value,onState:v=>view=v});return {c,get value(){return value;},get view(){return view;}};}
test('local source allows irrelevant shot text edits, rejects selected edits and recovers exact original',()=>{const s=setup();s.c.check();const issue=s.c.locate(0);assert.equal(issue.row,100);s.value.panel.shots[0].visual='elsewhere';assert.equal(s.c.refresh().stale,false);s.value.panel.shots[99].visual='selected';assert.equal(s.c.refresh().stale,true);assert.equal(s.c.locate(0),null);s.value.panel.shots[99].visual='';assert.equal(s.c.refresh().stale,false);assert.equal(s.c.locate(0).row,100);});
test('selection and identity order changes stop old location even for identical text',()=>{const s=setup();s.c.check();s.value.selectedId='row-101';assert.equal(s.c.refresh().stale,true);s.value.selectedId='row-100';assert.equal(s.c.refresh().stale,false);[s.value.ids[0],s.value.ids[1]]=[s.value.ids[1],s.value.ids[0]];assert.equal(s.c.locate(0),null);});
test('motif reference context and fields remain part of local source',()=>{const s=setup();s.c.check();s.value.panel.motifs[0].meaning+='changed';assert.equal(s.c.refresh().stale,true);s.value.panel.motifs[0].meaning=s.view.report.source.motifs[0].meaning;s.value.panel.fields['mv-title']+='changed';assert.equal(s.c.locate(0),null);});
test('async request proof retains IDs privately and refuses altered identity',()=>{const s=setup(),p=s.c.payload();assert.equal(s.c.isCurrent(p),true);assert.deepEqual(Object.keys(p),['panel','row']);assert.equal(s.c.isCurrent(structuredClone(p)),false);s.value.panel.shots[0].visual='elsewhere';assert.equal(s.c.isCurrent(p),true);[s.value.ids[0],s.value.ids[1]]=[s.value.ids[1],s.value.ids[0]];assert.equal(s.c.isCurrent(p),false);});
test('old revision callbacks and failed checks preserve latest report',()=>{const s=setup(),before=s.c.check();s.c.check();assert.equal(s.c.locate(0,before.revision),null);const latest=structuredClone(s.view);s.value.selectedId='unknown';assert.throws(()=>s.c.check());assert.deepEqual(s.view,latest);s.c.clear();assert.equal(s.c.locate(0),null);});
test('invalid IDs never permit ambiguous original row selection',()=>{for(const ids of [['duplicate','duplicate'],['',...Array(119).fill('id')],Array(120).fill('row-1')]){const s=setup();s.value.ids=ids;assert.throws(()=>s.c.check());}});
test('zero selected issues do not imply timing or other row acceptance',()=>{const p=payload();p.panel.motifs=p.panel.motifs.slice(0,1);p.panel.shots[99]=Object.fromEntries(Object.keys(p.panel.shots[99]).map(k=>[k,'原文']));Object.assign(p.panel.shots[99],{motif_id:'motif-1',screen_direction:'neutral',start:'bad',end:'bad'});const w=wire(p);assert.equal(w.data.issue_count,0);assert.equal(w.meta.needs_review,true);assert.ok(w.data.review_notes[0].includes('其他鏡頭及全片時間'));});
test('1000th original shot remains bounded and selected source contains only one shot',()=>{const p=payload();p.panel.shots=Array.from({length:1000},()=>structuredClone(p.panel.shots[0]));p.row=1000;const d=S.report(p);assert.equal(d.issues.length,11);assert.equal(d.row,1000);assert.ok(!Object.hasOwn(d.source,'shots'));});
test('oversize full JSON is refused while the previous checked reply remains reusable',()=>{const p=payload(),before=wire(p);const large=payload();large.panel.shots[99].visual='a'.repeat(256*1024);assert.throws(()=>S.checkedResult(large,wire(large)));assert.deepEqual(S.checkedResult(p,before).data,before.data);});
