// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),M=require('../web/backup-download.js'),D=require('../web/backup-download-dom.js');
const id=n=>'draft-'+n.repeat(32),raw=()=>new TextEncoder().encode('zip').buffer,sha=b=>crypto.createHash('sha256').update(new Uint8Array(b)).digest('hex');
const descriptor=(selection='selected',count=1)=>({backup_schema_version:1,backup_sha256:sha(raw()),bytes:3,entry_count:count,selection,download_url:'/api/drafts/backup/download/'+'1'.repeat(32)});
const later=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {resolve,reject,promise};};
function setup(other={}){const sent=[],errors=[],requests=[];const c=M.createController({prepare:async p=>{requests.push(p);return descriptor();},read:async()=>raw(),hash:async b=>sha(b),send:()=>true,onSent:(d,p)=>sent.push({d,p}),onError:e=>errors.push(e.message),...other});return {c,sent,errors,requests};}
test('selection requests are strict isolated IDs, sorted without changing the original',()=>{const p={ids:[id('2'),id('1')]},copy=M.request(p);assert.deepEqual(copy,{ids:[id('1'),id('2')]});copy.ids.push(id('3'));assert.deepEqual(p.ids,[id('2'),id('1')]);assert.deepEqual(M.request({}),{});});
test('selection request refuses unknown paths duplicate IDs empty sparse arrays hidden symbols and getters',()=>{for(const p of [null,[],{ids:[]},{ids:[id('1'),id('1')]},{ids:['../x']},{ids:[id('a').toUpperCase()]},{ids:[id('1')],path:'x'},{ids:new Array(1)},{ids:Array(1001).fill(id('1'))}])assert.throws(()=>M.request(p));let touched=0;for(const p of [Object.defineProperty({},'ids',{enumerable:true,get(){touched++;return [id('1')];}}),Object.defineProperty({},'extra',{value:1}),{[Symbol('ids')]:[id('1')]}])assert.throws(()=>M.request(p));const a=[id('1')];Object.defineProperty(a,'0',{enumerable:true,get(){touched++;return id('1');}});assert.throws(()=>M.request({ids:a}));assert.equal(touched,0);});
test('selected download sends a copied click-time request and checks selection and exact count',async()=>{const p={ids:[id('1')]},pending=later(),entered=later(),h=setup({prepare:arg=>{entered.resolve(arg);return pending.promise;}});const work=h.c.download(p),copy=await entered.promise;copy.ids[0]=id('3');p.ids[0]=id('2');pending.resolve(descriptor());assert.equal(await work,true);assert.deepEqual(h.sent[0].p,{ids:[id('1')]});for(const d of [descriptor('all'),descriptor('selected',0),descriptor('selected',2)]){const v=setup({prepare:async()=>d});assert.equal(await v.c.download({ids:[id('1')]}),false);assert.equal(v.sent.length,0);assert.equal(v.errors.length,1);}});
test('invalid request never starts I/O and whole-library default keeps its existing payload',async()=>{let calls=0;const h=setup({prepare:async p=>{calls++;assert.deepEqual(p,{});return descriptor('all',3);}});assert.equal(await h.c.download({ids:[]}),false);assert.equal(calls,0);assert.equal(await h.c.download(),true);assert.deepEqual(h.sent[0].p,{});});
test('selected prepare read and hash cancellation suppress late replies and newer all download stays current',async()=>{for(const phase of ['prepare','read','hash']){const pending=later(),entered=later();let call=0;const h=setup({prepare:async p=>p.ids?descriptor():descriptor('all',3),[phase]:(...args)=>{if(++call===1){entered.resolve();return pending.promise;}return phase==='prepare'?descriptor('all',3):phase==='read'?raw():sha(raw());}});const old=h.c.download({ids:[id('1')]});await entered.promise;assert.equal(await h.c.download(),false);h.c.cancel();assert.equal(await h.c.download(),true);pending.resolve(phase==='prepare'?descriptor():phase==='read'?raw():sha(raw()));assert.equal(await old,false);assert.equal(h.sent.length,1);assert.equal(h.sent[0].d.selection,'all');assert.equal(h.errors.length,0);}});
function dom(){const nodes=Object.fromEntries(['backup-download','backup-download-cancel','backup-save-selected','backup-verify-file','backup-verify-source','backup-verify-note','backup-verify-cancel'].map(k=>[k,{files:[],dataset:{},value:'',textContent:'',disabled:false}]));let selected=id('1'),enabled=true,serial=0;const requests=[],notes=[],pending=later(),listeners=new Map(),timers=[];let delay=false;const document={getElementById:k=>nodes[k],body:{append(){}},createElement:()=>({click(){},remove(){}})};const adapter=D.createAdapter(document,{prepare:async(signal,p)=>{requests.push({signal,p});if(delay)await pending.promise;return descriptor(p.ids?'selected':'all',p.ids?1:3);},maximum:()=>M.maxBytes,allowed:()=>enabled,verificationAllowed:()=>enabled,captureSelected:()=>selected,say:t=>notes.push(t),events:{addEventListener:(n,f)=>{if(!listeners.has(n))listeners.set(n,new Set());listeners.get(n).add(f);},removeEventListener:(n,f)=>listeners.get(n)?.delete(f)},hash:async b=>sha(b),fetch:async()=>new Response(raw(),{headers:{'Content-Length':'3','Content-Type':'application/octet-stream'}}),byteOptions:{url:{createObjectURL:()=>String(++serial),revokeObjectURL(){}},BlobType:Blob,schedule:f=>{timers.push(f);return timers.length;},cancel(){}}});return {nodes,adapter,requests,notes,pending,set selected(v){selected=v;},set enabled(v){enabled=v;},set delay(v){delay=v;},finish(){for(const f of timers.splice(0))f();}};}
test('native selected action captures one version once even if the chooser later changes',async()=>{const h=dom();h.delay=true;const old=h.nodes['backup-save-selected'].onclick();await Promise.resolve();assert.equal(h.nodes['backup-save-selected'].disabled,true);h.selected=id('2');h.adapter.refresh();h.pending.resolve();assert.equal(await old,true);assert.deepEqual(h.requests[0].p,{ids:[id('1')]});assert.match(h.notes.at(-1),new RegExp(id('1')));assert.match(h.nodes['backup-verify-source'].textContent,/1 版/);assert.equal(h.nodes['backup-save-selected'].disabled,false);h.finish();h.adapter.dispose();});
test('selected control disables on missing choice busy disabled library and disposal without changing all flow',async()=>{const h=dom();h.selected=null;h.adapter.refresh();assert.equal(h.nodes['backup-save-selected'].disabled,true);assert.equal(h.nodes['backup-save-selected'].onclick(),false);assert.equal(h.requests.length,0);h.selected=id('1');h.enabled=false;h.adapter.refresh();assert.equal(h.nodes['backup-save-selected'].disabled,true);assert.equal(h.nodes['backup-save-selected'].onclick(),false);h.enabled=true;h.adapter.refresh();assert.equal(await h.nodes['backup-download'].onsubmit({preventDefault(){}}),true);assert.deepEqual(h.requests[0].p,{});assert.match(h.nodes['backup-verify-source'].textContent,/3 版/);h.finish();h.adapter.dispose();assert.equal(h.nodes['backup-save-selected'].onclick,null);assert.equal(h.nodes['backup-save-selected'].disabled,true);});
test('selected cancel aborts its own request and preserves prior whole-library proof',async()=>{const h=dom();assert.equal(await h.nodes['backup-download'].onsubmit({preventDefault(){}}),true);h.finish();const source=h.nodes['backup-verify-source'].textContent;h.delay=true;const work=h.nodes['backup-save-selected'].onclick();await Promise.resolve();h.nodes['backup-download-cancel'].onclick();assert.equal(h.requests[1].signal.aborted,true);const note=h.notes.at(-1);h.pending.resolve();assert.equal(await work,false);assert.equal(h.nodes['backup-verify-source'].textContent,source);assert.equal(h.notes.at(-1),note);h.adapter.dispose();});
