// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const review=require('../web/delivery-review.js'),importer=require('../web/delivery-import.js'),pack=require('../web/delivery-package.js');
const hash=async raw=>crypto.createHash('sha256').update(raw).digest('hex');
const fs=require('node:fs'),vm=require('node:vm');
const pair=scope=>[{scope,files:{'changed.md':'原文\r\n','empty.txt':'','removed.txt':'移除','same.html':'<script>literal()</script>'}},{scope,files:{'added.json':'{}','changed.md':'原文\n','empty.txt':'','same.html':'<script>literal()</script>'}}];
const fixtures=JSON.parse(execFileSync('python',['-X','utf8','-c',`import json
from musiclab.delivery_review import compare
rows=[]
for scope in ['music','storyboard','lyrics','audio']:
 old={'scope':scope,'files':{'changed.md':'原文\\r\\n','empty.txt':'','removed.txt':'移除','same.html':'<script>literal()</script>'}}
 new={'scope':scope,'files':{'added.json':'{}','changed.md':'原文\\n','empty.txt':'','same.html':'<script>literal()</script>'}}
 rows.append({'old':old,'new':new,'expected':compare(old,new)})
print(json.dumps(rows,ensure_ascii=False))`],{encoding:'utf8',timeout:10000}));
test('Python and browser exact-name comparison agrees across four scopes and preserves sources',async()=>{for(const row of fixtures){const saved=structuredClone(row);assert.deepEqual(await review.compare(row.old,row.new,hash),row.expected);assert.deepEqual(row,saved);}});
test('line ending change, literal HTML and empty text are distinct exact-byte cases',async()=>{const [old,newer]=pair('music'),d=await review.compare(old,newer,hash);assert.deepEqual(d.counts,{added:1,changed:1,removed:1,unchanged:2});assert.equal(d.files.find(x=>x.name==='empty.txt').incoming.bytes,0);assert.equal(d.files.find(x=>x.name==='changed.md').status,'changed');});
test('empty and same baselines yield complete add and unchanged summaries',async()=>{const [old,newer]=pair('lyrics');assert.equal((await review.compare({scope:'lyrics',files:{}},newer,hash)).counts.added,4);assert.equal((await review.compare(old,old,hash)).counts.unchanged,4);});
test('same text with a renamed or recased file remains add and remove',async()=>{const d=await review.compare({scope:'music',files:{'A.md':'same'}},{scope:'music',files:{'a.md':'same'}},hash);assert.deepEqual(d.counts,{added:1,changed:0,removed:1,unchanged:0});});
test('baseline shape, capacity, Unicode and file name bounds match existing delivery rules',async()=>{for(const value of [null,[],{}, {scope:'music',files:{},path:'outside'},{scope:'music',files:{'x.wav':'x'}},{scope:'music',files:{'x.md':'\ud800'}},{scope:'music',files:{'x.md':'x'.repeat(pack.maxSource+1)}},{scope:'music',files:Object.fromEntries(Array.from({length:65},(_,i)=>[i+'.txt','x']))}])assert.throws(()=>review.baseline(value));await assert.rejects(review.compare({scope:'music',files:{}},{scope:'audio',files:{}},hash));});
test('128 union rows retain every added and removed name',async()=>{const old={scope:'storyboard',files:Object.fromEntries(Array.from({length:64},(_,i)=>['old'+i+'.txt','舊']))},next={scope:'storyboard',files:Object.fromEntries(Array.from({length:64},(_,i)=>['new'+i+'.txt','新']))};const d=await review.compare(old,next,hash);assert.equal(d.files.length,128);assert.equal(d.counts.added,64);assert.equal(d.counts.removed,64);});
test('bounded excerpt preserves full small text, missing versus empty and complete surrogate pairs',()=>{assert.deepEqual(review.excerpt(''),{text:'',present:true,truncated:false});assert.deepEqual(review.excerpt(null),{text:'',present:false,truncated:false});assert.deepEqual(review.excerpt('a💡b',2),{text:'a',present:true,truncated:true});assert.equal(review.excerpt('a'.repeat(32768)+'💡').text.length,32768);assert.throws(()=>review.excerpt('x',0));});
test('bounded original line-ending counts distinguish textarea-normalized display without splitting CRLF',()=>{assert.deepEqual(review.lineEndings('a\r\nb\nc\rd'),{crlf:1,lf:1,cr:1});assert.deepEqual(review.lineEndings(''),{crlf:0,lf:0,cr:0});assert.equal(review.lineEndings(null),null);assert.throws(()=>review.lineEndings({}));});
test('default digest is available without a caller-specific hash function',async()=>{const [old,next]=pair('audio');assert.deepEqual(await review.compare(old,next),await review.compare(old,next,hash));});
async function wire(files){const manifest=await pack.manifest({scope:'music',label:'合成對照',files},hash);const sha='a'.repeat(64);return{selected:{bytes:2000,sha256:sha,manifest},wire:{files,data:{format:'zoe-delivery-inspection',schema_version:1,archive_bytes:2000,archive_sha256:sha,manifest},meta:{version:pack.version,protocol_version:1,needs_review:true}}};}
function setup(read,custom={}){const [old]=pair('music'),view={scope:'music',revision:1,resultRevision:1,bundle:{files:old.files,note:'current',dirty:false},busy:false,media:[{}]};let replaced=0;const c=importer.createController({capture:()=>view,read,hash,replace:r=>{replaced++;view.bundle={files:r.files};view.resultRevision++},restore:b=>{view.bundle=b;view.resultRevision++},...custom});return{view,c,replaced:()=>replaced};}
const selected={name:'selected.zip',size:2000};
test('preview includes removed and changed original text before any explicit apply',async()=>{const [,next]=pair('music'),{view,c,replaced}=setup(()=>wire(next.files));await c.inspect(selected);assert.equal(replaced(),0);assert.deepEqual(c.status().comparison.counts,{added:1,changed:1,removed:1,unchanged:2});assert.equal(c.filePreview('changed.md').before.text,'原文\r\n');assert.equal(c.filePreview('changed.md').incoming.text,'原文\n');assert.equal(c.filePreview('removed.txt').incoming.present,false);assert.equal(c.filePreview('empty.txt').incoming.present,true);assert.equal(c.filePreview('unknown.txt'),null);const copy=c.status().comparison;copy.files.length=0;assert.equal(c.status().comparison.files.length,5);assert.equal(view.bundle.files['removed.txt'],'移除');});
test('apply still retains complete large incoming text and scoped undo restores baseline',async()=>{const next={'large.md':'甲'.repeat(40000)},{view,c}=setup(()=>wire(next));await c.inspect(selected);assert.equal(c.filePreview('large.md').incoming.truncated,true);assert.equal(c.apply(),true);assert.equal(view.bundle.files['large.md'].length,40000);view.revision++;assert.equal(c.undo(),true);assert.equal(view.bundle.files['removed.txt'],'移除');});
test('cancel and a newer selection clear comparison and original text access',async()=>{const [,next]=pair('music'),{c}=setup(()=>wire(next.files));await c.inspect(selected);c.cancel();assert.equal(c.status().comparison,null);assert.equal(c.filePreview('changed.md'),null);await c.inspect(selected);await c.inspect({name:'bad.txt',size:10});assert.equal(c.status().comparison,null);});
test('changes during asynchronous baseline comparison reject the whole preview',async()=>{const [,next]=pair('music');let entered,release,n=0;const ready=new Promise(r=>entered=r),hold=new Promise(r=>release=r);const sample=await wire(next.files);const {view,c,replaced}=setup(async()=>sample,{hash:async raw=>{if(++n===5){entered();await hold;}return hash(raw)}});const work=c.inspect(selected);await ready;view.revision++;release();assert.equal(await work,false);assert.equal(c.status().pending,false);assert.equal(replaced(),0);});
test('late comparison cannot replace the newer selected ZIP summary or original preview',async()=>{let enter,release,n=0;const ready=new Promise(r=>enter=r),hold=new Promise(r=>release=r),first=await wire({'first.md':'first'}),second=await wire({'second.md':'second'});const {c}=setup(async f=>f.name==='first.zip'?first:second,{hash:async raw=>{if(++n===2){enter();await hold;}return hash(raw)}});const work=c.inspect({name:'first.zip',size:2000});await ready;assert.equal(await c.inspect({name:'second.zip',size:2000}),true);const current=c.status().comparison;release();assert.equal(await work,false);assert.deepEqual(c.status().comparison,current);assert.equal(c.filePreview('second.md').incoming.text,'second');assert.equal(c.filePreview('first.md'),null);});
test('DOM comparison selects changed content first, shows removed and literal files, then clears cancelled text',async()=>{const ids=['delivery-import-file','delivery-import-preview','delivery-import-apply','delivery-import-undo','delivery-import-note','delivery-import-files','delivery-import-source','delivery-import-cancel','delivery-review-file','delivery-review-summary','delivery-review-before','delivery-review-incoming','delivery-review-before-note','delivery-review-incoming-note','delivery-reader','delivery-reader-side','delivery-reader-content','delivery-reader-note','delivery-reader-first','delivery-reader-previous','delivery-reader-next','delivery-original-download','delivery-original-note','delivery-report-json','delivery-report-md','delivery-report-form','delivery-report-name','delivery-report-content'],elements={};for(const id of ids)elements[id]={value:'',replaceChildren(){this.children=[];this.value=''},append(item){(this.children||=[]).push(item)}};const [old,next]=pair('music'),view={scope:'music',revision:1,resultRevision:1,bundle:{files:old.files},busy:false,media:[]};const context={MusicDeliveryImport:importer};vm.runInNewContext(fs.readFileSync('web/delivery-text-dom.js','utf8'),Object.assign(context,{MusicDeliveryText:require('../web/delivery-text.js')}));vm.runInNewContext(fs.readFileSync('web/delivery-import-dom.js','utf8'),context);const c=context.MusicDeliveryImportDom.createAdapter({getElementById:id=>elements[id],createElement:()=>({})},{capture:()=>view,read:()=>wire(next.files),hash,replace:()=>{},restore:()=>{}});await c.inspect(selected);assert.equal(elements['delivery-review-file'].value,'changed.md');assert.match(elements['delivery-review-before-note'].textContent,/CRLF 1／LF 0/);assert.match(elements['delivery-review-incoming-note'].textContent,/CRLF 0／LF 1/);elements['delivery-review-file'].value='removed.txt';elements['delivery-review-file'].onchange();assert.equal(elements['delivery-review-before'].value,'移除');assert.equal(elements['delivery-review-incoming-note'].textContent,'ZIP成果沒有這個檔案');elements['delivery-review-file'].value='same.html';elements['delivery-review-file'].onchange();assert.equal(elements['delivery-review-incoming'].value,'<script>literal()</script>');c.cancel();assert.equal(elements['delivery-review-incoming'].value,'');assert.equal(elements['delivery-review-file'].disabled,true);});
