// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../web/editor-keys.js');
const gesture=(extra={})=>({key:'ArrowUp',altKey:true,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:38,...extra});
const source=(n=3)=>({ids:Array.from({length:n},(_,i)=>'row-'+i),visible:true,busy:false});
test('only unmodified Alt arrows request movement; normal editing composition repeat and other shortcuts retain their behavior',()=>{assert.equal(P.delta(gesture()),-1);assert.equal(P.delta(gesture({key:'ArrowDown',keyCode:40})),1);for(const edit of [{altKey:false},{ctrlKey:true},{metaKey:true},{shiftKey:true},{repeat:true},{isComposing:true},{keyCode:229},{key:'ArrowLeft'},{key:'Enter'}])assert.equal(P.delta(gesture(edit)),0);for(const edit of [{altKey:1},{keyCode:NaN},{keyCode:-1},{keyCode:256},{extra:true}])assert.throws(()=>P.delta(gesture(edit)),/狀態/);});
test('bounded proposals preserve every input ID and move only one neighboring identity in all three lists',()=>{for(const [list,n] of [['arrangement',40],['shots',1000],['cues',10000]]){const value=source(n),before=structuredClone(value),plan=P.proposal(list,value,'row-'+(n-1),gesture());assert.equal(plan.index,n-2);assert.equal(plan.after[n-2],'row-'+(n-1));assert.equal(plan.after[n-1],'row-'+(n-2));assert.deepEqual(value,before);plan.before[0]='changed';assert.deepEqual(value,before);assert.equal(P.proposal(list,value,'row-0',gesture()),null);assert.equal(P.proposal(list,value,'row-'+(n-1),gesture({key:'ArrowDown'})),null);}const sparse=source();delete sparse.ids[1];assert.throws(()=>P.proposal('cues',sparse,'row-2',gesture()));assert.throws(()=>P.proposal('cues',source(),'missing',gesture()));});
function setup(){let value=source(),captures=0,consumes=0,moves=0,finished=0;const errors=[];const c=P.createController({allowed:()=>value.visible&&!value.busy,capture:()=>{captures++;return value;},moveTarget:plan=>{moves++;value.ids=[...plan.after];return true;},onMoved:()=>finished++,onError:e=>errors.push(e.message)});return{c,errors,get value(){return value},set value(v){value=v},get counts(){return {captures,consumes,moves,finished}},consume:()=>{consumes++;return true;}};}
test('ignored hidden busy disposed and unknown requests cannot capture creative data consume a key or move a row',()=>{for(const kind of ['normal','busy','hidden','disposed','unknown']){const s=setup();if(kind==='busy')s.value.busy=true;if(kind==='hidden')s.value.visible=false;if(kind==='disposed')s.c.dispose();assert.equal(s.c.request(kind==='unknown'?'foreign':'cues','row-1',gesture(kind==='normal'?{altKey:false}:{}),s.consume),false);assert.deepEqual(s.counts,{captures:0,consumes:0,moves:0,finished:0});assert.equal(s.errors.length,kind==='unknown'?1:0);}});
test('metadata race before consumption and a change during consumption stop the writer without rollback',()=>{for(const phase of ['capture','consume','noncancelable']){let value=source(),reads=0,writes=0,consumes=0;const c=P.createController({allowed:()=>true,capture:()=>{reads++;if(phase==='capture'&&reads===2)value.ids.reverse();return value;},moveTarget:()=>{writes++;return true;}});assert.equal(c.request('cues','row-1',gesture(),()=>{consumes++;if(phase==='consume')value.ids.reverse();return phase!=='noncancelable';}),false);assert.equal(writes,0);assert.equal(consumes,phase==='capture'?0:1);}});
test('confirmed movement uses isolated plans and checks actual ordered metadata before notifying focus',()=>{const s=setup();assert.equal(s.c.request('shots','row-1',gesture(),s.consume),true);assert.deepEqual(s.value.ids,['row-1','row-0','row-2']);assert.deepEqual(s.counts,{captures:4,consumes:1,moves:1,finished:1});assert.deepEqual(s.errors,[]);});
test('false writer and mismatched actual-after never notify success or undo external changes',()=>{for(const mode of ['false','wrong-order','hidden','mutated-plan']){const value=source();let finished=0;const c=P.createController({allowed:()=>true,capture:()=>value,moveTarget:plan=>{if(mode==='false')return false;value.ids=mode==='wrong-order'?['row-2','row-1','row-0']:[...plan.after];if(mode==='hidden')value.visible=false;if(mode==='mutated-plan'){plan.after.reverse();value.ids=[...plan.after];}return true;},onMoved:()=>finished++});assert.equal(c.request('cues','row-1',gesture(),()=>true),false);assert.equal(finished,0);if(mode==='wrong-order')assert.deepEqual(value.ids,['row-2','row-1','row-0']);}});
