// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),P=require('../web/shot-field-position.js');
test('offscreen camera field is placed below the fixed toolbar and above viewport bottom',()=>{const v={top:912,bottom:973,height:720,coverBottom:268},offset=P.scrollOffset(v);assert.ok(offset>0);assert.ok(v.top-offset>=280);assert.ok(v.bottom-offset<=708);});
test('returning to an earlier field covered by the toolbar moves it into the remaining viewport',()=>{const v={top:35,bottom:77,height:844,coverBottom:350},offset=P.scrollOffset(v);assert.ok(offset<0);assert.ok(v.top-offset>=362);assert.ok(v.bottom-offset<=832);});
test('already visible fields do not scroll and original metadata stays unchanged',()=>{const v=Object.freeze({top:350,bottom:410,height:720,coverBottom:268});assert.equal(P.scrollOffset(v),0);});
test('a taller field reveals its start without pretending the whole field fits',()=>{const v={top:900,bottom:1500,height:720,coverBottom:268},offset=P.scrollOffset(v);assert.equal(v.top-offset,280);assert.ok(v.bottom-offset>720);});
test('a toolbar outside the viewport leaves the normal viewport available',()=>{const v={top:900,bottom:960,height:500,coverBottom:0},offset=P.scrollOffset(v);assert.ok(v.top-offset>=12);assert.ok(v.bottom-offset<=488);});
test('invalid bounds, unknown metadata and nonfinite coordinates are refused',()=>{for(const change of [v=>v.top=Infinity,v=>v.height=0,v=>v.bottom=0,v=>v.height=10000001,v=>v.extra=1,v=>v.top='5']){const v={top:912,bottom:973,height:720,coverBottom:268};change(v);assert.throws(()=>P.scrollOffset(v));}});
test('runtime accessor or hidden coordinate fields are refused without getter reads',()=>{let reads=0;const v={top:912,bottom:973,height:720,coverBottom:268};Object.defineProperty(v,'top',{enumerable:true,get(){reads++;return 912;}});assert.throws(()=>P.scrollOffset(v));assert.equal(reads,0);const h={top:912,bottom:973,height:720,coverBottom:268};Object.defineProperty(h,'extra',{value:1});assert.throws(()=>P.scrollOffset(h));});
function actual(){const text=fs.readFileSync('web/app.js','utf8'),start=text.indexOf('function focusShot('),end=text.indexOf("$('shots-collapse').onclick",start);let rectangle={top:912,bottom:973},focused=null,scrolled=[];const details={open:false},field={value:'unchanged',focus:v=>focused=v,getBoundingClientRect:()=>rectangle},summary={focus:v=>focused=v},article={querySelector:s=>s==='details'?details:s==='summary'?summary:field,scrollIntoView(){}};
 const context={$:()=>({children:[article]}),document:{querySelector:()=>({getBoundingClientRect:()=>({top:8,bottom:268})})},window:{innerHeight:720,scrollBy:v=>{scrolled.push(v);rectangle={top:rectangle.top-v.top,bottom:rectangle.bottom-v.top};}},MusicShotFieldPosition:P};vm.runInNewContext(text.slice(start,end),context);return {...context,details,field,scrolled,get rectangle(){return rectangle;},get focused(){return focused;}};}
test('actual shared focus helper reveals the field, opens the shot and keeps its value',()=>{const s=actual();s.focusShot(0,'camera');assert.equal(s.details.open,true);assert.equal(s.field.value,'unchanged');assert.equal(s.focused.preventScroll,true);assert.equal(s.scrolled.length,1);assert.ok(s.rectangle.top>=280&&s.rectangle.bottom<=708);});
test('summary focus and a missing shot keep the original card navigation without field scrolling',()=>{const s=actual();s.focusShot(0);assert.equal(s.scrolled.length,0);s.focusShot(100,'camera');assert.equal(s.scrolled.length,0);});
