// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../web/draft-compare.js'),S=require('../web/draft-compare-download.js'),C=require('../web/draft-compare-controller.js'),D=require('../web/draft-compare-dom.js'),T=require('../web/text-download.js');
const root=path.resolve(__dirname,'..');
function payload(){const a=JSON.parse(fs.readFileSync(path.join(root,'examples/draft-comparison-baseline.json'),'utf8')),b=structuredClone(a);b.panels.music.fields['music-title']='原字串\r\n🎵 <img src=x>';return {baseline:a,current:b};}
test('select preserves the complete owned report, literal Unicode and fixed file names without modifying it',async()=>{const report=await P.compare(payload()),before=structuredClone(report),j=S.select(report,'json'),m=S.select(report,'markdown');assert.equal(j.name,'draft-comparison.json');assert.equal(m.name,'draft-comparison.md');assert.deepEqual(JSON.parse(j.content),report);assert.equal(j.content,JSON.stringify(report,null,2)+'\n');assert.equal(m.content,P.markdown(report));assert.deepEqual(report,before);assert.ok(j.content.includes('🎵 <img src=x>'));assert.ok(!m.content.includes('<img'));});
test('complete download keeps all bounded details and counts beyond the ten-entry screen page',async()=>{const p=payload();p.current.panels.lyrics.cues=Array.from({length:250},(_,i)=>({start:'',end:'',text:`原句 ${i}`}));const report=await P.compare(p),r=JSON.parse(S.select(report,'json').content);assert.equal(r.details.length,report.details.length);assert.ok(r.details.length>10&&r.details.length<=200);assert.equal(r.details_truncated,true);assert.equal(r.panels.lyrics.collections.cues.added_rows,250);assert.ok(S.select(report,'markdown').content.includes('容量限制'));});
test('unknown formats, unknown envelopes, invalid Unicode, getters and report capacity refuse serialization',async()=>{const good=await P.compare(payload());assert.throws(()=>S.select(good,'../json'));for(const change of [x=>x.schema_version=2,x=>x.extra=true,x=>x.source.encoding='unknown',x=>x.review_notes[0]='\ud800',x=>x.details[0].fields[0].after.excerpt='x'.repeat(262144)]){const bad=structuredClone(good);change(bad);assert.throws(()=>S.select(bad,'json'));}let reads=0;const bad=structuredClone(good);Object.defineProperty(bad,'format',{enumerable:true,get(){reads++;return good.format;}});assert.throws(()=>S.select(bad,'json'));assert.equal(reads,0);});
test('download rechecks complete controller source even without an observed change event',async()=>{const p=payload(),gate={identity:{},revision:[0],media:[{}],tab:'music',allowed:true,visible:true};const c=C.create({capture:()=>p,gate:()=>gate});await c.run();let sends=0,sent=0;const errors=[];const d=T.createController({select:()=>S.select(c.read(),'json'),send:v=>{sends++;assert.deepEqual(JSON.parse(new TextDecoder().decode(v.bytes)),c.read());return true;},onSent:()=>sent++,onError:e=>errors.push(e.message)});assert.equal(d.download(),true);p.current.panels.music.fields['music-title']='後續編修';assert.equal(d.download(),false);assert.equal(sends,1);assert.equal(sent,1);assert.match(errors[0],/來源已有變更/);assert.equal(p.current.panels.music.fields['music-title'],'後續編修');});
test('gate and native media identity changes refuse download without emitting bytes',async()=>{for(const change of [g=>g.media[0]={},g=>g.identity={},g=>g.tab='audio',g=>g.allowed=false,g=>g.visible=false,g=>g.revision[0]++]){const p=payload(),gate={identity:{},revision:[0],media:[{}],tab:'music',allowed:true,visible:true},c=C.create({capture:()=>p,gate:()=>gate});await c.run();change(gate);let sends=0;const d=T.createController({select:()=>S.select(c.read(),'markdown'),send:()=>{sends++;return true;}});assert.equal(d.download(),false);assert.equal(sends,0);}});
test('sender failure does not acknowledge success or consume a retryable current report',async()=>{const p=payload(),gate={identity:{},revision:[0],media:[],tab:'music',allowed:true,visible:true},c=C.create({capture:()=>p,gate:()=>gate});await c.run();let fail=true,sent=0;const d=T.createController({select:()=>S.select(c.read(),'json'),send:()=>{if(fail)throw Error('temporary');return true;},onSent:()=>sent++});assert.equal(d.download(),false);assert.equal(sent,0);fail=false;assert.equal(d.download(),true);assert.equal(sent,1);assert.deepEqual(p,payload());});
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners=new Map();this.hidden=false;this.disabled=false;this.value='';this.textContent='';this.classList={add(){},remove(){}};this.attributes={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=[...x];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.listeners.set(k,v);}removeEventListener(k,v){if(this.listeners.get(k)===v)this.listeners.delete(k);}emit(k){return this.listeners.get(k)?.();}focus(){}}
function setup(prefix='draft'){const el=Object.fromEntries(['start','cancel','status','report','list','scope','previous','next','page','expand','collapse','open-note','kind','kind-note','row-collection','row-number','row-start','row-cancel','row-status','row-result','row-full','row-previous','row-next','row-navigation','download-json','download-markdown','download-status'].map(x=>[x,new Element()]));el.scope.value='all';const document={getElementById:id=>el[id.replace(prefix+'-compare-','')],createElement:tag=>new Element(tag),querySelector:()=>null},p=payload(),gate={identity:{},revision:[0],media:[],tab:'music',allowed:true,visible:true},sent=[],errors=[];const downloads={createController:opts=>T.createController({...opts,send:v=>{sent.push(v);return true;}})},adapter=D.bind(document,{prefix,downloads,capture:()=>p,gate:()=>gate,onError:e=>errors.push(e.message)});return {el,document,p,gate,sent,errors,adapter};}
test('both preview DOM adapters export the same complete report regardless of filter and page',async()=>{for(const prefix of ['draft','library']){const s=setup(prefix);s.p.current.panels.lyrics.cues=Array.from({length:25},(_,i)=>({start:'',end:'',text:String(i)}));const before=structuredClone(s.p);await s.el.start.emit('click');assert.equal(s.el['download-json'].disabled,false);s.el.scope.value='lyrics';s.el.scope.emit('change');s.el.next.emit('click');assert.equal(s.el['download-json'].emit('click'),true);const json=s.sent[0];assert.equal(JSON.parse(new TextDecoder().decode(json.bytes)).details.length,26);s.el.scope.value='audio';s.el.scope.emit('change');assert.equal(s.el['download-markdown'].emit('click'),true);assert.match(s.el['download-status'].textContent,/已送出/);assert.match(s.el['download-status'].textContent,/不會另存工作台草稿/);assert.deepEqual(s.p,before);assert.equal(s.errors.length,0);s.adapter.dispose();}});
test('stale clear cancel and dispose stop download and remove only owned listeners',async()=>{for(const action of ['stale','clear','cancel','dispose']){const s=setup();await s.el.start.emit('click');if(action==='stale'){s.gate.tab='audio';s.adapter.refresh();}else if(action==='cancel')s.el.cancel.emit('click');else s.adapter[action]();if(action==='clear')assert.equal(s.el['download-status'].textContent,'');assert.equal(s.el['download-json'].emit('click')||false,false);assert.equal(s.sent.length,0);s.adapter.dispose();assert.equal(s.el['download-json'].listeners.size,0);assert.equal(s.el.start.listeners.size,0);}});
test('pagehide removes download listeners and subsequent dispose remains harmless',async()=>{const previousAdd=globalThis.addEventListener,previousRemove=globalThis.removeEventListener,events=new Map();globalThis.addEventListener=(k,v)=>events.set(k,v);globalThis.removeEventListener=(k,v)=>{if(events.get(k)===v)events.delete(k);};try{const s=setup();await s.el.start.emit('click');events.get('pagehide')();s.adapter.dispose();assert.equal(s.el['download-json'].listeners.size,0);assert.equal(s.el['download-markdown'].listeners.size,0);assert.equal(events.size,0);assert.equal(s.el['download-json'].emit('click'),undefined);}finally{globalThis.addEventListener=previousAdd;globalThis.removeEventListener=previousRemove;}});
test('fixed assets and shared byte adapter load before comparison download bindings',()=>{const html=fs.readFileSync(path.join(root,'web/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'web/app.js'),'utf8'),server=fs.readFileSync(path.join(root,'music_lab_server.py'),'utf8');assert.ok(html.indexOf('/draft-compare-download.js')<html.indexOf('/draft-compare-dom.js'));for(const prefix of ['draft','library']){assert.match(html,new RegExp('id="'+prefix+'-compare-download-status"[^>]*role="status"'));assert.match(app,new RegExp("prefix:'"+prefix+"',downloads:textDownloader"));}assert.match(server,/"\/draft-compare-download.js"/);});
