// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {execFileSync}=require('node:child_process');
const R=require('../web/storyboard-readiness.js');
const partial=()=>JSON.parse(fs.readFileSync('examples/unfinished-storyboard-review.json','utf8')).panel;
const wire=p=>{const data=R.report(p);return {data,files:{'storyboard-review.json':JSON.stringify(data),'storyboard-review.md':R.markdown(data)},meta:{version:'0.31.0',protocol_version:1,needs_review:true}};};
test('storyboard report preserves duplicate motif related positions and raw shot blanks',()=>{const p=partial(),before=structuredClone(p),d=R.report(p);assert.equal(d.issue_count,7);assert.equal(d.filled_shots,0);assert.equal(d.issues[0].related_row,2);assert.ok(d.issues.some(i=>i.scope==='shots'&&i.row===3&&i.field==='visual'));assert.deepEqual(d.source,p);d.source.shots[0].visual='changed';assert.deepEqual(p,before);});
test('bounded report counts all 1000 shots and 30 motifs while optional reason and timing remain separate',()=>{const p=partial();p.motifs=Array.from({length:30},(_,i)=>({id:`motif-${i+1}`,name:'',meaning:''}));p.shots=Array.from({length:1000},()=>Object.fromEntries(Object.keys(p.shots[0]).map(k=>[k,''])));const d=R.report(p);assert.equal(d.issue_count,11060);assert.equal(d.issues.length,200);assert.equal(d.filled_shots,0);assert.equal(d.details_truncated,true);assert.match(R.markdown(d),/全部鏡頭與母題/);});
test('actual Python report is accepted with complete source JSON and Markdown matching',()=>{const p=partial();const reply=JSON.parse(execFileSync(process.platform==='win32'?'python':'python3',['-X','utf8','-c',"import json;from musiclab.application import build;print(json.dumps(build('storyboard_review',{'panel':json.loads(input())}).wire(),ensure_ascii=False))"],{input:JSON.stringify(p),encoding:'utf8',timeout:10000}));assert.deepEqual(R.checkedResult(p,reply),reply);});
test('unknown versions source changes hidden edits and false success cannot replace previous files',()=>{const mutations=[v=>v.data.schema_version=999,v=>v.data.status='fields_checked',v=>v.data.issue_count=0,v=>v.data.source.fields['mv-anchor']='hidden edit',v=>v.data.source.shots.reverse(),v=>v.data.issues.pop(),v=>v.data.extra=true,v=>v.meta.protocol_version=2,v=>v.meta.needs_review=false,v=>v.files['storyboard-review.json']='{}',v=>v.files['storyboard-review.md']='fake',v=>v.files['extra']='bad'];for(const edit of mutations){const p=partial(),w=wire(p);edit(w);assert.throws(()=>R.checkedResult(p,w));}});
test('strict report JSON rejects duplicate keys Unicode corruption and mismatching same-title report',()=>{const p=partial();for(const content of ['{"schema_version":1,"schema_version":999}','{"x":"\\ud800"}']){const w=wire(p);w.files['storyboard-review.json']=content;assert.throws(()=>R.checkedResult(p,w));}const other=partial();other.shots[2].visual='other';assert.throws(()=>R.checkedResult(p,wire(other)));});
test('accepted wire and caller source remain isolated while object key order is canonical',()=>{const p=partial(),w=wire(p);w.data.source.fields=Object.fromEntries(Object.entries(w.data.source.fields).reverse());w.files['storyboard-review.json']=JSON.stringify(w.data);const accepted=R.checkedResult(p,w);accepted.data.source.shots[0].visual='changed';assert.notEqual(w.data.source.shots[0].visual,'changed');assert.notEqual(p.shots[0].visual,'changed');});
function handler(){const source=fs.readFileSync('web/app.js','utf8'),start=source.indexOf("$('mv-ready-report').onclick="),end=source.indexOf("function lyricsReviewPayload()",start),elements={'mv-ready-report':{},'mv-visual':{hidden:false}},events=[];let resolve;const p=partial();const ctx={$:id=>elements[id],capturePanel:()=>p,storyboardReadyController:{check:()=>events.push('local-check')},MusicStoryboardReadiness:R,api:(_route,payload)=>{events.push({route:_route,payload:structuredClone(payload)});return new Promise(r=>resolve=r);},setFiles:(files,note)=>events.push({files,note}),say:text=>events.push(text),run:(_b,fn)=>fn(()=>ctx.current),current:true};vm.createContext(ctx);vm.runInContext(source.slice(start,end),ctx);return {p,ctx,elements,events,start:()=>elements['mv-ready-report'].onclick(),respond:r=>resolve(r)};}
test('actual report handler sends unchanged incomplete source and only replaces files after verified reply',async()=>{const s=handler(),before=structuredClone(s.p),pending=s.start();assert.deepEqual(s.events.slice(0,2),['local-check',{route:'/api/storyboard-review',payload:{panel:before}}]);assert.equal(s.elements['mv-visual'].hidden,false);s.respond(wire(s.p));await pending;assert.equal(s.elements['mv-visual'].hidden,true);assert.deepEqual(Object.keys(s.events[2].files),['storyboard-review.json','storyboard-review.md']);assert.deepEqual(s.p,before);});
test('actual handler leaves prior visual files and later edits when request is stale',async()=>{const s=handler(),pending=s.start();s.p.shots[2].visual='later edit';s.ctx.current=false;s.respond(wire(partial()));await pending;assert.equal(s.elements['mv-visual'].hidden,false);assert.equal(s.events.length,2);assert.equal(s.p.shots[2].visual,'later edit');});
test('actual handler rejects foreign reply before visual or file mutation',async()=>{const s=handler(),pending=s.start();const bad=wire(s.p);bad.data.issue_count=0;s.respond(bad);await assert.rejects(pending,/不一致/);assert.equal(s.elements['mv-visual'].hidden,false);assert.equal(s.events.length,2);});
