// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../web/backup-selection.js'),D=require('../web/backup-selection-dom.js');
const id=n=>'draft-'+n.toString(16).padStart(32,'0');
const record=(n,label='合成 '+n+' 🎵')=>({library_schema_version:1,id:id(n),label,stored_at:'2026-10-06T10:00:00+00:00',sha256:'a'.repeat(64),bytes:200,draft_schema_version:3,created_with:'0.131.0',titles:{music:'原文',storyboard:'',lyrics:''}});
function harness(items=[record(1),record(2),record(3)]){let s={enabled:true,busy:false,selected:items[0]||null,displayed:items},captures=0;const errors=[],states=[];const c=M.createController({capture:()=>{captures++;return s;},onError:e=>errors.push(e.message),onState:v=>states.push(v)});return {c,errors,states,get captures(){return captures;},get s(){return s;},set s(v){s=v;}};}
test('empty controller and unsuccessful changes have no undo',()=>{const h=harness([]);assert.equal(h.c.undo(),false);assert.equal(h.c.clear(),false);assert.equal(h.c.add(),false);assert.equal(h.c.remove(id(1)),false);assert.equal(h.c.refresh().canUndo,false);assert.equal(h.c.refresh().undoKind,null);});
test('clearing 1000 versions can restore exact order and metadata after a search changes',()=>{const items=Array.from({length:1000},(_,i)=>record(1000-i)),h=harness(items);h.c.addDisplayed();const before=h.c.refresh().entries;h.c.clear();h.s.displayed=[];h.s.selected=null;assert.equal(h.c.refresh().undoCount,1000);assert.equal(h.c.refresh().undoKind,'clear');assert.equal(h.c.undo(),true);assert.deepEqual(h.c.refresh().entries,before);assert.equal(h.c.request().ids.length,1000);assert.equal(h.c.refresh().canUndo,false);assert.equal(h.c.undo(),false);});
test('single addition can return to an empty selection and consumes the one checkpoint',()=>{const h=harness();h.c.add();const sent=h.c.request();assert.equal(h.c.refresh().undoCount,0);assert.equal(h.c.undo(),true);assert.equal(h.c.request(),null);assert.deepEqual(sent,{ids:[id(1)]});assert.equal(h.c.undo(),false);});
test('bulk addition restores only its predecessor and never retains caller metadata references',()=>{const h=harness();h.c.add();h.c.addDisplayed();h.s.displayed[0].label='caller mutation';h.s.displayed=[];h.s.selected=null;assert.equal(h.c.undo(),true);assert.deepEqual(h.c.request(),{ids:[id(1)]});assert.equal(h.c.refresh().entries[0].label,record(1).label);});
test('single removal restores the original insertion position and full literal label',()=>{const h=harness([record(3),record(1,'<img>\n原文'),record(2)]);h.c.addDisplayed();const before=h.c.refresh().entries;h.c.remove(id(1));h.s.displayed=[record(4)];h.s.selected=record(4);assert.equal(h.c.undo(),true);assert.deepEqual(h.c.refresh().entries,before);});
test('partial search removal restores the complete previous selection without loading more versions',()=>{const h=harness(Array.from({length:41},(_,i)=>record(i+1)));h.c.addDisplayed();h.s.displayed=h.s.displayed.slice(0,20);h.c.removeDisplayed();assert.equal(h.c.refresh().count,21);assert.equal(h.c.undo(),true);assert.equal(h.c.refresh().count,41);assert.equal(h.s.displayed.length,20);});
test('only the latest successful change is reversed; undo does not expose older changes',()=>{const h=harness();h.c.addDisplayed();h.c.remove(id(1));h.c.remove(id(2));assert.equal(h.c.refresh().undoKind,'remove');h.c.undo();assert.deepEqual(h.c.request(),{ids:[id(2),id(3)]});assert.equal(h.c.undo(),false);});
test('no-op and invalid change preserve the existing clear checkpoint',()=>{const h=harness();h.c.addDisplayed();h.c.clear();assert.equal(h.c.clear(),false);assert.equal(h.c.remove('not-an-id'),false);assert.equal(h.c.refresh().undoKind,'clear');assert.equal(h.c.undo(),true);assert.equal(h.c.refresh().count,3);});
test('a contradictory late displayed record refuses the entire undo and permits corrected retry',()=>{const h=harness();h.c.addDisplayed();h.c.clear();h.s.displayed=[record(1),record(2,'矛盾')];assert.equal(h.c.refresh().canUndo,false);assert.match(h.c.refresh().undoProblem,/不一致/);assert.equal(h.c.undo(),false);assert.equal(h.c.refresh().count,0);assert.equal(h.c.refresh().undoKind,'clear');h.s.displayed=[record(1),record(2)];assert.equal(h.c.undo(),true);assert.equal(h.c.refresh().count,3);});
test('selected metadata participates in undo checking even when absent from displayed records',()=>{const h=harness();h.c.add();h.s.displayed=[];h.s.selected=record(1,'矛盾');assert.equal(h.c.undo(),false);assert.equal(h.c.refresh().count,1);h.s.selected=record(1);assert.equal(h.c.undo(),true);});
test('conflicting duplicate unselected metadata refuses undo before changing any entry',()=>{const h=harness();h.c.addDisplayed();h.c.clear();h.s.selected=null;h.s.displayed=[record(4),record(4,'矛盾')];assert.equal(h.c.undo(),false);assert.equal(h.c.refresh().count,0);h.s.displayed=[];assert.equal(h.c.undo(),true);});
test('busy and disabled captures keep checkpoint and selections until retry',()=>{const h=harness();h.c.addDisplayed();h.c.clear();for(const flags of [{busy:true},{enabled:false}]){const original=h.s;h.s={...original,...flags};assert.equal(h.c.undo(),false);assert.equal(h.c.refresh().canUndo,false);assert.equal(h.c.refresh().undoCount,3);h.s=original;}assert.equal(h.c.undo(),true);});
test('unknown root fields and sparse displayed arrays preserve undo and permit retry',()=>{for(const kind of ['extra','sparse']){const h=harness();h.c.addDisplayed();h.c.clear();const original=structuredClone(h.s);if(kind==='extra')h.s.path='forbidden';else delete h.s.displayed[1];assert.equal(h.c.undo(),false);assert.equal(h.c.refresh().count,0);h.s=original;assert.equal(h.c.undo(),true);}});
test('metadata getters cannot run during undo checking or replace the checkpoint',()=>{const h=harness();h.c.addDisplayed();h.c.clear();let calls=0;Object.defineProperty(h.s.displayed[1],'label',{enumerable:true,get(){calls++;return 'hook';}});assert.equal(h.c.undo(),false);h.c.refresh();assert.equal(calls,0);h.s.displayed=[record(1),record(2),record(3)];assert.equal(h.c.undo(),true);});
test('disposed controller releases checkpoint and does not capture late undo calls',()=>{const h=harness();h.c.addDisplayed();h.c.clear();h.c.dispose();const captures=h.captures;h.s=null;assert.equal(h.c.undo(),false);assert.equal(h.c.request(),null);assert.equal(h.states.at(-1).undoKind,null);assert.equal(h.states.at(-1).canUndo,false);assert.equal(h.captures,captures);});
test('legacy capture without displayed metadata retains undo support and source is unchanged',()=>{const h=harness();delete h.s.displayed;const before=structuredClone(h.s);h.c.add();h.c.clear();h.c.undo();assert.deepEqual(h.s,before);assert.deepEqual(h.c.request(),{ids:[id(1)]});});
function dom(){const document={activeElement:null,getElementById:k=>nodes[k],createElement:()=>element()};function element(){return {textContent:'',disabled:false,children:[],attrs:{},append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},setAttribute(k,v){this.attrs[k]=v;},focus(){document.activeElement=this;}};}const nodes=Object.fromEntries(['backup-selection-add','backup-selection-add-displayed','backup-selection-remove-displayed','backup-selection-remove-note','backup-selection-displayed-note','backup-selection-clear','backup-selection-undo','backup-selection-undo-note','backup-selection-list','backup-selection-note','backup-save-batch'].map(k=>[k,element()]));let s={enabled:true,busy:false,selected:record(1),displayed:[record(1),record(2)]},notify=()=>{};const handlers=new Map(),events={addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:n=>handlers.delete(n)};const adapter=D.bind(document,{capture:()=>s,events,onChange:()=>notify()});return {document,nodes,adapter,events,handlers,get s(){return s;},set s(v){s=v;},set notify(f){notify=f;}};}
test('DOM clear sends focused control to undo and restored batch is immediately downloadable',()=>{const h=dom();h.notify=()=>{h.nodes['backup-save-batch'].disabled=h.adapter.request()===null;};h.nodes['backup-selection-add-displayed'].onclick();h.nodes['backup-selection-clear'].focus();h.nodes['backup-selection-clear'].onclick();assert.equal(h.document.activeElement,h.nodes['backup-selection-undo']);assert.equal(h.nodes['backup-save-batch'].disabled,true);assert.match(h.nodes['backup-selection-undo'].textContent,/清空/);assert.match(h.nodes['backup-selection-undo-note'].textContent,/2 版/);h.nodes['backup-selection-undo'].onclick();assert.equal(h.nodes['backup-save-batch'].disabled,false);assert.equal(h.nodes['backup-selection-undo'].disabled,true);assert.equal(h.document.activeElement,h.nodes['backup-save-batch']);h.adapter.dispose();});
test('manual refresh leaves undo focus and unchanged list nodes intact',()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();const item=h.nodes['backup-selection-list'].children[0];h.nodes['backup-selection-undo'].focus();h.s.displayed=[];h.s.selected=null;h.adapter.refresh();assert.equal(h.document.activeElement,h.nodes['backup-selection-undo']);assert.equal(h.nodes['backup-selection-list'].children[0],item);h.adapter.dispose();});
test('failed DOM undo keeps focus and literal conflict note, retry can restore',()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();h.nodes['backup-selection-clear'].onclick();h.nodes['backup-selection-undo'].focus();h.s.selected=record(1,'conflict');h.adapter.refresh();assert.equal(h.nodes['backup-selection-undo'].onclick(),false);assert.equal(h.document.activeElement,h.nodes['backup-selection-undo']);assert.match(h.nodes['backup-selection-undo-note'].textContent,/不一致/);h.s.selected=record(1);h.adapter.refresh();assert.equal(h.nodes['backup-selection-undo'].onclick(),true);h.adapter.dispose();});
test('pagehide removes the undo handler and cannot restore into the disposed adapter',()=>{const h=dom();h.nodes['backup-selection-add-displayed'].onclick();const late=h.nodes['backup-selection-undo'].onclick;h.handlers.get('pagehide')();assert.equal(h.nodes['backup-selection-undo'].onclick,null);assert.equal(h.nodes['backup-selection-undo'].disabled,true);assert.equal(late(),false);assert.equal(h.adapter.request(),null);});
