// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),D=require('../web/editor-keys-dom.js');
function setup(){
 const nodes={},events=[],document={body:{},activeElement:null,getElementById:id=>nodes[id]};let busy=false,mode='normal';
 for(const [list,panel] of [['arrangement','music'],['shots','storyboard'],['cues','lyrics']]){nodes[panel]={isConnected:true,hidden:false};nodes[list]={id:list,isConnected:true,children:[],listeners:new Map(),addEventListener(t,f){this.listeners.set(t,f);},removeEventListener(t,f){assert.equal(this.listeners.get(t),f);this.listeners.delete(t);}};render(list,['a','b','c'].map(id=>({id:list+'-'+id,values:[' 0016.000 ', '原文🎵\r\n保留']})));}
 function render(list,rows){const container=nodes[list];for(const row of container.children){row.isConnected=false;row.fields.forEach(f=>f.isConnected=false);}container.children=rows.map(item=>{const row={dataset:{historyId:item.id},isConnected:true,parentElement:container,querySelectorAll:()=>row.fields,contains:t=>row.fields.includes(t)};row.fields=item.values.map((value,i)=>({tagName:i?'TEXTAREA':'INPUT',type:'text',value,isConnected:true,disabled:false,readOnly:false,hidden:false,selectionStart:2,selectionEnd:5,selectionDirection:'backward',closest:()=>row,focus(){document.activeElement=this;events.push(['focus',list,item.id,i]);},setSelectionRange(...args){[this.selectionStart,this.selectionEnd,this.selectionDirection]=args;events.push(['caret',...args]);}}));return row;});}
 const adapter=D.bind(document,{busy:()=>busy,onMove:(list,id,delta)=>{events.push(['move',list,id,delta]);if(mode==='false')return false;const rows=nodes[list].children.map(row=>({id:row.dataset.historyId,values:row.fields.map(f=>f.value)})),index=rows.findIndex(r=>r.id===id);[rows[index],rows[index+delta]]=[rows[index+delta],rows[index]];if(mode==='wrong')rows.reverse();render(list,rows);document.activeElement=mode==='foreign-focus'?{foreign:true}:document.body;return true;},onError:e=>events.push(['error',e.message])});
 return{nodes,document,events,adapter,set busy(v){busy=v;},set mode(v){mode=v;},key(list,index=1,field=1,extra={}){const target=nodes[list].children[index].fields[field];document.activeElement=target;const event={key:'ArrowUp',altKey:true,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:38,target,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...extra};nodes[list].listeners.get('keydown')?.(event);return event;}};
}
test('all three lists move the active stable row and restore the same textarea with backward caret selection',()=>{for(const list of ['arrangement','shots','cues']){const s=setup(),before=s.nodes[list].children[1].fields[1].value,e=s.key(list);assert.equal(e.defaultPrevented,true);assert.equal(s.nodes[list].children[0].dataset.historyId,list+'-b');assert.equal(s.document.activeElement,s.nodes[list].children[0].fields[1]);assert.equal(s.document.activeElement.value,before);assert.deepEqual(s.events.at(-1),['caret',2,5,'backward']);assert.equal(s.nodes[list].listeners.size,1);}});
test('raw text clocks are never parsed and input caret positions survive a downward movement',()=>{const s=setup(),e=s.key('cues',1,0,{key:'ArrowDown',keyCode:40});assert.equal(e.defaultPrevented,true);assert.equal(s.document.activeElement.value,' 0016.000 ');assert.equal(s.document.activeElement,s.nodes.cues.children[2].fields[0]);assert.equal(s.document.activeElement.selectionDirection,'backward');});
test('ordinary keys and composing repeated or combined modifiers do not consume keys or read display values',()=>{for(const extra of [{altKey:false},{ctrlKey:true},{metaKey:true},{shiftKey:true},{repeat:true},{isComposing:true},{keyCode:229},{key:'ArrowLeft'},{defaultPrevented:true}]){const s=setup(),f=s.nodes.cues.children[1].fields[1];Object.defineProperty(f,'value',{get:()=>assert.fail('ignored key read display')});const e=s.key('cues',1,1,extra);assert.equal(e.defaultPrevented,extra.defaultPrevented===true);assert.deepEqual(s.events,[]);}});
test('hidden busy disabled readonly select disconnected foreign or inactive targets cannot move or prevent defaults',()=>{for(const kind of ['hidden','busy','disabled','readonly','select','detached','foreign','inactive']){const s=setup(),row=s.nodes.shots.children[1],f=row.fields[0];if(kind==='hidden')s.nodes.storyboard.hidden=true;if(kind==='busy')s.busy=true;if(kind==='disabled')f.disabled=true;if(kind==='readonly')f.readOnly=true;if(kind==='select')f.tagName='SELECT';if(kind==='detached')row.isConnected=false;if(kind==='foreign')row.parentElement=s.nodes.cues;const e={key:'ArrowUp',altKey:true,ctrlKey:false,metaKey:false,shiftKey:false,repeat:false,isComposing:false,keyCode:38,target:f,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};s.document.activeElement=kind==='inactive'?row.fields[1]:f;s.nodes.shots.listeners.get('keydown')(e);assert.equal(e.defaultPrevented,false,kind);assert.deepEqual(s.events,[],kind);}});
test('first and last boundaries retain native behavior and the original active control',()=>{for(const [index,extra] of [[0,{}],[2,{key:'ArrowDown',keyCode:40}]]){const s=setup(),e=s.key('cues',index,1,extra);assert.equal(e.defaultPrevented,false);assert.equal(s.document.activeElement,s.nodes.cues.children[index].fields[1]);assert.deepEqual(s.events,[]);}});
test('failed writes and mismatched final order keep intervening state without refocusing it',()=>{for(const mode of ['false','wrong']){const s=setup();s.mode=mode;s.key('shots');assert.equal(s.events.filter(x=>x[0]==='focus').length,0);assert.equal(s.events.filter(x=>x[0]==='caret').length,0);}});
test('successful movement does not steal an intervening external focus and dispose removes exactly three listeners',()=>{const s=setup();s.mode='foreign-focus';s.key('arrangement');assert.deepEqual(s.document.activeElement,{foreign:true});assert.equal(s.events.filter(x=>x[0]==='focus').length,0);s.adapter.dispose();for(const list of ['arrangement','shots','cues'])assert.equal(s.nodes[list].listeners.size,0);});
test('actual app keyboard callback delegates to existing movement controls without introducing a raw-source writer',()=>{const app=fs.readFileSync('web/app.js','utf8'),a=app.indexOf('const editorKeys=MusicEditorKeysDOM.bind('),b=app.indexOf('editorPosition=MusicEditorPositionDOM.bind(',a),events=[];let options;const ctx={MusicEditorKeysDOM:{bind:(_d,o)=>{options=o;return {};}},document:{},state:{busy:false},moveMusicSection:(...args)=>{events.push(['music',...args]);return {};},editorOrder:{move:(...args)=>{events.push(['order',...args]);return {};}},say:()=>{}};vm.runInNewContext(app.slice(a,b),ctx);assert.equal(options.onMove('arrangement','current-song',-1),true);assert.deepEqual(events.at(-1),['music',-1,'current-song',true]);for(const list of ['shots','cues']){assert.equal(options.onMove(list,'current-row',1),true);assert.deepEqual(events.at(-1),['order',list,'current-row',1]);}});
