// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),F=require('../web/verification-focus.js');
function harness(){let view={available:true,pending:false,waiting:false,contextRevision:1},active='other';const calls=[];const c=F.createController({capture:()=>view,noteFocused:()=>active==='note',focusPicker:()=>{calls.push('picker');active='picker';return true;},focusNote:()=>{calls.push('note');active='note';return true;}});return {c,calls,get view(){return view;},set view(v){view=v;},get active(){return active;},set active(v){active=v;}};}
test('ordinary state refresh has no focus effect while an explicit cancellation focuses an available picker',()=>{const h=harness();h.c.refresh(h.view);assert.deepEqual(h.calls,[]);h.c.cancelled();assert.equal(h.active,'picker');assert.deepEqual(h.calls,['picker']);h.c.refresh(h.view);assert.deepEqual(h.calls,['picker']);});
test('waiting cancellation can resume exactly once only while the same note and source remain current',()=>{const h=harness();h.view.available=false;h.view.waiting=true;h.c.cancelled();assert.equal(h.active,'note');h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);h.view.available=true;h.view.waiting=false;h.c.refresh(h.view);h.c.refresh(h.view);assert.deepEqual(h.calls,['note','picker']);});
test('leaving or clearing a note invitation prevents revival even after returning to the note',()=>{for(const clear of [false,true]){const h=harness();h.view.available=false;h.view.waiting=true;h.c.cancelled();if(clear)h.c.clear();else{h.active='other';h.c.refresh(h.view);}h.active='note';h.view.available=true;h.view.waiting=false;h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);}});
test('source change a new pending action or unavailable non-waiting state invalidates the invitation',()=>{for(const patch of [{contextRevision:2},{pending:true},{waiting:false}]){const h=harness();h.view.available=false;h.view.waiting=true;h.c.cancelled();h.c.refresh({...h.view,...patch});h.view.available=true;h.view.waiting=false;h.c.refresh(h.view);assert.deepEqual(h.calls,['note']);}});
test('invalid metadata and a failed capture refuse focus without accepting unknown state',()=>{const h=harness();for(const patch of [{available:1},{pending:null},{waiting:'true'},{contextRevision:0},{contextRevision:NaN},{contextRevision:1.5}]){h.view={available:true,pending:false,waiting:false,contextRevision:1,...patch};h.c.cancelled();h.c.refresh(h.view);}assert.deepEqual(h.calls,[]);const c=F.createController({capture:()=>{throw Error('unavailable');},noteFocused:()=>true,focusPicker:()=>assert.fail(),focusNote:()=>assert.fail()});c.cancelled();});
test('invitation retains only its primitive epoch and cannot be changed by subsequent mutation of a supplied view',()=>{const h=harness();h.view.available=false;h.view.waiting=true;h.c.cancelled();const epoch=h.view.contextRevision;h.view.contextRevision=2;h.c.refresh({...h.view,available:true,waiting:false,contextRevision:epoch});assert.deepEqual(h.calls,['note','picker']);});
test('picker focus failure falls back to note but creates no resume invitation and failed note focus cannot resume',()=>{let picker=0,note=0;const v={available:true,pending:false,waiting:false,contextRevision:1},c=F.createController({capture:()=>v,noteFocused:()=>true,focusPicker:()=>{picker++;throw Error('focus');},focusNote:()=>{note++;return true;}});c.cancelled();c.refresh(v);assert.equal(picker,1);assert.equal(note,1);v.available=false;v.waiting=true;const no=F.createController({capture:()=>v,noteFocused:()=>true,focusPicker:()=>assert.fail(),focusNote:()=>false});no.cancelled();no.refresh({...v,available:true,waiting:false});});
test('dispose suppresses all future focus side effects and requires explicit injected interfaces',()=>{const h=harness();h.view.available=false;h.view.waiting=true;h.c.cancelled();h.c.dispose();h.view.available=true;h.view.waiting=false;h.c.refresh(h.view);h.c.cancelled();assert.deepEqual(h.calls,['note']);assert.throws(()=>F.createController({}));});
