// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../musiclab/assets/lyrics-review.js'),V=require('../musiclab/assets/delivery-versions.js');
const input=()=>({title:'  原創待辦 🎵  ',duration:'8',cues:[{start:'',end:'',text:'原句\r\n第二行'},{start:' 0 ',end:'2',text:' 重複原文 '},{start:'0.0004',end:'1',text:' 重複原文 '}]});
const wire=p=>{const d=R.review(p);return {data:d,files:{'lyrics-review.json':JSON.stringify(d,null,2)+'\n','lyrics-review.md':R.markdown(d)},meta:{version:V.current,protocol_version:1,needs_review:true}};};
function setup(request){const s={value:input(),reports:[],errors:[],states:[],requests:[],waiting:[]};s.c=R.createController({capture:()=>s.value,request:(p,current)=>{s.requests.push(p);return request?request(p,current):new Promise((resolve,reject)=>s.waiting.push({p,resolve,reject}));},onReport:(data,files)=>s.reports.push({data,files}),onError:e=>s.errors.push(e.message),onState:v=>s.states.push(v)});return s;}
test('the full reply requires current product metadata and exact root/data/files/meta',()=>{const p=input();assert.deepEqual(R.checkedResult(p,wire(p)).data,R.review(p));for(const edit of [r=>r.meta.version='0.999.0',r=>r.meta.version='0.25.0',r=>r.meta.protocol_version=2,r=>r.meta.needs_review=false,r=>r.meta.extra='x',r=>r.extra='x',r=>delete r.meta.version,r=>r.files.extra='x',r=>r.data.source.cues[1].text='different',r=>r.files['lyrics-review.json']='{}',r=>r.files['lyrics-review.md']+='x']){const r=wire(p);edit(r);assert.throws(()=>R.checkedResult(p,r));assert.throws(()=>R.inspect(r,p));}});
test('source getters are rejected before any reads in the pure model',()=>{for(const field of ['title','duration','cues']){const p=input(),value=p[field];let reads=0;Object.defineProperty(p,field,{enumerable:true,get(){reads++;return value;}});assert.throws(()=>R.review(p));assert.equal(reads,0);}for(const field of ['start','end','text']){const p=input(),value=p.cues[0][field];let reads=0;Object.defineProperty(p.cues[0],field,{enumerable:true,get(){reads++;return value;}});assert.throws(()=>R.review(p));assert.equal(reads,0);}});
test('source capture failures and getters never invoke transport and release only the current pending state',async()=>{const s=setup(),p=input();let reads=0;Object.defineProperty(p.cues[0],'start',{enumerable:true,get(){reads++;return '';}});s.value=p;assert.equal(await s.c.check(),false);assert.equal(reads,0);assert.equal(s.requests.length,0);assert.equal(s.reports.length,0);assert.equal(s.errors.length,1);assert.equal(s.states.at(-1).pending,false);});
test('reply getters are rejected before reading metadata, files or data',()=>{for(const field of ['meta','files','data']){const p=input(),r=wire(p),value=r[field];let reads=0;Object.defineProperty(r,field,{enumerable:true,get(){reads++;return value;}});assert.throws(()=>R.inspect(r,p));assert.equal(reads,0);}});
test('sparse cue arrays and accessor array elements cannot silently become timing checked',()=>{for(const cues of [new Array(1),Object.assign(new Array(3),{1:{start:'0',end:'1',text:'x'}})])assert.throws(()=>R.review({cues}));let reads=0;const cues=[];Object.defineProperty(cues,'0',{enumerable:true,get(){reads++;return {start:'0',end:'1',text:'x'};}});assert.throws(()=>R.review({cues}));assert.equal(reads,0);});
test('undefined, hidden, symbolic and invalid Unicode source values are refused before normalization',()=>{for(const edit of [p=>p.duration=undefined,p=>p.title='\ud800',p=>p.duration='\udc00',p=>p.cues[0].text='\ud800',p=>p.cues[0].start='\ud800',p=>Object.defineProperty(p,'hidden',{value:true}),p=>Object.defineProperty(p.cues[0],'hidden',{value:true}),p=>p.cues[Symbol('x')]=1,p=>p.extra=1,p=>p.cues[0].start=Infinity]){const p=input();edit(p);assert.throws(()=>R.review(p));}});
test('hidden, symbolic and non-JSON reply fields are refused before touching files',()=>{for(const edit of [r=>Object.defineProperty(r,'hidden',{value:true}),r=>Object.defineProperty(r.meta,'hidden',{value:true}),r=>Object.defineProperty(r.files,'hidden',{value:true}),r=>r[Symbol('x')]=true,r=>r.meta.extra=undefined,r=>r.files['lyrics-review.md']='\ud800']){const p=input(),r=wire(p);edit(r);assert.throws(()=>R.inspect(r,p));}});
test('canonical source retains default fields without changing original optional omissions or raw Unicode',()=>{const p={cues:[{start:'\u0085 0 \u0085',end:'1',text:' e\u0301 🎵 \r\n原文 '}]},before=structuredClone(p),s=R.checkedSource(p);assert.deepEqual(s,{title:'歌詞校時檢查',duration:null,cues:p.cues});s.cues[0].text='changed';assert.deepEqual(p,before);const d=R.review(p);assert.equal(d.source.cues[0].text,before.cues[0].text);assert.equal(d.issues[0].code,'multiline_text');});
test('full checked results isolate data and file maps from subsequent reply mutations',()=>{const p=input(),r=wire(p),before=structuredClone(r),accepted=R.checkedResult(p,r);r.files['lyrics-review.md']='changed';r.data.source.cues[0].text='changed';assert.deepEqual(accepted,{data:before.data,files:before.files});accepted.data.source.cues[1].text='consumer';accepted.files['lyrics-review.json']='consumer';assert.equal(p.cues[1].text,' 重複原文 ');});
test('invalid source can be repaired and retried without publishing a report or guessing timing',async()=>{const s=setup();s.value={cues:new Array(1)};assert.equal(await s.c.check(),false);assert.equal(s.requests.length,0);s.value=input();const pending=s.c.check();s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await pending,true);assert.equal(s.reports.length,1);assert.equal(s.reports[0].data.source.cues[0].start,'');});
test('an unknown-version reply preserves the previous report and allows current-version retry',async()=>{const s=setup();let pending=s.c.check();s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await pending,true);const original=structuredClone(s.reports[0]);pending=s.c.check();const bad=wire(s.waiting[1].p);bad.meta.version='0.999.0';s.waiting[1].resolve(bad);assert.equal(await pending,false);assert.deepEqual(s.reports,[original]);pending=s.c.check();s.waiting[2].resolve(wire(s.waiting[2].p));assert.equal(await pending,true);assert.equal(s.reports.length,2);});
test('transport cannot change the click-time snapshot by modifying its isolated input',async()=>{const s=setup(p=>{p.cues[0].text='transport changed';return Promise.resolve(wire(p));}),before=structuredClone(s.value);assert.equal(await s.c.check(),false);assert.deepEqual(s.value,before);assert.equal(s.reports.length,0);assert.match(s.errors[0],/內容有修改/);});
test('publishing owns its two file strings instead of retaining the response map',async()=>{let response;const s=setup(p=>{response=wire(p);return Promise.resolve(response);});assert.equal(await s.c.check(),true);const before=structuredClone(s.reports[0]);response.files['lyrics-review.md']='late mutation';response.data.source.cues.reverse();assert.deepEqual(s.reports[0],before);});
test('outer current failure and invalidate suppress transport or late error without replacing prior state',async()=>{const s=setup();assert.equal(await s.c.check(()=>false),false);assert.equal(s.requests.length,0);const pending=s.c.check();s.c.invalidate();s.waiting[0].reject(Error('obsolete'));assert.equal(await pending,false);assert.equal(s.errors.length,0);assert.equal(s.reports.length,0);assert.equal(s.states.at(-1).pending,false);});
test('an obsolete finally cannot end a newer request pending state',async()=>{const s=setup(),old=s.c.check(),current=s.c.check();s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await old,false);assert.equal(s.states.at(-1).pending,true);s.waiting[1].resolve(wire(s.waiting[1].p));assert.equal(await current,true);assert.equal(s.states.at(-1).pending,false);assert.equal(s.reports.length,1);});
test('optional omitted title/duration keep the exact request shape while report defaults remain explicit',async()=>{const s=setup();s.value={cues:[{start:'0',end:'1',text:'原句'}]};const pending=s.c.check();assert.deepEqual(Object.keys(s.waiting[0].p),['cues']);s.waiting[0].resolve(wire(s.waiting[0].p));assert.equal(await pending,true);assert.equal(s.reports[0].data.source.title,'歌詞校時檢查');assert.equal(s.reports[0].data.source.duration,null);});
