// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../musiclab/assets/lyrics-review.js'),P=require('../web/lyrics-cue-review.js'),Q=require('../web/readiness-request.js'),D=require('../web/lyrics-cue-review-dom.js'),V=require('../musiclab/assets/delivery-versions.js');
const partial=(n=120)=>({lyrics:{title:' 原創合成🎵 ',duration:'8',cues:Array.from({length:n},()=>({start:'',end:'',text:' 原句🎵  '}))},row:n});
const wire=p=>{const data=P.report(p);return {data,files:{'lyrics-cue-review.json':JSON.stringify(data,null,2)+'\n','lyrics-cue-review.md':P.markdown(data)},meta:{version:V.current,protocol_version:1,needs_review:true}};};
function harness(){const p=partial(3),s={value:{lyrics:p.lyrics,ids:['a','b','c'],selectedId:'c'},views:[]};s.c=P.createController({capture:()=>s.value,onState:v=>s.views.push(v)});return s;}
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};}
test('selected original row120 is diagnosed even when whole details end at row100',()=>{const p=partial(),before=structuredClone(p),d=P.report(p),whole=R.review(p.lyrics);assert.equal(whole.issue_count,240);assert.ok(!whole.issues.some(i=>i.row===120));assert.equal(d.issue_count,2);assert.deepEqual(d.issues.map(i=>[i.row,i.field]),[[120,'start'],[120,'end']]);assert.deepEqual(p,before);assert.deepEqual(d.source,{title:p.lyrics.title,duration:'8',cue:p.lyrics.cues[119]});});
test('selected issues share global duration duplicate and horizon overlap rules in original order',()=>{const p={lyrics:{duration:'bad',cues:[{start:'0',end:'10',text:'長'},{start:'0',end:'2',text:'重複'},{start:'1',end:'3',text:'多\n行'}]},row:1};for(const row of [1,2,3]){p.row=row;assert.deepEqual(P.report(p).issues,R.review(p.lyrics).issues.filter(i=>i.row===0||i.row===row));}});
test('zero selected issues retains unfinished other rows and requires whole package and listening',()=>{const p=partial();p.lyrics.cues[119]={start:'0',end:'1',text:' 原文🎵  '};const d=P.report(p);assert.equal(d.issue_count,0);assert.ok(R.review(p.lyrics).issue_count>200);assert.match(P.markdown(d),/仍須完整歌詞包與實聽/);});
test('count all selected long-horizon relationships before bounding retained details',()=>{const p={lyrics:{cues:[{start:0,end:10001,text:'長'}].concat(Array.from({length:9999},(_,i)=>({start:i+1,end:i+2,text:'短'})))},row:1},d=P.report(p);assert.equal(d.issue_count,9999);assert.equal(d.issues.length,200);assert.ok(d.details_truncated);assert.equal(d.issues.at(-1).related_row,201);assert.ok(d.issues.every(i=>i.row===1&&i.field==='end'));assert.ok(Buffer.byteLength(JSON.stringify(wire(p)))<2*1024*1024);});
test('full own source is checked before getters cloning or sparse-array analysis',()=>{for(const edit of [p=>p.lyrics.cues=new Array(1),p=>p.lyrics.cues[0].text='\ud800',p=>p.extra=true,p=>p.lyrics.cues[0].unknown=true]){const p=partial();edit(p);assert.throws(()=>P.report(p));}let reads=0;const p=partial();Object.defineProperty(p,'row',{enumerable:true,get(){reads++;return 120;}});assert.throws(()=>P.report(p));assert.equal(reads,0);});
test('row must be an existing original integer and optional source defaults stay explicit',()=>{for(const row of [true,false,0,-1,1.5,121,null,'120',Infinity,NaN])assert.throws(()=>P.report({...partial(),row}));const p={lyrics:{cues:[{start:'0',end:'1',text:' é 🎵 '}]},row:1},before=structuredClone(p);assert.equal(P.report(p).source.title,'歌詞校時檢查');assert.equal(P.report(p).source.duration,null);assert.deepEqual(p,before);});
test('full current reply envelope report and both files are checked and isolated',()=>{const p=partial(),good=wire(p),checked=P.checkedResult(p,good);for(const edit of [w=>w.meta.version='0.999.0',w=>w.meta.extra=true,w=>w.extra=true,w=>w.data.source.cue.text='different',w=>w.files['lyrics-cue-review.json']='{}',w=>w.files['lyrics-cue-review.md']+='x']){const w=wire(p);edit(w);assert.throws(()=>P.checkedResult(p,w));}good.data.issues.reverse();good.files['lyrics-cue-review.md']='changed';const expected=wire(p);assert.deepEqual(checked,{data:expected.data,files:expected.files});});
test('complete reply getters are refused before reads',()=>{let reads=0;const p=partial(),w=wire(p);Object.defineProperty(w,'meta',{enumerable:true,get(){reads++;return {};}});assert.throws(()=>P.checkedResult(p,w));assert.equal(reads,0);});
test('source controller diagnoses selected row and rejects edits in any timing relationship',()=>{const s=harness();const v=s.c.check();assert.equal(v.report.row,3);assert.equal(s.c.locate(0,v.revision).row,3);s.value.lyrics.cues[0].start='0';assert.ok(s.c.refresh().stale);assert.equal(s.c.locate(0,v.revision),null);s.value.lyrics.cues[0].start='';assert.equal(s.c.refresh().stale,false);assert.equal(s.c.locate(0,v.revision).field,'start');});
test('selection and identical-text stable-ID reorder invalidate locations until exact recovery',()=>{const s=harness(),v=s.c.check();s.value.selectedId='b';assert.ok(s.c.refresh().stale);s.value.selectedId='c';assert.ok(!s.c.refresh().stale);s.value.ids=['b','a','c'];assert.ok(s.c.refresh().stale);s.value.ids=['a','b','c'];assert.ok(!s.c.refresh().stale);s.c.check();assert.equal(s.c.locate(0,v.revision),null);});
test('proofs reject copied mutated payloads and duplicate or incomplete row identities',()=>{const s=harness(),p=s.c.payload();assert.ok(s.c.isCurrent(p));assert.equal(s.c.isCurrent(structuredClone(p)),false);p.lyrics.cues[0].text='change';assert.equal(s.c.isCurrent(p),false);s.value.ids=['a','a','c'];assert.throws(()=>s.c.check());s.value.ids=['a'];assert.throws(()=>s.c.payload());});
test('shared request publishes only complete current reports and good-bad-good retry keeps previous files',async()=>{const s=harness(),reports=[],errors=[];let calls=0;const c=Q.createController({source:s.c,checkedResult:P.checkedResult,request:async p=>{const w=wire(p);if(++calls===2)w.meta.version='0.999.0';return w;},onReport:v=>reports.push(v),onError:e=>errors.push(e)});assert.ok(await c.check());const previous=structuredClone(reports[0]);assert.equal(await c.check(),false);assert.deepEqual(reports,[previous]);assert.equal(errors.length,1);assert.ok(await c.check());assert.equal(reports.length,2);});
test('late source edits and cancelled errors cannot publish or replace current work',async()=>{const s=harness(),pending=[],reports=[],errors=[],stale=[];const c=Q.createController({source:s.c,checkedResult:P.checkedResult,request:p=>{const d=deferred();pending.push({p,...d});return d.promise;},onReport:v=>reports.push(v),onError:e=>errors.push(e),onStale:()=>stale.push(true)});let work=c.check();s.value.lyrics.duration='7';pending[0].resolve(wire(pending[0].p));assert.equal(await work,false);assert.equal(reports.length,0);assert.equal(stale.length,1);work=c.check();c.invalidate();pending[1].reject(Error('late'));assert.equal(await work,false);assert.equal(errors.length,0);});
test('old finally preserves newer pending ownership and transport input cannot mutate raw source',async()=>{const s=harness(),pending=[],states=[],reports=[];const c=Q.createController({source:s.c,checkedResult:P.checkedResult,request:p=>{const d=deferred();pending.push({p,...d});return d.promise;},onReport:v=>reports.push(v),onState:v=>states.push(v)}),before=structuredClone(s.value),old=c.check(),next=c.check();pending[0].resolve(wire(pending[0].p));assert.equal(await old,false);assert.ok(states.at(-1).pending);pending[1].resolve(wire(pending[1].p));assert.ok(await next);assert.equal(states.at(-1).pending,false);assert.equal(reports.length,1);assert.deepEqual(s.value,before);});
function dom(){const nodes={};function node(){return {disabled:false,hidden:false,value:'c',textContent:'',children:[],isConnected:true,classList:{toggle(){}},append(x){this.children.push(x);},replaceChildren(){this.children=[];},focus(){document.activeElement=this;}};}for(const suffix of ['box','check','report','status','pages','previous','next','page-note','issues'])nodes['cue-review-'+suffix]=node();for(const suffix of ['check','previous','next','note'])nodes['cue-issue-'+suffix]=node();nodes['cues-order']=node();const document={activeElement:null,getElementById:id=>nodes[id],createElement:()=>node()};return {document,nodes};}
test('literal DOM paginates every retained selected issue and refuses stale busy and hidden locations',()=>{const {document,nodes}=dom(),located=[];let visible=true,busy=false;const d=D.bind(document,{visible:()=>visible,busy:()=>busy,onCheck:()=>true,onLocate:(i,r)=>{located.push([i,r]);return true;}}),data=P.report(partial());data.issues=Array.from({length:200},(_,i)=>({...data.issues[0],related_row:i+1}));data.issue_count=240;d.render({report:data,stale:false,revision:1});const seen=[];for(let page=0;page<10;page++){seen.push(...nodes['cue-review-issues'].children.map(li=>li.children[0].textContent));if(page<9)nodes['cue-review-next'].onclick();}assert.equal(seen.length,200);assert.equal(nodes['cue-review-issues'].children[19].children[0].onclick(),true);assert.deepEqual(located,[[199,1]]);busy=true;d.refresh();assert.ok(nodes['cue-review-check'].disabled);assert.equal(nodes['cue-review-issues'].children[0].children[0].onclick(),false);busy=false;visible=false;d.refresh();assert.ok(nodes['cue-review-report'].disabled);visible=true;d.render({report:data,stale:true,revision:1});assert.ok(nodes['cue-review-issues'].children.every(li=>li.children[0].disabled));});
test('literal DOM reports selected zero and global duration without changing source content',()=>{const {document,nodes}=dom();let checks=0;const d=D.bind(document,{visible:()=>true,busy:()=>false,onCheck:()=>{checks++;return true;},onLocate:()=>true}),p=partial(1);p.lyrics.cues[0]={start:'0',end:'1',text:'<literal>'};d.render({report:P.report(p),stale:false,revision:1});assert.match(nodes['cue-review-status'].textContent,/原句 1／共1句/);assert.match(nodes['cue-review-status'].textContent,/仍須完整歌詞包與實聽/);assert.ok(nodes['cue-review-pages'].hidden);nodes['cue-review-check'].onclick();assert.equal(checks,1);p.lyrics.duration='bad';d.render({report:P.report(p),stale:false,revision:2});assert.match(nodes['cue-review-issues'].children[0].children[0].textContent,/作品 · 作品宣告/);});
