// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../web/editor-copy.js'),O=require('../web/editor-order.js');
function rows(list,n=3){return Array.from({length:n},(_,i)=>({id:'r'+i,value:Object.fromEntries(P.specs[list].fields.map(k=>[k,k==='open'?i===0:k==='start'?String(i*2):k==='end'?String(i*2+2):'原文\r\n🎵\t'+i]))}));}
function setup(list='cues'){let value={entries:rows(list),visible:true,busy:false},reads=0,writes=0,allowed=true;const errors=[],c=O.createController({allowed:()=>allowed,capture:()=>{reads++;return value;},apply:(_l,e)=>{value.entries=e;writes++;},onError:e=>errors.push(e.message)});return {c,errors,get value(){return value;},set value(v){value=v;},set allowed(v){allowed=v;},get reads(){return reads;},get writes(){return writes;},refresh:()=>c.refresh(list,{ids:value.entries.map(e=>e.id),visible:value.visible,busy:value.busy})};}
test('shots and cues move entire raw fields with original times and stable IDs',()=>{for(const list of O.lists){const source={entries:rows(list),visible:true,busy:false},before=structuredClone(source),p=O.move(list,source,'r1',-1);assert.deepEqual(p.entries.map(e=>e.id),['r1','r0','r2']);assert.deepEqual(O.restore(list,{...source,entries:p.entries},p.record),before.entries);p.entries[0].value.start='later';assert.deepEqual(source,before);}});
test('unknown lists invalid shape and bad directions refuse without source reads or writes',()=>{const s=setup();for(const list of ['arrangement','motifs','__proto__'])assert.equal(s.c.move(list,'r0',1),null);assert.equal(s.reads,0);assert.equal(s.writes,0);for(const edit of [v=>v.extra=1,v=>v.entries[0].value.extra='',v=>v.entries[0].id='',v=>v.entries[0].value.start=0]){const value={entries:rows('cues'),visible:true,busy:false};edit(value);assert.throws(()=>O.move('cues',value,'r0',1));}assert.throws(()=>O.move('cues',s.value,'r0',-1));});
test('metadata view contains only undo coordinates and does not read raw fields',()=>{const s=setup();s.c.move('cues','r1',-1);const before=s.reads,view=s.refresh();assert.equal(s.reads,before);assert.deepEqual(view,{canUndo:true,stale:false,record:{id:'r1',from:1,to:0}});view.record.id='forged';assert.equal(s.refresh().record.id,'r1');});
test('undo restores only latest order while retaining subsequent text and clock edits',()=>{for(const list of O.lists){const s=setup(list);s.c.move(list,'r1',-1);s.c.move(list,'r1',1);s.value.entries[1].value.start='001.250';s.value.entries[0].value[P.specs[list].fields.at(-2)]='後續原文\r\n';const before=structuredClone(s.value.entries);assert.ok(s.c.undo(list));assert.deepEqual(s.value.entries.map(e=>e.id),['r1','r0','r2']);for(const e of s.value.entries)assert.deepEqual(e.value,before.find(b=>b.id===e.id).value);assert.equal(s.c.undo(list),null);}});
test('structural changes permanently invalidate undo even if original order returns',()=>{for(const mutate of [e=>e.pop(),e=>e.reverse(),e=>e[0].id='new',e=>e.push({id:'r4',value:{...e[0].value}})]){const s=setup();s.c.move('cues','r1',-1);const moved=structuredClone(s.value.entries);mutate(s.value.entries);assert.equal(s.refresh().canUndo,false);s.value.entries=moved;assert.equal(s.refresh().canUndo,false);assert.equal(s.c.undo('cues'),null);assert.equal(s.writes,1);}});
test('busy hidden disposed guards stop reads and undo can resume without losing history',()=>{const s=setup();s.c.move('cues','r1',-1);s.allowed=false;const before=s.reads;assert.equal(s.c.move('cues','r0',1),null);assert.equal(s.c.undo('cues'),null);assert.equal(s.reads,before);s.value.busy=true;assert.equal(s.refresh().canUndo,false);s.allowed=true;assert.equal(s.c.move('cues','r0',1),null);s.value.busy=false;s.value.visible=false;assert.equal(s.c.undo('cues'),null);s.value.visible=true;assert.ok(s.c.undo('cues'));s.c.dispose();const reads=s.reads;assert.equal(s.c.move('cues','r0',1),null);assert.equal(s.reads,reads);});
test('source changing between capture and commit preserves external edits and does not write',()=>{let reads=0,writes=0,value={entries:rows('shots'),visible:true,busy:false};const c=O.createController({allowed:()=>true,capture:()=>{if(++reads===2)value.entries[0].value.start='external';return value;},apply:()=>writes++});assert.equal(c.move('shots','r1',-1),null);assert.equal(writes,0);assert.equal(value.entries[0].value.start,'external');});
test('apply mutations cannot alias the expected after snapshot or create an undo record',()=>{let value={entries:rows('cues'),visible:true,busy:false};const errors=[],c=O.createController({allowed:()=>true,capture:()=>value,apply:(_l,e)=>{e[0].value.text='foreign';value.entries=e;},onError:e=>errors.push(e.message)});assert.equal(c.move('cues','r1',-1),null);assert.equal(value.entries[0].value.text,'foreign');assert.match(errors[0],/移動後/);assert.equal(c.refresh('cues',{ids:value.entries.map(e=>e.id),visible:true,busy:false}).canUndo,false);});
test('independent list histories clear only the named list and capacity movement stays valid',()=>{const values=Object.fromEntries(O.lists.map(l=>[l,{entries:rows(l),visible:true,busy:false}])),c=O.createController({allowed:()=>true,capture:l=>values[l],apply:(l,e)=>values[l].entries=e});for(const l of O.lists)c.move(l,'r1',-1);c.clear('shots');assert.equal(c.undo('shots'),null);assert.ok(c.undo('cues'));const full={entries:rows('shots',1000),visible:true,busy:false};assert.equal(O.move('shots',full,'r999',-1).entries.length,1000);assert.throws(()=>O.metadata('shots',{ids:Array.from({length:1001},(_,i)=>'r'+i),visible:true,busy:false}));});
