# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Pure complete test-ID partition; no discovery, timing or process control."""
from .test_run_summary import MAX_TESTS, WORKERS, identifiers

# Approximate local diagnostic costs, not a benchmark or deadline guarantee.
# Unlisted/new methods retain a positive fallback; all discovered IDs still run.
DEFAULT_COST = 56
COST_HINTS = {
    "test_audio_acceptance.AcceptanceTests.test_http_binary_conditions_and_invalid_queries": 547,
    "test_audio_acceptance_input.AcceptanceInputTests.test_actual_cli_report_handoff_and_exclusive_outputs_preserve_inputs": 875,
    "test_audio_acceptance_input.AcceptanceInputTests.test_actual_http_fixed_asset_and_unchanged_json_payload_boundary": 515,
    "test_audio_acceptance_review.AcceptanceReviewTests.test_actual_http_bad_then_good_and_fixed_assets": 531,
    "test_audio_acceptance_review.AcceptanceReviewTests.test_cli_status_and_exclusive_outputs": 750,
    "test_audio_evidence.AudioEvidenceTests.test_actual_http_invalid_header_then_good_data_and_review_asset": 531,
    "test_audio_result.AudioResultTests.test_actual_cli_agent_mcp_http_after_invalid_requests_share_source_bound_current_reports": 984,
    "test_audio_statistics.AudioStatisticsTests.test_actual_pcm_matrix_rounding_silence_extremes_and_supported_measurement_remain_readable": 516,
    "test_audio_statistics.AudioStatisticsTests.test_fixed_native_asset_and_real_http_agent_mcp_cli_reports_keep_same_domain_data": 937,
    "test_backup_download.BackupDownloadTests.test_actual_loopback_single_use_stream_and_fixed_assets_use_the_same_contract": 657,
    "test_backup_export.BackupExportTests.test_http_actual_origin_library_boundaries_and_existing_prepare_wire_remain": 563,
    "test_backup_result.BackupResultTests.test_cli_agent_mcp_share_full_backup_result_contract_and_readonly_write_annotations": 547,
    "test_backup_result.BackupResultTests.test_native_file_hash_actual_http_full_wire_and_fixed_asset_order": 609,
    "test_backup_selection.BackupSelectionTests.test_actual_selected_and_all_downloads_keep_exact_requested_ids_and_single_use": 610,
    "test_backup_selection.BackupSelectionTests.test_invalid_ids_unknown_fields_query_and_origin_reject_before_preparing_archive": 593,
    "test_backup_selection.BackupSelectionTests.test_selected_healthy_revision_can_be_backed_up_without_reading_unselected_revision": 562,
    "test_delivery_context.ContextTests.test_actual_agent_mcp_and_cli_contexts_from_other_cwd_no_source_or_auto_writes": 532,
    "test_delivery_inspect.InspectionHTTPTests.test_http_invalid_source_queries_and_origin_refuse": 515,
    "test_delivery_inspect.InspectionHTTPTests.test_http_shared_inspection_all_text_and_old_version_without_staging": 516,
    "test_delivery_package.DeliveryHTTPTests.test_discard_and_server_close_remove_staging": 516,
    "test_delivery_package.DeliveryHTTPTests.test_prepare_download_all_exact_bytes_and_take_once": 516,
    "test_delivery_package.DeliveryHTTPTests.test_wrong_origin_shape_and_query_are_refused": 547,
    "test_delivery_search.SearchTests.test_actual_cli_search_only_metadata_overwrite_and_mixed_flags": 1344,
    "test_delivery_search.SearchTests.test_four_scopes_full_large_original_tail_positions_and_followup_window": 1844,
    "test_delivery_selection.SelectionTests.test_cli_explicit_outputs_include_full_large_text_and_refuse_default_overwrite": 985,
    "test_delivery_selection.SelectionTests.test_real_agent_and_mcp_from_other_cwd_share_selected_result_and_leave_source_unchanged": 640,
    "test_delivery_selection.SelectionTests.test_verified_full_eight_MiB_64_file_archive_returns_small_subset_and_preserves_default_cap": 547,
    "test_delivery_text.TextWindowTests.test_cli_explicit_window_metadata_refuses_overwrite_and_invalid_mixed_settings": 1609,
    "test_delivery_text.TextWindowTests.test_four_scopes_large_64_file_archive_returns_labeled_bounded_original_with_full_metadata": 1453,
    "test_delivery_text.TextWindowTests.test_real_agent_and_mcp_two_windows_from_different_cwd_do_not_write_or_change_source": 953,
    "test_delivery_text.TextWindowTests.test_windows_reconstruct_original_bom_emoji_mixed_newlines_controls_and_literal_html": 1141,
    "test_delivery_versions.DeliveryVersionHTTPTests.test_existing_host_origin_gate_and_fixed_routes_do_not_open_paths": 562,
    "test_delivery_versions.DeliveryVersionHTTPTests.test_fixed_script_matches_policy_no_store_csp_and_browser_load_order": 515,
    "test_draft_backup.BackupTests.test_http_real_zip_download_preview_restore_origin_and_disabled_boundaries": 625,
    "test_draft_compare.DraftComparisonTests.test_cli_explicit_sources_status_and_exclusive_outputs_preserve_source_bytes": 547,
    "test_draft_compare.DraftComparisonTests.test_loopback_http_full_reply_recovers_after_invalid_source_and_stops_owned_thread": 516,
    "test_draft_compare_browser.BrowserDraftComparisonTests.test_large_cues_complete_counts_and_detail_limit_match_python": 891,
    "test_draft_compare_row.DraftCompareRowTests.test_browser_full_report_and_markdown_match_python_for_all_collections_and_statuses": 688,
    "test_draft_compare_row.DraftCompareRowTests.test_cli_invalid_json_selector_and_missing_rows_never_write": 562,
    "test_draft_compare_row.DraftCompareRowTests.test_cli_status_exclusive_outputs_and_original_bytes": 563,
    "test_draft_compare_row.DraftCompareRowTests.test_loopback_http_full_wire_recovers_and_closes_owned_thread": 531,
    "test_draft_library.DraftAdapterTests.test_http_selected_library_contract_origin_and_disabled_boundary": 531,
    "test_draft_retention.RetentionHttpTests.test_native_export_keeps_exact_content_and_errors_remain_recoverable": 516,
    "test_draft_retention.RetentionHttpTests.test_real_retention_asset_and_workbench_module_order": 516,
    "test_editor_copy.EditorCopyAssetsTests.test_copy_assets_keep_host_origin_gates_and_cannot_select_user_paths": 562,
    "test_editor_copy.EditorCopyAssetsTests.test_fixed_copy_assets_match_installation_and_load_after_draft_before_app": 547,
    "test_editor_keys.EditorKeysAssetsTests.test_fixed_assets_and_literal_keyboard_help": 516,
    "test_editor_keys.EditorKeysAssetsTests.test_keyboard_assets_do_not_expand_paths_or_operation_authority": 531,
    "test_editor_order.EditorOrderAssetsTests.test_fixed_order_assets_match_and_load_in_dependency_order": 516,
    "test_editor_order.EditorOrderAssetsTests.test_order_fixed_routes_preserve_gates_and_no_user_path_authority": 578,
    "test_editor_position.EditorPositionAssetsTests.test_position_assets_and_transient_controls_load_after_shared_order_metadata": 547,
    "test_editor_position.EditorPositionAssetsTests.test_position_assets_keep_host_origin_and_no_external_operation_authority": 532,
    "test_editor_selection.EditorSelectionAssetsTests.test_fixed_assets_match_and_load_after_metadata_models": 515,
    "test_editor_selection.EditorSelectionAssetsTests.test_host_origin_and_fixed_paths_preserve_original_authority": 546,
    "test_json_document.JsonDocumentTests.test_real_http_rejects_duplicate_and_invalid_utf8_then_valid_request": 516,
    "test_library_receipt.LibraryReceiptTests.test_fixed_native_asset_and_real_http_save_read_flow_use_same_complete_contract": 531,
    "test_library_result.LibraryResultTests.test_actual_cli_agent_and_mcp_full_wire_share_pure_library_checks": 578,
    "test_library_result.LibraryResultTests.test_real_loopback_asset_pages_and_read_wires_preserve_source_and_host_origin_gates": 750,
    "test_library_revision.LibraryRevisionTests.test_fixed_shared_native_asset_and_http_list_read_pin_complete_revision": 547,
    "test_library_search.LibrarySearchTests.test_actual_four_adapters_share_full_source_search_cursor_and_browser_validator": 1563,
    "test_loudness.LoudnessTests.test_real_cli_agent_mcp_and_http_share_the_measured_result": 1016,
    "test_lyric_timing.LyricTimingTests.test_real_http_shift_and_static_shared_asset_match": 516,
    "test_lyrics_cue_review.LyricsCueReviewTests.test_cli_explicit_input_and_refused_overwrite": 547,
    "test_lyrics_export_bundle.ExportBundleTests.test_http_and_large_bounded_package_return_exact_source_not_a_compact_excerpt": 531,
    "test_lyrics_export_review.ExportReviewTests.test_actual_http_route_asset_order_and_no_table_mutation": 531,
    "test_lyrics_export_review.ExportReviewTests.test_limits_all_counts_and_bounded_details": 531,
    "test_lyrics_lrc.LrcTests.test_actual_http_asset_order_and_response_match": 516,
    "test_lyrics_media_handoff.LyricsMediaHandoffTests.test_real_cli_exports_all_three_choices_without_changing_source_or_overwriting": 1359,
    "test_lyrics_media_handoff.LyricsMediaHandoffTests.test_real_http_preserves_choices_recovers_from_invalid_and_embeds_same_media_layer": 578,
    "test_lyrics_package.LyricsPackageTests.test_actual_cli_roundtrip_bom_other_cwd_no_override_and_no_overwrite": 1234,
    "test_lyrics_package.LyricsPackageTests.test_actual_http_route_inspects_and_refuses_unknown_without_mutation": 531,
    "test_lyrics_preview.PreviewTests.test_actual_loopback_contract_asset_order_and_source_checked_http_preview": 531,
    "test_lyrics_result.LyricsResultHttpTests.test_actual_http_asset_order_and_checked_literal_build": 579,
    "test_lyrics_review.LyricsReviewTests.test_real_http_recovers_and_serves_actual_deferred_dependency": 516,
    "test_lyrics_search.LyricsSearchTests.test_actual_cli_agent_mcp_good_bad_good_and_exclusive_outputs": 704,
    "test_lyrics_search.LyricsSearchTests.test_actual_http_fixed_assets_raw_text_and_invalid_recovery": 547,
    "test_lyrics_seed.LyricsSeedTests.test_real_http_assets_valid_seed_and_rejection_share_domain": 531,
    "test_lyrics_srt.SrtTests.test_actual_http_static_script_order_and_source_response": 515,
    "test_lyrics_whitespace.LyricsWhitespaceTests.test_cli_and_http_reject_bom_recover_and_preserve_input": 1062,
    "test_maintenance.MaintenanceFilesystemTests.test_changed_token_bytes_age_or_tag_refuse_without_deletion": 3000,
    "test_maintenance.MaintenanceFilesystemTests.test_corrupt_archive_or_extra_user_files_never_become_candidates": 2094,
    "test_maintenance.MaintenanceFilesystemTests.test_drafts_backups_media_other_outputs_and_partial_packages_preserved": 3313,
    "test_maintenance.MaintenanceFilesystemTests.test_oversized_recovery_journal_refuses_before_any_move": 2203,
    "test_maintenance.MaintenanceFilesystemTests.test_path_escape_normalization_output_refusal_and_unknown_record": 1828,
    "test_maintenance.MaintenanceFilesystemTests.test_real_cli_another_cwd_preview_prune_and_restore_and_invalid_flags": 3766,
    "test_maintenance.MaintenanceFilesystemTests.test_real_git_preview_prune_journal_restore_exact_and_no_overwrite": 3531,
    "test_maintenance.MaintenanceFilesystemTests.test_recorded_active_or_unavailable_process_blocks_pruning": 2922,
    "test_maintenance.MaintenanceFilesystemTests.test_reparse_guard_and_changed_receipt_destination_refuse": 969,
    "test_maintenance.MaintenanceFilesystemTests.test_source_reproduction_failure_prevents_pruning": 1281,
    "test_maintenance.MaintenanceFilesystemTests.test_tampered_recovery_identity_or_unknown_version_refuse_all_publishing": 2984,
    "test_maintenance.MaintenanceFilesystemTests.test_zip_central_budget_refuses_before_entry_object_allocation": 1188,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_changed_unselected_identity_invalidates_the_complete_preview": 3156,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_default_preview_shape_and_restore_record_actions_are_not_expanded": 2500,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_existing_cli_receipt_refuses_before_any_preview_or_prune": 1500,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_full_or_other_batch_tokens_cannot_authorize_this_selection": 5031,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_invalid_selection_refuses_before_audit_and_default_129_limit_remains": 1516,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_latest_versions_changed_before_move_leave_journal_and_original_files": 2718,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_protected_unknown_and_noncanonical_selection_preserve_all_files": 3093,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_real_cli_two_package_batch_restore_and_remaining_candidate": 6563,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_recorded_running_or_unverified_job_blocks_selected_pruning": 5032,
    "test_maintenance_batch.PruneBatchFilesystemTests.test_selected_batch_still_obeys_the_unchanged_journal_byte_budget": 4515,
    "test_maintenance_catalog.MaintenanceCatalogTests.test_full_catalog_boundary_and_overflow_refuse_before_package_io": 2375,
    "test_maintenance_catalog.MaintenanceCatalogTests.test_real_129_entry_cli_preview_prune_restore_preserves_partial_files": 4078,
    "test_music_arrangement.MusicArrangementTests.test_actual_asset_defer_order_and_existing_operation_contract": 515,
    "test_music_lab.IntegrationTests.test_cli_all_four_outputs_and_collision_refusal": 1218,
    "test_music_markdown.MusicMarkdownTests.test_http_and_browser_source_guard_accept_exact_full_files": 578,
    "test_music_readiness.MusicReadinessTests.test_assets_defer_order_no_browser_validation_drift_and_normal_loopback_shutdown": 532,
    "test_music_review.MusicReviewTests.test_cli_input_and_modern_draft_no_overwrite_and_exit_codes": 656,
    "test_music_review.MusicReviewTests.test_loopback_http_uses_same_application_boundary": 500,
    "test_music_search.MusicSearchTests.test_actual_cli_agent_mcp_good_bad_good_and_exclusive_outputs": 734,
    "test_music_search.MusicSearchTests.test_actual_http_fixed_assets_raw_text_and_invalid_recovery": 547,
    "test_planning_markdown.PlanningMarkdownTests.test_agent_mcp_http_and_browser_guard_deliver_same_full_files_for_both_operations": 578,
    "test_planning_markdown.PlanningMarkdownTests.test_cli_preserves_all_nine_file_bytes_and_refuses_replacing_each_output": 594,
    "test_planning_report_input.PlanningReportInputTests.test_fixed_browser_input_asset_matches_source_and_uses_existing_loopback_server": 515,
    "test_planning_source.PlanningSourceTests.test_real_http_shared_result_and_ordered_asset": 546,
    "test_process_probe.ProcessProbeTests.test_real_cim_parent_never_declares_live_original_terminal": 6812,
    "test_process_probe.ProcessProbeTests.test_real_cli_fallback_from_other_cwd_blocks_live_then_accepts_original_exit": 10672,
    "test_process_probe.ProcessProbeTests.test_real_managed_child_cim_live_then_original_eof_and_empty_query": 6781,
    "test_release_archive.GitArchiveTests.test_fixed_profile_keeps_all_raw_bytes_when_autocrlf_and_eol_change": 563,
    "test_release_archive.GitArchiveTests.test_legacy_reconstruction_mismatch_is_retained_without_profile_inference": 719,
    "test_release_archive.GitArchiveTests.test_modern_prune_restore_reproduces_original_manifest_and_zip_after_config_change": 3641,
    "test_release_archive.GitArchiveTests.test_self_consistent_modern_manifest_cannot_hide_wrong_source_bytes": 765,
    "test_release_capture.ReleaseCaptureTests.test_real_git_both_read_modes_preserve_exact_selected_source_bytes": 516,
    "test_release_capture.ReleaseCaptureTests.test_real_git_overbudget_producer_and_names_reader_refuse_before_domain_or_archive": 1141,
    "test_release_metadata.CommittedReleaseTests.test_real_stale_commits_refuse_before_archive_or_destination_creation": 1266,
    "test_release_metadata.CommittedReleaseTests.test_selected_commit_is_used_even_when_working_metadata_is_newer_or_invalid": 563,
    "test_release_metadata.CommittedReleaseTests.test_successful_process_with_invalid_test_summary_cannot_issue_manifest": 656,
    "test_release_zip.ReleaseZipTests.test_real_git_producer_refuses_many_directories_before_zipfile_and_test_children": 6078,
    "test_seed_import.SeedImportTests.test_real_cli_seed_from_other_cwd_preserves_source_and_rejects_overrides": 547,
    "test_storyboard_duration.StoryboardDurationTests.test_real_four_adapters_reject_old_total_then_accept_adopted_request_without_overwriting_source": 1250,
    "test_storyboard_frames.StoryboardFramesTests.test_real_http_rejects_invalid_frames_then_recovers_and_serves_shared_module": 515,
    "test_storyboard_ratio.StoryboardRatioTests.test_actual_agent_completed_custom_ratio_matches_browser_full_source_checks": 672,
    "test_storyboard_readiness.StoryboardReadinessTests.test_actual_loopback_asset_and_defer_order_preserve_tool_contract_and_stop_normally": 500,
    "test_storyboard_review.StoryboardReviewTests.test_cli_input_and_modern_draft_no_overwrite_and_exit_codes": 578,
    "test_storyboard_review.StoryboardReviewTests.test_loopback_http_uses_same_application_boundary": 531,
    "test_storyboard_search.StoryboardSearchTests.test_actual_cli_agent_mcp_good_bad_good_and_exclusive_outputs": 657,
    "test_storyboard_search.StoryboardSearchTests.test_actual_http_fixed_assets_raw_text_and_invalid_recovery": 515,
    "test_storyboard_timing.StoryboardTimingTests.test_real_cli_raw_and_modern_draft_share_reports_and_no_overwrite": 547,
    "test_storyboard_timing.StoryboardTimingTests.test_real_http_routes_and_module_defer_order": 547,
    "test_test_run_summary.NativeTestRunnerTests.test_actual_deadline_collects_owned_worker_and_refuses_success": 1359,
    "test_text_verification.TextVerificationTests.test_actual_loopback_serves_same_bytes_without_file_read_post_or_path_permission": 532
}


def partition(ids, weights=None):
    """Balance estimated work, then preserve each worker's discovery order."""
    source = identifiers(ids, MAX_TESTS, 512)
    if not source or len(set(source)) != len(source):
        raise ValueError('Independent discovery must be nonempty and unique')
    hints = COST_HINTS if weights is None else weights
    if not isinstance(hints, dict) or len(hints) > MAX_TESTS:
        raise ValueError('Invalid test cost hints')
    identifiers(list(hints), MAX_TESTS, 512)
    if any(type(cost) is not int or not 1 <= cost <= 120000 for cost in hints.values()):
        raise ValueError('Invalid test cost estimate')
    loads = [0] * WORKERS; counts = [0] * WORKERS; assignments = {}
    ranked = sorted(enumerate(source), key=lambda row: (-hints.get(row[1], DEFAULT_COST), row[0]))
    for index, identifier in ranked:
        group = min(range(WORKERS), key=lambda item: (loads[item], counts[item], item))
        assignments[identifier] = group
        loads[group] += hints.get(identifier, DEFAULT_COST); counts[group] += 1
    return [[identifier for identifier in source if assignments[identifier] == group] for group in range(WORKERS)]
